### DISCUSSION TITLE
Get Variables availble from functions to variables in the main yaml file

### DISCUSSION THREAD

**Discussion by Nadiush1993** [artilleryio/artillery#1008] [Artillery]
Hello,

i am trying to calc in a request a specific IDs with using afterResponse function and after that continue with next request using those ID's i have calculated in a seperate js file.
how can i return those ID's or use them in the next request.

any ideas someone?
thanks!

**Comment by hassy** [comment]
hi @Nadiush1993 👋 

You can set a variable by assigning to [`context.vars`](https://artillery.io/docs/guides/guides/http-reference.html#afterResponse), for example:

```js
function setVar(requestParams, response, context, ee, next) {
  context.vars.requestId = 12345;
  return next();
}
```

used in a scenario:

```yaml
- get:
    url: "/"
    afterResponse: setVar # this will set requestId variable
- post:
    url: "/{{requestId}}" # requestId variable is available now
```

**Comment by driesie** [comment]
I know this is an old topic but it is something I'm currently struggling with.

How do I dynamically set a variable without it being hardcoded like the above example?

**Reply by hassy** [reply]
hi @driesie 👋 you can load values from environment variables. For example, if you set an environment variable before running Artillery with:

```sh
export MYVAR=123456
```

You can refer to that value inside an Artillery script via `$processEnvironment` like this:

```yaml
- get:
    url: "/users/{{ $processEnvironment.MYVAR }}"
```

You can also use dotenv files to load environment variables automatically when running Artillery with the `--dotenv` option - https://www.artillery.io/docs/guides/guides/command-line#options

**Reply by driesie** [reply]
hi @hassy 

not sure if this will help me because I want to set a variable dynamically based on a response from an api that I then want to use later in my playwright function

so I have this in my yml file

```
- post:
          url: "/ipgw/wrapper/v1/customer-token/{{guid}}/pay"
          form:
            amount: 10
            reference:  "{{uuid}}"
            return_url: "https://www.google.com/"
          capture:
            - json: "$.url"
              as: "redirectUrl"
          expect:
            statusCode: 200
            contentType: json
 ```
 
 i want to then use that redirectUrl that I get back from that api call in my playwright function
 
 ```
 async function ipgHostedPages(page, context) {
    await page.goto(context.vars['redirectUrl']);

    await page.getByPlaceholder('CVV').fill('***');
    await page.getByRole('button', { name: 'Pay' }).click();

    await page.getByLabel('Password:').fill('***');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('Redirect Now').click();
}
 ```

**Reply by hassy** [reply]
Hi @driesie it's not possible to mix HTTP actions like `post` and Playwright functions in the same scenario right now in Artillery.

You can try using the built-in `request` method (https://playwright.dev/docs/api/class-page#page-request) to make that initial call.

**Comment by driesie** [comment]
When I set my variable like below in my yml file

```
  variables:
    redirectUrl: "foo"
```

this part from my function actually picks up 'foo'

```
await page.goto(context.vars['redirectUrl']);
```

but I want to dynamically set this based on the url that my one api returns, so far no luck, I even tried using 'set' but 'redirectUrl' remains 'foo'

```
- post:
          url: "/ipgw/wrapper/v1/customer-token/{{guid}}/pay"
          form:
            amount: 10
            reference:  "AndreRef"
            return_url: "https://www.google.com/"
          capture:
            - json: "$.url"
              as: "url"
          expect:
            statusCode: 200
            contentType: json
          set:
            var: "{{ redirectUrl }}"
            value: "{{ url }}"
      - log: "API URL: {{ url }}"
      - log: "Variable URL: {{ redirectUrl }}"
```
