### DISCUSSION TITLE
Handle 301 redirects in flow request ?

### DISCUSSION THREAD

**Discussion by avnerma** [artilleryio/artillery#1016] [Artillery]
I wonder if there is a way to automatically handle 301 response status code ?
we are created the following scenario -

```yaml
scenarios:
    - flow:
      - get:
          url: "/api/last"
          capture:
            regexp: ".+"
            as: "id"            
          expect:
            - statusCode: 200     
      - get:
          url: "/api/{{ id }}/zip"
          capture:
            regexp: ".+"
            as: "url"    
          expect:
            - statusCode: 301  
      - get:
           url: "{{ url }}"
           expect:
             - statusCode: 200
```
and we getting error - "Failed expectations for request" on the last flow request.
Is there a better way to handle it ?
