### DISCUSSION TITLE
Function on WS

### DISCUSSION THREAD

**Discussion by hsabillon7** [artilleryio/artillery#1050] [Artillery]
It's possible for Artillery to run a WebSocket test with all the logic inside a function and when the function finishes the test is finished for each virtual user. Because we have a custom client that does all the logic of the connection and petitions. If a run the test below it runs the function successfully but the test for the virtual user it's never completed. Do I have to add some code to the function or it's even possible to do what I'm looking for?

```
config:
  target: "ws://localhost:8000"
  processor: "./customClient.js"
  phases:
    - duration: 10
      arrivalRate: 1
      name: Warm up

scenarios:
  - name: "Custom client tests"
    engine: ws
    flow:
      - function: "customClient"
      - think: 1
```
