### DISCUSSION TITLE
Redirect and "expect" statement

### DISCUSSION THREAD

**Discussion by ambrosmiroslav** [artilleryio/artillery#1052] [Artillery]
Hi!
I am trying to create my very first test scenario with artilleryio.
Our web application uses Post/Redirect/Get design pattern (https://en.wikipedia.org/wiki/Post/Redirect/Get).
One step of my scenario flow is:

```
      - post:
          url: "/Login/Role"
          form:
            action: "SelectRole"
            role: "115"
          expect:
            - statusCode: 200
```

The POST request to "/Login/Role" with given parameters results in the status code "302" with location header set to "/User/UserInfo" and zero content-length. Following this redirect results in the status code "200" with HTML page and non-zero content-length.

I would like to use "expect" statement with "matchesRegexp" to check the HTML page contains some text to prove briefly the scenario goes well. But it seems the defined "expect" is checked for both responses - "302" with no content and "200" with content.

So I think it is impossible to define single "expect" condition to match redirected response within single flow step:
```
          expect:
            - statusCode: 200
```
or
```
          expect:
            - matchesRegexp: .+ExpectedText.+
```

As the status code could be "302" or "200".
As the response body could be empty or non-empty.

Am I right?

I could try to split this step into two steps with "followRedirect: false" in the first one. So I should be able to resolve them separately with proper "expect" values...

Thank you for any advice.

**Comment by ambrosmiroslav** [comment]
Now I have two solutions of my problem.

1) Don't follow the redirects automatically (having full control over the expectations):

```
      - post:
          url: "/Login/Role"
          form:
            .... some form values
          followRedirect: false
          expect:
            - statusCode: 302
            - headerEquals:
              - "location"
              - "/User/UserInfo"
      - get:
          url: "/User/UserInfo"
          expect:
            - statusCode: 200
            - matchesRegexp: John Doe
```

2) Follow the redirects automatically (having sufficient control over the expectations):

```
      - post:
          url: "/Login/Role"
          form:
            .... some form values
          expect:
            - statusCode:
              - 200
              - 302
            - matchesRegexp: (^$)|(John Doe)
```

The status code could be either 200 or 302 and the response could be either empty or some HTML page containing the given user name.
