### DISCUSSION TITLE
Variables in capture.json query

### DISCUSSION THREAD

**Discussion by leduyminh48** [artilleryio/artillery#1059] [Artillery]
is it possible to pass variable to jsonPath query like this:
```yaml
  - name: "Adding comments"
    flow:
      - loop:
          - get:
              url: "/task/{{$loopElement.id}}"
              qs:
                relations: "[\"comments\"]"
              capture:
                json: "$.comments[?(@['comment']==\"{{commentStr}}\")]"
                as: "capturedComment"
          - log: "capturedComment {{capturedComment}}"
        over: tasks

```
