### DISCUSSION TITLE
xpath failing

### DISCUSSION THREAD

**Discussion by indiejames** [artilleryio/artillery#1071] [Artillery]
I am attempting to use the `xpath` capture, but the scenario fails every time. This is the portion of my YML file that uses `xpath`:
```
- loop:
        # - think: 2
        - get:
            # url: "/search/granules.iso"
            url: "/granules.iso"
            headers:
              "CMR-Scroll-Id": "{{ scrollId2 }}"
            capture:
              xpath: "//(results)/result"
              as: "hitsXml"
            strict: false
        whileTrue: "isStillScrollingXml"
```
My JavaScript function `isStillScrollingXml` is never called - the scenario just fails. I have tried different values for the `xpath` parameter such as `//result`, etc., with no luck. The xml response from the GET is the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<results>
  <hits>5</hits>
  <took>92</took>
  <result concept-id="G1200000010-PROV1" collection-concept-id="C1200000005-PROV1" revision-id="1" format="application/echo10+xml">
    <Granule>
      <GranuleUR>ur6</GranuleUR>
      <InsertTime>2012-01-11T10:00:00.000Z</InsertTime>
      <LastUpdate>2012-01-19T18:00:00.000Z</LastUpdate>
      <Collection>
        <DataSetId>Entry Title 0</DataSetId>
      </Collection>
    </Granule>
  </result>
</results>
```
(Note that if I enable DEBUG the response shown  is a string with all the double quotes escaped)

Pasting this into an online xpath tester shows my `xpath` value works, so I'm not sure what is going on. There is no error reported by artillery.

Does anyone have an idea of what I might be doing wrong or how I can turn on some logging that will identify what the underlying error is?
