### DISCUSSION TITLE
Specifying different headers for different environment

### DISCUSSION THREAD

**Discussion by cchen-bay1** [artilleryio/artillery#1073] [Artillery]
I am looking for a way to specify different authorization headers for different environments. I tried the following but it didn't work:
  
```
environments:
    local:
      target: http://localhost:8080
      headers:
         authorization: 'Basic blahblah'
```

Any suggestions?

**Comment by hassy** [comment]
hi @cchen-bay1 👋 this can be done via `config.defaults` which allows default HTTP parameters to be set for all requests, and can be set per environment. Something like this:

```
environments:
    local:
      target: http://localhost:8080
      defaults:
        headers:
           authorization: 'Basic blahblah'
```
