### DISCUSSION TITLE
How to make Http timeout NOT to stop a scenario

### DISCUSSION THREAD

**Discussion by AndriianChestnykh** [artilleryio/artillery#1079] [Artillery]
Hi

I am trying to run load tests agains a system where long http responses are possible. Sometimes the responses took even a few minutes, so a timeout will happen (whatever `timeout:` setting in yml config file or no setting at all)
The scenario that I try looks like this (simplified):
```
scenarios:
  - name: "Create and cancel order"
    flow:
      - function: "generateOrderId"
      - post:
          url: "/api/v1/orders"
          json:
            orderId: "{{ orderId }}"
      - delete:
          url: "/api/v1/orders/{{ orderId }}"
```
**Current behaviour:** If a timeout at POST occurs then DELETE requests does not happen
**Desirable behaviour:** DELETE should happen in any case

I didn't manage to find some config setting for that so far. Can you advise?
