### DISCUSSION TITLE
Test scenarios limits with websocket

### DISCUSSION THREAD

**Discussion by hsabillon7** [artilleryio/artillery#1083] [Artillery]
I've been using artillery to do some HTTP/REST tests and running scenarios with a high number of total requests (1,000,000+) without any issues. 

Now I'm trying to run the same scenario with a custom function on websocket but it seems like cannot run a test bigger than 120,000 scenarios because the test keeps running forever, no test executed but Artillery keeps showing the elapsed time and other metrics with 0 values and NaN like this example:

```
Elapsed time: 11 minutes, 21 seconds
  Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
```

If the tests if lower Artillery finishes the test and gives me the results.

Here's my test
```
config:
  target: "ws://localhost:8888"
  processor: "customTest.js"
  phases:
    - duration: 300
      arrivalRate: 500
      name: Sustained load

scenarios:
  - name: "Testing WebSocket implementation"
    engine: ws
    flow:
      - function: "wsCustomTest"
```
