### DISCUSSION TITLE
I would like to loop through all the binary files in a dir and post it in the request body on every request.

### DISCUSSION THREAD

**Discussion by rizzyDev** [artilleryio/artillery#1113] [Artillery]
My custom function is able to read all the files synchronously without any issues and its as simple as below:

Function (requestParams, context, ee, next){
let dir = .\somewhere:

(fs.readdirSync(dir).forEach(file => {
requestParams.body = fs.readFileSync(`${dir}${file}`). 

return next()
}

When i try to use it beforeRequest: "function" attrib using loops, it always ends up posting the same file over and over. Is there a way i can loop through all the files and send it in the request body, untill the length of dir is reached?

I am able to post a single file without any troubles. However i need to post all the files in the dir sequentially. I noticed whileTrue option but unable to use it for some reason.

Note: I am able achieve this use case to send to my api using request module of node.js, which posts all the files in the dir.

Please your suggestions would be helpful.

**Comment by flentini** [comment]
Hi @rizzyDev , 

It's posting the same file because you are reading the directory at every request, and in your loop you exit after reading the first result.
I think you could solve that by reading the directory once, before your users start sending the actual requests, using a [before](https://artillery.io/docs/guides/guides/test-script-reference.html#The-before-and-after-sections) section. You can then send the files sequentially, using `whileTrue` to check when you get to the end of the dir. Something like this:

```yaml
config:
  target: "http://yourtarget"
  processor: "./functions.js"
  phases:
    - duration: 1
      arrivalRate: 1

before:
  flow:
    - function: "readDir"

scenarios:
  - name: "Sending files"
    flow:
      - loop:
          - think: 1
          - post:
              url: "/"
              beforeRequest: "readFile"
        whileTrue: "gotFile"
```

```javascript
function readDir(context, events, next) {
  // get the files list once
  context.vars.files = fs.readdirSync("./files");

  return next();
}

function readFile(requestParams, context, events, next) {
  // get one file and remove it from the list
  const fileName = context.vars.files.pop();

  requestParams.body = fs.readFileSync(`./files/${fileName}`)

  return next();
}

function gotFile(context, next) {
  // continue if we still have files to send
  return next(context.vars.files.length > 0)
}
```
