### DISCUSSION TITLE
The beforeRequest / afterRequest function hooks are never getting called for me

### DISCUSSION THREAD

**Discussion by rujiel** [artilleryio/artillery#1120] [Artillery]
Hello, I have a use case where I need to generate X number of directories containing Y number of files. In order to do this I have to pass an incrementing count into a function that I'm calling in a loop. But right now it looks like the "beforeRequest" and "afterRequest" methods are never called. As a result the count I am trying to feed into the js file is always undefined. Everything else is working properly though if I don't use any functions.

I'm using artillery version 1.7.6 with node version v14.17.0
Here is a simplified example. My artillery test file:

```
config:
  target: "http://localhost"
  http:
    maxSocket: 5
    timeout: 60
  phases:
    - duration: 1
      arrivalRate: 1
      maxVusers: 1
  processor: "./process.js"
scenarios:
  - flow:
      - loop:
          - function: "generateRequestData"
          - post:
              beforeRequst: "myBeforeRequestHandler"
              afterRequest: "myAfterRequestHandler"
              url: "/test"
              duration: 60
              json: "{{payload}}"
        count: 1
```

And the process.js script:

```
	'use strict';
	 module.exports = {
	  generateRequestData, myBeforeRequestHandler, myAfterRequestHandler
	};
	function generateRequestData(userContext, events, done) {
		userContext.vars.payload = {
			"count": userContext.vars.count
		}
		return done();
	}

	function myBeforeRequestHandler(requestParams, context, ee, next) {
		if (context.vars.count === undefined)
			context.vars.count = 0;
		console.log('myBeforeRequestHandler: '+next)
	}

	function myAfterRequestHandler(requestParams, context, ee, next) {
		context.vars.count++;
		console.log('myAfterRequestHandler: '+next)
	}
```
