### DISCUSSION TITLE
Expect Support For Ws

### DISCUSSION THREAD

**Discussion by vakil-neelin** [artilleryio/artillery#1123] [Artillery]
It would be nice to have the expect plugin work for the ws engine so users can check response values. If this is already possible please let me know how to use it. I have expects written for my web sockets but they are not run.

I am on 2.0.0-dev5

**Comment by vaib-ag** [comment]
Even I am trying the similer scenarios. I need to send 1st request as authentication request and assert if the authentication is passed or not. Also after several send, I need to validate the reponse from the server. 
As an additional checkpoint, I need to validate if the server is responding back or have closed the connection (with or without error). 

Without the assertions, this is kind of impossible. 
Also is there any way where we can take the response inside the custome code to play with it?

**Reply by vakil-neelin** [reply]
Currently you can capture the response, but not really check it besides using a function call. I would use this but I am not sure how to fail the user without stopping execution entirely.

To capture the response you can use something like this:
```
      - send:
          payload:
              username: "XXXX"
              password: "XXXX"
          capture:
            - json: "$.auth_token"
              as: "auth_token"
```
