### DISCUSSION TITLE
Question on doco

### DISCUSSION THREAD

**Discussion by wired00** [artilleryio/artillery#1150] [Artillery]
Should this:
https://artillery.io/docs/guides/getting-started/writing-your-first-test.html#Load-Phases

```
config:
  target: "https://example.com/api"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 600
      arrivalRate: 50
      name: Sustained load
```

Actually be?

```
config:
  target: "https://example.com/api"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 600
      arrivalCount: 50
      name: Sustained load
```

Note the `arrivalCount: 50`. 

I came to this conclusion over detail in fixed number of arrivals per second. it describes the fixed number would use `arrivalCount`
https://artillery.io/docs/guides/guides/test-script-reference.html#Fixed-number-of-arrivals-per-second
