### DISCUSSION TITLE
Invalid URI for FUZZ tests

### DISCUSSION THREAD

**Discussion by ermolaevakate** [artilleryio/artillery#1172] [Artillery]
hello! 
I have FUZZ script: 
```
config:
  target: "http://tets.net"
  phases:
    - duration: 100
      arrivalRate: 1
  ensure:
    maxErrorRate: 1
  plugins:
    expect: {}
    fuzzer: {}

scenarios:
  - flow:
      - get:
          url: "test?oneParameter={{naughtyString}}&secondParameter=0"
          followRedirect: false
          headers:
            Accept: 'application/hal+json, application/json, text/plain, */*'
            Cache-Control: 'no-cache, no-store'
            Authorization: "Bearer ..."
          expect:
             -statusCode: 400
```
with passing some parameters from fuzz plugin;
and I can't use fuzz plugin because of the recent bug fixed I guess: https://github.com/artilleryio/artillery/issues/512
everytime I get an "Invalid URI" error while execution;
Is it possible to allow to use fuzzer plugin and don't get such an error?
