### DISCUSSION TITLE
Unable to get an xpath query to work on an XML response body

### DISCUSSION THREAD

**Discussion by nvingoe** [artilleryio/artillery#1194] [Artillery]
Hi there, I'm struggling to get a straight forward xpath query to pull out a GUID from an XML response body and I was wondering if I'm doing something fundamentally wrong.  Here's a snippet from my  .yml file (not the entire file):

```yaml
- post:
  url: "/Patients"
  beforeRequest: "readPmrFile"  
  name: CreatePatient
  capture:
    xpath: "/PatientCreateResponse/PatientId"
    as: "pmrGUID"
    strict: false
  headers:
    Content-Type: "application/xml"  
  - post:
   url: "/Patients/{{ pmrGUID }}"       
   beforeRequest: "readDrugFile"  
   name: UpdateProspectiveDrug  
```

I've run in various debug modes and I can see that the XML response of that call is as below, which I've also confirmed via Postman

```xml
<?xml version="1.0" encoding="utf-8"?>
<PatientCreateResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Warnings />
    <Logs />
    <Errors />
    <PatientId>5a1105f7-56ed-4537-bd33-b793b1707a05</PatientId>
</PatientCreateResponse>
```

However the value of "pmrGUID" never seems to be set. Any pointers would be much appreciated.
