### DISCUSSION TITLE
Getting EADDRINUSE with high load

### DISCUSSION THREAD

**Discussion by Shazwazza** [artilleryio/artillery#1210] [Artillery]
I'm not a nodejs dev so I'm not entirely sure what this means but from everything I've read it seems like this shouldn't occur.

A similar issue was reported quite some time ago here https://github.com/artilleryio/artillery/issues/90.

I'm using the latest 1.7.2 and using this simple config:

```yml
config:
  phases:
    - duration: 30
      arrivalRate: 200
      rampTo: 600
scenarios:
  - name: "Test"
    flow:
      - get:
          url: "/"
```

I haven't tested if I get the same result in 1.6.x but seems quite similar to the previous report. If I run `netstat` after the run there are thousands of items in `TIME_WAIT` for `mynews` (not sure why it's mynews?) Eventually those go away but they are created from artillery. 

I can't push my site it's peek without this result. I'm assuming this shouldn't occur but let me know otherwise and any tips for how I can push the RPS high enough for this page to start showing some lag.

```
All virtual users finished
Summary report @ 23:18:11(-0700) 2021-05-20
  Scenarios launched:  12131
  Scenarios completed: 9600
  Requests completed:  9600
  Mean response/sec: 290.49
  Response time (msec):
    min: 3
    max: 46
    median: 7
    p95: 11
    p99: 15
  Scenario counts:
    FrontEnd: 12131 (100%)
  Codes:
    200: 9600
  Errors:
    EADDRINUSE: 2531
```

![image](https://user-images.githubusercontent.com/1742685/119091479-7c455280-ba50-11eb-96fa-e1858ef99af1.png)
