### DISCUSSION TITLE
Passing nested object for a payload/request body doesn't work

### DISCUSSION THREAD

**Discussion by meglenast** [artilleryio/artillery#1228] [Artillery]
I'm quite new to using Artillery but I have the following problem , when trying to pass a nested json object as a payload of a request  it looks like it's not working, wheres this problem doesn't seem to appear when passed non-nested objects. I tried the following two approaches: 

1. Tried to pass the payload as an inlined json object as it follows:
```
json:
                    field1: { subfield1: 123, subfield2: 456 }
                    field2: "value2"
                    field3: { subfield3: "string", subfield4: "string" }
                    field4: "value4"

```
the object seems to be passed alright when i log it in the requstParams like so. However, I don't get the expected response.
```
function printRequestPaylaod (requestParams, response, context, ee, next) {
    console.log(`${JSON.stringify(requestParams.json)}`);
    return next();
}
```
2. Tried to pass the payload from JS with the help of the before request hook as it follows:

```
function setJSONbody(context, ee, next) {
    context.body = { "field1": {"subfield1":123, "subfield2":456}, "field2": "value2", "field3":"value3"};
    /    return next();
}
        - post:
            url: "/someURL"
            json: "{{ body }}"
            beforeResponse:
                - "setJSONbody"
```

I am not getting the same issues while having a payload which isn't a nested json object.
And I can't find a similar example in the documentation either.

**Comment by flentini** [comment]
hi @meglenast :wave: 

you can pass a nested json object using
```yaml
scenarios:
  - flow:
      - post:
          url: '/'
          json:
            field1: { subfield1: 123, subfield2: 456 }
            field2: "value2"
            field3: { subfield3: "string", subfield4: "string" }
            field4: "value4"
```
or you can get the same result with a custom javascript function as a `beforeRequest` hook:

```javascript
function setJSONBody(requestParams, context, ee, next) {
  requestParams.body = JSON.stringify({
    field3: {
      subfield4: "hello",
    },
  });

  return next();
}
module.exports = { setJSONBody };
```
```yaml
scenarios:
  - flow:
      - post:
          url: '/'
          beforeRequest: "setJSONBody"
```
note that `setJSONBody` stringifies the object and the scenario does not have a `json` property.
