### DISCUSSION TITLE
Authorization header gets scrambled when coming from environment variable?

### DISCUSSION THREAD

**Discussion by erzz** [artilleryio/artillery#1233] [Artillery]
```
config:
  target: "https://mysite.com"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 1
      rampTo: 40
      name: Ramp up load
    - duration: 120
      arrivalRate: 40
      name: Sustained load
scenarios:
  - name: "filters"
    flow:
      - log: "{{ $processEnvironment.ID_TOKEN }}"
      - get:
          url: "/search/ru/ph/filters"
          headers:
            Authorization: "{{ $processEnvironment.ID_TOKEN }}"
```

In the above case every request results in `errors.ERR_INVALID_CHAR`

The value of `ID_TOKEN` is `Bearer long-jwt` and the log I added above presents it correctly. In fact I copy from that log and use it  in the browser and it works there.

If I replace the environment variable in the config with `Authorization: "Bearer long-jwt"` it works fine.  The issue is only when trying to use it as a variable
