### DISCUSSION TITLE
Having  authentication both in the config section and in the scenarios section?

### DISCUSSION THREAD

**Discussion by meglenast** [artilleryio/artillery#1235] [Artillery]
Hello, is it possible to have authentication both in the config section and in the scenarios section. I can't find a similar example to what I'm trying to achieve documented. So far I'm doing the following, which doesn't seem to work.

```
config:
  target: '/some-target'
  phases::
    - duration: 1
      arrivalRate: 1
 default:
  headers:
    Authorization: 'Bearer  {{token}}'
scenarios:
  - flow:
    -post:
      url: "/some-url"
     auth:
      user: "{{ $processEnvironment.USER }}"
      pass: "{{ $processEnvironment.PASS }}"
    capture:
      json: "$.token"
      as: "token"  


```
With other words I want to specify some of the request to use the specified authentication schema in the scenario section and for the unspecified request the default authentication method form the _cofig_ section to be used. Is this possible to be done in any way?
