### DISCUSSION TITLE
Socket.io authorization unique for each VU

### DISCUSSION THREAD

**Discussion by Gerben-T** [artilleryio/artillery#1258] [Artillery]
I'm using the `before` flow to set an auth token in `context.vars.pushServerToken`, but this hook only runs once.
I want this token to be generated for each VU, so the logical thing would be to move the `before` flow to `beforeScenario`, but the problem is that this hook seems to run AFTER the socket has been created. Which means that the socket doesn't have the auth token i generated for it.

```yaml
config:
  target: "xxx"
  processor: "processor.js"
  ...
  phases:
    - duration: 10
      arrivalRate: 1
      name: Single test

before:
  flow:
    - function: "setAuthToken"

scenarios:
  - name: First test
    engine: "socketio"
    socketio:
      path: "/v2/socket.io/"
      transports: ["websocket"]
      rejectUnauthorized: false
      auth:
        token: "Bearer {{ pushServerToken }}"
    flow:
      ...
```

and `processor.js`

```js
const fs = require("fs");
const path = require("path");
const dotenv = require("dotenv");
const testEnv = dotenv.parse(fs.readFileSync(path.join(__dirname, "../", "test.env")));
const serverEnv = dotenv.parse(fs.readFileSync(path.join(__dirname, "../", "server.env")));

const JWT = require("jsonwebtoken");

module.exports = {
	setAuthToken,
};

function setAuthToken(context, ee, next) {
	const token = JWT.sign({
		userId: context.vars.$uuid,
		memberId: testEnv.MEMBER_ID,
	}, serverEnv.SECRET, {algorithm: "HS256"});

	context.vars.pushServerToken = token;

	return next();
}
```
