### DISCUSSION TITLE
No Concurrent User chart on HTML report (v2.0.0-10)

### DISCUSSION THREAD

**Discussion by kanpizza1150** [artilleryio/artillery#1293] [Artillery]
Hi everyone! Here's the Configuration. 

```
config:
  target: "my endoint" 
  plugins:
    expect: {}
    metrics-by-endpoint:
      useOnlyRequestNames: true
  phases:
    - arrivalRate: 1
      maxVUsers: 25
      duration: 30
  processor: "./customFile.js"
  ensure:
    maxErrorRate: 5 #percent
```

I ran
```
yarn artillery run xxx.yaml -o xxx.json
```
and then 
```
yarn artillery report xxx.json -o xxx.html
```
to generate HTML report but there is no `Concurrent User` chart has been shown.

Is there any configuration I've missed? Or any way to generate the Concurrent User chart?

These are all dependencies installed in the project.
```
  "dependencies": {
    "artillery": "^2.0.0-10",
    "artillery-plugin-expect": "^2.0.0-3",
    "artillery-plugin-metrics-by-endpoint": "^1.0.2"
  },
```

Thanks!
