### DISCUSSION TITLE
Scenario counts tabel on HTML Report

### DISCUSSION THREAD

**Discussion by kanpizza1150** [artilleryio/artillery#1294] [Artillery]
Hi all! I've generated HTML report from JSON by running
```
yarn artillery report xxx.json -o xxx.html
```
Here's the configuration
```
config:
  target: "xxx" 
  plugins:
    expect: {}
    metrics-by-endpoint:
      useOnlyRequestNames: true
  phases:
    - arrivalRate: 1
      maxVUsers: 25
      duration: 30
  processor: "./customFile.js"
  ensure:
    maxErrorRate: 5 #percent
  defaults:
    headers:
      Authorization: "xxx
scenarios:
  - name: "== Search scenarios 3 =="
  - flow:
      ...
```

On the HTML report, there are 2 rows in the `Scenario counts` table as below:

<h4 style="box-sizing: border-box; font-family: sans-serif; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); margin-top: 10px; margin-bottom: 10px; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Scenario counts</h4><p style="box-sizing: border-box; margin: 0px 0px 10px; font-family: sans-serif; font-size: 13.3333px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p>

1 | 17 (56.667%)
-- | --
== Search scenarios 3 == | 13 (43.333%)

Can someone explain what is row `1` comes from? 
In my expectation the report should show only `== Search scenarios 3 ==`  which is the scenario I've named it.

Thanks!
