### DISCUSSION TITLE
Using Expect plugin headerEquals when value is an array

### DISCUSSION THREAD

**Discussion by fage88** [artilleryio/artillery#1323] [Artillery]
Hello,

I am trying to use the expect plugin to validate that certain cookies are being set.
I have a request with headers that look like this
![image](https://user-images.githubusercontent.com/4366901/152389061-3e491047-866f-4499-ae97-00fe32b0f60a.png)
I have an expect block that looks like this 
```
- get:
          url: "{{ primaryUrl }}"
          auth:
            user: "{{ basicAuthUser }}"
            pass: "{{ basicAuthPass }}"
          capture:
            json: "$"
            as: "siteData"
          expect:
            - statusCode: 200
            - contentType: "text/html"
            - hasHeader: "set-cookie"
            - headerEquals:
                - "set-cookie"
                - 
                  - "prime-platform={{ siteData.platform }};Version=1;Path=/"
                  - "prime-site={{ siteData.siteName }};Version=1;Path=/"
                  - "prime-site-status={{ siteData.status }};Version=1;Path=/"
```
But I am seeing this
```
  not ok header set-cookie values equals prime-platform=bios;Version=1;Path=/,prime-site=vb;Version=1;Path=/,prime-site-status=DRAFT;Version=1;Path=/  {}
  expected: prime-platform=bios;Version=1;Path=/,prime-site=vb;Version=1;Path=/,prime-site-status=DRAFT;Version=1;Path=/
       got: prime-platform=bios;Version=1;Path=/,prime-site=vb;Version=1;Path=/,prime-site-status=DRAFT;Version=1;Path=/
```

It looks to me like the `expected` and `got` values are the same, but they are not being calculated as equal.  Is there a syntax I am missing to deal with arrays/multi value headers?
