### DISCUSSION TITLE
test() can only be called in a test file

### DISCUSSION THREAD

**Discussion by Evengelius** [artilleryio/artillery#1325] [Artillery]
Hello,

I am currently building a scenario that works with both Artillery & Playwright.

It works without any issue with a flowfunction : 

```
config:
  target: "https://artillery.io"
  phases:
    - arrivalRate: 1
      duration: 10
  engines:
    playwright: {}
  processor: ./tests/playwright/flow.js
scenarios:
  - name: "Dev account signup"
    engine: playwright
    flowFunction: "devAccountSignupFlow"
```

The function here, is **devAccountSignupFlow** , and it is generated by the codegen of PlayWright

Here it is : 

```
async function devAccountSignupFlow (page) {
  // Go to https://artillery.io/
  await page.goto('https://artillery.io/');
  // Click text=Pricing
  await page.click('text=Pricing');
  (...)
```

With this project structure  :

![image](https://user-images.githubusercontent.com/34001724/153034744-0bbe74b6-9f31-4104-a855-b02f9a90f871.png)

And this command to make it run :

`artillery run tests/browser-load-test.yml`

----------

However if I try to create my own function :

Like this one for example, 

```
const { test, expect } = require('@playwright/test');

test('basic test', exampleFunction);

async function exampleFunction({page}) {
    await page.goto('https://playwright.dev/');
    const title = page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
}

module.exports = {
    exampleFunction
};
```

With this script :

```
config:
  target: "https://artillery.io"
  phases:
    - arrivalRate: 1
      duration: 10
  engines:
    playwright: {}
  processor: ./playwright/example.spec.js
scenarios:
  - name: "Dev account signup"
    engine: playwright
    flowFunction: "exampleFunction"
```

It is not working.

I do have an error saying,

`test() can only be called in a test file`

We cannot create a Playwright script with its built-in "test()" function?

This method is useful to execute the test  and check visually what is happening.

Like for instance, if I want to see the test running in Playwright before Artillery, I can right

`npx playwright test tests/playwright/example.spec.js`

**Comment by hassy** [comment]
It seems like the `test()` function may check that it's invoked in a script which is executed with the `playwright test` command.

The `exampleFunction` function does not make use of the `test()` function - a possible solution might be to extract it into a separate file which can then be required by both:

1. spec file you run with `playwright test`
2. an Artillery test using the function for a load test

Would that work?

**Comment by Evengelius** [comment]
Hello @hassy,

I actually found a wonderful solution based on your last message, so I want to share it with people who might struggle with this in any coming future,

----------

To be honest, you don't even need the `test()` function from Playwright.
In Playwright, if you want to run your test, you have to write,

`npx playwright test  path/to/your/script` 

Add it a `--headed` if you want it to open the browser for you : so that you will visually check what is happening.
This was my goal.

So yes, basically I thought I had to build 2 separates scripts in order to do that.. 

But then I read the [Playwright docs](https://playwright.dev/docs/codegen#record-using-custom-setup), and figured out this : 

```
  // Make sure to run headed.
  const browser = await chromium.launch({ headless: false });
```

And so I discovered that I could drastically simplify my code, to keep it simple.
And with just the codegen from Playwright, and an Artillery YML script, we can write soething like this :

```
//
// Most of this code is generated with playwright codegen
// https://playwright.dev/docs/cli/#generate-code
//

const {chromium} = require("@playwright/test");

async function exampleFunctionFlow () {
  const browser = await chromium.launch({ headless: false });

  // Setup context however you like.
  const context = await browser.newContext({ /* pass any options */ });
  await context.route('**/*', route => route.continue());

  // Creates a new page in the browser context.
  const page = await context.newPage();

  // Happy Hacking
  await page.goto('https://github.com');
  await page.waitForTimeout(3000) // I don't want the browser to close super fast, so I added a 3sec delay.

  // Once done we make sure to close the browser
  await browser.close();
}

module.exports = {
  exampleFunctionFlow,
};
```

----------

And the Artillery part 

```
config:
  target: "https://github.com"
  phases:
    - arrivalRate: 1
      duration: 1
      name: Warm up
  engines:
    playwright: {}
  processor: ./flows.js
scenarios:
  - name: "Example Flow"
    engine: playwright
    flowFunction: "exampleFunctionFlow"
```

By simply doing this, if we run it, `artillery run browser-load-test.yml`, it will open the chrome browser and follow every step we defined.

And this is exactly what I wanted.
