### DISCUSSION TITLE
Specific number of users and second in parameter

### DISCUSSION THREAD

**Discussion by Evengelius** [artilleryio/artillery#1330] [Artillery]
Hello,

Is there a way to pass in parameter the number of users we want to execute the script for? And this for a specific number of time ?

Like for instance : 

`artillery run my-test.yml -Dusers=1 -Dseconds=60`

I think to solve this the goal might be to extract in a define variable the number of duration and "rampTo", but I don't know how to do.

```
  phases:
    - duration: 5
      arrivalRate: 1
      rampTo: 3
      name: Running
```
