### DISCUSSION TITLE
How to load the custom JS code before all scenarios?

### DISCUSSION THREAD

**Discussion by A6196511** [artilleryio/artillery#1335] [Artillery]
Hi, for my load test script I need to clean DB and then fill it in by test data. The logic for that is contained in the separate JS file. However, in the guide https://www.artillery.io/docs/guides/guides/http-reference#loading-custom-js-code  I see that it is only possible to load the custom JS code via `beforeRequest` or `beforeScenario`, which is not acceptable for my current case. Is there a way to load the custom JS code only once, before all scenarios?

Regards, Alex

**Comment by flentini** [comment]
Hi @A6196511 :wave:  - you could use a [before](https://www.artillery.io/docs/guides/guides/test-script-reference#before-and-after-sections) section, with a [function step](https://www.artillery.io/docs/guides/guides/http-reference#function-steps-in-a-flow) :

```yaml
config:
  target: http://target
  processor: './processor.js'
before:
  flow:
    - function: 'populateDb'
scenarios:
  - flow:
  ...
```

**Reply by A6196511** [reply]
Hi @flentini. Thanks for the quick reply, but it does not work for me:


```
config:
  target: "<url>"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
  processor: "./load-functions.js"
before:
  flow:
    - function: "seedingHelper"


scenarios:
  - name: "Balance"
    flow:
      - post:
          url: "/test"
          Content-Type: "application/xml"
          body: 
```

In the case above function is not called. However, it works with `beforeRequest` or `beforeScenario`

```
config:
  target: "<url>"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
  processor: "./load-functions.js"


scenarios:
  - name: "Balance"
    beforeRequest: "seedingHelper"
    flow:
      - post:
          url: "/test"
          Content-Type: "application/xml"
          body:
```
