### DISCUSSION TITLE
Can we run multiple processors?

### DISCUSSION THREAD

**Discussion by Evengelius** [artilleryio/artillery#1338] [Artillery]
Hello guys,

Can we run multiple processors for specific scenarios?

Like this for instance : 

```
config:
  target: "https://my-url.io/"
  payload:
    path: "../../data/feeders/login.csv"
    fields:
      - "username"
      - "password"
  phases:
    - duration: 1
      arrivalRate: 1
      rampTo: 1
      name: Running
  engines:
    playwright: {}
  processor: ["./login.js", "./navigation.js", "./homepage.js"]
scenarios:
  - name: "Authentication"
    engine: playwright
    flowFunction: "authenticationFlow"
  - name: "Navigation"
    engine: playwright
    flowFunction: "navigationFlow"
  - name: "Home Page"
    engine: playwright
    flowFunction: "homepageFlow"
```

So far I remember, we can only execute one processor..
