### DISCUSSION TITLE
Change config variables every duration?

### DISCUSSION THREAD

**Discussion by janrembold** [artilleryio/artillery#1342] [Artillery]
Hi,
to simulate new incoming users I need to update my socket.io auth variables on every duration.
The following code already creates a random auth string but only once for the whole test:

```
config:
  target: "http://localhost:3000"
  phases:
    - duration: 20
      arrivalRate: 10
  socketio:
    auth: 
      token: "{{ $randomString() }}"      

scenarios:
  - name: "Emit an event"
    engine: socketio
    flow:
      - emit:
          channel: "init"
```

Is this possible to rotate/update the `socketio.auth.token` for every duration? Or how would you tackle this scenario?

Thanks in advance!
Best, Jan
