### DISCUSSION TITLE
Playwright script failing with 'Error' in Artillery

### DISCUSSION THREAD

**Discussion by cbeach47** [artilleryio/artillery#1343] [Artillery]
Hello folks!

I am fairly new to Artillery, and have some experience with Playwright (PW).

I've developed a PW script that runs fine standalone, but needs the timeout bumped up to 60000 via the PW config object.

When I run the same script in Artillery, I get the following error. I'm thinking it has to do with the default PW timeout, but not sure how to tell Artillery to use a higher test timeout (or if that's even the issue). Any guidance would be appreciated!

```
worker error, id: 1 page.evaluate: Target closed
    at Page.<anonymous> (/Users/...../.nvm/versions/node/v15.14.0/lib/node_modules/artillery-engine-playwright/index.js:47:52) {
  name: 'Error'
}
```

My Artillery config:
```
config:
  target: https://artillery.io
  # Enable the Playwright engine:
  engines:
    playwright:
      timeout: 60000
  processor: "./tests/flows.js"
scenarios:
  - engine: playwright
    flowFunction: "helloFlow"
    flow: []
```

**Comment by hassy** [comment]
hi @cbeach47 👋 We don't have a way to customise the configuration of Playwright (like `timeout`) when used with Artillery yet (but we should). Are you encountering that error every time you run the script?

**Reply by cbeach47** [reply]
Hi @hassy - everytime  I run the PW script that takes longer then 30 seconds, that error occurs.

I can run other PW scripts that are shorter in duration and Artillery works just fine.

Can you think of any way to configure the PW script without global PW configuration for timeouts, or configure Artillery, to allow longer PW scripts to be used with Artillery?

**Comment by cbeach47** [comment]
Hi @hassy - just following up on this discussion.

**Comment by cbeach47** [comment]
Hi @hassy ! I've recently heard of some interest is using Playwright with Artillery again - do you know if progress has been made with being able to customize the configuration of Playwright?

**Reply by hassy** [reply]
hi @cbeach47 👋 yes indeed, please see https://github.com/artilleryio/artillery-engine-playwright#configuration

**Reply by sambordo1** [reply]
hi @cbeach47  or @hassy I see you figured this issue out so I was wondering if you could help me. I am using 

```
engines:
    playwright:
      launchOptions:
        headless: false
      contextOptions:
        storageState: '.auth/local-user.json'
      defaultTimeout: 120
```

I see in the above link that defaultTimeout takes in a number in seconds and is under playwright instance. It seems to be completely ignoring my defaultTimeout. I am wondering if you could let me know how i'm configuring this wrong. I am very new to playwright and artillery and would really appreciate the help. Thanks!
