### DISCUSSION TITLE
How to handle nested json as payload ?

### DISCUSSION THREAD

**Discussion by blassaut** [artilleryio/artillery#1356] [Artillery]
Hello,

I'm quite new to artillery. I'm currently testing it in order to know if it's the correct choice to perform load testing / concurrent testing.

I have a question about the payload and how it is possible to handle nested json ? I didn't find any recipe in the documentation.

Let's say I would like to to use this json : 

```json
{"inputs": 
				[
	        		{
			            "name": "image_input",
			            "data": {
					                "type": "image",
					                "value": "my-url"
		            			}
	        		},
	        		{
			            "name": "context",
			            "data": {
					                "type": "text",
					                "value": "my-context"
		            			}
	        		}
    			]	
}
```

How can I load it using artillery with a csv file :     

```yml
path: "test.csv"
      fields:
        - "inputs"
```

And in the scenario part : 

```yml
- post:
          url: "/orders/"
          headers:
            authorization: "Token {{ $processEnvironment.API_KEY }}"
          json:
            inputs: "{{ inputs }}"
```

How should I build the csv and/or the yml part ?

I did not find any information on the doc on this matter.

Thank you for your help

**Comment by blassaut** [comment]
All good :) I found the answer

**Reply by hassy** [reply]
What did you end up doing @blassaut?

**Reply by blassaut** [reply]
In the yml:

```yml
json:
            inputs:
            - name: image_input
              data:
                type: image
                value: "{{ url }}"
            - name: context
              data:
                type: text
                value: "{{ context }}"
```

and in the csv:

```csv
url,context
my_url,my_context
```
