### DISCUSSION TITLE
Upgrading from v1.6.2 to latest

### DISCUSSION THREAD

**Discussion by mellema** [artilleryio/artillery#1367] [Artillery]
I'm upgrading from v1.6.2 and finding breaking changes. Are these documented somewhere? Here's my first problem. 

```
before:
  flow:
    - loop:
        - post:
            url: "/api/auth"
            json:
              method: "login"
              arguments:
                email: "{{$loopElement}}"
                password: "Pass1234"
```

This works fine in v1.6.2 but I'm getting a 400 bad request error when I try to run it in the latest version. I examined the requestParams under both versions and see some differences. v1.6.2 has this but the latest version does not:

```
jar: RequestJar {
    _jar: CookieJar { enableLooseMode: true, store: { idx: {} } }
  },
````
