### DISCUSSION TITLE
TypeError [Error]: Cannot read properties of undefined (reading 'undefined')

### DISCUSSION THREAD

**Discussion by ligonsk** [artilleryio/artillery#1386] [Artillery]
I want to do a simple load test where users just go to the specific end point. My endpoint actually opens a web socket connection from a php app so I want to see if the connection is established, but I get

> worker error, id: 1 TypeError [Error]: Cannot read properties of undefined (reading 'undefined')

This is my basic script:

```
config:
  target: "http://10.0.2.25"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 600
      arrivalRate: 50
      name: Sustained load
  scenarios:    
      flow:
        - think: 600 # do nothing for 10m and disconnect
```

I saw other post regarding this issue and he mentioned tabbing issue, but I don't see a tab issue if I do have one

I also tried to change the `scenarios` part to `GET`:

```
  scenarios:    
      flow:
        - get:
              url: "/"
```

But same error.
