### DISCUSSION TITLE
Changing Target url with every virtual user

### DISCUSSION THREAD

**Discussion by akhiljay** [artilleryio/artillery#1448] [Artillery]
I have a use case where the target url changes with every virtual user that is created. Is there a way for artillery to accommodate that?

**Comment by hassy** [comment]
yes, use a full URL in your request spec. Relative URLs use target, otherwise the URL that's provided will be used.

**Reply by akhiljay** [reply]
Thank you, so it can look something like this? 
````
scenarios:
  - flow:
      - loop:
          - get:
              url: "/products/{{ $loopElement }}"
        over:
          - id123
          - id456
          - id789
  ````
