### DISCUSSION TITLE
Multiple Configs and Processors

### DISCUSSION THREAD

**Discussion by ramgiteng** [artilleryio/artillery#1471] [Artillery]
Hello,

I am trying to create a complex config.yml file, which consists of a combination of configurations. I would like to create multiple configs - each of which has its own set of processors, load phases, and scenarios.

### Use Case: 
To Combine multiple configs and/or processors in the **_same YAML file_**

### YAML File 1:
```
config:
  target: "http://www.lambdatest.com"
  processor: "../Script1.js"
  phases:
    - duration: 15
	  arrivalCount: 3
scenarios:
  - flow:
    - function: "function1"
config:
  target: "http://www.lambdatest.com"
  processor: "../Script2.js"
  phases:
    - duration: 15
	  arrivalCount: 3
scenarios:
  - flow:
    - function: "function2"
```

### YAML File 2:
```
config:
  target: "http://www.lambdatest.com"
  processor: "../Script1.js"
  phases:
    - duration: 15
       arrivalCount: 3
  processor: "../Script2.js"
  phases:
    - duration: 15
       arrivalCount: 3	
scenarios:
  - flow:
    - function: "function1"
  - flow:
    - function: "function2"
```

### Expected Outcome:
Using either one of the above configurations, ../Script1.js to execute first with its specified load phases and corresponding scenario (function 1) **before** executing ../Script2.js with its corresponding load phases and scenario (function 2).

### Actual Outcomes:

- YAML File 1: Artillery complains about using multiple configs.
- YAML File 2: Artillery complains about using a duplicate "processor"

### Questions:

1. How can we model a workload scenario using Artillery to use multiple configs (each config has its own set of configurations like load phases, processor, scenarios) such that each config is executed sequentially?
2. How can we run multiple config.yml files **sequentially** using `artillery run config1.yml config2.yml`? (This seems to run both config.yml files simultaneously)
