### DISCUSSION TITLE
Capture raw HTML body that's not in a JSON

### DISCUSSION THREAD

**Discussion by ron-hiner-anttila** [artilleryio/artillery#1476] [Artillery]
Version info: artillery/2.0.0-3 win32-x64 node-v16.15.0

I have a security token swap where the swapped token is delivered not as a JSON but just as raw html in the body.  The first capture is a json so that works as expected.  I've tried a variety of json and xpath methods and none of them are capturing the data.  I've tried "$", "$.", (those are dollar signs not showing up) "\$.value", "/".  Is there a way for me to accomplish this?

----------------------------
```
config:
  target: 'url'
  phases:
   - duration: 1
     arrivalRate: 1

before:
  flow:
    - log: "Get auth token"
    - post:
        url: "Auth0TokenUrl"
        json:
          grant_type: "xxx"
          client_id: "xxx"
          realm: "xxx"
          scope: "openid profile email offline_access"
          audience: "xxx"
          username: "xxx"
          password: "xxx"
        capture:
            json: "$.access_token"
            as: "token"
        expect:
          - statusCode: 200
    - post:
        url: "JwtTokenSwapUrl"
        headers: 
          Authorization: "Bearer {{ token }}"
        capture: 
          xpath: "/"
          as: "swappedToken"
        
scenarios:
 - flow:
   - log: "Token: {{ swappedToken }}"
   - get:
      headers:
        Authorization: 'Bearer {{ swappedtoken }}'
      url: "/"
```
--------------------------------

Here's an example response:

```
2022-06-07T17:02:16.479Z http:response "superLongStringofRandomChars"
2022-06-07T17:02:16.479Z http captures and matches:
2022-06-07T17:02:16.479Z http {}
2022-06-07T17:02:16.479Z http { swappedToken: { value: '', strict: undefined, failed: true } }
[1] Failed capture or match error
```

Thanks for any help!

**Comment by hassy** [comment]
hi @ron-hiner-anttila! 

Depending on HTML markup, a regular expression or a Cheerio selector should work (https://www.artillery.io/docs/guides/guides/http-reference#extracting-and-re-using-parts-of-a-response-request-chaining)

Do you have an example full response from the service you're trying to capture? (feel free to redact as needed)

**Reply by ron-hiner-anttila** [reply]
Hello @hassy, thank you for the quick reply!  Of course, below is the raw html response (with the token shortened for readability).  You can see the only thing in the body is the plain token string.  

`HTTP/1.1 200 
Content-Type: text/plain;charset=UTF-8
Content-Length: 921
Connection: keep-alive
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
Date: Wed, 08 Jun 2022 12:33:48 GMT
X-Kong-Upstream-Latency: 197
X-Kong-Proxy-Latency: 1
Via: kong/2.1.4

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJSRUFEOlBSQUNUSUNFIiwiTUFOQ...`

**Reply by hassy** [reply]
No worries! I've set a mock endpoint which returns a `text/plain` response with that string here:

https://run.mocky.io/v3/8b383570-ff2d-4fbc-8c0c-1d9ddda6095b

We can ping it with `artillery probe` to confirm:

```
$ artillery probe -b https://run.mocky.io/v3/8b383570-ff2d-4fbc-8c0c-1d9ddda6095b

Connected to https://run.mocky.io/v3/8b383570-ff2d-4fbc-8c0c-1d9ddda6095b (185.42.117.109)

HTTP/1.1 200 OK
content-type: text/plain; charset=UTF-8
date: Wed, 08 Jun 2022 15:56:15 GMT
content-length: 86
sozu-id: 01G520FQRCQNMW9541W5TEEQ6P


 DNS Lookup | TCP Connection | SSL Handshake | Time to First Byte | Content Transfer
  2ms       |  31ms          |     66ms      |     41ms           |   5ms           |
            |                |               |                    |                 |
            2ms              |               |                    |                 |
                          33ms               |                    |                 |
                                           99ms                   |                 |
                                                                141ms               |
                                                                               total:146ms


Body stored in: /var/folders/yd/nyh8vtm17w92h5hm4pdhs8j00000gn/T/202258-49829-j4nqbe.8ywuf.txt

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJSRUFEOlBSQUNUSUNFIiwiTUFOQ
```

And we can capture that with a `regexp` like this:

```yaml
config:
  target: "https://run.mocky.io"
scenarios:
  - flow:
    - get:
        url: "/v3/8b383570-ff2d-4fbc-8c0c-1d9ddda6095b"
        capture:
          - regexp: '.*'
            as: plainTextResponse
    - log: "got back: {{ plainTextResponse }}"
```

▶️ Live runnable example of the script here:

https://superrepl.com/?s=d76cdad8-104b-4127-85b0-f38fd49815b9
