### DISCUSSION TITLE
Dynamic payload csv

### DISCUSSION THREAD

**Discussion by efabisze** [artilleryio/artillery#1479] [Artillery]
So, is it possible to generate the contents of the payload csv and use the new contents?  Whenever I use the scenario below, the contents uses "old" data from the csv file instead of the new data, seems like the payload is saved during the config, but is there any way to change it to the new data?

Payload designation in config:
```
 payload:
    path: "timeslots.csv"
    fields:
      - "fileStartDateTime"
    order: sequence
```

Calling function in before section:
```
before:
  flow:
    - function: "beforeRequestTimeSlot"
scenarios:
```

Code that generates contents of csv:
```
    function allTimeSlots(response) {

        var fs = require('fs');
        console.log("In alltimeslots function")

        let allTimeSlots = [];
        let availTimeSlots = response.dates[0].availableTimeSlots;


        let timeOfDayTimeslots = availTimeSlots.map(timeOfDay => {
            return timeOfDay.timeSlots.map(timeSlots => {
                return timeSlots.startDateTime;
            })
        })


        timeOfDayTimeslots.forEach(x => {
            allTimeSlots.push(x);
        })

        allTimeSlots = allTimeSlots.flat();
        console.log("All Time Slots : " + allTimeSlots);

        const path = require("path");
        fs.writeFileSync(path.resolve(__dirname, "./timeslots.csv"), allTimeSlots.join('\n'));
        
}
```
