### DISCUSSION TITLE
How to trigger a failure for current worker?

### DISCUSSION THREAD

**Discussion by eliezercazares** [artilleryio/artillery#1491] [Artillery]
Hello, I am using Socket.io Engine v3, hence, Expect Assertions are not working.

But I wrote a custom function called "validateResponse()" and in this function I verify the "Capture:" I did before on YAML.

Something like:

Yaml
```
- emit: [ "x", "y" ]
   response:
      on: "x-response"
      capture:
          json: "$.status"
          as: "lastStatus"
- function: "validateResponse"
- emit: [ "a", "b" ]
   response:
      on: "a-response"
      capture:
          json: "$.status"
          as: "lastStatus"
- function: "validateResponse"
```

Custom.js
```
function validateResponse(userContext, events, done) {
   if( userContext.vars.lastStatus != "success" ) {
      **CAN I HAZ THROW ERROR HERE PLZ**
   }
}
```

@hassy hope you can help me man, so far I have not been able to do assertions on socket io, but if I'm only able to throw errors in custom function I will be able to programatically.

This is an example of how I am performing my validations while Expect Plugin extends support to Socket.io, as we can capture many values, we can have more specific methods for validations such as ValidateResponseIsEqual, etc...

But right now, I cannot throw an error. Test moves on of course as I am not able to throw an error that finishes the current worker.

**Comment by hassy** [comment]
hi @eliezercazares - you should be able to callback `done()` with an error to have it logged in the output, and to stop the virtual user. e.g.:

```js
function validateResponse(userContext, events, done) {
   if(userContext.vars.lastStatus != "success" ) {
      return done(new Error('last status is not success'));
   } else {
     return done(); // no error, everything is OK
   }
}

```

**Reply by eliezercazares** [reply]
> hi @eliezercazares - you should be able to callback `done()` with an error to have it logged in the output, and to stop the virtual user. e.g.:
> 
> ```js
> function validateResponse(userContext, events, done) {
>    if(userContext.vars.lastStatus != "success" ) {
>       return done(new Error('last status is not success'));
>    } else {
>      return done(); // no error, everything is OK
>    }
> }
> ```

That it's awesome! I had to remove the "return" statement but it works perfectly!
I love it, I can now assert in Socket.io

If it's no bother, it's there anyway I can get the current "emit" or "request" name (supposing I am setting a name), something like:

```
- emit: ["addMessage", "Hello world!"]
   name: "Salutation message"
   response:
      ...
```

Then in our "validateResponse" method:
```
function validateResponse(userContext, events, done) {
   if(userContext.vars.lastStatus != "success" ) {
      return done(new Error(`status for $userContext.vars.currentRequest.name is not success`));
   } else {
     return done(); // no error, everything is OK
   }
}
```

Of course "userContext.vars.currentRequest.name" would return undefined, but I hope I can explain myself.

I tried looking into:
"events._events.summary.context._events.summary.context 

But I can keep adding "_events.summary.context" and I can never log what it's inside. Looks like a circular reference or something.
