### DISCUSSION TITLE
check for bot response time websocket chat

### DISCUSSION THREAD

**Discussion by suyash-nexxt** [artilleryio/artillery#1503] [Artillery]
Hi Team, 

I'm new to artillery and wanted to ask ya'll if what I am seeking to achieve is possible with artillery. I have a chatbot (websocket) where users interact with a bot. Now in my test I have set up virtual users to send messages. This part is fine but I also want to check the response time of bots reply to users. Is it possible and if yes can you direct me to what I should be looking for?

Thanks!

**Comment by eliezercazares** [comment]
Hi suyash, sockets or websockets do not send responses.
Verify if your server side is using Acknowledgements, or that server it's emitting back to the socket id it corresponds, and that your client catches and handles that event from server.
If you do this, you can set up a function in your processor file that stores the timestamp in userContext.vars.eventNameStartTimestamp if not set (call it on your emit from client side), and then when your client app catches the event or acknowledgement serving as a response, you set another variable, userContext.vars.eventNameStopTimestamp..
immediately you can do a minus StartTimestamp and store it in another variable:
userContext.vars.eventNameEffectiveTime

and proceed to do as you wish with it.

**Reply by suyash-nexxt** [reply]
Hi eliezer, thank you for your reply.  Will it be possible to capture response on artillery if we are using native web socket (engine: ws)?

**Reply by eliezercazares** [reply]
Hi Suyash,
sure it is.. however Expect plugin won't work... you can base your code on this YAML:
```
      - emit: [ "myEvent", "{{ myEventData }}" ]
        response:
          on: "myEventReply"
          capture:
            json: "$.success"
            as: "myEventReplyPayload"
        #  expect:
        #    - contentType: json
        #    - hasProperty: success
        #    - equals:
        #      - true
        #      - "{{ myEventReplyPayload }}"
      - function: "acknowledgedSuccessfully" # verify if .success == true using userContext.vars.myEventReplyPayload
      - log: "Response of myEvent: {{ myEventReplyPayload }}"
```

See how I am using a function named acknowledgedSuccessully as the workaround for expect plugin, according to @hassy  we might see Expect support soon. :D
