### DISCUSSION TITLE
Templated values in default cookies not supported?

### DISCUSSION THREAD

**Discussion by Zodiase** [artilleryio/artillery#1552] [Artillery]
First just to clarify, `scenarios.flow.*.cookie.*` works as expected.

The questions I have are only about default cookies. And there are 2 parts.

## Part 1
I was hoping to set `context.vars.foobar = "123"`, for example, from the `beforeScenario` hook and change the cookie values dynamically. This doesn't seem to work if I have a cookie in the default cookies, such as:
```
config:
  defaults:
    cookie:
      some-cookie: "{{ foobar }}"
```
When monitoring network traffic I can see I always get `some-cookie: undefined`.

## Part 2
What's more frustrating is that even setting the context variable values with the `--variables` option doesn't work for default cookies either.
If I use option `--variables` with `{foo: 1, bar: 2}`, and this config:
```
config:
  defaults:
    cookie:
      foo: "{{ foo }}"
scenarios:
  - name: "bar"
    flow:
      - get:
        cookie:
          bar: "{{ bar }}"
```
I would see these cookies in traffic:
```
foo: undefined
bar: 2
```

----

I'd like to use default cookies for cookies that are shared across scenarios and steps, such as authentication and session cookies. Is there a way I'm missing, other than copy-pasting the same templated cookies everywhere?
