### DISCUSSION TITLE
Playwright engine and basic auth

### DISCUSSION THREAD

**Discussion by tchambers97** [artilleryio/artillery#1580] [Artillery]
I want to use the artillery playwright engine to load test a site that requires basic HTTP authentication. Are there any examples of this being done? Thanks.

**Comment by hassy** [comment]
hi @tchambers97 👋 where do the logins credentials get loaded from, a static file (e.g. a CSV file), or does the test need to fetch them first from somewhere else dynamically?

**Reply by tchambers97** [reply]
We generally load basic creds from a static file.

**Reply by tchambers97** [reply]
I should be more specific, we load them from a dotenv file.

**Reply by hassy** [reply]
Using a dotenv file makes it pretty straightforward to load those credentials! `artillery run` command has a [`--dotenv` flag](https://www.artillery.io/docs/guides/guides/command-line#options) which accepts dotenv files. Any values in a dotenv file can then be read through the special [`$processEnvironment`](https://www.artillery.io/docs/guides/guides/command-line#options) variable.

To pass a username/password loaded from a dotenv file to Playwright, we can use the [`httpCredentials`](https://playwright.dev/docs/api/class-browser#browser-new-context-option-http-credentials) option. We just released an update to Artillery's Playwright integration which allows for those options to be customized.

Your test script's `config` section would look something like:

```yaml
config:
  target: "https://example.net"
  engines:
    playwright:
      contextOptions:
        httpCredentials:
          username: "{{ $processEnvironment.USERNAME }}"
          password: "{{ $processEnvironment.PASSWORD }}"
```

with a dotenv file that looks like:

```
USERNAME=hassy
PASSWORD=pony1
```

And you'd run the test with:

```sh
artillery run --dotenv .env.example my-test.yml
```

Note that this requires the most recent release (v0.1.0) of `artillery-engine-playwright` to work.

Please let me know if that solves this for you!
