### DISCUSSION TITLE
playwright engine is not loading contextOptions

### DISCUSSION THREAD

**Discussion by mianali** [artilleryio/artillery#1583] [Artillery]
I am trying to to use the playwright contextOptions, and it is not taking the configuration that I use.
Is there something wrong in my config?

```
config:
  target: https://artillery.io
  # Enable the Playwright engine:
  engines:
    playwright:
      contextOptions:
        storageState: "auth.json"
  processor: "./flows.js"
scenarios:
  - engine: playwright
    flowFunction: "helloFlow"
    flow: []
```

**Comment by hassy** [comment]
hi @mianali 👋 

The configuration looks right.

Are you using the most recent version of `artillery-engine-playwright`?

and how are you checking whether the option is being applied or not?

**Reply by mianali** [reply]
Hello @hassy 
no, I was using a previous version, I upgrade to 2.0.0-23 and Its woks now. Thank you.
But also I was trying to use the **beforeScenario** hooks, and does not work anyway.

This is my config now

```
config:
  target: https://artillery.io
  # Enable the Playwright engine:
  engines:
    playwright:
      contextOptions:
        storageState: "auth.json"
  processor: "./flows.js"
scenarios:
  - name: "Example"
    engine: playwright
    beforeScenario: "mybeforescenario"
    flowFunction: "helloFlow"
    flow: []
```



this is my flow.js

```
module.exports = { helloFlow, mybeforescenario };

async function helloFlow(page) {
    console.log('********** IN scenario **********');    
    //
    // The code below is just a standard Playwright script:
    //
    // Go to https://artillery.io/
    await page.goto('https://artillery.io/');
    // Click text=Pricing
    await page.click('text=Pricing');
    // assert.equal(page.url(), 'https://artillery.io/pro/');
    // Click text=Sign up
    await page.click('text=Sign up');
}

async function mybeforescenario(context, ee, next) {
    console.log('********** before scenario **********');
    return next();
}
```

when I run this I see in console the Log "IN Scenario" but I don't see the "before scenario"


thank you very much for your time
