### DISCUSSION TITLE
Is the documentation for turning off strict capture incorrect?

### DISCUSSION THREAD

**Discussion by smacktoid** [artilleryio/artillery#1601] [Artillery]
The docs section describing [how to turn off strict capture](https://www.artillery.io/docs/guides/guides/http-reference#turn-off-strict-capture) appears to have a syntax error.

```
- get:
    url: "/"
    capture:
      json: "$.id"
      as: "id"
    strict: false # We don't mind if `id` can't be captured and the next requests 404s
- get:
    url: "/things/{{ id }}"
```

The `strict: false` setting is applied at the same level as `capture`, which didn't seem to work for me. It wasn't until I shifted it in line with a specific capture item that it started to work.

i.e. this fails, but appears to align with the documentation:

```
    capture:
            - json: "$..messages[(@.length-1)].id"
              as: last_message_id
    strict: false
```

But this appears to work:

```
    capture:
            - json: "$..messages[(@.length-1)].id"
              as: last_message_id
              strict: false
```

Am I right? Do the docs need a slight change here?
