### DISCUSSION TITLE
Running the Artillery Hello World

### DISCUSSION THREAD

**Discussion by mission-lblaney** [artilleryio/artillery#1604] [Artillery]
If you run the artillery "hello world" from the docs...

```
config:
  target: https://artillery.io
  phases:
    - duration: 60
      arrivalRate: 10
    - duration: 600
      arrivalRate: 100
scenarios:
  - flow:
      - get:
          url: "/"
      - get:
          url: "/docs"
```

Your IP gets black listed and you are not able to access the site anymore =/ 

![image](https://user-images.githubusercontent.com/108361700/191024441-9b875cd5-50e8-432f-a553-f3bfa13ef4ad.png)
