### DISCUSSION TITLE
How to use unique data for each instance?

### DISCUSSION THREAD

**Discussion by vibha-w3w** [artilleryio/artillery#1609] [Artillery]
Hi,

I have to perform a load testing which takes existing users. This could read from a csv/variable/custom function. But, I need to have a load higher than 1 user/sec (maybe 100users/sec). But each instance should pick up a unique user from test dataset. There will be enough testdata for all instances so that it need not repeat.

I have tried reading from csv with sequence order, writing my own function and also adding in variable. This seems to work fine if I have `arrivalRate` as 1. When I increase this, the instances seem to pick up same user.

Example:
  ```
config:
  payload:
    -
      path: "users.csv"
      fields:
        - "username"
        - "password"
      order: sequence
      skipHeader: true
      loadAll: true
  phases:
    - duration: 5
      arrivalRate: 2
```
will pick users like
```
⠼ user1@example.com
user1@example.com
⠧ user2@example.com
user2@example.com
⠏ user3@example.com
user3@example.com
⠙ user4@example.com
user4@example.com
Phase completed: 

user5@example.com
user5@example.com
```
whereas I am expecting it to use
```
⠼ user1@example.com
user2@example.com
⠧ user3@example.com
user4@example.com
⠏ user5@example.com
user6@example.com
⠙ user7@example.com
user8@example.com
Phase completed: 

user9@example.com
user10@example.com
```
Is there any way to achieve this?
