### DISCUSSION TITLE
Encrypt/Decrypt

### DISCUSSION THREAD

**Discussion by disciplezero** [artilleryio/artillery#1630] [Artillery]
Hi there,

I'm working with an API that requires a hash added to every request, and responds with an encoded response. Artillery is giving me a series of odd issues that I'm hoping there's a way to work around. Here's a sample of what I'm working with:

```
config:
  target: "https://example.com"
  processor: "script.js"
  phases:
    - duration: 1
      arrivalRate: 1
  variables:
    api_key: AK_1234567890
    user_id: UID_1234567890
scenarios:
      - post:
          url: /api/login
          beforeRequest:
            - signRequest
          form:
            api_key: "{{ api_key }}"
            user_id: "{{ user_id }}"
          afterResponse:
            - decodeResponse
          capture:
            json: $.session.access_key
            as: access_key
```

There are two problems. 

1. When signRequest is called, the variables in the form haven't been expanded yet. So I have to manually fill out those fields. This is doable, but makes it hard to maintain a general solution.
2. Decode response is called after capture is attempted and fails. I need to be able to decode the response and provide the json as a result.

I can work around both of these issues, but it requires putting a lot more code into the processor. Is there something I'm missing?

Thanks!
