### DISCUSSION TITLE
How can I capture dynamic payload data from the function before post request?

### DISCUSSION THREAD

**Discussion by rohitpatil7892** [artilleryio/artillery#1670] [Artillery]
I am trying to create dynamic data and wanted to use this data as a post-request payload. How can I capture this data from a function and how to use it in the request payload 
My current script is as follows
```

config:
  environments:
    test:
      target: "https://my-test-request"
      phases:
        - duration: 10
          arrivalRate: 10
          maxVusers: 10
      processor: "./processor.js" 

scenarios:
  - flow:
    - function: "calculatePayload"
      capture:
        - json: "$"
          as: data
    - post:
        url: "/poatApi"
        json: "{{data}}"
        expect:
          - statusCode: 200
```

and my customer function is

```
async function calculatePayload() {
  console.log('inside Requests');
  let data = [
    {
      "name": "sample data array"
      ]
    }
  ]
  return data
}
```

If it's possible then please help me or else please suggest any other option ( I don't want to use a CSV file )
thanks in advance :)

**Comment by juanig1** [comment]
Hey!
[This part](https://www.artillery.io/docs/guides/guides/http-reference#loading-custom-js-code) of the documentation provides a really similar example to yours (via [beforeRequest](https://www.artillery.io/docs/guides/guides/http-reference#beforerequest-hooks)).
I suggest checking it out!

That being said, something like this should work:

modified script:
```
config:
  environments:
    test:
      target: "http://0.0.0.0:8080"
      phases:
        - duration: 10
          arrivalRate: 10
          maxVusers: 10
      processor: "./processor.js"

scenarios:
  - flow:
    - post:
        url: "/postApi"
        beforeRequest: "calculatePayload"
        json: "{{ data }}"
```

modified processor:
```
module.exports = { calculatePayload };
function calculatePayload(requestParams, context, ee, next) {
  let data = [
    {
      "name": "sample data array"
    }
  ]
  context.vars['data'] = data;
  return next();
}
```

Running `artillery run index.yaml --environment test` against netcat (`nc -l 8080` in a new terminal) nets me:
```
POST /postApi HTTP/1.1
user-agent: Artillery (https://artillery.io)
content-type: application/json
content-length: 30
Host: 0.0.0.0:8080
Connection: keep-alive

[{"name":"sample data array"}]
```

Good luck!
