### DISCUSSION TITLE
issue: Cannot read properties of undefined (reading 'createScenario')

### DISCUSSION THREAD

**Discussion by rajeet** [artilleryio/artillery#1694] [Artillery]
---
config:
  target: https://socket.url.com
  phases:
    - duration: 5
      arrivalRate: 1
  engine: 
    socketio-v2: 
      path: "/driver"
      query: "uid=132&key=xxxxxxxx"
scenarios:
  - name: First Scenario
    engine: socketio-v2
    flow:
      - emit:
          channel: data
      - response:
          channel: data

<img width="974" alt="Screenshot 2022-11-19 at 12 19 06" src="https://user-images.githubusercontent.com/6507257/202838004-a9ce153f-9bea-41f8-b04e-349cae7fac84.png">

Hello, Here I have same issue with undefined (reading 'createScenario')

**Comment by juanig1** [comment]
Hi!
Seems it's not picking up the engine (that error could be a little more descriptive, noted).
You are using `config.engine`, but it should be `config.engines`.
Something like this should work (simpler version, relevant links [socketio-v2 doc](https://github.com/pudkrong/artillery-engine-socketio-v2#install--configure) and [our socketio docs](https://www.artillery.io/docs/guides/guides/socketio-reference)):
```
config:
  target: https://socket.url.com
  phases:
    - duration: 5
      arrivalRate: 1
  engines:
    socketio-v2: {}
scenarios:
    - name: First Scenario
      engine: socketio-v2
      flow:
        - emit:
            channel: "data"
            data: "data"
```
