### DISCUSSION TITLE
Converting HTTP response into individual virtual user sessions

### DISCUSSION THREAD

**Discussion by adamfisher** [artilleryio/artillery#1705] [Artillery]
I get an array of member IDs in the **before** block successfully and store it in the `memberIds` variable which may contain thousands of IDs. The `memberIds` are then used in the **scenario** block to iterate over each user and simulate getting their offers. The problem is Artillery only sees this is a single virtual user but I would like each memberID to be a separate virtual user that calls to get their offers individually. So if `memberIds.count == 500` then there should be `vusers == 500`. Any way to achieve this?

```yml
config:
  http:
    timeout: 90
  target: "https://example.com"
    variables:
      apiKey: "1234"
      campaignId: "5678"
phases:
  - name: "Get Members"
    duration: 10
    arrivalRate: 20
before:
  flow:
    - log: "Get member IDs for the Campaign"
    - get:
        url: "/api/getmembers/{{ campaignId }}"
        headers:
          X-ApiKey: "{{ apiKey }}"
        capture:
          - json: "$"
            as: "memberIds"
scenarios:
  - name: "Load Member Offers"
    flow:
      - loop:
          - get:
              url: "/api/getoffers/{{ $loopElement }}"
              headers:
                X-ApiKey: "{{ apiKey }}"
              expect:
                - statusCode: 200
                - contentType: json
                - hasProperty: CustomerId
        over: memberIds
```
