### DISCUSSION TITLE
Can DEBUG print only errors?

### DISCUSSION THREAD

**Discussion by tchambers97** [artilleryio/artillery#1736] [Artillery]
Hi! I was wondering if http debug could be used to return only errors. I'm seeing about a 1.5% failure rate when running a load test, failing either because the GraphQL endpoint returned an error or there was a capture error. Turning on even just `DEBUG=http` is too much data to look through. Any way to filter that further? 
Thanks!

**Comment by hassy** [comment]
hi @tchambers97 👋 There isn't a way to do it with `DEBUG` (it prints everything out by design), but this is a great candidate for a bit of custom JS. Do those errors only happen when you run a test from AWS, or also when you run them locally?

**Reply by hassy** [reply]
I'll see if I can put an example together quickly

**Reply by tchambers97** [reply]
Thanks, Hassy! This occurs with both AWS and local testing :)

**Reply by hassy** [reply]
Haven't forgotten about this, just haven't quite managed to take a proper look yet. But just had an idea for you to try in the meantime.

You could try loading the [`expect` plugin](https://www.artillery.io/docs/guides/plugins/plugin-expectations-assertions) and configuring it to print the details of failed expectations with the `prettyError` formatter. Something like this:

```yaml
config:
  target: https://my.app
  plugins:
    expect:
      outputFormat: prettyError
```

You can then add status code expectations to requests, e.g.:

```yaml
- post:
    url: "/some/endpoint"
    json:
      somekey: somevalue
    expect:
      - statusCode: 200
```

With the plugin enabled & expectations set, any time an expectation fails (e.g. an endpoint returns 500), the plugin will print the details (headers, body) etc.
