### DISCUSSION TITLE
Is there any way to see benchmark per scenarios ?

### DISCUSSION THREAD

**Discussion by abcfy2** [artilleryio/artillery#1745] [Artillery]
Now I get summary output is :

```
--------------------------------
Summary report @ 16:19:25(+0800)
--------------------------------

errors.EAI_AGAIN: .............................................................. 12
errors.ECONNRESET: ............................................................. 1415
errors.EINVAL: ................................................................. 6
errors.EMFILE: ................................................................. 84115
errors.ENOTFOUND: .............................................................. 4
errors.ETIMEDOUT: .............................................................. 457368
http.codes.200: ................................................................ 694
http.codes.201: ................................................................ 123767
http.codes.500: ................................................................ 134759
http.codes.504: ................................................................ 180
http.request_rate: ............................................................. 80/sec
http.requests: ................................................................. 802320
http.response_time:
  min: ......................................................................... 3
  max: ......................................................................... 30019
  median: ...................................................................... 645.6
  p95: ......................................................................... 28862.3
  p99: ......................................................................... 29445.4
http.responses: ................................................................ 259400
vusers.completed: .............................................................. 259400
vusers.created: ................................................................ 802320
vusers.created_by_name.GET /mint-request/:targetToken: ......................... 200370
vusers.created_by_name.POST /mint-request (offchain): .......................... 200415
vusers.created_by_name.POST /mint-request (onchain): ........................... 200561
vusers.created_by_name.POST /verify-link: ...................................... 200974
vusers.failed: ................................................................. 542920
vusers.session_length:
  min: ......................................................................... 10.3
  max: ......................................................................... 30026.6
  median: ...................................................................... 658.6
  p95: ......................................................................... 28862.3
  p99: ......................................................................... 29445.4
vusers.skipped: ................................................................ 3704120
Log file: result.json

Estimated AWS Lambda cost for this test: $2.0459
```

It only show global

```
http.codes.200: ................................................................ 694
http.codes.201: ................................................................ 123767
http.codes.500: ................................................................ 134759
http.codes.504: ................................................................ 180
http.request_rate: ............................................................. 80/sec
http.requests: ................................................................. 802320
http.response_time:
  min: ......................................................................... 3
  max: ......................................................................... 30019
  median: ...................................................................... 645.6
  p95: ......................................................................... 28862.3
  p99: ......................................................................... 29445.4
```

Is there any way to show these metrics per scenarios?
