### DISCUSSION TITLE
Playwright & chromium launch arguments

### DISCUSSION THREAD

**Discussion by suchcodewow** [artilleryio/artillery#1759] [Artillery]
I'm looking to reduce the cpu/memory footprint with chromium launch arguments.  I saw the artillery yaml files supported 'headless' similar to the playwright config file.

But is there support for passing along launch arguments to chromium?  I'm guessing the disable-gpu, etc, args would be helpful- but I didn't see support for it in the templates.

Thanks,

**Comment by suchcodewow** [comment]
This works just fine:
```
  engines:
    playwright:
      launchOptions:
        headless: false
        args: [--disable-gpu-sandbox, --auto-open-devtools-for-tabs]
```
