### DISCUSSION TITLE
Setting Artillery tests to run on CI (using GitHub Actions)

### DISCUSSION THREAD

**Discussion by ArCiGo** [artilleryio/artillery#1770] [Artillery]
I set my YAML file as the documentation suggests, but when the CI/CD is triggered throws an error telling me that the `/home/node/artillery/bin/artillery` path does not exist.

My code looks like this:

```YAML
jobs:
  artillery:
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute load tests
        run: /home/node/artillery/bin/artillery run performanceTests/performance.yml
```

First question: How can I fix it?

On the other hand, I'm using **dotenv-cli** to pass the `target` as an env variable. Locally, everything works as expected (I just only run the following command: 

```shell
> npm run artillery:test
# artillery:test has the following structure: dotenv -- artillery run --output performanceResults/report.json performanceTests/performance.yml && artillery report --output performanceResults/report.html performanceResults/report.json
```

My **.env** file has the following structure:

```
# Artillery env variables
BASE_URL_TARGET=<theURL>
```

**performance.yml**:

```YAML
config:
  target: "{{ $processEnvironment.BASE_URL_TARGET }}"
  plugins:
    expect: {}
# rest of the code...
```

I set a repository secret in my repo, so every time that the CI is triggered it creates a **.env** file with the env variable that is used in my Artillery tests.

My second question is: How can I pass the env variable to the job? Do I need to install **dotenv-cli** in the job? This is an approach that I have:

```YAML
jobs:
  artillery:
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Writing .env file
         run: |
             echo '${{ secrets.ARTILLERY_ENV_CI }}' > .env
      - name: Execute load tests
        run: /home/node/artillery/bin/artillery run performanceTests/performance.yml
```

Thanks in advance for your help!

**Comment by hassy** [comment]
Thank you @ArCiGo. There's a bug in our docs, the `run` command should be:

```
run: /home/node/artillery/bin/run run performanceTests/performance.yml
```

Will update the docs, thank you!

**Reply by ArCiGo** [reply]
And about my second question, how can I pass the env variable that was stored in my `.env` that was created in the step `Writing .env variable`? Or is there another way to pass env variables stored in CI?

**Reply by hassy** [reply]
You don't need to create a `.env` file, you can create an environment variable from a secret in the GitHub Action, and then use that environment variable directly inside an Artillery test script via `$processEnvironment` variable.

So this:

```yaml
     - name: Execute load tests
        run: /home/node/artillery/bin/artillery run performanceTests/performance.yml
```

becomes:

```yaml
     - name: Execute load tests
       env:
        ARTILLERY_ENV_CI: "${{ secrets.ARTILLERY_ENV_CI }}"
       run: /home/node/artillery/bin/run run performanceTests/performance.yml
```

and inside `performance.yml`:

```yaml
config:
  target: "{{ $processEnvironment.ARTILLERY_ENV_CI }}"
```
