### DISCUSSION TITLE
Feature/Use environment variables with AWS Lambda

### DISCUSSION THREAD

**Discussion by nbrown-cmx** [artilleryio/artillery#1786] [Artillery]
Our team would like to use environment variable substitution (Detailed here: https://www.artillery.io/docs/guides/guides/test-script-reference#using-environment-varables) in test specs when running on the aws:lambda platform (Detailed here: https://www.artillery.io/docs/guides/guides/command-line#platform-aws-lambda-awslambda). These are both individually supported features, but are currently not compatible when used together.

The functional change is the lambda function's environment needs to be set with the desired environment variables. But we're uncertain what would be the best way to determine what environment variables should be set. Some options we've discussed:

- Adding new CLI option(s) to explicitly name the environment variables, and infer their values from the runtime environment
- Adding new CLI option(s) to provide the name and values of all environment variables needed in lambda
- Passing all environment variables currently defined in the runtime environment through to the lambda
- Passing only environment variables with an artillery specific prefix/suffix currently defined in the runtime environment through to the lambda's environment

Happy to work on the PR once the community agrees on how the environment variables should be specified.

**Comment by hassy** [comment]
hi @nbrown-cmx 👋 this is possible already with the [`--dotenv` flag](https://www.artillery.io/docs/guides/guides/command-line#set-scenario-variables-on-the-fly).

Quick example:

This test will make a GET request to 3 endpoints. The URLs are read from environment variables. We'll load the `metrics-by-endpoint` plugin to show the individual URLs in the report. If environment variables don't get set, we won't see any URLs in the report.

```yaml
config:
  target: http://asciiart.artillery.io:8080
  phases:
    - duration: 10
      arrivalRate: 1
  plugins:
    metrics-by-endpoint: {}
scenarios:
  - flow:
      - get:
          url: "{{ $processEnvironment.URL1 }}"
      - get:
          url: "{{ $processEnvironment.URL2 }}"
      - get:
          url: "{{ $processEnvironment.URL3 }}"
```

And a `vars.env` file:

```
URL1=/dino
URL2=/pony
URL3=/armadillo
```

Run the test with:

```sh
artillery run --platform aws:lambda --dotenv vars.env script.yml
```

And we should see something like:

```
All VUs finished. Total time: 12 seconds

--------------------------------
Summary report @ 16:58:29(+0000)
--------------------------------

http.codes.200: ................................................................ 30
http.request_rate: ............................................................. 4/sec
http.requests: ................................................................. 30
http.response_time:
  min: ......................................................................... 66
  max: ......................................................................... 68
  median: ...................................................................... 67.4
  p95: ......................................................................... 67.4
  p99: ......................................................................... 67.4
http.responses: ................................................................ 30
plugins.metrics-by-endpoint./armadillo.codes.200: .............................. 10
plugins.metrics-by-endpoint./dino.codes.200: ................................... 10
plugins.metrics-by-endpoint./pony.codes.200: ................................... 10
plugins.metrics-by-endpoint.response_time./armadillo:
  min: ......................................................................... 66
  max: ......................................................................... 68
  median: ...................................................................... 67.4
  p95: ......................................................................... 67.4
  p99: ......................................................................... 67.4
plugins.metrics-by-endpoint.response_time./dino:
  min: ......................................................................... 66
  max: ......................................................................... 68
  median: ...................................................................... 67.4
  p95: ......................................................................... 67.4
  p99: ......................................................................... 67.4
plugins.metrics-by-endpoint.response_time./pony:
  min: ......................................................................... 66
  max: ......................................................................... 68
  median: ...................................................................... 67.4
  p95: ......................................................................... 67.4
  p99: ......................................................................... 67.4
vusers.completed: .............................................................. 10
vusers.created: ................................................................ 10
vusers.created_by_name.0: ...................................................... 10
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 270.9
  max: ......................................................................... 301.8
  median: ...................................................................... 278.7
  p95: ......................................................................... 278.7
  p99: ......................................................................... 278.7

Estimated AWS Lambda cost for this test: $0.0012
```

Where we can see that `/pony`, `/armadillo` and `/dino` were hit as expected. 🎉
