### DISCUSSION TITLE
Unable to generate shared auth token in before block - function not executing

### DISCUSSION THREAD

**Discussion by noaheakin** [artilleryio/artillery#1811] [Artillery]
I am trying generate a single auth token before creating my VUs that can be shared by all request traffic. Your [documentation](https://github.com/artilleryio/artillery/blob/b4363a93f4c50046ede9b4aa8462f529810220ae/examples/generating-vu-tokens/README.md) says this can be achieved by executing a function in the before block which I have done:
```
config:
  target: "https://nonprod-target.com"
  processor: "./lib/helper.js"
  tls:
    rejectUnauthorized: false
  environments:
    nonprod:
      target: "https://nonprod-target.com"
      phases:
        - duration: 1
          arrivalRate: 3
          name: "Sustained load"
    prod:
      target: "https://prod-target.com"
      phases:
        - duration: 1
          arrivalRate: 1
          name: "Sustained load"
before:
  flow:
    - function: "generateSharedAuthToken"
scenarios:
  - flow:
    - post:
        url: "/api/signin"
        headers:
          Authorization: "{{ authToken }}"
```
However, when I do this the script never attempts to execute the provided function. I cloned down Artillery's [example](https://github.com/artilleryio/artillery/blob/b4363a93f4c50046ede9b4aa8462f529810220ae/examples/generating-vu-tokens/auth-with-token.yml) but when I ran it locally I saw the same behavior - the generateSharedToken() method is never run, resulting in the following output:
![Screen Shot 2023-02-07 at 11 05 01 AM](https://user-images.githubusercontent.com/68296152/217341236-06e52aba-7cb1-46ff-8216-78ef2ba69f02.png)

Did something change since this example? How can I run a function to generate the shared token before executing my scenarios block? Thanks so much!
