### DISCUSSION TITLE
How to take up the bearer token generated during login to test the subsequent API calls ?

### DISCUSSION THREAD

**Discussion by gk70** [artilleryio/artillery#1823] [Artillery]
Hello,
There seems to be not much documentation...
Following yml file when executed in VScode 
set export SERVICE_API_KEY="e.." artillery run test.yml 
```
config:
  target: http://xxx.net/api/pgm-customers
  phases:
    - duration: 1
      arrivalRate: 1
scenarios:
  - flow:
      - get:
          url: "/"
          headers:
            x-api-key: "{{ $processEnvironment.SERVICE_API_KEY }}"
          capture:
           - json: "$.accessToken"
             as: "accessToken"
          expect:
            - statusCode: 200
```
has the output 401. It's an angular application. Access token is stored in localStorage. So how do I get it before executing the target url ?

**Comment by hassy** [comment]
Hi @gk70 👋 If the service responds with JSON that contains an `accessToken` field and you capture it, you can then use "{{ accessToken }}" in subsequent steps, e.g.:

```
- post:
    url: "/some/path"
    headers:
      Authorization: "Bearer {{ accessToken }}"
```

If you're testing an Angular application through its UI and the token is only available in local storage, you're better off using our Playwright integration - https://github.com/artilleryio/artillery-engine-playwright Playwright scripts will have full access to local storage.
