### DISCUSSION TITLE
Unable to log the response header output

### DISCUSSION THREAD

**Discussion by amrsa1** [artilleryio/artillery#1858] [Artillery]
Version info: 
```
2.0.0-30
```

Running this command: 
```
npx artillery run load.yml
```

I expected to see this happen:

*i expect to the output in terminal when i use the key log*

Instead, this happened:

*nothing is happening just the test reultt*

Sample:

```
     scenarios:
    - name: "Register"
      flow:
        - get:
            url: "/register?returnurl=%2F"
            capture:
              headers:
                - Set-Cookie
              as: capturedHeaders  
        - extract:       
              - token: '{{ capturedHeaders["Set-Cookie"][0] }}'
        - log: "{{ token }}" 
```

**Comment by hassy** [comment]
Hi @amrsa1 👋 That `extract` step is not a valid Artillery step. Did you see it in the docs or examples somewhere?

You should be able to log `capturedHeaders`

**Comment by amrsa1** [comment]
nothing is being logged

```
scenarios:
    - name: "Register"
      flow:
        - get:
            url: "/register?returnurl=%2F"
            capture:
              headers:
                - Set-Cookie
              as: capturedHeaders  
              log: "{{ capturedHeaders }}"    
```
@hassy 
could you please share with me where in document i could find how i can log the request/response header ?

**Reply by hassy** [reply]
@amrsa1 `log` is documented here:

https://www.artillery.io/docs/guides/guides/http-reference#logging

`log` is its own step, it doesn't work because you have it nested under the `get` step. Change to:

```yaml
scenarios:
    - name: "Register"
      flow:
        - get:
            url: "/register?returnurl=%2F"
            capture:
              headers:
                - Set-Cookie
              as: capturedHeaders  
        - log: "{{ capturedHeaders }}"    
```
