### DISCUSSION TITLE
payload does not get the data in the expected order

### DISCUSSION THREAD

**Discussion by beita1** [artilleryio/artillery#1860] [Artillery]
- This may be a BUG or It's just that I'm using it wrong

# Requirements
Artillery: 2.0.0-30
Node.js:   v18.12.1
OS:        darwin

# Files
## users.csv
```
a,sandsqajyu
a,sandqwkwu1
a,sandgdv4h1
a,sandxyt2c4
a,sandjtdmxq
a,sandpfsnrp
a,sandt97sxe
a,sandjkxsaw
a,sandigtkpm
a,sandpfamgn
```
## config.yaml
```
config:
  target: "http://****/"
  plugins:
    expect: {}
    ensure: {}
  phases:
    - name: "a"
      duration: 1 
      arrivalCount: 10
  environments:
    sandbox:
      target: "http://****"
    local:
      target: "http://****"
  ensure:
    thresholds:
      - "socketio.response_time.p99": 300 
      - "socketio.response_time.p95": 100
  payload:
    path: "users.csv"
    fields:
      - "userSession"
      - "appId"
  socketio:
    transports: ['websocket']
scenarios:
  - name: "ide peak traffic"
    engine: socketio
    socketio:
      extraHeaders:
        cookie: "user_session={{ userSession }}"
      query:
        EIO: 4,
        appId: "{{ appId }}"
    flow:
      - log: "Current environment is set to: {{ $environment }}, appId: {{ appId }}"         
      - think: 3 # 3s

```

## Expect
- when i run command: **artillery run -e sandbox config.yml** , I expect get the unique appId for each scenario
```
⠴ Current environment is set to: sandbox, appId: sandpfsnrp
⠦ Current environment is set to: sandbox, appId: sandsqajyu
⠧ Current environment is set to: sandbox, appId: sandgdv4h1
⠏ Current environment is set to: sandbox, appId: sandxyt2c4
⠋ Current environment is set to: sandbox, appId: sandjtdmxq
⠙ Current environment is set to: sandbox, appId: sandpfsnrp
⠹ Current environment is set to: sandbox, appId: sandt97sxe
⠼ Current environment is set to: sandbox, appId: sandjkxsaw
⠹ Current environment is set to: sandbox, appId: sandigtkpm
⠼ Current environment is set to: sandbox, appId: sandpfamgn
```

## Actual
- But I got duplicate appId
```
⠴ Current environment is set to: sandbox, appId: sandpfsnrp
⠦ Current environment is set to: sandbox, appId: sandgdv4h1
⠧ Current environment is set to: sandbox, appId: sandgdv4h1
⠏ Current environment is set to: sandbox, appId: sandqwkwu1
⠋ Current environment is set to: sandbox, appId: sandsqajyu
⠙ Current environment is set to: sandbox, appId: sandgdv4h1
⠹ Current environment is set to: sandbox, appId: sandpfamgn
⠼ Current environment is set to: sandbox, appId: sandqwkwu1
⠹ Current environment is set to: sandbox, appId: sandpfamgn
⠼ Current environment is set to: sandbox, appId: sandqwkwu1
```
