### DISCUSSION TITLE
Unable to use chance plugin

### DISCUSSION THREAD

**Discussion by amrsa1** [artilleryio/artillery#1861] [Artillery]
Seems that chance plugin is not working as expected when i need to generate random values 

i have used the following 

```
  plugins:
    expect: {}
    chance: {}
  variables:
    - fullName: 'name'
```

```
scenarios:
    - name: "Register"
      flow:
        - get:
            url: "/"
            capture:
              header: 
                - set-cookie
              as: "responseHeaders"
            expect:
            - statusCode: 200
            - contentType: text/html; charset=utf-8
        - log: "im here {{ fullName }}"

```

logging output is showing 
`im here undefined`
