### DISCUSSION TITLE
beforeRequest inside loop not working

### DISCUSSION THREAD

**Discussion by johnnyrockoff** [artilleryio/artillery#1898] [Artillery]
Sup guys I have a loop with 2 request: Put and Get iterating over 1 element, but no matter what it never calls the second request, it executes only the first... I get a passed result on console log but the second request inside loop is never called :(

```
- loop:
    - log: "Third Loop"
    - put:
        url: "/api/v1/asset"
        beforeRequest: "generateUUID"
        afterResponse: "afterResponseHandler"
        headers:
          Authorization: "Bearer {{accessToken}}"
          contentType: "application/json"
          accept: "application/json"
        json:
          title: "Automation Put title"
          assetType: "Automation Put type"
          description: "Automation Put desc"
          url: "Automation Put0{{$randomNumber(1,10000)}}.com"
          assetStatus: "Automation Put status"
          alternateText: "Automation Put"
          allowedAccessRoles:
          - "Automation Put"
          subType: "Automation Put"
          applicationTypes:
          - "Automation Put"
          legacyId: "0{{$randomNumber(1,10000)}}"
          sortOrder: 0
          id: "{{ uuid }}"
        capture:
          - json: "$.title"
            as: "title"
        expect:
        - statusCode: 201 
        name: "Asset_UpdateAsset Test_Case_Id_539299"    
    - get:
        url: "/api/v1/asset/{{ $loopElement }}"
        headers:
          Authorization: "Bearer {{accessToken}}"
          contentType: "application/json"
          accept: "application/json"
        name: "Asset_GetAsset"
        capture:
          json: $.title
          as: "responseTitle"
        expect:
        - statusCode: 200
        - contentType: json
        - equals:
          - "{{ title }}"
          - "{{ responseTitle }}"
    over: putId
```

My custom JS

```
async function generateUUID(requestParams, context, ee, next) {
  try {
    let d = new Date().getTime();

    if (typeof performance !== 'undefined' && typeof performance.now === 'function') {
        d += performance.now(); // use high-precision timer if available 
    }
    const uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
        const r = (d + Math.random() * 16) % 16 | 0; d = Math.floor(d / 16);
        return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });

    context.vars.uuid = uuid;

    return next();
  } catch (e) {
    console.log(`Custom Error on Update: ${e}`);
    return next(e);
  }
}

async function afterResponseHandler(requestParams, response, context, ee, next) {
  try {
    if(response.statusCode !== 200 && response.statusCode !== 201) {
        if(response.statusMessage)
            console.error(response.url, response.statusCode+": "+response.statusMessage);

        let err = new Error();
        err.code = response.statusCode;
        return next(err);
    }

    return next(); 
  } catch (e) {
    console.log(`Custom Error on Update: ${e}`);
    return next(e);
  }
}
```

The results:

Current environment is set to: dev
{"name":"Asset_UpdateAsset Test_Case_Id_539299","url":"/api/v1/asset","results":[{"ok":true,"expected":201,"type":"statusCode","got":201}]}

What should I do?
