### DISCUSSION TITLE
expect plugin in before

### DISCUSSION THREAD

**Discussion by jromero-pg** [artilleryio/artillery#1903] [Artillery]
I'm trying to "fail fast" in a `before` step, the expect plugin appears to only work in `scenarios`. Am I missing something?

Below is an example test script. As you can see, the `expect` plugin fails only in `scenarios`.

I would expect (🥁) it to also assert in the `before` flow.

```yml
config:
  target: https://run.mocky.io/v3
  plugins:
    expect: {}

before:
  flow:
    - log: "before > started"
    - get:
        url: "/49393aad-e636-4f9c-9462-77a269ee523f"
        expect:
          - statusCode: 404
    - log: "before > finished"

scenarios:
  - flow:
      - log: "scenario > started"
      - get:
          url: "/49393aad-e636-4f9c-9462-77a269ee523f"
          expect:
            - statusCode: 404
      - log: "scenario > finished"
```

```bash
❯ DEBUG=plugin:expect artillery run /tmp/test.yml
Test run id: tbrjk_aqmn3twwm8qjwde9t6a87qmrtqzqf_j8zc
⠋   plugin:expect Not running in a worker, exiting +0ms
before > started
⠏ before > finished
⠙ 2023-04-29T04:08:17.502Z plugin:expect Initialized
Phase started: unnamed (index: 0, duration: 1s) 23:08:17(-0500)

Phase completed: unnamed (index: 0, duration: 1s) 23:08:18(-0500)

scenario > started
⠙ 2023-04-29T04:08:19.090Z plugin:expect Checking expectations
* GET /v3/49393aad-e636-4f9c-9462-77a269ee523f

2023-04-29T04:08:19.090Z plugin:expect checker: statusCode
2023-04-29T04:08:19.090Z plugin:expect check statusCode
2023-04-29T04:08:19.091Z plugin:expect prettyPrint formatter
  not ok statusCode 200
  expected: 404
       got: 200
  Request params:
    https://run.mocky.io/v3/49393aad-e636-4f9c-9462-77a269ee523f
    ""
  Headers:
  content-type: application/json; charset=UTF-8
  date: Sat, 29 Apr 2023 04:08:19 GMT
  content-length: 16
  sozu-id: 01GZ5K51EY3RK9X02FJS0KRY0Y
  Body:
{
  "ok": true
}
  User variables:
    target: https://run.mocky.io/v3
    $environment: undefined
    $uuid: f1a5e37a-e152-41a2-a625-d91a50a08345
scenario > finished
```
