### DISCUSSION TITLE
Testing Max Concurrency of an API

### DISCUSSION THREAD

**Discussion by Jmendoza194** [artilleryio/artillery#1904] [Artillery]
Hello, I am testing our API to see how many concurrent requests it can handle per second. The test I have set up is pretty simple and looks like this:

```
config:
  plugins:
    json-include: {}
  target: "some url"
  http:
    # Responses have to be sent within 300 seconds, or an `ETIMEDOUT` error gets raised.
    timeout: 300
  phases:
    - duration: 1
      arrivalRate: 20
      name: Warm up
  processor: "./requestHandlers.js"

scenarios:
  - flow:
      - post:
          url: "some url"
          json: "!include(test.json)"
          afterResponse: "handleResponse"
          beforeRequest: "setRequestBody"
```

I am using an extension to handle objects as our API requires an object as one of the arguments to be passed to it. I just need help understanding how the arrival rate and duration correlates to the request per second given in the summary report. From what I understand, the way I have my test set up is that over the course of 1 second, 20 virtual users are made and each one will make a single request, which in my mind should mean that the requests per second is 20. However, I am getting different results and I'm having a hard time understanding the summary reports. Here is an example of one of my test results with an arrival rate of 20 and duration of 1 second:

```

All VUs finished. Total time: 38 seconds

--------------------------------
Summary report @ 16:27:28(-0700)
--------------------------------

http.codes.200: ................................................................ 20
http.request_rate: ............................................................. 6/sec
http.requests: ................................................................. 20
http.response_time:
  min: ......................................................................... 1177
  max: ......................................................................... 3374
  median: ...................................................................... 2143.5
  p95: ......................................................................... 3262.4
  p99: ......................................................................... 3262.4
http.responses: ................................................................ 20
vusers.completed: .............................................................. 20
vusers.created: ................................................................ 20
vusers.created_by_name.0: ...................................................... 20
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 3768.3
  max: ......................................................................... 35116
  median: ...................................................................... 24594.7
  p95: ......................................................................... 35252.8
  p99: ......................................................................... 35252.8
```

The summary report I provided is the last summary report out of 4 reports, and I'm having hard time understanding why its getting a request rate of 6/sec instead of 20. Is the request rate based on the response time as well, or purely on how many requests are made in that 1 second that I provided as a duration? Any help is appreciated.
