### DISCUSSION TITLE
How to pass the JSON payload as an Input of API testing

### DISCUSSION THREAD

**Discussion by toanjansaha** [artilleryio/artillery#1905] [Artillery]
Hi, 

I am doing an API testing using Artillery and I need to pass a JSON payload which is an array of more 20+ fields. How can I achieve this through Artillery test script? 

JSON Payload Example:  
                 [
                    {"Product": "Name 1","ProductId": "ID1","ProductVersion": 1,"OrderId": "1111","OrderAmount": "100"},
                    {"Product": "Name 2","ProductId": "ID2","ProductVersion": 1,"OrderId": "2222","OrderAmount": "3000"}
                    ]

Http Method : POST

**Comment by hassy** [comment]
Two ways:


First one is to use the `json` property on the request object, e.g.:

```yaml
- post:
    url: "/products"
    json:
      - Product: "Name 1"
        ProductId: ID1
        ProductVersion: 1
      - Product: "Name 2"
        ProductId: ID2
        ProductVersion: 2
```

Second one is to use the `body` property to pass in literal JSON string, and set the header:

```yaml
- post:
    url: "/products"
    body: |
      [
        {"Product": "Name 1","ProductId": "ID1","ProductVersion": 1,"OrderId": "1111","OrderAmount": "100"},
        {"Product": "Name 2","ProductId": "ID2","ProductVersion": 1,"OrderId": "2222","OrderAmount": "3000"}
      ]
    headers:
      content-type: application/json
```
