### DISCUSSION TITLE
Artillery scripting doubts

### DISCUSSION THREAD

**Discussion by Sipun693** [artilleryio/artillery#1908] [Artillery]
my apis are failing with 401 although token is correct

```
config:
  target: "https://example.com"
  plugins:
    expect: {}
  phases:
    - duration: 2
      arrivalRate: 1
scenarios:
  - name: Login
    flow:
      - post:
          url: "https://auth/token"
          form:
            grant_type: password
            username: xyz
            password: abc
          capture:
            json: $.access_token
            as: access_token
          expect:
            - statusCode: 200
  - name: "api_1"
    flow:
    - get: 
          url: "/api/assets"
          headers:
            authorization: Bearer {{access_token}}
          expect:
           - statusCode: 200
```

by removing name and flow for api_1 it's giving 200 but my concern is i want to mention all transaction names. How can i do it?
