### DISCUSSION TITLE
Loadtest Socket.io and emit message with ack and check respond

### DISCUSSION THREAD

**Discussion by exodia0x** [artilleryio/artillery#1926] [Artillery]
Hi, I want to write loadtest with socket.io connection and send message with channel command and capture acknowledgement when server respond and check it if ack == "act" that is success else if failed. Anyone can guild me? I write some coding but not working as example below

```
config:
  target: "https://xxxxxxxxxxxxxx.com"
  phases:
    - duration: 1
      arrivalRate: 1
      # rampTo: 1000
      name: "Testing"
  plugins:
    expect: {}
  socketio:
    extraHeaders: 
      key: "Peace_testing_Nodejs"
    transports: ["websocket"]
  variables:
    key: '1234'
    command: '1234'
    value:
      msg: 'Testing form Artillery'
      modifyDate: '__ENV.timestamp'

scenarios:
  - name: "Send Message"
    engine: socketio
    flow:
      - emit:
          channel: "command"
          event: "command"
          data:
            key: '{{ key }}'
            command: '{{ command }}'
            value:
              msg: '{{ value.msg }}'
              modifyDate: '{{ value.modifyDate }}'
          acknowledge: true
      - think: 1
      - check:
          - expect:
              - statusCode: 200
                equals:
                  - "act"
            saveAs: acknowledgeStatus
      - think: 1
      - log: "Acknowledgment Status: {{ acknowledgeStatus }}"
```
I try with

```
scenarios:
  - name: "Send Message"
    engine: socketio
    flow:
      - emit:
          channel: "command"
          event: "command"
          data:
            key: '{{ key }}'
            command: '{{ command }}'
            value:
              msg: '{{ value.msg }}'
              modifyDate: '{{ value.modifyDate }}'
          acknowledge:
            match:
              json: "$.command"
              value: "act"
      - think: 1
```
it's didn't work too I change value: "act" so not equ server respond but still show success
