### DISCUSSION TITLE
About IP blacklist

### DISCUSSION THREAD

**Discussion by maska-mt** [artilleryio/artillery#1930] [Artillery]
```
config:
  target: https://www.artillery.io
  phases:
    - duration: 60
      arrivalRate: 1
    - duration: 300
      arrivalRate: 10
scenarios:
  - flow:
      - get:
          url: "/docs"
      - get:
          url: "/docs/resources"
```
I forgot to change the target and ran it. So my IP gets blacklisted.
It's my fault. Sorry. Is there any solution?
