### DISCUSSION TITLE
ECONNRESET error after 100 RPS

### DISCUSSION THREAD

**Discussion by PLajus** [artilleryio/artillery#1932] [Artillery]
After hitting ~100 RPS Artillery starts throwing an ECONNRESET error. 

I found that this error usually indicates an issue with the backend, however, the server responds to other requests fine and I don't see any requests from Artillery reaching the endpoints.

Running any test after getting the error returns an ECONNRESET no matter the load or test steps. So far I've found that it goes back to normal after the system, which Artillery is running on, is restarted.

This happens with any test after hitting 100+ RPS.

I'd like to know what could be the reason and why I'm unable to run any successful tests after getting said error.

Version info: 
```
Artillery: 2.0.0-30
Node.js:   v18.12.1
OS:        win32
```

Running this command: 
```
artillery run test.yml
```

![image](https://user-images.githubusercontent.com/77925599/226414196-e33d925d-8133-49b7-be70-2b1b65740922.png)
![image](https://user-images.githubusercontent.com/77925599/226414424-d6de1d3e-d667-4227-b6a7-39d6ac28ad9f.png)

**test.yml**
```yml
config:
  target: "http://localhost:8080"
  http:
    timeout: 300
    extendedMetrics: true
  phases:
    - duration: 10
      arrivalRate: 10
      name: Warm up
    - duration: 240
      arrivalRate: 10
      rampTo: 200
      name: Ramp up load
    - duration: 60
      arrivalRate: 200
      name: Sustained load

scenarios:
  - name: "Read user"
    flow:
      - get:
          url: "/users"
  - name: "Read product"
    flow:
      - get:
          url: "/products"
```
