### DISCUSSION TITLE
Automating HTTP POST API with dynamic nested JSON payload.

### DISCUSSION THREAD

**Discussion by abimarank** [artilleryio/artillery#1935] [Artillery]
I have an HTTP POST API with a nested JSON payload, I need to modify a few values for keys and send them to the API for load testing. 

Here are the steps I want to execute.

1. Read the JSON payload with placeholders for values changing dynamically
2. Populate the placeholders with random values or from CSV or any other ways
3. Send each request with different values for those placeholders.

I can do this in JMeter, but I was trying to do this with artillery IO, but wasn't able to do it. I feel there is a limitation on this functionality in the framework.

Anyone else came across similar requirements and sorted them out?

**Comment by hassy** [comment]
Hi @abimarank 👋 Artillery provides several ways to do this, for example:

- You can load dynamic values from a CSV file using `config.payload` the functionality.
- Those values may now be used as template strings directly in the JSON payload definition.

A very simple example to illustrate:

```
config:
  payload:
    # Load a CSV file with two columns: title and year
    - path: my-values.csv
      fields:
        - title
        - year
scenarios:
  - flow:
      post:
        url: "/movies"
        json:
          title: "{{ title }}"
          year: "{{ year }}"
```

You can also use Artillery's support for running arbitrary Node.js code and hooks like `beforeRequest` to do pretty much anything you want if your requirements are more complex: https://www.artillery.io/docs/guides/guides/test-script-reference#processor---custom-js-code
