### DISCUSSION TITLE
Socket.IO giving timeout error and websocket error

### DISCUSSION THREAD

**Discussion by devashish-gopalani-cognoai** [artilleryio/artillery#1942] [Artillery]
I have been trying to perform load testing on my socket-io deployment. The script which I am using is:

```
config:
  target: "https://xyz.com"
  socketio:
    path: "/websocket"
    transports: ["websocket"]
    query:
      roomKey: "9871829299"
  phases:
    - duration: 600
      arrivalRate: 5
  engines:
    socketio-v3: {}

scenarios:
  - name: Load Test Scenario
    engine: socketio-v3
    flow:
      - loop:
        - namespace: "/cobrowse"
          emit:
            channel: "cobrowse_packet"
            data: "world"
        - think: 1
        count: 70

```

Now when I run the script, I get the following 2 errors printed in my console (while the script is running):

```
2023-06-13T11:50:05.842Z socketio Error: websocket error
    at WS.onError (/home/devashish/Projects/WebSocketServiceLoadTest/node_modules/engine.io-client/build/cjs/transport.js:45:37)
    at ws.onerror (/home/devashish/Projects/WebSocketServiceLoadTest/node_modules/engine.io-client/build/cjs/transports/websocket.js:78:39)
    at callListener (/home/devashish/Projects/WebSocketServiceLoadTest/node_modules/engine.io-client/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onError (/home/devashish/Projects/WebSocketServiceLoadTest/node_modules/engine.io-client/node_modules/ws/lib/event-target.js:230:9)
    at WebSocket.emit (node:events:513:28)
    at emitErrorAndClose (/home/devashish/Projects/WebSocketServiceLoadTest/node_modules/engine.io-client/node_modules/ws/lib/websocket.js:1002:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

```
2023-06-13T11:39:56.071Z socketio Error: timeout
    at Timeout.<anonymous> (/home/devashish/Projects/WebSocketServiceLoadTest/node_modules/socket.io-client/build/cjs/manager.js:173:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

Can someone help me understand why are these errors coming and how can I fix them?

The final output which gets printed (after the tests have completed running) is:
```
All VUs finished. Total time: 11 minutes, 24 seconds

--------------------------------
Summary report @ 17:20:48(+0530)
--------------------------------

engine.socketio.emit: .......................................................... 94937
engine.socketio.emit_rate: ..................................................... 71/sec
errors.Error: timeout: ......................................................... 1072
errors.Error: websocket error: ................................................. 52
errors.timeout: ................................................................ 781
errors.websocket error: ........................................................ 81
vusers.completed: .............................................................. 1248
vusers.created: ................................................................ 3000
vusers.created_by_name.Load Test Scenario: ..................................... 3000
vusers.failed: ................................................................. 1752
vusers.session_length:
  min: ......................................................................... 70071.9
  max: ......................................................................... 136552.3
  median: ...................................................................... 73889.3
  p95: ......................................................................... 108048.6
  p99: ......................................................................... 119412.6
Log file: test-case-29.json
```

Socket.IO server version - 4.6.0
Redis streams version (adapter which I am using) - 0.1.0
