### DISCUSSION TITLE
Combine playwright and custom plugin

### DISCUSSION THREAD

**Discussion by gweit** [artilleryio/artillery#1966] [Artillery]
Hi,

Is there a way or a workaround to combine the playwright engine and a custom plugin? - and get the browser metrics passed to the custom plugin?

```
config:
  target: https://example.com
  phases:
    - duration: 4
      arrivalRate: 2
  plugins:
    hello-world:
      greeting: "Hello playwright! 👋"
  # Load the Playwright engine:
  engines:
    playwright: {}
  # Path to JavaScript file that defines Playwright test functions
  processor: "./flows.js"
scenarios:
  - engine: playwright
    flowFunction: "helloFlow"
    flow: []
```
