### DISCUSSION TITLE
How to define total test duration of the load test in scenario

### DISCUSSION THREAD

**Discussion by rrnareshkumar** [artilleryio/artillery#2004] [Artillery]
Hi , Please suggest how to define total test duration of the load test .

For Example :  I want to test a API for 1 hour with total users count as 10 .
I want to ramp up 10 users in 120 seconds  and run the test for 1 hour with 10 users.

I had a look at  the different examples provided in https://www.artillery.io/docs , I can see examples for different types of users ramp up patterns but i didn't find examples to define total test duration , Kindly suggest .

**Comment by hassy** [comment]
You can cap the number of concurrent VUs with `maxVusers` ([docs](https://www.artillery.io/docs/reference/test-script#constant-arrival-rate)).

So it would look like this:

```
config:
  phases:
    - duration: 120
      arrivalRate: 1
      rampTo: 10
      maxVusers: 10
    - duration: 3600
      arrivalRate: 1
      maxVusers: 10
```

This will make Artillery keep the total number of concurrent VUs no more than 10.

(If your scenario duration is <1 sec, you will need to increase the `arrivalRate`)
