### DISCUSSION TITLE
Question: Using variables in "url:"

### DISCUSSION THREAD

**Discussion by eliezercazares** [artilleryio/artillery#2038] [Artillery]
Version info: 
```
<version> 2.0.0-27
```

Running this command: 
```
<command> artillery run -e functional --output report.json ---config config.xml scenarios/scenario.yml
```

This is more of a question...

Can I use variables in the URL object?

I.e.

````
scenarios:
    - name: "My scenario"
       flow:
      -post:
           url: "/abc/def/{variable}"
````

thanks a lot for your help!
I have been able to use it in the company I work for because you guys have so much documentation and community. Thanks!
