### DISCUSSION TITLE
Attempting to run playwright engine is trying to launch the wrong chromium version

### DISCUSSION THREAD

**Discussion by lockenj** [artilleryio/artillery#2061] [Artillery]
When attempting to run a simple playwright scenario using artillery I get this error:

⠸ worker error, id: 1 browserType.launch: Executable doesn't exist at /Users/monster/Library/Caches/ms-playwright/chromium-1064/chrome-mac/Chromium.app/Contents/MacOS/Chromium

notice the `Library/Caches/ms-playwright/chromium-1064`... When I ran `npx playwright install` it installed `Library/Caches/ms-playwright/chromium-1028`

Version info: 
```
VERSION INFO:

Artillery: 2.0.0-35
Node.js:   v20.2.0
OS:        darwin
```

Digging through the source I could not see why it was trying to use `chromium-1064`

**Comment by lockenj** [comment]
For the record:

If I move `Library/Caches/ms-playwright/chromium-1028` to `Library/Caches/ms-playwright/chromium-1064` and then run `npx artillery run myScenario.yml` it works.

**Comment by hassy** [comment]
hi @lockenj 👋 I'd need to check to make sure but this is most likely due to mismatch between versions of Playwright. We are currently using [v1.34.3](https://github.com/artilleryio/artillery/blob/main/packages/artillery-engine-playwright/package.json#L14) whereas `npx playwright install` will install browsers for the most recent release of Playwright. Those paths can change between releases of Playwright.

**Reply by spencerlavallesonos** [reply]
@hassy Do you have any suggestions for this browser not existing issue during GHA runs where messing with the browser-install cache isn't recommended? Running into this with the following workflow file: 

```Yaml
name: ShopToCheckout Load Test
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'int/test/stage/prod'
        default: test
        required: false
        type: string
  # schedule: 
  #   # Everyday at 0000 UTC
  #   - cron: '0 0 * * *'
 
jobs:
  artillery:
    runs-on: [ "self-hosted", "<REDACTED>" ]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Node
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: node

      - name: Install Yarn
        run: npm install -g yarn
        
      - name: Set npm config
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{secrets.<REDACTED>}}' >> ${{ github.workspace }}/.npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Install Playwright
        run: npx playwright install
        
      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          # Not cloud for now (embargo is active)
          command: run src/Artillery/heavy_load.yaml
        env:
          ENVIRONMENT_TO_TEST: ${{ github.event.inputs.message }}
```
