### DISCUSSION TITLE
Artillery v2.0.0-36

### DISCUSSION THREAD

**Discussion by hassy** [artilleryio/artillery#2064] [Announcements]
<img width="1920" alt="artillery-github-release-header-2 0 0-36" src="https://github.com/artilleryio/artillery/assets/1490/5c1a8818-d803-49d1-a7df-d50c7f0dac5b">

## New features

- [Dynatrace](https://www.dynatrace.com/) support - the official `publish-metrics` plugin can now be configured to send Artillery metrics and events to Dynatrace. [Read more in the docs](https://www.artillery.io/docs/reference/extensions/publish-metrics#dynatrace). (https://github.com/artilleryio/artillery/commit/140ee923601f3fa5027a37ce67659b9ad7017719)
- `config.http.defaults` - default headers and cookies for all requests in a test may now be set via `config.http.defaults` (https://github.com/artilleryio/artillery/commit/938f9c472b415128062f0e38f0f4a8a14ee10db2)

### Artillery Dashboard ([join the waitlist](https://www.artillery.io/cloud))

- Send load phase start/end timings for visualization (https://github.com/artilleryio/artillery/pull/2022)
- Send CLI exit code to display in test run results (https://github.com/artilleryio/artillery/commit/407d225ed7a96d22a5bba889478b4424b26f0356)
- Fix test run status not always getting reported correctly (https://github.com/artilleryio/artillery/commit/48a4a91c966b5fe352e45d9a8ab1d37789700d21)
- Fix bug which caused test runs on AWS Lambda to not be tagged correctly (https://github.com/artilleryio/artillery/commit/919327fa09030bbf8db503251b9720ebd1ebdef9)

### Core

- Allow variables set with `--variables` to be used anywhere in `config` (https://github.com/artilleryio/artillery/commit/c08c6951095615711beea66d11e99dd9a0162cd8)
- Fix for encoding of array values in query strings (https://github.com/artilleryio/artillery/commit/06989c62e56697afeb3a1f1c6a5b0986d357ed93)
- Make sure CLI exit handlers are always run (https://github.com/artilleryio/artillery/commit/77f6423435c59392f121ae314269f8f396e58b64)
- Fix bug affecting match groups in regexp captures (https://github.com/artilleryio/artillery/commit/e92306e73e67e48584df49d21f7bc7ea57f1d4f5)

### Plugins

- `publish-metrics` - Exit early if required config is missing for publish-metrics (https://github.com/artilleryio/artillery/commit/7871d398cfb462a5bc31d766df63762f82eb32fe)
- `publish-metrics` - Reduce memory usage of the plugin (https://github.com/artilleryio/artillery/commit/338b070778d4aed99b53b3a4745e28c2f150e5e1)
- `expect` - add `useRequestNamesOnly` option (https://github.com/artilleryio/artillery/pull/1995)
- `ensure` - fix bug where ensure config under `config.plugins.ensure` would not get picked up (https://github.com/artilleryio/artillery/commit/d1136f37d492d61e91a41334549a08196980b26c)

This release brought to you by @inesni @bernardobridge @hassy 

<hr /><em>This discussion was created from the release <a href='https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.0-36'>Artillery v2.0.0-36</a>.</em>

**Comment by Thilaknath** [comment]
Hello Team, @hassy  I am trying to use the dynatrace plugin to publish metrics. But I get the following error 
```
 plugin:publish-metrics:dynatrace Metrics sent to Dynatrace +1ms
⠋   plugin:publish-metrics:dynatrace Sending event to Dynatrace +5s
  plugin:publish-metrics:dynatrace Cleaning up +2ms
  plugin:publish-metrics:dynatrace Waiting for pending request ... +0ms
⠴   plugin:publish-metrics:dynatrace There has been an error in sending event to Dynatrace:  HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1694441764452,
    socket: 1694441764452,
    lookup: 1694441764453,
    connect: 1694441764572,
    secureConnect: 1694441764688,
    upload: 1694441764688,
    response: 1694441764806,
    end: 1694441764808,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 119,
      tls: 116,
      request: 0,
      firstByte: 118,
      download: 2,
      total: 356
    }
  }
} +359ms
```

I am trying to publish to our centrally managed dynatrace instance at our org. I have the credential and url configured properly.  Am i missing something ?

**Reply by hassy** [reply]
Thanks for reporting the issue @Thilaknath! Can you confirm that you're able to access the [API Explorer](https://www.dynatrace.com/support/help/dynatrace-api#api-explorer) on `https://{your-domain}/e/{your-environment-id}/rest-api-doc/` from the same machine/network that you're running Artillery on? 

cc'ing @InesNi who's leading our monitoring/o11y integrations.

**Reply by Thilaknath** [reply]
Yes I can confirm that, I can access the api url documentation from the above referenced link from the machine I am running tests on.

**Reply by InesNi** [reply]
Hi @Thilaknath,

From the debug output that you provided it seems that the metrics have been sent, and the event is the one causing the error 🤔 .

There are a couple of things that might be causing this, but we'd need to troubleshoot it. A couple of requests:
- Could you confirm that the `metrics` have reached the platform, since the log says they did? 
- Could you confirm that you have permissions to ingest `events` as well as metrics?
- And could you please share your config, so I can see how you have configured the reporter (to get a better idea of possible issues)?

Thank you again for reporting this!

**Reply by Thilaknath** [reply]
Hello @InesNi My config for dynatrace below. I don't see the metrics when I try to click on Observe and Explore in Dynatrace. Can you advice If I should be checking elsewhere?

1) Also where do you see from the logs the events are shipped to dynatrace as I just see `:dynatrace There has been an error in sending event to Dynatrace:  HTTPError: Response code 404 (Not Found)` 
2) I have created a token which has the following scope
![Screenshot 2023-09-12 at 8 09 19 AM](https://github.com/artilleryio/artillery/assets/3452073/806234d5-83e7-4d49-b71d-159f23cd65db)
3) Config 
```
 plugins:
    publish-metrics:
      - type: dynatrace
        apiToken: "XXXX-XXXX-XXXX"
        envUrl: "https://apm.cf.<org>.ondemand.com/e/<environment-id>"
        prefix: "artillery."
        dimensions:
          - "service:my-service"
          - "host_id:1.2.3.4"
        event:
          title: "Loadtest"
          entitySelector: "type(SERVICE),entityName.equals(MyService)"
          properties:
            - "Tool:Artillery"
            - "Load per minute:100"
            - "Load pattern:production"
```

**Reply by InesNi** [reply]
Hi @Thilaknath,

I meant that the `metrics` seemed to have been sent from reading the first line in the logs you provided: 
```
plugin:publish-metrics:dynatrace Metrics sent to Dynatrace +1ms
``` 
and the fact that there doesn't seem to be an error related to metrics in those logs.

I have tried to run the test with your config and I am able to find metrics and events in Dynatrace. I only have access to a SaSS Dynatrace instance though, so I am not able to check if there may be some differences (especially in the UI) between the two.


### For the events issue
Can you try running without `entitySelector`? I suspect this might be issue. I wasn't getting any `events` when I had entitySelector without having that entity, and when there's a mistake in entitySelector I get a 400. Not exactly the same issue, but maybe in the managed version the API behaves differently here if it can't find an entity? 
[Here](https://www.dynatrace.com/support/help/shortlink/api-events-v2-post-event#request-body-objects) and [here](https://www.dynatrace.com/support/help/dynatrace-api/environment-api/entity-v2/entity-selector) you can find out more about the requirements for `entitySelector` and `properties` as well as examples and links to more information. 

I would also check if there is any additional thing you might need to configure/enable for managed services in order to ingest custom data.

### For not finding metrics
In Dynatrace SaSS we can find `metrics` on several of the widgets below `Observe and explore`. For example:  `Metrics`, `Data explorer` or `Dashboards` all allow to visualise metrics one way or another:

![Screenshot 2023-09-12 at 16 00 04](https://github.com/artilleryio/artillery/assets/39635558/92da5795-b994-4f0b-ba87-4256147457ed)

Can you find the equivalent widgets in Dynatrace managed?

For example, in the Data Explorer, you can see artillery data below:

<img width="683" alt="Screenshot 2023-09-12 at 15 28 47" src="https://github.com/artilleryio/artillery/assets/39635558/502f1eb3-6203-40da-bb46-447d1704248e">

**Reply by Thilaknath** [reply]
Hello @InesNi 

1) I get the same error 404 even after removing the `entitySelector` from the config.
2) I don't see any events being sent to dynatrace, Yes I have a similar view in our managed dynatrace instance and don't find any of the artillery related metrics.
3) I am available for a Microsoft Teams call if you are willing to debug. 

Update: I was able to execute a request using postman and I was able to ingest data to our managed instance I was providing the url as the following 
`https://apm.cf.<org>.ondemand.com/e/<environment-id>/api/v2/metrics/ingest` in postman and the token that I am using is valid for ingesting the metrics.


Thank you

**Reply by InesNi** [reply]
Hey @Thilaknath,

I think I know what might be wrong - I believe there is a bug in the way the `metrics`/`events` endpoints are being appended to the URL - it gets surfaced in the managed URL only. I'll have a fix soon and send a canary version your way with the fix so you can test. 

Thanks for the help so far 🙏🏻

**Reply by Thilaknath** [reply]
@InesNi  Thank you. Does this mean after your fix. I should still only specify this as the `envUrl` ryt ? `https://apm.cf.<org>.ondemand.com/e/<environment-id>`

**Reply by InesNi** [reply]
@Thilaknath Yes that is correct. The configuration stays the same and should work as intended in the first place. 

The fix is in place 🤞🏻, you can install version `artillery@2.0.0-37-ab5dd4f` to test it. If it works, it will land on Artillery's next CLI release, but for now you can use the canary version provided.

**Reply by Thilaknath** [reply]
Hello @InesNi Thank you for the fix. Please refer the attached screenshots and advice if I am missing something. There still seems to be a small bug as when the test ends, There is one 400 request. 
<img width="1276" alt="Screenshot 2023-09-12 at 1 24 36 PM" src="https://github.com/artilleryio/artillery/assets/3452073/070bd372-396f-4847-870f-cc68023a47e4">

Also within dynatrace, I am now able to see the metrics appear in Data explorer view, But still there seems to be no data present. Can you advice if I need additional configuration passed ? I don't have the `entitySelector` configured. Should I bring it back. I am assuming you should have some defaults if its not configured. 

Refer screenshot for what I see in dynatrace
![Screenshot 2023-09-12 at 1 26 08 PM](https://github.com/artilleryio/artillery/assets/3452073/dd782496-aaea-4bf3-9f7e-6cb9dafcf0d8)
![Screenshot 2023-09-12 at 1 26 22 PM](https://github.com/artilleryio/artillery/assets/3452073/21146f8e-715f-4ebb-885d-c8104e4c8169)

**Reply by InesNi** [reply]
Hi @Thilaknath ! That's weird 🤔, usually a 400 from Dynatrace would indicate something malformed in the request.

- Could you please share your full test script (with scenario and config), so I can try to see if I spot anything that may be causing it, or try to reproduce it on my side?
- Can you try to check the following page: https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/metric-faq#datapoint-unavailable. It shows some advice as to why metrics might not be showing on Dynatrace side, and how you might be able to spot things like Rejections on your side.

Thanks again 🙏🏻

**Reply by Thilaknath** [reply]
Hello @InesNi 
Below is my test config, I have masked the service URL and the Api token. But the rest should be the same.
```
config:
  target: https://<SERVICE-URL>
  phases:
    - duration: 2
      arrivalRate: 1
      name: "Warm-up Phase"
  plugins:
    publish-metrics:
      - type: dynatrace
        # DY_API_TOKEN is an environment variable containing the API key
        apiToken: "<VALID-TOKEN>"
        envUrl: "https://apm.cf.ondemand.com/e/<VALID-ENV-ID>"
        prefix: "artillery."
        dimensions:
          - "service:my-service"
          - "host_id:1.2.3.4"
        event:
          title: "Loadtest"
          properties:
            - "Tool:Artillery"
            - "Load per minute:100"
            - "Load pattern:production"
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 700
  ensure:
    thresholds:
      - http.response_time.p99: 1250
      - http.response_time.p95: 800
scenarios:
  - flow:
      - get:
          url: "/actuator/health"
```

**Reply by Thilaknath** [reply]
Update: The rejection dashboard was of no use as I was not seeing any data for the time frame I was trying to ingest data.

**Reply by Thilaknath** [reply]
Update: I am not sure why the 400 bad request is there. But i see some data points in dynatrace after removing the management filter

**Reply by InesNi** [reply]
Great @Thilaknath 🎉, glad we've made progress.

I'll continue trying to replicate the 400 bad request with your config and/or try to see if it's possible to get a more meaningful error message from Dynatrace's API. In the meantime, at least it seems you are able to get data into the platform.

**Reply by Thilaknath** [reply]
Yes and Thank you for your support @InesNi

**Reply by InesNi** [reply]
Hi @Thilaknath,

I realised that the issue might be with the `/` being created by metrics from the `metrics-by-endpoint` plugin (which I think is the same issue you're facing in one of the `open-telemetry` debug logs you showed). Dynatrace doesn't accept those characters.

As a workaround, you should be able to do the following:

**1. Set your config to use `useOnlyRequestNames`** (https://www.artillery.io/docs/reference/extensions/metrics-by-endpoint#plugin-configuration)
```yaml
plugins:
   metrics-by-endpoint:
      useOnlyRequestNames: true
```

**2. `name` your requests with a string that follows [this convention](https://www.dynatrace.com/support/help/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key):**

```yaml
scenarios:
  - flow:
      - get:
          url: "/actuator/health"
          name: actuator
```

---

I'll work on a fix for the reporter, but I've tested the workaround above, and was able to get past the `400 Bad Request` issue, so you should be able to use this for now  🤞🏻 .
