### DISCUSSION TITLE
Artillery-Playwright GitLab CI

### DISCUSSION THREAD

**Discussion by dids-reyes** [artilleryio/artillery#2080] [Artillery]
I'm trying to run my load test in CI but i don't know the correct way, tried it in local and it's perfectly working.

Currently this is my `.gitlab-ci.yml`
```
stages:
  - load_test

artillery:
  stage: load_test
  tags:
    - ta
    - pt
    - ubuntu-droplet
  image:
    name: artilleryio/artillery:latest
    entrypoint: [""]
  script: 
    - npm install -g artillery artillery-engine-playwright && \
        npm cache clean --force && \
        rm -rf /root/.cache && \
        rm -rf /ms-playwright/firefox* && \
        rm -rf /ms-playwright/webkit*
    - /home/node/artillery/bin/run run -login.yml
```

<img width="977" alt="Screenshot 2023-08-24 at 2 45 51 PM" src="https://github.com/artilleryio/artillery/assets/48916955/d2a0cfe1-413c-41e8-a799-6e00bc1afb91">

`login.js` contains basic test login in the website I'm trying to test.

Here's the Error in CI

<img width="784" alt="Screenshot 2023-08-24 at 2 42 37 PM" src="https://github.com/artilleryio/artillery/assets/48916955/367adc91-60e6-4d21-8c42-d51a6655a7e7">

What's wrong with my current `.gitlab-ci.yml`?
