### DISCUSSION TITLE
Assign weight scenarios with Playwright

### DISCUSSION THREAD

**Discussion by kevinpurwito** [artilleryio/artillery#2087] [Artillery]
Hi, is it possible to assign weight scenarios with Playwright?

I believe we should only add weight right? but using this yaml
```
# openRandomPage will run 75% of the time, based on the weight
scenarios:
  - engine: playwright
    testFunction: "openStaffPage"
    weight: 1
  - engine: playwright
    testFunction: "openRandomPage"
    weight: 3
```

will make the testFunctions failed, while when I remove the weight, it will run properly

Thank you!
