### DISCUSSION TITLE
Advice on how to optimize my artillery playwright load tests on fargate

### DISCUSSION THREAD

**Discussion by colmtroy** [artilleryio/artillery#2094] [Artillery]
I have a test script as follows:

```
config:
  target: "snip"
  phases:
    - arrivalRate: 1
      duration: 4
  engines:
    playwright: {}
  processor: ./sordercheck.js
scenarios:
  - name: "Place order with check payment method"
    engine: playwright
    testFunction: "placeorderwithcheck"
```

my playwright test basically does something like the following (urls removed for privacy)

```
//
// The code in this function was generated with
// playwright codegen
// https://playwright.dev/docs/codegen
//

async function placeorderwithcheck(page) {
  await page.goto('snip');
  await page.locator('a.swatch-anchor:has-text("Black")').click();
  await page.locator('[data-value="10"]').check();
  await page.locator('text=Add to cart').click();
  await page.locator('text=Checkout & Shipping').click();
  await page.locator('input[name="billing_email"]').click();
  await page.locator('input[name="billing_email"]').fill('user@domain.com');
  await page.locator('input[name="billing_phone"]').click();
  await page.locator('input[name="billing_phone"]').fill('11111111111');
  await page.locator('input[name="billing_first_name"]').fill('John');
  await page.locator('input[name="billing_last_name"]').fill('Doe');

  // US billing country
  await page.locator('#select2-billing_country-container').click();
  await page.locator('span.select2-search.select2-search--dropdown > input').fill('united states');
  await page.locator('.select2-container .select2-results__option--highlighted').click();

  // US billing street address
  await page.locator('text=Email address *Phone *First name *Last name *Country / Region *Select a country  >> [placeholder="House number and street name"]').click();
  await page.locator('text=Email address *Phone *First name *Last name *Country / Region *Select a country  >> [placeholder="House number and street name"]').fill('Beverley Hills');
  await page.locator('text=Email address *Phone *First name *Last name *Country / Region *Select a country  >> [placeholder="Apartment\\, suite\\, unit\\, etc\\. \\(optional\\)"]').press('Tab');

  // US billing city
  await page.locator('input[name="billing_city"]').fill('Los Angeles');

  // US billing state.
  await page.locator('#select2-billing_state-container').click();
  await page.locator('span.select2-search.select2-search--dropdown > input').fill('california');
  await page.locator('.select2-container .select2-results__option--highlighted').click();

  // US billing zip.    
  await page.locator('input[name="billing_postcode"]').click();
  await page.locator('input[name="billing_postcode"]').fill('90210');

  //await page.locator('label[for="payment_method_braintree_cc"]').click();
  await page.locator('text=Check').click();

  // Wait for the specific XHR request to complete
  await page.waitForResponse(response => {
    return response.url().includes('update_order_review') && response.status() === 200;
  });

  await page.locator('button[name="woocommerce_checkout_place_order"]').click();

}

module.exports = {
  placeorderwithcheck,
};
```

Through trial and error, I've found that an arrival rate of 1 and a duration of 4 is the sweet spot for this particular load test because if I add any more virtual users I start to experience timeouts when I run the script on my local machine and on the fargate workers.

Right now I'm limited to 140 vCPUs on AWS (sidenote: it took me forever to figure out why I was seeing errors attempting to run my fargate tests until I realized my quota was set to 64vCPUs and that I had to ask for this to be bumped up via a support ticket - might be worth adding something that to the fargate docs).

So I can just about get away with a count of 30 workers (given each artillery worker is using 4 vCPUS if I'm not mistaken?).

Is there some other way I could structure my tests to get more bang from my buck from each worker, either by allowing each worker to loop through the playwright script repeatedly, or by somehow optimizing by script structure in some other way?

At the moment I cant see any other solution than to seek another quota increase from AWS to 400 vCPUS if I want to run a count of 100 workers for example.

Any tips would be greatly appreciated.

**Comment by alexjeen** [comment]
I think --count parameter factors in, so if you have too high arrival rates (like 1+) the Fargate workers will get overloaded.
, I have a simple similar test, with this config (it means 1 new virtual user every **second** x 30), im still getting to grips with the meaning of the phases and such:

```
config:
  target: https://google.com
  phases:
    - arrivalRate: 1
      duration: 1800
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
      thresholds:
        - http.response_time.p99: 750
        - http.response_time.p95: 500  
  engines:
    playwright: {}   
  processor: "./login.js"
scenarios:
  - engine: playwright
    testFunction: "login"
```

This already causes a very high load.

Also 4096 VCPU is not a sensible default for node JS I don't think it matters, so your better off running tests like this so you can use your Fargate VCPU quote more efficient (you can request a higher VCPU count per AWS account through quota management):

    artillery run-fargate --region eu-west-1 --count 30 --cpu 1 --memory 2 artillery.yml

And I suggest running them as spot, it is about 50% cheaper and its a fault tolerant workload (remember to increase your quota there as well):

    artillery run-fargate --region eu-west-1 --count 30 --cpu 1 --memory 2 --spot artillery.yml

Great tool BTW!
