### DISCUSSION TITLE
How to create a proper load test?

### DISCUSSION THREAD

**Discussion by kevinpurwito** [artilleryio/artillery#2104] [Artillery]
Hi this is the first time I use artillery to do some load testing, I have this phases in mind:
1) warm the test until 1K requests per minute (around 15 req/s) for 5 minutes
2) slowly ramp up until 10K requests per minute (around 150 req/s) for 10 minutes
3) sustain the peak 10K requests per minute for 5 minutes

I have the following yaml:
```yaml
  phases:
    - duration: 300 # 5 minutes
      arrivalRate: 1
      rampTo: 15
      maxVusers: 15
      name: Warm up the API

    - duration: 600 # 10 minutes
      arrivalRate: 15
      rampTo: 150
      maxVusers: 150
      name: Ramp up to peak load

    - duration: 300 # 5 minutes
      arrivalRate: 150
      maxVusers: 150
      name: Sustained peak load
      
  # Load the Playwright engine:
  engines:
    playwright:
      launchOptions:
        headless: true
```

The scenario I run is to login using 1 user credential, and then open some random pages of my web app.

But the result I get is kinda weird, the summary is like this:

browser.http_requests | 247737
vusers.created | 1697
vusers.created_by_name.0 | 441
vusers.created_by_name.1 | 1256
vusers.failed | 1696
vusers.skipped | 93603

CMIIW but does this mean only 1 vuser succeed out of 1697? and why the skipped vusers are so high ya?
