### DISCUSSION TITLE
Run loadtest on AWS from Azure Devops pipeline

### DISCUSSION THREAD

**Discussion by verhoevenhans** [artilleryio/artillery#2114] [Artillery]
Help needed on how to run an Artillery testscript from Azure Devops on an AWS environment.

On my local machine I can successfully start a loadtest with the run-fargate command. 
"artillery run-fargate --region xxxxxx --security-group-ids xxxxxxxxxxxxxxx --subnet-ids xxxxxxxxxxx .\testscript.yml"
This works great.

Now what I want is to run this command from within Azure Devops. I saw a task called "AWS CLI" and tried to use it, but I am not familiar with the command/subcommand structure this task requires. We did successfully create a service connection for this and entered this in awsCredentials parameter.

My current YAML looks like this, but this does not work.

```
trigger:
  - main
 
pool:
  vmImage: ubuntu-latest

steps: 

- task: AWSCLI@1
  inputs:
    awsCredentials: 'xxxxxxxx'
    regionName: 'eu-west-1'
    awsCommand: 'ecs'
    awsSubCommand: 'send-command'
    awsArguments: 'artillery run-fargate --region xxxxxxxx --security-group-ids xxxxxxxxx --subnet-ids xxxxxxxxxx .\testscript.yml'

```

When running the above, I get the following error:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: --document-name

```

An alternative YAML that I tried was the following:
```
trigger:
  - main
 
pool:
  vmImage: ubuntu-latest
 
steps:
 
  - script: sudo apt-get install awscli
    displayName: "Install awscli"
    
  - script: export AWS_DEFAULT_REGION="xxxxxxxxxx"
    displayName: "AWS_region"

  - script: export AWS_ACCESS_KEY_ID="xxxxxxxxxxxxxxxx"
    displayName: "AWS_Access_key"

  - script: export AWS_SECRET_ACCESS_KEY="xxxxxxxxxxxxxxxxx"
    displayName: "AWS_Secret_Access_key"

  - script: export AWS_SESSION_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    displayName: "AWS_Session_Token"
    
  - script: npm install -g artillery@latest
    displayName: "Install Artillery"
 
  - script: mkdir $(System.DefaultWorkingDirectory)/reports
    displayName: "Make reports directory"
 
  - script: artillery run-fargate --region eu-west-1 --security-group-ids xxxxxxxxxxxxxxxxxx --subnet-ids xxxxxxxxxxxxx .\testscript.yml
    displayName: "Execute load tests"
 
  - script: artillery report --output reports/report reports/report.json
    displayName: "Generate HTML report"
 
  - publish: $(System.DefaultWorkingDirectory)/reports
    artifact: artillery-test-report

```

The ERROR I get when running the above is:   
```
CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE,
     set AWS_SDK_LOAD_CONFIG=1
    Code: CredentialsError
```

Is anyone familiar with how we can run the run-fargate command from an Azure Pipeline?

In the [documentation ](https://www.artillery.io/docs/reference/cli/run-fargate)I also see that you can --launch-config, but I don't see any examples for this.
