### DISCUSSION TITLE
Help Interpret Results

### DISCUSSION THREAD

**Discussion by Thilaknath** [artilleryio/artillery#2133] [Artillery]
Hello Team, I am fairly new to artillery and I have been trying to run a scenario for one of our services. I am exeucting the tests from my local and also through a docker container in parallel to simulate multiple agents (Haven't evaluated the fargate yet. Will do so in future)

My config is as below with just one phase
```
    - duration: 30
      arrivalRate: 200
      name: "Spike Phase"
```

Below are my results from my local and docker executed around the same time (30 seconds difference)
Local Machine
```
--------------------------------
Summary report @ 14:27:40(-0400)
--------------------------------

errors.ECONNRESET: ............................................................. 2
errors.ETIMEDOUT: .............................................................. 24
http.codes.202: ................................................................ 5974
http.downloaded_bytes: ......................................................... 0
http.request_rate: ............................................................. 161/sec
http.requests: ................................................................. 6000
http.response_time:
  min: ......................................................................... 112
  max: ......................................................................... 7885
  median: ...................................................................... 125.2
  p95: ......................................................................... 1326.4
  p99: ......................................................................... 1686.1
http.responses: ................................................................ 5974
vusers.completed: .............................................................. 5974
vusers.created: ................................................................ 6000
vusers.created_by_name.Update order: ........................................... 6000
vusers.failed: ................................................................. 26
vusers.session_length:
  min: ......................................................................... 336.9
  max: ......................................................................... 8822.4
  median: ...................................................................... 361.5
  p95: ......................................................................... 1863.5
  p99: ......................................................................... 2276.1
```

Docker Execution
```
--------------------------------
Summary report @ 18:28:42(+0000)
--------------------------------

errors.ETIMEDOUT: .............................................................. 17
http.codes.202: ................................................................ 5983
http.downloaded_bytes: ......................................................... 0
http.request_rate: ............................................................. 32/sec
http.requests: ................................................................. 6000
http.response_time:
  min: ......................................................................... 14
  max: ......................................................................... 5556
  median: ...................................................................... 135.7
  p95: ......................................................................... 584.2
  p99: ......................................................................... 2231
http.responses: ................................................................ 5983
vusers.completed: .............................................................. 5983
vusers.created: ................................................................ 6000
vusers.created_by_name.Update order: ........................................... 6000
vusers.failed: ................................................................. 17
vusers.session_length:
  min: ......................................................................... 412.5
  max: ......................................................................... 7358.6
  median: ...................................................................... 518.1
  p95: ......................................................................... 1978.7
  p99: ......................................................................... 3072.4
```

My question. How do I best interpret the TPS of my service ? Considering both test ran for 30s around the same time. Should the TPS be calculated as SUM(http.codes.202_Local + http.codes.202_Docker) / 30 or should it be SUM(http.request_rate_Local + http.request_rate_Docker) 

The values are pretty off. Can you help understand which would be the more accurate finding to calculate TPS. We come from using the nGrinder tool. Any pointers would help us a lot. 

Also we would like to really find out how much request a single instance of our service can handle/second. Hence we are defining scenarios for the same.

**Comment by bernardobridge** [comment]
Hello @Thilaknath,

Would you be able to share your test script, so I can understand better what it's doing? It's hard to know what transaction is here, as I don't know how many requests each VU is doing.

In general, though, a couple of pointers:

1. You typically don't want to be separating your runs into different "agents", unless you have a specific need for it. If you're trying to get more throughput, then Fargate (or Lambda, if your test is short) are the best options. The reason for this is that otherwise you'll lose result aggregation between the runs in each agent. But if you use something like Fargate, Artillery will take care of that aggregation for you.
2. Coming from different load test tools, you may need to think a little bit differently about Artillery's workload model, which aims to emulate real life usage as much as possible. This blog post explains it more: https://www.artillery.io/blog/load-testing-workload-models. Essentially, arrivals model users arriving into your application, but that doesn't necessarily translate into a fixed RPS/TPS.
3. Together with point 2, if you then have some golden signals for your application, you can try to define passing criteria for your test. For example, let's say an SLO for your application is that the latency of a specific endpoint should be below 500 ms. You could define an [ensure check](https://www.artillery.io/docs/reference/extensions/ensure) to make sure that's the case, and then run different arrival rates (hypothesis) that pass or fail that SLO. The ensure checks can assert on any metric - so you can make more complex assertions if needed. You'll then be able to say things like: _if 200 users are suddenly arriving every second over the course of 30 seconds, it breaks my SLO's, so my application cannot handle it (but maybe 100 would?)_.
4. You can also be observing from the point of view of your application, in your own monitoring systems, as they may be better suited to thinking in terms of "transactions" (i.e. you may have your observability set up to look for transactions in specific ways). So you may want to pair that with what you're seeing from the load generator.

Hopefully that helps you get started! But do feel free to share your test script like I mentioned above, and I can see if there's anything that jumps out 👍

**Reply by Thilaknath** [reply]
Hello @bernardobridge . Thanks a lot for your details. Below attached is a testScript I am using. 

```
config:
  # target: "http://localhost:8080"
  target: "https://<--MASKED--URL-->"
  phases:
    - duration: 90
      arrivalRate: 300
      name: "Spike Phase"
  processor: "./customProcessor.js"
before:
  flow:
    - post:
        url: "https://<--MASKED--URL-->/oauth/token"
        headers:
          Accept: "application/json"
        form:
          request_type: "token"
          grant_type: "client_credentials"
          client_id: "<--MASKED-ID>"
          client_secret: "<--MASKED-SECRET>"
        capture:
          - json: "$.access_token"
            as: "oauth_bearer_token"
scenarios:
  - name: "Update order"
    flow:
      - function: "generateOrderId"
      - patch:
          url: "public/orders/{{ orderId }}"
          headers:
            Authorization: "Bearer {{ oauth_bearer_token }}"
            Content-Type: "application/merge-patch+json"
            X-Item-TTL: 3600
          beforeRequest:
            - "setRequestBody"
```

I would like to hit the `/public/orders/<orderID>` endPoint of our service to understand how much requests it could process with one instance of the service. We are running the service in cloud foundry. We want to know  when the service would degrade so we could scale accordingly.
