### DISCUSSION TITLE
How to aggregate Playwright metrics by test.step instead of page

### DISCUSSION THREAD

**Discussion by stefan123t** [artilleryio/artillery#2164] [Artillery]
I do appreciate the artillery-engine-playwright integration to re-use DOM-model based playwright scripts for load-testing and I have been able to come up with a simple scenario, as below.

This works fine but as the app-context does not change all the events / interactive actions are aggregated with the same app-context.
Is there a way to allow aggregation based on playwright `test.step`'s ?

I tried to require / import test from @playwright/test but it still gives me as in https://github.com/artilleryio/artillery/discussions/1325:
```
| Error: test.step() can only be called from a test
    at TestTypeImpl._step (...\node_modules\playwright\lib\common\testType.js:191:26)
    at Function.step (...\node_modules\playwright\lib\transform\transform.js:236:12)
    at moveSimpson (...\search-person.js:6:16)
    at Array.scenario (...\artillery\node_modules\artillery-engine-playwright\index.js:136:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
```

Is simply aggregating the metrics using playwright `test.step`'s the right approach or would I rather need to create an artillery-plugin-metrics-by-test-step like in https://github.com/artilleryio/artillery/discussions/1196 ?

I read https://github.com/artilleryio/artillery/discussions/1831 and https://github.com/artilleryio/artillery/discussions/1754 discussion but I am still at loss being fairly new to Artillery.io

---

<details><summary>Details</summary>
<p>

**search-person.js**:
```javascript
// @ts-check
module.exports = { searchPerson };
// Note: this works without the following pwtest.step grouping's, i.e. only using await page....
const { test: pwtest } = require("@playwright/test");

async function searchPerson(page) {
  await pwtest.step('Step 1 - Homepage', async() => {
    await page.goto('https://example.tld/app-context/');
  });
  await pwtest.step('Step 2 - Login', async() => {
    await page.getByLabel('username').click();
    await page.getByLabel('username').fill('username');
    await page.getByLabel('username').press('Tab');
    await page.getByLabel('password').click();
    await page.getByLabel('password').fill('password');
    await page.getByRole('button', { name: 'login' }).click();
  });
  await pwtest.step('Step 3 - Some Button', async() => {
    await page.getByRole('button', { name: 'Yes' }).click();
  });
  await pwtest.step('Step 4 - Start > Search', async() => {
    await page.getByTitle('Search').click();
  });
  await pwtest.step('Step 5 - Lastname: Someone, Surname: Else, Search', async() => {
    await page.getByLabel('lastname').click();
    await page.getByLabel('lastname').fill('Someone');
    await page.getByLabel('surname').click();
    await page.getByLabel('surname').fill('Else');
    await page.getByRole('button', { name: 'Search' }).click();
  });
  // ...
  await pwtest.step('Step 14 - Logout', async() => {
    await page.getByRole('link', { name: 'logout' }).click();
  });
}
```

**search-person.yml**
```yml
config:
  target: https://example.tld/app-context/
  # Load the Playwright engine:
  phases:
    - name: Warm up phase
      duration: 20
      arrivalRate: 0
      rampTo: 5
    - name: Cool down phase
      duration: 5
      arrivalRate: 5
      rampTo: 0
  engines:
    playwright:
      launchOptions:
        headless: true # false to debug in browser instance
#        aggregateByName: true
  # Path to JavaScript file that defines Playwright test functions
  processor: "./search-person.js"
scenarios:
  - name: searchPerson
    engine: playwright
    testFunction: "searchPerson"
```

</p>
</details>

**Comment by bernardobridge** [comment]
Hi @stefan123t,

I believe the best way to do what you're describing would be to leverage Artillery's ability to emit custom metrics. You might be interested in using the pattern I described here https://github.com/artilleryio/artillery/issues/2147#issuecomment-1729259684 to achieve this, which does the following:

1. Creates the following utility wrapper `withTransactionTimer` which captures timings for arbitrary actions:
```js
const withTransactionTimer = async (transactionName, events, userActions) => {
  const startedTime = Date.now();
  await userActions();
  const difference = Date.now() - startedTime;

  events.emit('histogram', transactionName, difference)
}
```
2. Instead of wrapping your steps with `pwtest.step`, use the `withTransactionTimer` function;
3. You should now see metrics emitted in your Artillery reports with the names given to the first argument of `withTransactionTimer`, in addition to the usual Playwright metrics. It will give you metrics for the groups of actions you did.

Hope that helps!

**Reply by bernardobridge** [reply]
Also, @stefan123t, just a note that you can also use this config option:
https://www.artillery.io/docs/reference/engines/playwright#aggregate-metrics-by-scenario-name

`aggregateByName: true`

To aggregate metrics by the scenario name. Depending on how many things you're trying to aggregate, this may be simpler. If you're trying to get many transaction timers, then the approach above would be better.

**Reply by stefan123t** [reply]
Thanks @bernardobridge this works like a charm 🪄 / real 🚀 science,
I gave it a try and it emits the metric per `withTransactionTimer` see below for reference.

Now I do have a lot of `browser.page.*` metrics under `.aggregate.summaries` with distinct URLs as some of them contain a path `;jsessionid=hash:jvmid`.
While this should not be the case in the first place and has to be changed in the application logic I would like to filter them out using the `aggregateByName: true` but with not effect.

```json
      "browser.page.FCP.https://example.tld/app-context/;jsessionid=yTnM7t1Z-YuFCHqmYqeyg2UQOjK6kIlgV_W15KXDZbdp99jorPdc!1687860459": {
        "min": 87.1,
        "max": 87.1,
        "count": 2,
        "p50": 87.4,
        "median": 87.4,
        "p75": 87.4,
        "p90": 87.4,
        "p95": 87.4,
        "p99": 87.4,
        "p999": 87.4
      },
...
```

Any chance you can give me a hint on how to fix that too ?

Kind regards,
Stefan

---


<details><summary>Details</summary>
<p>

**search-person.js**:
```javascript
// @ts-check
module.exports = { searchPerson };

const withTransactionTimer = async (transactionName, events, userActions) => {
  const startedTime = Date.now();
  await userActions();
  const difference = Date.now() - startedTime;

  events.emit('histogram', transactionName, difference)
}

async function searchPerson(page, userContext, events) {
  await withTransactionTimer('Step 01 - Homepage', events, async() => {
    await page.goto('https://example.tld/app-context/');
  });
  await withTransactionTimer('Step 02 - Login', events, async() => {
    await page.getByLabel('username').click();
    await page.getByLabel('username').fill('username');
    await page.getByLabel('username').press('Tab');
    await page.getByLabel('password').click();
    await page.getByLabel('password').fill('password');
    await page.getByRole('button', { name: 'login' }).click();
  });
  await withTransactionTimer('Step 04 - Start > Search', events, async() => {
    await page.getByTitle('Search').click();
  });
  await withTransactionTimer('Step 05 - Lastname: Someone, Surname: Else, Search', events, async() => {
    await page.getByLabel('lastname').click();
    await page.getByLabel('lastname').fill('Someone');
    await page.getByLabel('surname').click();
    await page.getByLabel('surname').fill('Else');
    await page.getByRole('button', { name: 'Search' }).click();
  });
  // ...
  await withTransactionTimer('Step 14 - Logout', events, async() => {
    await page.getByRole('link', { name: 'logout' }).click();
  });
}
```

**search-person.yml**:
```
config:
  target: https://example.tld/app-context/
  # Load the Playwright engine:
  phases:
    - name: Warm up phase
      duration: 20
      arrivalRate: 0
      rampTo: 5
    - name: Cool down phase
      duration: 5
      arrivalRate: 5
      rampTo: 0
  engines:
    playwright:
      launchOptions:
        headless: true # false to debug in browser instance
        aggregateByName: true
  # Path to JavaScript file that defines Playwright test functions
  processor: "./search-person.js"
scenarios:
  - name: searchPerson
    engine: playwright
    testFunction: "searchPerson"
```
</p>
</details>

**Reply by bernardobridge** [reply]
Hi @stefan123t . Glad it helped!

Also, thanks for the really detailed report, it makes things easy 🎉!

You're setting `aggregateByName` in the wrong location, that's an Artillery custom option, not a `launchOptions` from Playwright. Try this config:

```yaml
  engines:
    playwright:
      aggregateByName: true
      launchOptions:
         headless: true # << this is true by default, by the way
```

That should help with this 👍.
