### DISCUSSION TITLE
How to remove square brackets and double quotes from variable?

### DISCUSSION THREAD

**Discussion by drrc1709** [artilleryio/artillery#2176] [Artillery]
Hello everyone, I'm just starting with artillery, I have the following situation, from a csv file I have a list of names and I concatenate this to a windows route to send it within a json to a post http request, the issue is that this variable comes out with [\\"  my-variable \\"], how do I remove the square brackets, double quotes and backslash
 ```
 - post:
            url: "http://localhost:8080/api/v1/encrypt"
            headers:
              Content-Type: "application/json"    
              Accept: "application/json"          
            json:
              file: "C:/Users/drrodriguez/Desktop/E11/actas/{{ acta }}.zip"
            capture:
             - json: "$.file"
               as: "file"
             - json: "$.hash"
               as: "hash"
```

![image](https://github.com/artilleryio/artillery/assets/50565417/3d9d0538-2c2f-462e-8759-619e8bf7ec10)

**Comment by bernardobridge** [comment]
Hello @drrc1709 👋 ,

Can you please share a small snippet of how your `CSV` looks like, and how your `config` importing the CSV is?

**Reply by drrc1709** [reply]
Hi, @bernardobridge of course,  So I load the csv and this is the content 
```
payload:
    - path: "data/list.csv"
      fields:
        - "acta"
      order: sequence
      skipHeader: true
      loadAll: true
      name: acta
```

list.csv
```
acta
E11_31_001_01_01_001_01062022110506690_01_24_29052022_ASD_C
E11_31_001_01_01_002_01062022110645511_01_24_29052022_ASD_C
E11_31_001_01_01_003_01062022110740791_01_24_29052022_ASD_C
E11_31_001_01_01_004_01062022110855307_01_24_29052022_ASD_C
E11_31_001_01_01_005_01062022111037137_01_24_29052022_ASD_C
E11_31_001_01_01_006_01062022111128186_01_24_29052022_ASD_C
E11_31_001_01_01_007_01062022111245032_01_24_29052022_ASD_C
E11_31_001_01_01_008_01062022111455662_01_24_29052022_ASD_C
E11_31_001_01_01_009_01062022111556009_01_24_29052022_ASD_C
E11_31_001_01_01_010_01062022111656749_01_24_29052022_ASD_C
```

**Reply by bernardobridge** [reply]
Hi @drrc1709. Thanks for the information! 

First off, you're giving the same value to the `name` property and the `fields` property, which is not ideal, because both are defining a variable named the same. In this case, I believe the `name` field wins out, which is why you're seeing the data as an array (i.e. the entire CSV due to `loadAll`). I would still advise you to name them differently, however.

If you still want to use `loadAll` and `name` (https://www.artillery.io/docs/reference/test-script#payload-file-options), you can access an individual value like this:

```yaml
json:
     #choose the index of the array, I chose 0 here as an example
     file: "C:/Users/drrodriguez/Desktop/E11/actas/{{ acta[0] }}.zip"
```

But, if you prefer, you can not use `loadAll`/`name` and it will pick a value defined in `fields` based on the `order` you defined. Bear in mind [there are currently some reported issues](https://github.com/artilleryio/artillery/discussions/1860) with sequence order, so random order might be better.

Hope that helps!
