### DISCUSSION TITLE
Not able to use filter params in my artillery script

### DISCUSSION THREAD

**Discussion by shiv-vsics** [artilleryio/artillery#2182] [Artillery]
Hi Team,

I am a new user to artillery and exploring it. I have written one script and added params in that but somehow that is not working and its not picking filter. Could you please help me with the exmaples like how can i use single/multiple params in yaml sciprt. If i dont have use filter param, script works fine. I am adding correct filter values. 

Below is the sample for my yaml file. 
[TEST.txt](https://github.com/artilleryio/artillery/files/12793539/TEST.txt)

==================================================
```yaml
config:
  target: 'https://test.api.com'
  phases:
    - duration: 60
      arrivalRate: 5
      rampTo: 10
      name: Warm up the API
    - duration: 60
      arrivalRate: 10
      rampTo: 15
      name: Ramp up to Peak Load
  plugins:
    expect: {}

scenarios:
  - name: "Performance Test"  
    flow:
      - get:
          url: '/test/v2/value/'
          headers:
            appkey: 'ValidAppkey'
          params:
            filter: 'symbol in ("ABCDEFGH")'
    expect:
      - statusCode: 200
      - equals:
          - respMessage: "OK"
```
================================================

**Comment by InesNi** [comment]
Hi @shiv-vsics! Welcome to Artillery 🙌🏻.

We don't have a `params` option with `filter` available in requests. I'm going to assume maybe you're trying to use Query String parameters? If so, the correct way to use them in Artillery v2 is documented here: https://www.artillery.io/docs/reference/engines/http#query-strings

You can alter your scenario like this:

```yaml
scenarios:
  - name: "Performance Test"  
    flow:
      - get:
          url: '/test/v2/value/'
          headers:
            appkey: 'ValidAppkey'
          qs:
            filter: 'symbol in ("ABCDEFGH")'
```

Let me know if that helps. Thanks!
