### DISCUSSION TITLE
Load testing Socket Io with Artillery not working - timeouts

### DISCUSSION THREAD

**Discussion by aleksandarvanced** [artilleryio/artillery#2183] [Artillery]
Hello,
I am trying to test SocketIo with Artillery as specified in the link here https://socket.io/docs/v4/load-testing/#manual-client-creation and the documentation https://www.artillery.io/docs/reference/engines/socketio. 

Here is my test scenario - i am trying to connect to a server URL with a custom path - and i need to send a header as an Authentication. My scenario involves creating a specific amount of users, which emit a message to the server - to subscribe to a channel for example - and the server should start sending events after that

```
config:
  target: "https://example.com"
  socketio:
    path: "/customPath"
    extraHeaders:
      x-auth-header: "header-value"
  phases:
    - duration: 10
      arrivalRate: 2
  engines:
    socketio-v3: {}

scenarios:
  - name: Scenario
    engine: socketio-v3
    flow:
      # wait for the WebSocket upgrade (optional)
      - think: 1

      # emit an object
      - emit:
          channel: "channel/v1"
          data:
            method: "subscribe"
            params:
              param1: "xx"
              param2: "yy"
      # do nothing for 30 seconds then disconnect
      - think: 30
```

When i am executing the script with debug mode - i am getting `socketio Error: timeout`.

When executing this request through Postman Socket IO client - all works
Handshake path is `/customPath`
URL is `https://example.com`
Message sent after connection to event is `channel/v1` with the following JSON body
```
{
    "method": "subscribe",
    "params": {
        "param1": "xx",
        "param2": "yy"
    }
}
```

**Comment by bernardobridge** [comment]
Hey @aleksandarvanced,

Thanks for the report. The `socketio-v3` engine is third-party, but Artillery's own built-in `socketio` engine now supports v3/v4, so you should be able to use that (that documentation from SocketIO needs to be updated - we'll bring it to their attention once our new release is published, which fixes a couple of bugs with the engine).

I don't have the code for your server, but I just ran the following test and dummy server, without any timeout (both using the built-in `socketio` engine and the `socketio-v3` third-party):

```js
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
    path: '/customPath',
    // Middleware to handle authentication
    middleware: [(socket, next) => {
        const authHeader = socket.handshake.headers['x-auth-header'];
        if (authenticate(authHeader)) {
            return next();
        }
        next(new Error('Authentication error'));
    }]
});

function authenticate(authHeader) {
    // dummy authentication logic
    return authHeader === 'your-secret-token';
}

io.on('connection', (socket) => {
    console.log('a user connected');

    socket.on('channel/v1', (msg) => {
        console.log(msg)
        io.emit('channel/v1', msg);
    });

    socket.on('disconnect', () => {
        console.log('user disconnected');
    });
});

server.listen(3000, () => {
    console.log('listening on *:3000');
});
```

```yaml
config:
  target: "http://localhost:3000"
  socketio:
    path: "/customPath"
    extraHeaders:
      x-auth-header: "your-secret-token"
  phases:
    - duration: 10
      arrivalRate: 2
  engines:
    socketio: {}

scenarios:
  - name: Scenario
    engine: socketio
    flow:
      # wait for the WebSocket upgrade (optional)
      - think: 1

      # emit an object
      - emit:
          channel: "channel/v1"
          data:
            method: "subscribe"
            params:
              param1: "xx"
              param2: "yy"
      # do nothing for 30 seconds then disconnect
      - think: 30
```

What Artillery version are you using? 
Other than that, is there anything very different in what your server is doing compared to mine ? I understand this is a simplified example, but it does contain all the features you mentioned, I think. This is my report from running the test above:

```
--------------------------------
Summary report @ 20:24:43(+0100)
--------------------------------

socketio.emit: ................................................................. 20
socketio.emit_rate: ............................................................ 2/sec
socketio.response_time:
  min: ......................................................................... 0.1
  max: ......................................................................... 1.2
  median: ...................................................................... 0.2
  p95: ......................................................................... 0.7
  p99: ......................................................................... 0.7
vusers.completed: .............................................................. 20
vusers.created: ................................................................ 20
vusers.created_by_name.Scenario: ............................................... 20
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 31005
  max: ......................................................................... 31027.7
  median: ...................................................................... 31266.3
  p95: ......................................................................... 31266.3
  p99: ......................................................................... 31266.3
```

**Comment by aleksandarvanced** [comment]
@bernardobridge  Thanks for your reply.
Here is the artillery version
VERSION INFO:
Artillery: 2.0.0-37
Node.js:   v14.19.2
OS:        darwin

We are using Java Socket IO server - https://github.com/mrniko/netty-socketio.
From the logic perspective your server code looks pretty similar.

By using your artillery code - i am getting the following error
`errors.an URL must be specified: ............................................... 20`
According to https://github.com/artilleryio/artillery/issues/254, `engine: "socket.io"` needs to be specified in the scenario definition.

When adding engine: socketio back in the scenario, i am still getting the timeouts. 
Any idea how i can debug it? Already using the DEBUG command -  `DEBUG=socketio artillery run test-scenario.yml`

**Reply by aleksandarvanced** [reply]
Ok seems adding `transports: ["websocket"]` fixed the issue and now it works - i am not exactly sure why. Could it be because our server is sitting behind a reverse proxy?
One additional question - is it possible to listen for server to client events in artillery? Because the documentation here https://socket.io/docs/v4/load-testing/#manual-client-creationsays it is kinda not possible and that we need to use the manual approach for that.
Also how does passing JSON work in artillery? Because 
```
data:
            method: "subscribe"
            params:
              param1: "xx"
              param2: "yy"
``` 
does not seem to work - and i am seeing an example https://github.com/artilleryio/artillery/issues/657 which passes the json object inline in data?

**Reply by bernardobridge** [reply]
Hey @aleksandarvanced - maybe your reverse proxy wasn't configured for long polling (the default)? Not sure!

>One additional question - is it possible to listen for server to client events in artillery?

More or less. It's possible to listen for responses/acknowledgments from the server, so for example: 
```yaml
scenarios:
  - name: "Emit an event"
    engine: socketio
    flow:
      - emit:
          channel: "echo"
          data: "Hello from Artillery"
        response:
          channel: "echoResponse"
          data: "Hello from Artillery"
```

We're in the process of upgrading this interface to allow more flexibility in the arguments in the response, but for now the [third-party engine](https://github.com/ptejada/artillery-engine-socketio-v3) shows you how to listen to the server event (`response.on`). 

---

> Also how does passing JSON work in artillery? 

It should be possible to do it the same way you did it. In the example I gave in my first reply, the `console.log(msg)` in the server was successfully logging your data object. Just make sure the YAML indentation is correct.
