### DISCUSSION TITLE
Where are the JavaScript test examples?

### DISCUSSION THREAD

**Discussion by GeorgeXCV** [artilleryio/artillery#2187] [Artillery]
The docs say "Artillery test scripts are usually written as YAML, but they can also be written in JavaScript." However, I can't find any examples of tests in JavaScript. Does anyone have any they can share?

**Comment by hassy** [comment]
hi @GeorgeXCV 👋 the main entrypoint needs to be a YAML file, but you can drop into Javascript like this:

```yaml
config:
  processor: "./my-functions.js"
scenarios:
  - flow:
    - function: "myTestFunction"
```

```
// my-functions.js

function myTestFunction(userContext, events, done) {
  // Do anything here
  return done();
}

module.exports = { myTestFunction }
```

This makes use of the `function` step: https://www.artillery.io/docs/reference/engines/http#function-actions-and-beforescenario--afterscenario-hooks
