### DISCUSSION TITLE
ensure plugin with metrics by endpoint

### DISCUSSION THREAD

**Discussion by Mathdon** [artilleryio/artillery#2190] [Artillery]
Hi, I am using version 2.0.0-37 and using the ensure plugin.
I have it working with 
        - "http.response_time.p99": 2000
        - "vusers.failed": 1
        - "apdex.frustrated": 3
     
But it always fails when trying to use the p.99 metric from the metrics by endpoint plugin.

I have copied the metric name from what is printed in the console but it doesn't recognise it.

is this possible?

**Comment by bernardobridge** [comment]
Hello @Mathdon ,

Could you please share your full test script (with configuration), as well as any error you're getting? This will help us spot any issues and/or replicate your issue.

Thank you.

**Reply by Mathdon** [reply]
Hi @bernardobridge 

The below is what i used and received

```yml
config:
  target: '{{ $processEnvironment.BASE_URL }}' # this hostname will be used for each part of the flow
  plugins:
    apdex:
      threshold: 100
    expect: {}
    ensure:
      thresholds:
        - "plugins.metrics-by-endpoint.response_time./enforcement-driver-enquiry/v1/drivers/retrieve.p99": 2000
        - "http.response_time.p99": 2000
        - "vusers.failed": 1
        - "apdex.frustrated": 99
    metrics-by-endpoint: {}

  environments:
    ci:
      phases:
        - duration: 10
          arrivalRate: 1
          rampTo: 3
  payload:
    path: '../data.csv'
    fields:
      - 'field1'
scenarios:
  - name: 'retrieve'
    flow:
      - post:
          url: '/v1/drivers/retrieve'
          json:
            drivingLicenceNumber: '{{ field1 }}'
          expect:
            statusCode: 200
```

Then artillery returns

```
Checks:
ok: apdex.frustrated < 99
ok: vusers.failed < 1
ok: http.response_time.p99 < 2000
fail: http.plugins.metrics-by-endpoint.response_time./enforcement-driver-enquiry/v1/drivers/retrieve.p99 < 2000
```

and the metrics is shows
```
apdex.frustrated: .............................................................. 5
apdex.tolerated: ............................................................... 15
http.codes.404: ................................................................ 20
http.request_rate: ............................................................. 2/sec
http.requests: ................................................................. 20
http.response_time:
  min: ......................................................................... 145
  max: ......................................................................... 840
  median: ...................................................................... 198.4
  p95: ......................................................................... 699.4
  p99: ......................................................................... 699.4
http.responses: ................................................................ 20
plugins.metrics-by-endpoint./enforcement-driver-enquiry/v1/drivers/retrieve ...  20
plugins.metrics-by-endpoint.response_time./enforcement-driver-enquiry/v1/drivers/retrieve (enf):
  min: ......................................................................... 145
  max: ......................................................................... 840
  median: ...................................................................... 198.4
  p95: ......................................................................... 699.4
  p99: ......................................................................... 699.4
vusers.completed: .............................................................. 20
vusers.created: ................................................................ 20
vusers.created_by_name.retrieve: ............................................... 20
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 240.2
  max: ......................................................................... 940.5
  median: ...................................................................... 314.2
  p95: ......................................................................... 804.5
  p99: ......................................................................... 804.5
```
