### DISCUSSION TITLE
Playwright - Tests run only one and stops after that

### DISCUSSION THREAD

**Discussion by RobinSCU** [artilleryio/artillery#2191] [Artillery]
Good Morning,

I'm currently in the final steps of setting up Artillery with Playwright and i have the problem, that my playwright script runs only once and only with one vu.

I'm starting the script local on my pc with `artillery run example.yml`

This is my ultra-simplified yaml:

```yaml
config:
  target: http://asciiart.artillery.io:8080
  engines:
    playwright: {}
  processor: "./flow.js"
phases:
  - duration: 60
    arrivalRate: 1
    rampTo: 5
    name: Warm up phase
  - duration: 60
    arrivalRate: 5
    rampTo: 10
    name: Ramp up load
  - duration: 30
    arrivalRate: 10
    rampTo: 30
    name: Spike phase
scenarios:
  - engine: playwright
    flowFunction: helloFlow
    flow: []

```

and my simple script:

```js
async function helloFlow(page) {
  //
  // The code below is just a standard Playwright script:
  //
  // Go to https://artillery.io/
  await page.goto("https://www.artillery.io/");
  // Click text=Pricing
  await page.click("text=Cloud");
}
module.exports = { helloFlow };
```

More Infos:
OS: Windows 10
nodejs: 20.1.0
playwright 1.38.1
Artillery: 2.0.0.-37

Is there something i miss? 

We have our load test on Thuesday and i'm switching in panic mode from flood.io to Artillery :)

Thanks!
Robin
