### DISCUSSION TITLE
Refresh auth token

### DISCUSSION THREAD

**Discussion by Mathdon** [artilleryio/artillery#2196] [Artillery]
What would you suggest to handle re-freshing an auth token when testing API's that need this?

I use the before hook to make a request to get the token and then use that in the requests.

The problem I have is if trying to run a test for longer than an hour the token expires and I get 403's back from the API.

What would be the best way to refresh the token?

**Comment by hassy** [comment]
If the same token is shared by all VUs, you could use [a `beforeScenario` hook](https://www.artillery.io/docs/reference/engines/http#function-actions-and-beforescenario--afterscenario-hooks) and grab a new token when the current one expires.

**Reply by Mathdon** [reply]
Thank's for the reply @hassy I'll give that a go

**Reply by hassy** [reply]
Let us know if you run into any issues or need a pointer @Mathdon!

**Reply by Mathdon** [reply]
Hi @hassy 

I have make a little script that works for refreshing a token.

it works with these plugins

```yaml
  plugins:
    expect: {}
    metrics-by-endpoint:
      useOnlyRequestNames: true
    publish-metrics:
```
 
 But when adding these plugins
```yaml
   plugins:
    apdex:
      threshold: 2000
    ensure:
      thresholds:
        - "http.response_time.p99": 2000
        - "vusers.failed": 1
        - "apdex.frustrated": 99
```

It throws an error:
```stout
⠋ /node_modules/artillery-plugin-apdex/index.js:42
    script.config.processor.apdexAfterResponse = apdexAfterResponse;
                                               ^

TypeError: Cannot create property 'apdexAfterResponse' on string '../plugins/manage_auth_token.js'
    at new ApdexPlugin (/node_modules/artillery-plugin-apdex/index.js:42:48)
    at Launcher.initPlugins (/node_modules/artillery/lib/launch-platform.js:200:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Launcher.run (/node_modules/artillery/lib/launch-platform.js:394:5)
```

And:
```stout
⠋ /node_modules/artillery-plugin-ensure/index.js:38
    const checks = this.script.config.ensure || this.script.plugins.ensure;
                                                                    ^

TypeError: Cannot read properties of undefined (reading 'ensure')
    at new EnsurePlugin (/node_modules/artillery-plugin-ensure/index.js:38:69)
    at Launcher.initPlugins (/node_modules/artillery/lib/launch-platform.js:200:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Launcher.run (node_modules/artillery/lib/launch-platform.js:394:5)
```
I added the script using the processor
```yaml
processor: "../plugins/manage_auth_token.js"
```
And then it is called in the beforeRequest hook (get the same error in the beforeScenario hook)

Any ideas on this?
