### DISCUSSION TITLE
Playwright output as HAR file

### DISCUSSION THREAD

**Discussion by roydekleijn** [artilleryio/artillery#2199] [Artillery]
Hello,

I'm running some Playwright flows with artillery. I try to save the output (requests made by the browser) into a HAR file. This is fine when running 1 session/arrival/vusers, but doesn't work when running multiple sessions/arrivals.

This is the Playwright config I'm using:

```
  engines:
    playwright:
      contextOptions:
        recordHar: 
          path: 'requests3.har'
          mode: 'full'
          urlFilter: '**/xas/**'
      launchOptions:
        headless: true
```

My question is, how can I combine all the output in a single HAR file, OR how can I create 1 HAR file per session/arrival/vusers ? Which then can be processed later on. 

Happy to collaborate on this!
Roy
