### DISCUSSION TITLE
POST requests have empty request body

### DISCUSSION THREAD

**Discussion by Enforc3rr** [artilleryio/artillery#2208] [Artillery]
Basically I am trying to make a post request and my POST request bodies are empty.  

yml file -> 
```
config:
  target: "https://backend-url.com" # The target URL of your API
  processor: "./RequestBody.js"
  phases:
    - duration: 1 # Duration of the test in seconds
      arrivalRate: 1 # Number of virtual users to start per second
scenarios:
  - name: my-service-name 
    # beforeScenario: generatePostBody
    flow:
      - post:
          url: "/api/v1/order"
          beforeScenario: "generatePostBody"
          body: "{{ data }}"
          headers:
            Content-Type: "application/json"
```
RequestBody.js ->   
```
exports.generatePostBody = async (userContext, events, done) => {
  try {
    const jsonData = {
      merchant_username: "Login ID",
      customer_key: "API_KEY_12",
      customer: {
        name: "test",
      },
      transaction: {
        id: `T${generateRandomNumber()}`,
        number: `T${generateRandomNumber()}`,
        billLink: "https://abc.in/123",
        }
    };
    userContext.vars.data = JSON.stringify(jsonData);
    return done();
  } catch (err) {
    console.log(`Error occurred in function generatePostBody. Detail: ${err}`);
    throw err;
  }
};
function generateRandomNumber() {
  return Math.floor(Math.random() * 1000) + 1;
}


```

Thanks , I have tried many permutation and combination but nothing seemed to have worked , I know I am missing out a basic key detail right now.
