### DISCUSSION TITLE
Completed VUs and Created VUs

### DISCUSSION THREAD

**Discussion by okHadi** [artilleryio/artillery#2219] [Artillery]
I just ran a load test and the number of created VUs is 4040, while the number of completed VUs is just 418.
Failed VUs are only 209.
How is this possible? How does artillery define what is a completed VU?
This is the config yml file:
```
config:
  target: myurl
  phases:
  - duration: 200
    arrivalRate: 25
    maxVusers: 30
  engines:
    playwright: {extendedMetrics: true}
  processor: "./flows.js"
scenarios:
- engine: playwright
  testFunction: "helloFlow"
```
