### DISCUSSION TITLE
Payload on Fargate

### DISCUSSION THREAD

**Discussion by saveveltri** [artilleryio/artillery#2220] [Artillery]
Hello,

I hope this is not a duplicate question.

I have a playwright test suite that I can run on Fargate. The problem is that this suite makes modification to the system that involves the user experience; users can perform certain operations only once and the system gives an error message if the same user attempts to do the same operation concurrently.

I have a set of users inside a CSV but I'm not able to pick one CSV row uniquely just once.
Is there a particular configuration or any known workaround to run a test suite on fargate and be sure that a user is picked only once?

Thanks

**Comment by hassy** [comment]
Hi @saveveltri 👋 Artillery's CSV payload feature does not support using values just-once/uniquely. Other users have implemented a similar use case with Redis in the past (you load the data into a Redis list and then use the [LPOP](https://redis.io/commands/lpop/) command to grab values one by one - this is done from a `beforeScenario` hook). You can run a Redis container on the same Fargate cluster as you run Artillery or use a hosted Redis service for this - e.g. https://aws.amazon.com/redis/ or https://upstash.com/

**Reply by saveveltri** [reply]
Thanks @hassy for the advice. I was able to do that by adding a function which pops the id from redis inside the test JS. For some reason I was not able to manage to make the beforeScenario work.

```
config:
  target: "[LEGIT TARGET]"  
  engines:
    playwright:
      aggregateByName: 
        true          
      launchOptions:
        headless: true        
  processor: "[LEGIT PROCESSOR]"  

  phases:
    - duration: 5
      arrivalCount: 20
      name: Load
  

scenarios:  
  - name: "Load Test AV"   
    beforeScenario: "pickUsers"
    engine: playwright
    testFunction: "loadTest"
```

it seems that the function specified in the `beforeScenario` is not called. 

Thanks
