### DISCUSSION TITLE
Understanding Artillery SocketIO Syntax

### DISCUSSION THREAD

**Discussion by vito-vanhecke** [artilleryio/artillery#2222] [Artillery]
I am trying to make a script that tests my socket.io server, I followed a blog post regarding the subject. But it is not entirely what I wanted.
Here is the repo from the blogpost: [https://github.com/hassy/socketio-load-test-artillery-example/tree/master](https://github.com/hassy/socketio-load-test-artillery-example/tree/master)

What I am trying to achieve is 50 concurrent connections to this server, but users disconnect/connect seemingly at random.

Here is the yaml file for my current config:
```yml
config:
  target: "..."
  phases:
    - duration: 1m
      arrivalCount: 10
      name: Warm Up Fase
    - duration: 1m
      arrivalCount: 50
      name: Load Fase
    - duration: 10m
      arrivalCount: 50
      name: Sustained load 
  variables:
    greeting: ["hello", "goedemorgen", "добрый день", "guten tag", "bonjour", "hola"]
  processor: "./functions.js"
  engine: socketio
  socketio:
    auth:
      api_key: ...
      rooms: ...

scenarios:
  - name: "A user that just lurks"
    weight: 75
    flow:
      - emit:
          channel: "event"
          data: { "rooms": "...", "text": "lurker-{{ $randomString() }}" } 
      - think: 12m

  - name: "A mostly quiet user"
    weight: 15
    flow:
      - emit:
          channel: "event"
          data: { "rooms": "...", "text": "quiet-{{ $randomString() }}" } 
      - emit:
          channel: "event"
          data: { "rooms": "....", "text": "{{ greeting }}" } 
      - think: 12m

  - name: "A chatty user"
    weight: 10
    flow:
      - emit:
          channel: "event"
          data: { "rooms": "...", "text": "chatty-{{ $randomString() }}" } 
      - emit:
          channel: "event"
          data: { "rooms": "...", "text": "{{ greeting }}" } 
      - loop:
          - function: "setMessage"
          - emit:
              channel: "event"
              data: { "rooms": "...", "text": "{{ message }}" } 
          - think: 1s
        count: 60
      - think: 11m
```

So just to be clear, in the "Sustained load" phase, I want 50 users to be chatting away, or just lurking... Right now with this config there are at most like 10 users chatting a the same time
