### DISCUSSION TITLE
Artillery isnt able to connect to server errors.ECONNREFUSED

### DISCUSSION THREAD

**Discussion by vskk022** [artilleryio/artillery#2227] [Artillery]
I am trying to set up Artillery load test using:
```
config:
  target: "http://localhost:3002"
  phases:
    - duration: 1
      arrivalRate: 1
scenarios:
  - flow:
      - post:
          url: "/register"
          json:
            username: "world"
            password: "securepassword"
            email: "user@domain.com"
```

but I am getting
```
errors.ECONNREFUSED: ........................................................... 1
http.request_rate: ............................................................. 1/sec
http.requests: ................................................................. 1
vusers.created: ................................................................ 1
vusers.created_by_name.0: ...................................................... 1
vusers.failed: ................................................................. 1
```
I know that the server is reachable because when I call `http://localhost:3002/register` from postman, it returns the right response. Response body sent from Postman is:
```
{
  "username": "iasd5as524",
  "password": "JS9812!wj",
  "email": "aosdj@aasojsd1d.com"
}
```

My Node server is running inside Virtualbox with port forwarding enabled.
