### DISCUSSION TITLE
ArrivalRate of value greater than 1 repeats data from CSV in outgoing requests

### DISCUSSION THREAD

**Discussion by vskk022** [artilleryio/artillery#2228] [Artillery]
I noticed that `arrivalRate` value greater than 1, for example: arrivalRate: 2, sends 2 requests for each data line in CSV file. I want both requests to be unique.

CSV file -----------------
username,password,email
yFGhq7ZUNHh2,ekMXSTezd,if0U4BD0XyX@4WzXO3.com (This line is sent 2 times in 2 different requests)
alcbXVd7bn,nJZmJsPf2uK,GMVw1GNW@jbqosa2vx.com (This line is sent 2 times in 2 different requests)

I want that when I set `arrivalRate: 2` then line (1) should be sent once and same for line (2), and should be sent within 1 second. Similarly if I set `arrivalRate : 5` then I want 5 unique requests per second.

How do I do it?
```

config:
  target: "https://127.0.0.1:3001"
  https:
    timeout: 5
  tls:
    rejectUnauthorized: false
  phases:
    - duration: 1
      arrivalRate: 2
      rampTo: 2
      name: Warm up phase

  payload:
    path: "userdata.csv"
    fields:
      - "username"
      - "password"
      - "email"
    order: sequence
    skipHeader: true
scenarios:
  - flow:
      - post:
          url: "/register"
          json:
            username: "{{username}}"
            password: "{{password}}"
            email: "{{email}}"
```

**Comment by tamlyn** [comment]
This is a very common request (see also https://github.com/artilleryio/artillery/discussions/1798, https://github.com/artilleryio/artillery/discussions/1860, https://github.com/artilleryio/artillery/issues/922#issuecomment-1488367948, https://github.com/artilleryio/artillery/issues/1221). I understand that this cannot work in a distributed environment but I would expect it to work when running Artillery on a single machine. 

Is there really no other way to achieve this? It seems like such a key feature. 

In our case we're testing a user onboarding flow where each user needs a unique email and phone number. We could randomise the email but there's only a limited amount of valid phone numbers so randomisation is less appealing. I really like Artillery but so far but this issue means we either have to accept topping out our tests at `arrivalRate: 1` or switch to a different load testing framework 😢.

**Reply by hassy** [reply]
hi @tamlyn 👋 we do want to solve this natively in Artillery but there's no ETA yet. In the meantime a solution that we recommend and that has worked for other user with a similar use-case is to use something like Redis for shared memory between VUs:

1. You can load the dataset into a Redis list
2. Each VU can [pop](https://redis.io/commands/lpop/) a value off of the list in a [`beforeScenario` hook](https://www.artillery.io/docs/reference/engines/http#function-actions-and-beforescenario--afterscenario-hooks) and use it in the scenario itself

Happy to help get this to work. feel free to email me on hveldstra@artillery.io with more info too

**Reply by tamlyn** [reply]
Nice! That works really well actually. In an effort to keep things low tech, I cobbled something together using file locking rather than Redis.

1. Install [lockfile](https://www.npmjs.com/package/lockfile) from npm.

2. Save this as `user.js`:

```
const fs = require("fs");
const lockfile = require("lockfile");

const lockFilePath = `${__dirname}/counter.lock`;
const counterFilePath = `${__dirname}/counter.txt`;

function getCounterAndIncrement() {
  return new Promise((resolve, reject) => {
    lockfile.lock(lockFilePath, (err) => {
      if (err) return reject(err);

      const content = fs.readFileSync(counterFilePath, "utf8");
      const value = content.trim();
      const nextValue = (parseInt(value, 10) + 1).toString().padStart(4, "0");
      fs.writeFileSync(counterFilePath, nextValue);

      lockfile.unlock(lockFilePath, (err) => {
        if (err) return reject(err);
        resolve(value);
      });
    });
  });
}

exports.getUserDetails = function (context, ee, next) {
  getCounterAndIncrement().then(
    (userNumber) => {
      // do stuff with your unique user number here, e.g.
      context.vars.email = `loadtest+${userNumber}@example.com`;
      next();
    },
    (err) => {
      console.error(err);
      next(err);
    },
  );
};
```

3. Create a file in the same folder called `counter.txt` containing `0000`.

4. Update your load test:

```
config:
  # ... other config
  processor: ./user.js
scenarios:
  - flow:
      - function: getUserDetails
      - log: "New virtual user with email {{email}} "
      # ... other steps
```
