### DISCUSSION TITLE
Fargate execution and Artifactory

### DISCUSSION THREAD

**Discussion by ematta** [artilleryio/artillery#2247] [Artillery]
Hello folks, my team is using a proxy for our npm packages with artifactory. Our setup for artifactory is in a `.yarnrc.yaml` file (in `npmRegistryServer`). Is there any way we can:

1. Use `yarn` as a package installer?
2. Bundle our `.yarnrc.yaml` file?
3. Any other things we need to know about artifactory or proxies?

**Comment by hassy** [comment]
Hi @ematta 👋  I *think* it might just work, but we haven't tested it.

There's a way to tell Artillery to bundle specific files via `config.includeFiles`, for example:

```yaml
config:
  target: "https://myapp.example.com"
  includeFiles:
    - foo.json # paths are resolved relative to the directory where the test script is located
    - bar.xml
```

This will include `foo.json` and `bar.xml` in the bundle. The option is not documented yet, but it can be relied on. You should be able to use this option to bundle your `.yarnrc.yaml`.

Artillery will also automatically bundle the `yarn.lock` file if it's present, and run `yarn install` inside Fargate containers (instead of defaulting to `npm`). If `.yarnrc.yaml` is present, Yarn should then use your Artifactory instance to install those packages.

Let us know if that works. If it doesn't, please feel free to email me on hveldstra@artillery.io with any extra information you can share so that we can make it work.
