### DISCUSSION TITLE
Artillery + Playwright: Login once using before

### DISCUSSION THREAD

**Discussion by shiva-taramani** [artilleryio/artillery#2279] [Artillery]
Hi, all! It's me again, your novice who is trying to use artillery + playwright.

I am using the Playwright engine with artillery and I am running into a scenario where I want to authenticate just once and then have all the vusers share that authenticated session. I tried a `before` but that did not seem to work.

I also have my Playwright code using a [setup method](https://playwright.dev/docs/auth#basic-shared-account-in-all-tests).

Any help would be much appreciated. I think I am missing something obvious.

Thank you for the help!

**Comment by angelo-loria** [comment]
I'm also confused on how `before`/`beforeScenario` works with the Playwright engine. This starts executing `testFunction`, skipping the `beforeScenario`:

```
scenarios:
    - engine: playwright
      beforeScenario: "login"
      testFunction: "testFunction"
```

**Comment by angelo-loria** [comment]
Alright figured this out, although there might be a cleaner way to do it. I'm using a `before` section with a function that POSTs to a login API and then writes the response token I need to a JSON file (emulating the `storageState` function in Playwright.) This JSON file is then specified in the Playwright `contextOptions`.

My Artillery config:

```
config:
    target: https://siteUnderTest.com/
    engines:
        playwright: {
                contextOptions: { storageState: "state.json" },
            }
    processor: "./processors/playwright-flows.js"

before:
    flow:
        - function: postLogin

scenarios:
    - name: playwright flow
      engine: playwright
      testFunction: playwrightFlow

```

My JS script:

```
module.exports = { playwrightFlow, postLogin };
const playwright = require("playwright");

async function postLogin(context, ee, next) {
    const apiContext = await playwright.request.newContext({
        storageState: undefined,
    });
    const response = await apiContext.post(
        "https://siteUnderTest.com/api/v1/sign-in",
        {
            data: {
                username: "userName",
                password: "password",
            },
        }
    );
    const loginResponse = await response.json();
    var stateJson = {
        cookies: [
            {
                name: "token",
                value: loginResponse.user.token,
                domain: "https//www.siteUnderTest.com",
                path: "/",
                expires: -1,
                httpOnly: false,
                sameSite: "Lax",
                secure: true,
            },
        ],
    };
    const fs = require("fs");
    fs.writeFile(
        "state.json",
        JSON.stringify(stateJson, null, 2),
        function (err) {
            if (err) throw err;
        }
    );
    next();
}

async function playwrightFlow(page) {
    await page.goto(
        "https://siteUnderTest.com/home"
    );
    ...
```

**Comment by bernardobridge** [comment]
👋  You can now use `engine: playwright` correctly in `before`/`after`, since Artillery v2.0.4: https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.4

Example of reusing authentication with `storageState`: https://github.com/artilleryio/artillery/tree/main/examples/browser-playwright-reuse-authentication

*Note: `beforeScenario` is still not supported in the Playwright engine, but I believe a `before` hook better suits what was being attempted in this topic!*

**Reply by alexandre-embie** [reply]
I get 
```bash
[Error: ENOENT: no such file or directory, open './storage.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './storage.json'
}

```

with 
```yaml
config:
  target: "http://localhost:3000"
  engines:
    playwright:
      contextOptions: { storageState: "./storage.json" }
      defaultNavigationTimeout: 0,
      launchOptions:
        headless: false
      aggregateByName: true,
  processor: "./load.ts"
  phases:
    - duration: 1
      arrivalCount: 10
includeFiles: "./storage.json"
before:
  engine: playwright
  flowFunction: createActivity

scenarios:
  - engine: playwright
    flowFunction: main

```

and 

```ts
import * as fs from "node:fs";

import { Page } from "@playwright/test";

import { ParentController } from "../e2e/controllers/parent.controller";
import { DatabaseTestManager } from "../utils/database-manager";

export async function createActivity() {
  console.log("Creating activity");
  const storageState = JSON.parse(fs.readFileSync("./storage.json", "utf8"));

  const databaseTestManager = new DatabaseTestManager();
  const activityID = await databaseTestManager.createActivity({
    registrationFee: 10,
    childrenCapacity: 10
  });
  storageState.activityID = activityID;
  fs.writeFileSync("./storage.json", JSON.stringify(storageState));
}
export async function main(page: Page) {
  console.log("Main");
  const storageState = JSON.parse(fs.readFileSync("./storage.json", "utf8"));
  const parentController = new ParentController(page);
  const { email, password } = await parentController.createAccount();
  const parent = await parentController.login(email, password);
  const childID = await parent.addChild();

  await parent.payChildMembershipFee({ childID });

  const activityID = storageState.activityID;
  await parent.registerChildToActivity({ childID, activityID, paid: true });
}

```

Any idea what's happening ?

**Reply by bernardobridge** [reply]
@alexandre-embie, to use this with Artillery, an empty object in the specified `storage.json` file needs to exist before running the test (`{}`), as mentioned here: https://github.com/artilleryio/artillery/tree/main/examples/browser-playwright-reuse-authentication#example

That should be the issue. 🤞 

---

P.S. I also noticed `includeFiles` is on the root, rather than under `config` in your example. If you're doing this using Fargate, you'll need to set that correctly `config.includeFiles`).

**Reply by alexandre-embie** [reply]
<img width="1031" alt="image" src="https://github.com/artilleryio/artillery/assets/144031843/bcea5431-66d6-4506-8a18-35b93ee7b595">
@bernardobridge I have the file in my load dir as can be seen here 🤔

**Reply by bernardobridge** [reply]
@alexandre-embie looks like it might be a bug on our side, I can reproduce it. We will tackle this soon . Thanks! 🙇

**Reply by priyankshivhare-mb** [reply]
Do you happen to have any updates on this? I'm facing similar issues when I run Artillery inside ADO pipeline, it works locally.
![image](https://github.com/artilleryio/artillery/assets/61963877/96ae2652-3d47-4509-a34b-027e9af9807d)

**Reply by bernardobridge** [reply]
Hi @priyankshivhare-mb , yes, planning on providing a workaround with updated example for the next release (should be May 13th - we release every 2 weeks).

**Comment by bernardobridge** [comment]
Hello @priyankshivhare-mb , @alexandre-embie  and others 👋 . This should now be fixed in [Artillery v2.0.12](https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.12).

The example has been updated with the needed changes: https://github.com/artilleryio/artillery/tree/main/examples/browser-playwright-reuse-authentication

**Reply by HugoImaios** [reply]
Helllo @bernardobridge  :wave: 
By any chance, is there another example (somewhere hidden or in draft?) with reusing authentication **per VU** instead of one auth for all of them ?
I'm currently putting it together but it's not that simple :smile:

**Reply by bernardobridge** [reply]
Hey @HugoImaios 👋  What would it mean to reuse authentication per VU though? Wouldn't a single VU already be logging into the app itself each time the VU executes?

**Reply by HugoImaios** [reply]
yes you right I failed to explain. I confused VU and the users I have in my CSV file.
My use case would be to be able to run a login load test which only login (and maybe a few expects) but stores the storage state per user.
Then in other tests, with the same users, I could reuse the storage state to load test only the features needed, with no need for login each user again

**Reply by HugoImaios** [reply]
I made some abstraction in my playwright fixtures which already have a similar usage (except they are based on the parallelIndex provided by test info), and it works :)

**Reply by HugoImaios** [reply]
but my dream is still having fields from csv as variables available in the `config`, allowing for something like :
```yaml

config:
    target: 'https://www.domain.com'
    engines:
        playwright:
            contextOptions:
                storageState: "{{ $dirname }}/storageState/{{ username }}.json"
    payload:
        -   path: 'users.csv'
            fields:
                - "username"
                - "password"
            order: sequence
```
:heart_eyes: 

(currently username is undefined, breaking this poc and forcing me to create a new context/page with the user-dependant storagePath at runtime)

**Reply by shiva-taramani** [reply]
Yes, to this ☝️ . Single storage state works great. I am trying to run the same scenario with a different login for each vuser.

**Reply by shiva-taramani** [reply]
@bernardobridge @hassy Any thoughts on this?

I have this working where a list of users are used for the same scenario. I also try and reuse storageState, if already logged in before.

This works for the most part except I don't get the web vitals, as I need to create a new context (to reuse storageState in Playwright) and that doesn't have the init scripts like the following (I am trying to avoid copying and pasting code from the Artillery Playwright node_modules):

```
await context.addInitScript(() => {
          ['onLCP', 'onFCP', 'onCLS', 'onTTFB', 'onFID', 'onINP'].forEach(
          ....
```

**Reply by HugoImaios** [reply]
> @bernardobridge @hassy Any thoughts on this?
> 
> I have this working where a list of users are used for the same scenario. I also try and reuse storageState, if already logged in before.
> 
> This works for the most part except I don't get the web vitals, as I need to create a new context (to reuse storageState in Playwright) and that doesn't have the init scripts like the following (I am trying to avoid copying and pasting code from the Artillery Playwright node_modules):
> 
> ```
> await context.addInitScript(() => {
>           ['onLCP', 'onFCP', 'onCLS', 'onTTFB', 'onFID', 'onINP'].forEach(
>           ....
> ```

I ran into the same issue, I once tried to create a new context (mandatory to add storageState) and indeed I lost web core vitals (and status codes, and other metrics). I personnaly rolledback this to keep the artillery's context, and the metrics

**Reply by bernardobridge** [reply]
Hey @sthavamani-ut and @HugoImaios 👋 

So just to make sure I fully understand what you're trying to do.
- You have username/password in a CSV, you want to login from that CSV where the first time it logs in, it will save the storageState file with the username dynamically. Any further logins of that user would result in reusing the storageState

Is this correct?

**Reply by austin-patterson** [reply]
> Hey @sthavamani-ut and @HugoImaios 👋
> 
> So just to make sure I fully understand what you're trying to do.
> 
> * You have username/password in a CSV, you want to login from that CSV where the first time it logs in, it will save the storageState file with the username dynamically. Any further logins of that user would result in reusing the storageState
> 
> Is this correct?

If we can dare to dream, I think this sounds like an amazing enhancement!!! I can't speak for @sthavamani-ut or @HugoImaios, but I believe you have interpreted correctly.

**Reply by HugoImaios** [reply]
yep that's correct ! Sorry I only "reacted" back then and haven't replied since.
The main goal was to run a load test on the login/auth scenario, then reuse the dozens of storage state with cookies to run some other scenario, skipping the login step

**Reply by MariaStadnik** [reply]
@bernardobridge I have a question 'm using Artillery for browser load testing and am struggling with how to configure dynamic contexts for each test scenario. Specifically, I need to set extraHTTPHeader for my browser dynamically without hardcoding token values. I want each scenario to create its own context that includes a unique authorization token, so each test can authenticate individually.

Currently, I can't find a way to pass a new token for every scenario without embedding the token directly in the configuration. Is there a method in Artillery to dynamically generate or fetch tokens per scenario, or to set headers on a per-scenario basis before the browser context is created? I also don't want to store the hardcoded token value in my repository anywhere, so would like to utilize a mechanism of retrieving a token value dynamically via some js function.

Here is my Artillery yaml below:
```
  target: 'myTargetUrl'
  phases:
    - duration: 10
      arrivalCount: 2
      name: phase-for-ui-test
  engines:
    playwright: 
      extendedMetrics: true
      launchOptions:
        headless: false
      contextOptions:
        extraHTTPHeaders:
          Authorization: 'Bearer myTokenValue
  processor: 'processor.js'

scenarios:
  - engine: playwright
    testFunction: 'myTestFunction'
```
Thanks for any help
