### DISCUSSION TITLE
Lambda - Unzipped size must be smaller than 262144000 bytes

### DISCUSSION THREAD

**Discussion by LiamJBerridge** [artilleryio/artillery#2289] [Artillery]
Hey 👋 

I can see there is a closed bug for this but I'm still getting this issue in Artillery: 2.0.0-38. Is there a workaround for this issue? 

  resp.error = util.error(new Error(), error);
                          ^

InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes
    at Object.extractError (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/json.js:80:27)
    at Request.extractError (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
    at Request.callListeners (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'InvalidParameterValueException',
  '[Type]': 'See error.Type for details.',
  time: 2023-11-14T12:18:06.790Z,
  requestId: 'c99521f6-056c-4916-af1f-017987eb419a',
  statusCode: 400,
  retryable: false,
  retryDelay: 8.596363727204292
}

Cheers 🍻

**Comment by hassy** [comment]
Does your Artillery script have any external dependencies (on npm packages)? That could be one reason why you're running into the issue.

**Reply by LiamJBerridge** [reply]
Hey @hassy, 

this isn't an issue for us anymore, I did close off the discussion 😄

**Reply by hassy** [reply]
ah okay! :D how did you fix it? or did you decide not to use Lambda?

**Reply by LiamJBerridge** [reply]
We decided not to use lambda, we tried it as an experiment for an issue which I've just mentioned on another discussion 👍

**Comment by chronark** [comment]
I'm still running into this, it used to work a few months ago but now doesn't.

I don't think my script has any dependencies


```yaml
config:

  target: https://api.unkey.dev
  phases:
    - name: Warm up phase
      duration: 1m
      arrivalRate: 1
      rampTo: 5
    - name: Ramp up Load
      duration: 1m
      arrivalRate: 5
      rampTo: 10
    - name: Sustain phase
      duration: 3m
      arrivalRate: 10
      rampTo: 10
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    ensure: {}
    expect: {}

  ensure:
      thresholds:
        - http.response_time.p50: 100
        - http.response_time.p99: 150

scenarios:
  - flow:
      - post:
          url: "/v1/keys.verifyKey"
          json:
            key: "{{ $env.UNKEY_KEY }}"
          capture:
            - json: "$.valid"
              as: valid
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: valid
            - equals:
              - "true"
              - "{{ valid }}"

```
