### DISCUSSION TITLE
Can someone help me with how can i use Bearer Token using Artillery and can use the same in subsequent API requests ?

### DISCUSSION THREAD

**Discussion by shiv-vsics** [artilleryio/artillery#2290] [Artillery]
So basically i am having 2 APIs, 
1. API which is generating the Bearer Token
2. API which will use token in actual API endpoint.

In the attached sample script i have written the yaml file as per suggestions in Artillery document, but somehow thats not working, can someone check and suggest the required changes in the same ?
[sample script.txt](https://github.com/artilleryio/artillery/files/13349536/sample.script.txt)

```yml
config:
  target: 'https://test.api.test.com'
  phases:
    - duration: 5
      arrivalRate: 5
 
before:
  flow:
    - log: "Get auth token"
    - post:
        url: '/test/auth'
        json:
          username: "test@testing.com"
          password: "Test@123"
        capture:
          - json: $.access_token
            as: token
scenarios:
  - flow:
      - get:
          url: '/test/v1/testProduct'
          headers:
            appkey: 'thisisappkey'
            authorization: "Bearer {{ token }}"
after:
  flow:
    - log: "Invalidate token"
```

Sample response from Token API looks like below:
```json
{
    "token_type": "Bearer",
    "expires_in": 4800,
    "access_token": "rwudJtIjoiQVBJIiwiI6WyJfdsfsdfwefsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf",
    "scope": "openid profilesTest test api",
    "refresh_token": "rwudJtIjoiQVBJIiwiI6WyJfdsfsdfwefsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf",
    "id_token": "rwudJtIjoiQVBJIiwiI6WyJfdsfsdfwefsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf"
}
```

I want to use **ACCESS_TOKEN** value in the actual API Endpoint

**Comment by shiv-vsics** [comment]
@hassy

**Comment by bernardobridge** [comment]
Hi @shiv-vsics 👋, can you elaborate on "what's not working"? Are you getting an error?

Your script is correct, as far as I can see (by the way, for readability it's better to post your scripts using [Github Code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), rather than attaching files. I've updated your original post with it).

---

My suggestion: check if the token is correctly getting created in the variable by running a log action (after your `before`):

```yml
scenarios:
  - flow:
      - log: "token is {{ token }}"
```

That should output `token is rwudJtIjoiQVBJIiwiI6WyJfdsfsdfwefsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf`.

- If it doesn't, there is something wrong with the request you're making in the before hook. Maybe the `username` and `password` aren't being set correctly? Maybe the API doesn't expect a JSON there? You can try to use `DEBUG=http,http:request,http:response` to see what might be wrong.
- If it logs the correct response, then there's likely something wrong with your `get` request in the scenario instead. Maybe something wrong with the headers (for example, `Authorization` typically starts with upper case `A`)?

Hope that helps.

**Reply by shiv-vsics** [reply]
@bernardobridge Thank you for responding on the same.

I am getting error like :
**token is undefined
Error: Failed capture or match**

My API Token Response looks like below:

```
{
    "token_type": "Bearer",
    "expires_in": 4800,
    "access_token": "rwudJtIjoiQVBJIiwiI6WyJfdsfsdfwefsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf",
    "scope": "openid profilesTest test api",
    "refresh_token": "rwudJtIjoiQVBJIiwiI6WyJfdsfsdfwefsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf",
    "id_token": "rwudJtIjoiQVBJIiwiI6WyJfdsfsdfwefsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf"
}
```

![image](https://github.com/artilleryio/artillery/assets/66552369/9796ceb0-46f4-4155-833b-6f1155922103)


Looks like its not reading the Capture block properly, API URL and other details are correct only.

**Reply by shiv-vsics** [reply]
@bernardobridge 

Pasting the script here for reference:

```
config:
  target: 'https://test.api.test.com'
  phases:
    - duration: 5
      arrivalRate: 5
 
before:
  flow:
    - log: "Get auth token"
    - post:
        url: '/test/auth'
        json:
          username: "test@testing.com"
          password: "Test@123"
        capture:
          - json: $.access_token
            as: token
scenarios:
  - flow:
      - get:
          url: '/test/v1/testProduct'
          headers:
            appkey: 'thisisappkey'
            Authorization: "Bearer {{ token }}"
after:
  flow:
    - log: "Invalidate token"
```
