### DISCUSSION TITLE
Using playwright with plugin metrics-by-endpoint

### DISCUSSION THREAD

**Discussion by biosignature** [artilleryio/artillery#2294] [Artillery]
Hey,

I'm experimenting with Artillery and playwright (The goal is to have a single script, which can do both end to end testing whlie also being usable for performance testing). I'm wondering if it's possible to use the plugin metrics-by-endpoint in conjunction with playwright as the engine?

From what I can find, there's no mention of compatibility nor in-compatibility, but while I can get metrics-by-endpoint to work if I just build a simple test flow without playwright as the engine and base script, it doesn't seem to work together.

My yml file with playwright and attempted metrics-by-endpoint
```
config:
  target: http://app.awesome.int.endpoint.somewhere
  engines:
    playwright: {}
  processor: C:\my\super\secret\path\artillery-scenarios.js
  plugins:
    metrics-by-endpoint: {}
  phases:
    - duration: 10
      arrivalRate: 1
scenarios:
  - engine: playwright
    name: Doggo
    flow: []
    flowFunction: "commitLoop"
  - engine: playwright
    name: Kitty
    flow: []
    flowFunction: "simpleTest"
```

If it cannnot be done with plugin + playwright, is there a way for me to get a similar output as the "stripQueryString" param for metrics-by-endpoint?
My actual playwright script produces a number of objects on the page and does lookups and edits, and I would like the test to neatly aggrigate the metrics for each page together instead of displaying them seperately due to identifiers etc.
