### DISCUSSION TITLE
How to loop over a scenario list of variables using playwrigth engine

### DISCUSSION THREAD

**Discussion by servohatred** [artilleryio/artillery#2302] [Artillery]
I am trying to run the same scenario but with a different parameter multiple times. I am using the playwright engine.

this is my yaml content: 
```
 config:
  target: "www.test.com"
  engines:
    playwright:
      contextOptions:
        baseURL: "{{ $processEnvironment.BASE_URL }}"
  processor: "../../tests/test.js"
  variables:
    price:
      - "100"
      - "200"
scenarios:
  - name: 'insert price'
    engine: playwright
    flowFunction: "inserPrice"
    flow:
      - loop:
        over: price
```

and I am not able to loop over the variables. Still running once, is there anychance of running multiple scenarios using variables? 
I want to run this: 
scenario 1 with price 100
scenario 2 with price 200

thanks in advance!
