### DISCUSSION TITLE
How to send artillery + playwright metrics to influx+grafana

### DISCUSSION THREAD

**Discussion by Aroot42** [artilleryio/artillery#2303] [Artillery]
Hiya!
I have created script using artillery + playwright. It's working weel locally.
I have a question how I get translate test stats to influx+grafana. I run my script, open Grafana dashboard and cannot see anything.

**docker-compose.yml**
```
version: "3.4"
networks:
  pw:
  grafana:

services:
  playwright:
    build: .
    networks:
      - pw
    volumes:
      - ./scripts:/scripts
    depends_on:
      - influxdb

  influxdb:
    image:
      influxdb:1.8
      #    entrypoint: /bin/sh
      #    user: root
    networks:
      - pw
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=artilleryinfluxdb

  grafana:
    image:
      grafana/grafana:8.5.21
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

volumes:
  influxdb_data:
  grafana_data:
```
**grafana-dashboard.yaml**
```
apiVersion: 1
providers:
    - name: 'default'
      org_id: 1
      folder: ''
      type: 'file'
      options:
          path: /var/lib/grafana/dashboards
```
**grafana-datasource.yaml**
```
apiVersion: 1

datasources:
  - name: artilleryinfluxdb
    type: influxdb
    access: proxy
    database: artilleryinfluxdb
    url: http://influxdb:8086
    isDefault: true
```
