### DISCUSSION TITLE
I have a few questions about scenarios and csv payload

### DISCUSSION THREAD

**Discussion by bodycombathuang** [artilleryio/artillery#2330] [Artillery]
In my yaml file, I have defined 2 scenarios

```yml
scenarios:
  - name: "scenario1"
    flow:
      - post:
         url: "/automation"
         json:
           tag: "tag1"
  - name: "scenario2"
    flow:
      - post:
         url: "/automation"
         json:
           tag: "tag2"
```
and in my yml I have 2 virtual users
```yml
config:
  target: "http://localhost:3000"
  http:
    # Responses have to be sent within 10 seconds, or an `ETIMEDOUT` error gets raised.
    timeout: 10000
    maxSockets: 10000
  phases:
    - duration: 1
      arrivalRate: 2
      maxVusers: 11
```

1.I find each user only runs one scenario,  how can I make each virtual user run 2 scenarios?
2. In the report
[test-run-report.json](https://github.com/artilleryio/artillery/files/13490718/test-run-report.json)

in the json, you can see there are 4 virtual users, I have a requirement that response time for each virtual user should be displayed( but the json only displays min and max, median,not 4 response times)
how to achive that?

3. 
in yaml, I  use csv payload, the csv has 2 rows, and I have created 2 virtual users in yaml,, 
how can I make each virtual user reads different row, some times I find the 2 viertual users read same row
```yml
config:
  payload:
    # path is relative to the location of the test script
    path: "users.csv"
    fields:
      - "username"
      - "password"
scenarios:
  - flow:
      - post:
          url: "/auth"
          json:
            username: "{{ username }}"
            password: "{{ password }}"
```

**Comment by bodycombathuang** [comment]
@bernardobridge Could you help me with the questions, thanks

**Comment by bernardobridge** [comment]
Hello @bodycombathuang.

> 1. I find each user only runs one scenario,  how can I make each virtual user run 2 scenarios?

When multiple scenarios are specified, Artillery will run only one of them per virtual user, according to weight distribution. You can read more about it here: https://www.artillery.io/docs/reference/test-script#scenario-weights

If you want to run both requests, you are probably better off putting them inside the same scenario, like so:

```yml
scenarios:
  - name: "scenario1"
    flow:
      - post:
         url: "/automation"
         name: automation1
         json:
           tag: "tag1"
      - post:
         url: "/automation"
         name: automation2
         json:
           tag: "tag2"
```

Notice I put an additional `name` property there. You can then enable the `metrics-by-endpoint` [plugin](https://www.artillery.io/docs/reference/extensions/metrics-by-endpoint#plugin-configuration) with `useOnlyRequestNames`, and you will get independent metrics for each request in your JSON report.

```yml
config:
  plugins:
    metrics-by-endpoint:
       useOnlyRequestNames: true
```

---

> 2. in the json, you can see there are 4 virtual users, I have a requirement that response time for each virtual user should be displayed

This isn't directly possible. Artillery gives you an aggregation over time periods of the response time across all virtual users, not for every virtual user. 

You have a couple of options here:

Option 1: Use one of our tracing options with the `publish-metrics` plugin ([OpenTelemetry](https://www.artillery.io/docs/reference/extensions/publish-metrics#opentelemetry), [Honeycomb](https://www.artillery.io/docs/reference/extensions/publish-metrics#honeycomb) or [Lightstep])(https://www.artillery.io/docs/reference/extensions/publish-metrics#lightstep). This would allow you to see every single request and VU in the trace.

Option 2: (expensive - will take a lot of resources from the machine) Use `afterResponse` [hooks](https://www.artillery.io/docs/reference/engines/http#afterresponse-hooks) to record the responses from each request yourself, and then record them somewhere. This will be available under `res.timings.phases.firstByte`.

---

>3. how can I make each virtual user reads different row, some times I find the 2 virtual users read same row

As mentioned in our [docs](https://www.artillery.io/docs/reference/test-script#payload---loading-data-from-csv-files), this feature is currently not intended to provide determinism. If you need each virtual user or request to use unique values, you may need to use something like Redis in your test run.
