### DISCUSSION TITLE
Alternative to public subnets

### DISCUSSION THREAD

**Discussion by flashforge-labs** [artilleryio/artillery#2437] [Artillery]
Hey I was wondering if there is a work around to using public subnets? In my company they're restricted and not possible to implement. I've seen in the docs and from a response to a chat that public subnets are required, but there must be a way to use artillery without them? Any help would be great thanks.

**Comment by bernardobridge** [comment]
Hi @adavies48 👋,

You can create your own VPC with private subnets and have Artillery run in it by using the `--subnet-ids` flag (you can also configure security groups similarly). 

Here's the reference for the CLI flags:
https://www.artillery.io/docs/reference/cli/run-fargate#fargate-specific-flags

**Reply by flashforge-labs** [reply]
Great thank you, I will try that.

**Reply by bernardobridge** [reply]
Apologies @adavies48 , this information is actually incorrect. Please refer to the post below for the correct details:

https://github.com/artilleryio/artillery/discussions/2437#discussioncomment-8218900

**Comment by hassy** [comment]
You have to run in a public subnet to be able to pull Docker images from Artillery's public ECR repository.

The workaround is to:

* clone Artillery's worker image and host it in your own private ECR repo
* edit the IAM role that Artillery generates to allow pulls from your private ECR repo
* configure Artillery to use your own copy of the worker image by setting the `WORKER_IMAGE_URL` environment variable to the URL of the image in your private ECR repo

We'll support this natively in Artillery at some point but no ETA on that right now.

**Reply by flashforge-labs** [reply]
Perfect thank you, that sounds really promising. I'll give that a go.

**Reply by hassy** [reply]
Let us know if you run into any issues. You'll be doing something undocumented and outside of the current happy path. :)

**Reply by Mathdon** [reply]
Is this the worker image we need?

https://github.com/artilleryio/artillery/blob/main/packages/artillery/lib/platform/aws-ecs/worker/Dockerfile

**Reply by hassy** [reply]
Yep that's the Dockerfile. You can avoid having to rebuild it yourself and just pull from our public repo here: https://gallery.ecr.aws/d8a4z9o5/artillery-worker

Docker images are published automatically by CI and are tagged with the Git commit id. The image corresponding to v2.0.4 ([commit](https://github.com/artilleryio/artillery/commit/db60c0d4d0d929dc4deb2c20ccc26bc1412a409b)) is `public.ecr.aws/d8a4z9o5/artillery-worker:db60c0d4d0d929dc4deb2c20ccc26bc1412a409b`

**Reply by Mathdon** [reply]
Hi @hassy we may have got a work around by altering our security groups. But then had this error:

ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 5 time(s): RequestCanceled: request context canceled caused by: context deadline exceeded. Please check your task network configuration.

Have you seen that before? Any idea what would cause that?

**Reply by hassy** [reply]
Where are you seeing that error @Mathdon? This could be due to missing VPC Endpoint config for Fargate -> private ECR connectivity - https://repost.aws/knowledge-center/ecs-fargate-tasks-private-subnet

**Reply by Mathdon** [reply]
We saw it in the ecs when looking at the tasks. Will take a look, thanks :)

**Reply by Mathdon** [reply]
Good Morning @hassy hope you are well

We have followed your advice above and hosted the worker image in our private ECR.

When we run the tests now we het this error in cloudwatch

 ›   Warning: -p is not a artillery command.
      Did you mean run? [y/n]: 
      
 The command we run with was:
 
 artillery run-fargate --subnet-ids <subnet-id> --security-group-ids <sd-id> --region eu-west-2 profiles/fargate.yml
 
 We could not see where it was getting the -p command from?
 
 We saw that the entry point to the worker image was
 
 ENTRYPOINT ["/artillery/packages/artillery/bin/run"]
 
 So not sure what we need to change the run command to to get around this error?

**Reply by drdj85** [reply]
@Mathdon @hassy I had the same problem after doing this the exact same way with the -p and had to sideline this. Any way forward would be great if you can help?

**Reply by hassy** [reply]
@Mathdon @drdj85 How are you keeping your own copy of the image up to date? The entrypoint did indeed change recently (in https://github.com/artilleryio/artillery/commit/b9d895b3d740acb9ca0042b28ac97e4f51459930#diff-a33800f8944e9e0680e8427bdbe98ef51764c448e6681c5a68737ca2c304fc19L35). That change will be released in Artillery v2.0.12 which will also set the new entrypoint automatically. So you can either:

1. Upgrade to v2.0.12 when it's out on Monday May 13
2. Rebuild your private image using the Dockerfile from v2.0.11 (or earlier if you're on an earlier version of Artillery)

**Reply by drdj85** [reply]
@hassy manually pulling and pushing to private ecr. Thanks for the information, I’ll get the new image and give it another go when it’s released. Thanks for the help.

**Reply by Mathdon** [reply]
HI @hassy I have updated the image and updated to artillery 2.0.12 and have received a different error

runc create failed: unable to start container process: exec: "/artillery/loadgen-worker": stat /artillery/loadgen-worker: no such file or directory

Any ideas on this?

**Reply by Mathdon** [reply]
Hi @hassy  

Any idea of how we can resolve this?

**Reply by Mathdon** [reply]
Hi @hassy any help would be appreciated, feel like we are close to getting it working just stuck at the last hurdle

**Reply by hassy** [reply]
@Mathdon that's very odd, that file is definitely there (otherwise all Fargate tests would fail).

Can you double check that you updated the image that's hosted here: https://gallery.ecr.aws/d8a4z9o5/artillery-worker - that's the image used for distributed load tests. Rather than the image hosted on Dockerhub, which only wraps the Arillery CLI itself.

**Reply by hassy** [reply]
e.g. the image to clone into your private ECR repo for Artillery v2.0.14 would be `public.ecr.aws/d8a4z9o5/artillery-worker:2.0.14-x86_64`

**Reply by Mathdon** [reply]
Thank you @hassy I will check that :)

**Reply by hassy** [reply]
feel free to email me directly with any more information that might not be suitable to share publicly here - hveldstra@artillery.io

**Comment by bbeesley** [comment]
Gonna chime in here since I have this working now. First step was setting up a github action to sync the public ECR images over to our private ECR. Here's what my action looks like in case you wanna copy:

```yaml
name: Update the artillery-worker ecr image
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "The artillery worker docker image tag to import (dont include the architecture suffix)"
        required: true
        default: 2.0.21
env:
  IMAGE_SOURCE: 'public.ecr.aws/d8a4z9o5/artillery-worker'
  IMAGE_SINK: '<the aws account id where your private ecr repo lives>.dkr.ecr.eu-central-1.amazonaws.com/artillery-worker'
jobs:
  copy-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: install regctl
        uses: regclient/actions/regctl-installer@main
        with:
          release: 'latest'
      - name: aws auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <a role that can push to your ECR repo>
          aws-region: eu-central-1
      - name: ecr private login
        uses: aws-actions/amazon-ecr-login@v2
      - name: aws auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <a role that can read from public ECR - I think it just needs ecr-public:GetAuthorizationToken and sts:GetServiceBearerToken>
          aws-region: us-east-1
      - name: ecr public login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: copy amd64 image
        run: |
          regctl image copy ${{ env.IMAGE_SOURCE }}:${{ inputs.new_version }}-x86_64 ${{ env.IMAGE_SINK }}:${{ inputs.new_version }}-x86_64
      - name: copy arm64 image
        run: |
          regctl image copy ${{ env.IMAGE_SOURCE }}:${{ inputs.new_version }}-arm64 ${{ env.IMAGE_SINK }}:${{ inputs.new_version }}-arm64
```
obviously update the roles to work with your CI, but then you can just run the action with whatever tags you wanna copy across.

Next you need to make sure artillery has attempted to run in fargate already because you're gonna have to modify the execution role it creates. If you've already used artillery fargate in the aws account you're using, the role has been created, if not, just let it fail once.

The name of the role is artilleryio-ecs-worker-role, you need to attach policies to allow it to pull from your private ECR, I use AmazonS3ReadOnlyAccess and AmazonECSTaskExecutionRolePolicy. So now your role will be able to pull the private ECR image.

Now you can just run the command to kick off the test, but point it at the private subnets, something like this is what I use:

```shell
artillery run-fargate --region eu-central-1 --count 5 --cluster `aws ecs list-clusters --query "clusterArns[0]" --output text | grep -o '[^/]*$'`  \
    --subnet-ids "`aws ec2 describe-subnets --filters 'Name=tag:Tier,Values=Private' --query 'Subnets[*].SubnetId' --output text | tr '\t' ','`" \
    --security-group-ids "`aws ec2 describe-security-groups --filters 'Name=group-name,Values=default' --query 'SecurityGroups[*].GroupId' --output text`" my-private-test.yml --record --key ***
```

Then everything seems to work well. I guess the if I were to make a suggestion it would be that it'd be nice if there was an artillery cli flag I could pass to tell it to include private ECR permissions on the role so that manual step isn't required.
