### DISCUSSION TITLE
Config.yml coming up as undefined

### DISCUSSION THREAD

**Discussion by okHadi** [artilleryio/artillery#2447] [Artillery]
Greetings!
I've been working on my loadtest for some days and it had been working fine. Initially I kept testing it locally, but then on FARGATE.
Now, I'm once again trying to run it locally but for some reason it is not even finding the file.
I've tried:
- Two different windows machines
- Reinstalling artillery
- Even using WSL, but still the same
This my current file structure:
![image_2024-01-26_194851665](https://github.com/artilleryio/artillery/assets/64269712/bef62ce3-e334-4a6c-9d5d-094452c2184f)
When I try to run:
`artillery run config.yml`
I get this error:
`Error: ENOENT: no such file or directory, open 'C:\Users\____\Desktop\_____\undefined'
    Code: ENOENT`
    
   I can't figure out any reason for it not be working. I haven't changed anything, it is like I looked away and it just went to blow up.
   
   I have tried running the example script present in docs and that is running fine.
   
   This is my config.yml file:
  
  ```

  config:
  target: <dummyurl>
  phases:
  - duration: 500
    arrivalCount: 30
    maxVusers: 2
  includeFiles:
  - users1.csv
  payload:
  - path: "{{ $environment }}"
    fields:
    - "UserID"
    - "First Name"
    - "Last Name"
    order: sequence
  engines:
    playwright: {launchOptions: {headless: false}, defaultNavigationTimeout: 100000, extendedMetrics: true, useSeparateBrowserPerVU: true}

  processor: "./flows.js"
scenarios:
- engine: playwright
  testFunction: "loadTest"
  
```
