### DISCUSSION TITLE
How to implement a step-based increasing load using fargate

### DISCUSSION THREAD

**Discussion by En3Tho** [artilleryio/artillery#2452] [Artillery]
We're considering Artillery + Fargate + Playwright as a next step in our load testing story. One of the scenarios that we've really liked is a step based increasing load e.g. increment amount of workers by x every y minutes. Is there a way to get this kind of behavior out of the box in Artillery? It is very easy when running from 1 machine but not so when using multiple workers.

I guess we could:
1. Use large machines in Fargate (e.g. if browser takes 4 vcpu on average, then a machine with 40 vcpu could be allocated
2. I don't know if this is possible, but if a numeric Worker Id could be a known parameter to the test, then we could allocate many workers and write an in-code delay based workaround
3. Again, I don't know if this is possible but can test script file be customzed per worker? E.g. we could supply a script specifying immeadiate start to 10 workers, a script with a start delay to another 10 and an even greater delay to another e.t.c.
4. Script based solution: just run the whole test multiple times with a different amount of workers - the thing I don't like about this is that there is a huge delay before test can actually start. Around a minute or more.

Note that we generally have our own metrics and losing the ones that Artillery generates is not a huge problem.

If there is a straightforward way then please share. The way I understand it, Artillery basically duplicates a test to many workers in Fargate and it's not totally

**Comment by hassy** [comment]
Hi @En3Tho 👋 Just want to make sure I understand the main requirement. When you say "increment amount of workers by x every y minutes" do you mean:

1. Increase the number of new virtual users by X every Y minutes, or
2. Increase the number of total active virtual users by X every Y minutes?

Is there a reason this doesn't work:

```yaml
# Increase the total number of arrivals every minute:

- duration: 1m
  arrivalCount: 10
- duration: 1m
  arrivalCount: 20
```

or:

```yaml
# Increase the total number of total active VUs every minute
# We go from max active of 5 in the first minute, and 10 in second minute

- duration: 1m
  arrivalRate: 10
  maxVusers: 5
- duration: 1m
  arrivalRate: 10
  maxVusers: 10
```
