### DISCUSSION TITLE
Force stop test when the function throws an Error

### DISCUSSION THREAD

**Discussion by o-holyshevskyi** [artilleryio/artillery#2462] [Artillery]
Hi there,
I have the next .yml scenario:

```yml
config:
  target: https://localhost
  ensure:
    p95: 60000
    maxErrorRate: 1
  phases:
  - duration: 10
    arrivalRate: 1
  tls:
    rejectUnauthorized: false
  variables:
    defaultTheme: 'ArtilleryTest_Theme'
    facilitator-token: "some token"
  processor: "./artilleryScript.js"
before:
  flow:
    - log: "START senario_participant_session_connection"
    - log: "Get case data. Theme - {{defaultTheme}}"
    - get:
        ....
scenarios:
  - name: senario_session_connection
    beforeRequest: trapError
    flow:
    - log: "Connect to session by link - {{link}} and code - {{code}}"
    - log: "Open websocket connection for paricipant"
    - function: openParticipantSignalRClient
    - think: 5
    - function: closeSignalRParticipant
```

In this scenario, I use custom functions to open ws connection with SignalR and try to verify if this connection is opened correctly. So this is my function:

```js
function openParticipantSignalRClient(userContext, events, done) {
  try {
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
    const client = new SignalRClient("someUrl", userContext.vars.token);
    
    client.on("getSessionData", (sessionData) => {
      try {
        console.log("Received session data for userId:", sessionData.currentUserId);
        const actualSessionId = sessionData.session.id;
        const expectedSessionId = userContext.vars.sessionId;
        if (actualSessionId !== expectedSessionId) {
          throw new Error(`The ${actualSessionId} is not the same as expected: ${expectedSessionId}`);
        }
      } catch (error) {
        console.error(error);
        events._events.errors('ssss')
        //process.exit();
      } finally {
        done();
      }
    });
    
    userContext.vars.participantSignalrClient = client;
    client.connect().then(done);
    } catch (error) {
      console.error("CRASH: SignalR connection");
    }
}
```

I want to somehow force stop the test when the function is thrown by this state `actualSessionId !== expectedSessionId`

Does anyone have ideas? :)

**Comment by hassy** [comment]
hi @o-holyshevskyi 👋 calling the `done()` callback with an Error object stops that virtual user (and will be reported in `vusers.failed` metric)

**Reply by o-holyshevskyi** [reply]
Hi @hassy, unfortunatelly this did not help me :(

this is what I updated:

`done(new Error('Test stop'));`

```js
client.on("getSessionData", (sessionData) => {
      try {
        console.log("Received session data for userId:", sessionData.currentUserId);
        const actualSessionId = sessionData.session.id;
        const expectedSessionId = userContext.vars.sessionId;
        if (actualSessionId !== 'ss') {
          throw new Error(`The ${actualSessionId} is not the same as expected: ${expectedSessionId}`);
        }
      } catch (error) {
        console.error(error);
      } finally {
        done(new Error('Test stop'));
      }
    });
```

this returns me this result:

```
--------------------------------------
Metrics for period to: 13:21:40(+0200) (width: 1.677s)
--------------------------------------

http.codes.200: ................................................................ 1
http.downloaded_bytes: ......................................................... 1137
http.request_rate: ............................................................. 1/sec
http.requests: ................................................................. 1
http.response_time:
  min: ......................................................................... 1509
  max: ......................................................................... 1509
  mean: ........................................................................ 1509
  median: ...................................................................... 1495.5
  p95: ......................................................................... 1495.5
  p99: ......................................................................... 1495.5
http.responses: ................................................................ 1
vusers.created: ................................................................ 1
vusers.created_by_name.senario_participant_session_connection: ................. 1


--------------------------------------
Metrics for period to: 13:21:50(+0200) (width: 0s)
--------------------------------------

vusers.completed: .............................................................. 1
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 8219.1
  max: ......................................................................... 8219.1
  mean: ........................................................................ 8219.1
  median: ...................................................................... 8186.6
  p95: ......................................................................... 8186.6
  p99: ......................................................................... 8186.6
```

the `vusers.failed:` is 0
