### DISCUSSION TITLE
Arrival Rate and Duration don't work as expected when running playwright tests

### DISCUSSION THREAD

**Discussion by ATheCoder** [artilleryio/artillery#2483] [Artillery]
For example I have the following config yaml for artillery:

```
config:
  target: <Some Website>
  phases:
    - name: Login And Check Profile
      duration: 20
      arrivalCount: 10
  # Load the Playwright engine:
  engines:
    playwright:
      aggregateByName: true
  processor: "../playwright/loginAndCheckProfile.js"
  # Path to JavaScript file that defines Playwright test functions
  payload:
    # path is relative to the location of the test script
    path: "../data/users.csv"
    skipHeader: true
    fields:
      - "username"
      - "password"
scenarios:
  - engine: playwright
    testFunction: "visitMainPage"
    name: 'visitMainPage'

```

And then when I run the tests I get the following result:

```
All VUs finished. Total time: 21 seconds

--------------------------------
Summary report @ 10:49:41(+0000)
--------------------------------

browser.http_requests: ......................................................... 501
browser.page.FCP.visitMainPage:
  min: ......................................................................... 189.9
  max: ......................................................................... 305.1
  mean: ........................................................................ 225.6
  median: ...................................................................... 214.9
  p95: ......................................................................... 247.2
  p99: ......................................................................... 247.2
browser.page.TTFB.visitMainPage:
  min: ......................................................................... 65
  max: ......................................................................... 142.9
  mean: ........................................................................ 96.6
  median: ...................................................................... 85.6
  p95: ......................................................................... 127.8
  p99: ......................................................................... 127.8
browser.page.codes.200: ........................................................ 546
browser.page.codes.403: ........................................................ 10
vusers.completed: .............................................................. 10
vusers.created: ................................................................ 10
vusers.created_by_name.visitMainPage: .......................................... 10
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 1089.4
  max: ......................................................................... 1462.6
  mean: ........................................................................ 1225.7
  median: ...................................................................... 1200.1
  p95: ......................................................................... 1300.1
  p99: ......................................................................... 1300.1
  ```
  Which indicates only **10** virtual users. Even though I expect to see **200** virtual users.
