### DISCUSSION TITLE
Publish metrics to Azure Application Insights via Open Telemetry plugin

### DISCUSSION THREAD

**Discussion by vikramjb** [artilleryio/artillery#2550] [Artillery]
Hey 👋 

I was curious if anybody got Artillery to send metrics to Azure Application Insights via the open telemetry plugin. I have got the config right but I am getting an UnAuthorised exception

**YAML Config**

```
config:
  target: https://uat3-app.vendorpanel.com.au/
  plugins:
    publish-metrics:
      - type: "open-telemetry"
        serviceName: TestAppInsights
        metrics:
          endpoint: "<AzureAppInsightEndPoint>" 
          headers:
            access_token: "<AzureAppInsightEndPoint_AccessToken>"
            Authorization: "<AzureAppInsightEndPoint_AuthHeader>"
        traces:
          endpoint: "<AzureAppInsightEndPoint>" 
          headers:
            access_token: "<AzureAppInsightEndPoint_AccessToken>"
            Authorization: "<AzureAppInsightEndPoint_AuthHeader>"
```

**Error**

`{"stack":"OTLPExporterError: Unauthorized\n    at IncomingMessage.<anonymous> (C:\\Projects\\VPSuite\\Nimblex\\tests\\Nimblex.LoadTesting.Tests\\node_modules\\@opentelemetry\\otlp-exporter-base\\build\\src\\platform\\node\\util.js:103:39)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","message":"Unauthorized","name":"OTLPExporterError","data":"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>\r\n  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n","code":"401"}`

The reason why I have posted it here than an issue is because it's not really an issue with Artillery. I am curious if anybody has been able to get this funcitonality going and would be able to guide me towards the right path.

What I am not sure is

1. End point : I can't find any documention that tells me what is the correct end point. The connection string on Azure has two end points and I have tried with both with not much luck.
2. Auth Header: This is a another question, I can't find much documentation on what should the header be and from where I can get the API key.

Any help is appreciated 👍
