### DISCUSSION TITLE
Capture value from one function to vuContext and then read it on a afterhook

### DISCUSSION THREAD

**Discussion by vikramjb** [artilleryio/artillery#2561] [Artillery]
Hi @bernardobridge @InesNi @hassy  👋 

I have the following script

```js
const { expect } = require('@playwright/test');


module.exports = { 
  flowTest,
  logResults
};


async function  logResults(page, vuContext) {
  let finalCsv = vuContext.vars['finalCsv'];
  console.log(vuContext.vars);
  console.log('log results',finalCsv);
}

const measureStepForEachVirtualUser = async (transactionName, events, vuContext, userActions) => {
  let vuUserId = vuContext.vars.$uuid;
  const startedTime = Date.now();
  await userActions();
  const difference = Date.now() - startedTime;
  const csvRecord=`${vuUserId},${transactionName},${difference}`
  vuContext.vars['finalCsv'] = csvRecord;
}

async function flowTest(page, vuContext, events, test) {

  const { step } = test;

 //previous step code

  await measureStepForEachVirtualUser("some_step", events, vuContext, async () => {
    await page.getByRole('button', { name: 'Generate number' }).click();
    //check if number is generated before proceeding to the next step
    const generatedNumber = await page.inputValue('input#setupNumber');
    while (generatedNumber === '') {
      generatedNumber = await page.inputValue('input#setupNumber');
    }
  })
}
```

I am looking to get the value of csvRecord out to logResults through the vuContext but I am getting undefined. Is the right way to pass values between functions within a single test script file?

**Comment by bernardobridge** [comment]
👋 

Can you please share your YML file? I assume you're calling `logResults` somewhere there

**Reply by vikramjb** [reply]
@bernardobridge 👋 

Here's the YAML file

```
config:
  phases:
    - name: SingleLoadTest
      duration: 10
      arrivalCount: 1
  processor: "../tests/flowTest.js"
# before:
#   engine: playwright
#   flowFunction: "logResults"
after:
  engine: playwright
  flowFunction: "logResults"    
scenarios:
  - engine: playwright
    name: "Single-LOAD-"
    flowFunction: "flowTest"
    flow: []
```
