### DISCUSSION TITLE
Is it normal that when I put arrivalRate: 10, 10 chrome instance pop ?

### DISCUSSION THREAD

**Discussion by alexandre-embie** [artilleryio/artillery#2567] [Artillery]
I read in the documentation that artillery uses the power of the chrome context to prevent creating a new chrome instance but rather an "incognito" window that is less ram usage intensive. The thing is that with those parameters in my yaml, it still creates 10 window, which makes my computer ram very much:

```yaml
config:
  target: "http://localhost:3000"
  engines:
    playwright: {
      defaultNavigationTimeout: 0,
      launchOptions: {
        headless: false
      },
      aggregateByName: true
    }
  processor: "./main.ts"
  phases:
    - duration: 1
      arrivalRate: 10 EDIT: arrivalCount:10
scenarios:
  - engine: playwright
    testFunction: "main"

```

where main.ts is

```ts
import { Page } from "@playwright/test";

import { ParentController } from "../e2e/controllers/parent.controller";

export async function main(page: Page) {
  const parentController = new ParentController(page);
  const { email, password } = await parentController.createAccount();
  await parentController.login(email, password);
}

```

Basically I just need to test the concurrent account creation and login in of my platform. Hence why I put duration: 1 and arrivalRate: 10. In other words, I'd like the main function to execute in parallel, like if 10 users were using the app to create an account and login.

Is there some setting I can tweak ? My future steps are using AWS Fargate, to do the load test in the cloud.

Thanks for your help.
<img width="513" alt="image" src="https://github.com/artilleryio/artillery/assets/144031843/d8432cfc-4440-45ba-b745-69a83e398e8b">
