### DISCUSSION TITLE
Datadog Trace Resource Names Groupings

### DISCUSSION THREAD

**Discussion by joshuscurtis** [artilleryio/artillery#2592] [Artillery]
Currently, we are sending metrics and traces via the latest OTEL implementation with the ADOT image/task to Datadog.

When sending traces to Datadog, we are grouping by page name; this works for most pages. However, during our flow, there is a login redirect, which generates a randomised state string. This means a new tag is generated each time the scenario is running.

Within the Datadog docs, it looks like it is possible to quantization this, as per (https://docs.datadoghq.com/tracing/troubleshooting/quantization/).

Using a enviroment variable like so: 
`export DD_APM_REPLACE_TAGS = '[{"name": "span.name", "pattern": "get_id_[0-9]+", "repl": "get_id_x"}, {...}, …]'`

However, it is unclear how to do this using the ADOT image. Can you provide guidance on how to do this? 
In addition, would it be sensible to have this pramatisation/grouping of URLs within the artillery.io itself?

**Comment by hassy** [comment]
Should be possible to do directly in Artillery's integration I think @joshuscurtis. We'll take a look.  cc @InesNi

**Reply by joshuscurtis** [reply]
Brilliant, thanks! @hassy

**Comment by InesNi** [comment]
Hi @joshuscurtis 👋🏻 ,

We have released a new `replaceSpanNameRegex` [config setting](https://www.artillery.io/docs/reference/extensions/publish-metrics/datadog#configuration-options-2) in the [Artillery v2.0.9](https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.9). 
It matches  a regex pattern specified against all span names and replaces any match with the replacement string provided:

```yaml copy
  plugins:
    publish-metrics:
      - type: datadog
        apiKey: "{{ $env.DD_API_KEY }}"
        traces:
          serviceName: "my-service"
          replaceSpanNameRegex:
            - pattern: get_id_[0-9]+
              as: get_id_x

```

Hope this helps! Let us know if you have any other questions.
