### DISCUSSION TITLE
[Artillery, Playwright] How to have multiple test functions in one yml file?

### DISCUSSION THREAD

**Discussion by kxngHunter** [artilleryio/artillery#2599] [Artillery]
I have a login and logout test in different functions. Is it possible to have both tests in a yml file and based the name of the test in the run command? I am trying the scenario option but no luck. `artillery run --scenario-name login --dotenv .env` For example: 

```yaml
config:
  target: "{{ $env.BASE_URL }}"
  phases:
  - duration: 60
    arrivalCount: 2
    name: fixed_arrivals
  engines:
    playwright: 
      launchOptions:
        headless: false
      aggregateByName: true
  processor: "./tests/artillery/tests.ts"

scenarios:
  - engine: playwright
  - name: login
    flow:
      - flowFunction: "login"
  - name: logout
    flow:
      - flowFunction: "logout"
```

**Comment by bernardobridge** [comment]
Hi @kxngHunter  👋 

What you're doing should work, but you have errors in your yaml (you're using the YAML format for the HTTP engine mixed with playwright). Try this:

```yml
config:
  target: "{{ $env.BASE_URL }}"
  phases:
  - duration: 60
    arrivalCount: 2
    name: fixed_arrivals
  engines:
    playwright: 
      launchOptions:
        headless: false
      aggregateByName: true
  processor: "./tests/artillery/tests.ts"

scenarios:
  - engine: playwright
    name: login
    flowFunction: "login"
  - engine: playwright
    name: logout
    flowFunction: "logout"
```
