### DISCUSSION TITLE
How to add date dynamically to sending message

### DISCUSSION THREAD

**Discussion by pzur1** [artilleryio/artillery#2600] [Artillery]
Hi!
I have the socketio app which i am testing. I wrote simple test which looks like this:

```yaml
config:
  target: "http://localhost:3000/"
  phases:
    - duration: 10 
      arrivalRate: 1     
  environments:
    10:
      target: "http://localhost:3000/"
      phases:
        - duration: 10
          arrivalRate: 1
    100:
      target: "http://localhost:3000/"
      phases:
        - duration: 100
          arrivalRate: 1 
    500:
      target: "http://localhost:3000/"
      phases:
        - duration: 500
          arrivalRate: 1 
    1000:
      target: "http://localhost:3000/"
      phases:
        - duration: 1000
          arrivalRate: 1
          
scenarios:
  - name: "Emit an event"
    engine: socketio
    flow:
      - loop:
          - emit:
              channel: "chat
               message"
              data: "{{ data }}"    #here i want to have add date
          - think: 1
        count: "{{ count }}"
```

Test is called from powershell with command:

```
artillery run -e 10 --variables '{ \"data\": \"pgqrdbtymracjrkgzwtdvjaxzgvsvzcdilemxswwbewfbxq\", \"count\": 1 }' --output C:\my_path_to_test\load-test.yml
```

I want to add date dynamically (in the place where I add comment in my yaml file). I cannot pass it as an argument, because i need to have current time in each "request" i send.

What I tried?
I tried to add processor and function like this:
(changed part of yaml file)

```yml
config:
  target: "http://localhost:3000/"
  phases:
    - duration: 10 
      arrivalRate: 1
  processor: "./my-functions.js"  
```

and

```yaml
scenarios:
  - name: "Emit an event"
    engine: socketio
    flow:
      - loop:
          - emit:
              channel: "chat
               message"
              data: "{{ data }}"
          - function: "setupSomeData"      
          - think: 1
        count: "{{ count }}"
```

when my-functions.js looks like this:

```js
module.exports = {
   setupSomeData: function (userContext, events, done) {
    userContext.vars.data = userContext.vars.data + // DateTime.CurrentDateTimeInTicks; 
    console.log(userContext.vars.data);
}
}
```
Unfortunately it doesn't work. I don't see changed data on the server nor in console. Please help me or at least tell my if it is possible.
Regards

**Comment by bernardobridge** [comment]
Hi @pzur1 ! I changed your post to include [Github Code Blocks ](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to improve readability.

There's a couple of things wrong here:
- You need to call the `setupSomeData` function before the `emit` call that needs the data;
- Your processor needs to call `done()` at the end;
- You should set the data variable to what you need, not append to it (unless I misunderstood what you were trying to do).


So:

```yml
scenarios:
  - name: "Emit an event"
    engine: socketio
    flow:
      - loop:
          - function: "setupSomeData" 
          - emit:
              channel: "chat
               message"
              data: "{{ data }}"
          - think: 1
        count: "{{ count }}"
```

and

```js
module.exports = {
   setupSomeData: function (userContext, events, done) {
    userContext.vars.data = Date.now() //this will give you a timestamp. Modify with whatever date format you need; 
    console.log(userContext.vars.data);
    done()
}
}
```
