### DISCUSSION TITLE
Error rate and status code metrics not being published to splunk

### DISCUSSION THREAD

**Discussion by abhiUSB** [artilleryio/artillery#2630] [Artillery]
Hi,

I am working on to create dashboards in splunk from artillery published metrics.
It seem to have been publishing response time metrics to splunk but not the error rate or response code metrics.
I verified the output report json file, these metrics exist in the report but does not get emitted to splunk.
Do I need to do any specific configuration for the same ?

Thanks

**Comment by InesNi** [comment]
Hi @abhiUSB,

Thank you for getting in touch.

Could you provide a bit more information please:
- Artillery version you're using, 
- Node.js version
- Are you running tests locally or Fargate
- Could you provide the test script you are running

**Reply by abhiUSB** [reply]
Hi @InesNi 

Thanks for the prompt response.
Artillery version - 2.0.9
Node.js version - 20.11.1
Running tests through code build (not lambda or farget)
Here's the test script

```
config:
  target: <some valid url>
  phases:
    - duration: 10
      arrivalRate: 5
      name: Warm up phase
  environments: 
    local:
      target: <some valid url>
    dev:
      target: <some valid url>
    stage:
      target: <some valid url>
  plugins:
    metrics-by-endpoint: {}
    publish-metrics:
    - type: splunk
      realm: <some valid realm>
      accessToken: <some valid token>
      prefix: "artillery."
      dimensions:
        - "env:dev"
scenarios: # Actual scenarios for test cases
  - flow:
      - post:
          url: <some valid url>
          json: # Request payload
            loginName: <some valid login id>
            password: <some valid password>
```
