### DISCUSSION TITLE
HLS plugin error: "streamSelector is not a function"

### DISCUSSION THREAD

**Discussion by geldrin** [artilleryio/artillery#2631] [Artillery]
I wanted to try the HLS plugin for Artillery, but I get an error in `artillery-plugin-hls/index.js` when I execute the test plan.

It looks like the `streamSelector` option causes the issue, but I'm not sure if it's a bug, or a configuration error by my side.
The error message states that there's no `streamSelector` function defined:

```
glukacsy ~$ artillery run hlsloadtest/mytest.yml
(node:301964) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Test run id: t4f5a_85c6xwzde84kc5qmmrfthhf46q5qh_8zq8
[...]
Phase started: phase1: ramp-up (index: 0, duration: 30s) 18:27:03(+0200)

⠇ worker error, id: 1 TypeError [Error]: streamSelector is not a function
    at /home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery-plugin-hls/index.js:209:25
    at walkPlaylist (/home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery-plugin-hls/walk-manifest.js:156:15)
    at stream (/home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery-plugin-hls/index.js:202:23)
    at HlsPlugin.script.config.processor.hlsPluginStream (/home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery-plugin-hls/index.js:248:7)
    at iteratee (/home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/engine_http.js:626:21)
    at /home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery/node_modules/async/dist/async.js:3113:16
    at replenish (/home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery/node_modules/async/dist/async.js:1014:17)
    at /home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery/node_modules/async/dist/async.js:1019:9
    at eachLimit$1 (/home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery/node_modules/async/dist/async.js:3199:24)
    at Object.<anonymous> (/home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery/node_modules/async/dist/async.js:1049:16)
glukacsy@vsqdev-livetrans1 ~$ nano /home/glukacsy/.nvm/versions/node/v21.7.2/lib/node_modules/artillery-plugin-hls/index.js
```

This is the test I'm trying to execute (streamIDs and domains were changed):

```yaml
config:
  target: "https://my.doma.in"
  phases:
    - duration: 30
      arrivalRate: 3
      rampTo: 30
      name: "phase1: ramp-up"
    - duration: 180
      arrivalRate: 0
      rampTo: 30
      name: "phase2: hold-server-load"
    - duration: 30
      arrivalRate: 3
      rampTo: 0
      name: "phase3: ramp-down"
  plugins:
    hls: {}
  engines:
    http: {}

scenarios:
  - name: myFirstHLStest
    #engine: http
    flow:
      - get:
          url: "/live/smil:mystreamid.smil/playlist.m3u8"
          hls:
            concurrency: 4
            throttle: 2000
            streamSelector:
              bandwidth:
                min: 1200
                max: 2000
```

**Environtment:**
**OS:** `Ubuntu 22.04.4 LTS`
**Artillery:** `2.0.9`
**Node.js:**   `v21.7.2`

Has anyone run into this issue before?
