### DISCUSSION TITLE
Getting triggerUncaughtException while running my performance script on EC2 machine

### DISCUSSION THREAD

**Discussion by shiv-vsics** [artilleryio/artillery#2675] [Artillery]
Hi Team/ @bernardobridge,

I am trying running Artillery performance script on AWS EC2 instance but i am getting an Exception like **triggerUncaughtException**. Error image is attached. Can someone help me with it , why i am getting this exception??

**Artillery Version:** 2.0.10
**Node Version:** v18.17.1
**NPM Version:** 10.6.0

![image](https://github.com/artilleryio/artillery/assets/66552369/6281a6bf-1e4f-4a99-9a15-f5169dfebfc2)

Just to let you know that the same script is working fine on my local windows machine.

**Comment by hassy** [comment]
do you have a custom JS function running as part of the test? the error is from a request timeout (possibly to an auth endpoint?) but it doesn't look like it's coming from Artillery's own HTTP engine

**Reply by shiv-vsics** [reply]
@hassy Thank you for replying.

No, there is no custom JS function used in YAML script. I am using an Auth API to generate the token and then using the same token in actual API request. As i mentioned its working fine on my local but having problem with EC2 instance. Please let me know if you require any additional details.

**Reply by shiv-vsics** [reply]
Below is how my sample script looking like. @hassy

**Reply by shiv-vsics** [reply]
```
config:
  payload:
    path: "filterfile.csv"
    fields:
      - "filter"
    loadAll: true
    name: symb

  target: "https://qa.test.com"
  phases:
    - duration: 300
      arrivalRate: 15
 
before:
  flow:
    - log: "Get auth token"
    - post:
        url: "/test/auth"
        headers:
            appkey: 'testappkey'
            Content-Type: 'application/x-www-form-urlencoded'
        form:
          username: "test@test.com"
          password: "test@123"
        capture:
          - json: $.access_token
            as: token         

scenarios:
  - name: "Performance Testing For test API"  
    flow:
      - loop:
        - get:
            url: '/testing/v1/test'
            headers:
              appkey: 'testappkey'
              Authorization: "Bearer {{ token }}"
            qs:
              filter: 'issuedBy in ("{{ $loopElement.filter }}")'
        over: symb         
after:
  flow:
    - log: "Invalidate token"
    - log: "token is {{ token }}"

```
