### DISCUSSION TITLE
Use of tags in traces/events/spans and replaceSpanNameRegex not working

### DISCUSSION THREAD

**Discussion by AT2406** [artilleryio/artillery#2676] [Artillery]
As part of my load test running in fargate ive tried to use use the replcespannames but it does not seem to be working. This is a snippet of how i have set it up in the yml config, is there anything I am missing or have misaligned that is preventing it from working as intended. 

I have also attempted to use the tags inside of the traces, events and as part of the publish metrics object as shown below but no matter where i have tried to set them i am unable to get them to be used as variables in datadog, could i get some guidance on what to do so that the tags work properly?

```yml
  plugins:
    publish-metrics:
      - type: datadog
        apiKey: "{{ $env.DD_API_KEY }}"
        traces:
          serviceName: "WALT-TEST"
          replaceSpanNameRegex:
            - pattern: https://qa.eu.auth0.com/login_state_[a-zA-Z0-9_.?=&%-:]+
              as: page_nexus_auth0_login_page_redirect
            - pattern: https://qa.io/_redirect_[a-zA-Z0-9_.?=&%-:]+
              as: page_nexus_auth0_login_success_redirect
          useRequestNames: true
          tags:
            - "testType:smoke-test"
            - "tool:Artillery"
            - "env:performance"
            - "service:WALT-TEST"
        tags:
          - "testType:smoke-test"
          - "tool:Artillery"
          - "env:performance"
          - "service:WALT-TEST"
        event:
          title: "Smoke Test - Started"
          priority: normal
          tags:
            - "testId:smoke-test"
```

**Comment by InesNi** [comment]
Hi @AT2406 👋🏻 ,

Thank you for getting in touch, I will look into this but need a bit more information. Could you give me the Artillery and Node.js version you are using and the rest of your yml test script if possible?

**Reply by AT2406** [reply]
Hi @InesNi , im using artillery 2.0.10 and tried both node 18 and 20 but have been working mainly with 20 

this is my yml file
```yml
config:
  target: "{{ $env.WALT_URL }}"
  phases:
    - duration: 10m
      arrivalRate: 1
      maxVusers: 5
      name: step_1
    - duration: 10m
      arrivalRate: 1
      maxVusers: 10
      name: step_2
    - duration: 10m
      arrivalRate: 1
      maxVusers: 15
      name: step_3
    - duration: 10m
      arrivalRate: 1
      maxVusers: 20
      name: step_4
    - duration: 10m
      arrivalRate: 1
      maxVusers: 25
      name: step_5
  payload:
  - path: "../../data/users.csv"
    fields:
    - "email"
    - "password"
  includeFiles: 
    - "../accept-cookies.json"
  engines:
    playwright:
      contextOptions:
        storageState: "config/accept-cookies.json"
      extendedMetrics: true
      defaultNavigationTimeout: 60
      launchOptions:
        headless: true
  plugins:
    publish-metrics:
      - type: datadog
        apiKey: "{{ $env.DD_API_KEY }}"
        traces:
          serviceName: "WALT-TEST"
          replaceSpanNameRegex:
            - pattern: https://qa.eu.auth0.com/login_state_[a-zA-Z0-9_.?=&%-:]+
              as: page_nexus_auth0_login_page_redirect
            - pattern: https://qa.io/_redirect_[a-zA-Z0-9_.?=&%-:]+
              as: page_nexus_auth0_login_success_redirect
          useRequestNames: true
          tags:
            - "testType:step-load-test"
            - "tool:Artillery"
            - "env:performance"
            - "service:WALT-TEST"
        event:
          title: "Step Load Test - Started"
          priority: normal
          tags:
            - "testId:step-load-test"
        includeOnly:
          [
            "browser.step",
            "vusers",
            "browser.memory_used_mb",
            "info.reportdownloaded",
          ]
  processor: ../../index.js
scenarios:
  - engine: playwright
    name: "Load Test"
    testFunction: "generateReport"
    weight: 100
```

**Comment by InesNi** [comment]
Hi @AT2406,

I haven't been able to replicate neither of the issues you are encountering. I've used the script you provided above to run my own `testFunction` with Fargate sending traces to Datadog.

1. `replaceSpanNameRegex`
The configuration you provided above should work without a problem.
- Can you tell me what exactly happens? Do the span names change at all?
- Are you sure your regex is correct?
- Does the `testFunction` change the page URL somehow? 
- Are the traces arriving correctly to Datadog?

2. Tags
I get the tags correctly on the spans and events as well, with your exact configuration.
- Do any of the spans have the tags or none?
- How are you accessing/looking for the tags on Datadog? For instance
   -  to see span tags, you go to `APM` -> `Traces` -> click on span and see them under `info`
   - to search spans that have `testType` set to `step-load-test` you go to `APM` -> `Traces` and then in the search you enter `@testType:step-load-test`

**Reply by AT2406** [reply]
Hi, the names of the spans do not change, the journey function does not alter the url being navigated to, and yes the traces are visible and correct in datadog. Do the slash characters '/'  need to have a backslash '\' in the regex pattern for it to function correctly? If so then that may be what is causing the issue for me.

Ive tested out the patterns below on https://regexr.com/ and it seems to pick up this example url fine but when used in the artillery config is does not seem to pick up the different page urls in the test. Does renaming the spans with the regex not rename the pages that would be coming through to datadog?

```
https://qa.io/_redirect_qtg-tscscscsdcsaso0q3umoqewsnwsggpf0v1bw1mgteawoxetftkc5dkc_state_fnnflwdumzjtnnbzwullrdnixridethaeprntnebk
```

```yml
          replaceSpanNameRegex:
            - pattern: https:\/\/[a-zA-Z0-9_.?=&%-:]+\/login_state_[a-zA-Z0-9_.?=&%-:]+
              as: page_nexus_auth0_login_page_redirect
            - pattern: https:\/\/[a-zA-Z0-9_.?=&%-:]+\/_redirect_[a-zA-Z0-9_.?=&%-:]+
              as: page_nexus_auth0_login_success_redirect
```

As for the tags, they are visible in the spans in APM. I might have misunderstood their use as I was trying to use them as templated variables at the top of my datadog dashboard so that it is easier to filter out different tests being run at the same time but I have only been able to achieve this with the serviceName being set to something
