### DISCUSSION TITLE
Artillery Parallel Execution

### DISCUSSION THREAD

**Discussion by nithinkadam19** [artilleryio/artillery#2686] [Artillery]
Hi Team,

I would like to execute yamls parallelly. like i have 2 yamls first.yml and second.yml.

can you provide me a batch script on how to execute both the yamls parallelly.

i tried "@echo off
set "folderPath=%1"

if not defined folderPath (
  echo Please provide the folder path as a command-line argument.
  exit /b 1
)

for %%F in ("%folderPath%\*.yml") do (
 REM artillery run -o "%folderPath%\%%~nxF".json --config commonconfig.yml "%folderPath%\%%~nxF"
 artillery run --config commonconfig.yml "%folderPath%\%%~nxF" artillery run --config commonconfig.yml "%folderPath%\%%~nxF"
)"

But it is picking scripts one by one mean sequentially. i need to execute yamls parallely.

**Comment by hassy** [comment]
Can you use the `start` command as described here? https://stackoverflow.com/a/6306673/6787983

**Reply by priya-dsp** [reply]
hi @hassy , we have tried using start command in batch file. With this, multiple CLI/terminal will be processed and yamls are executed parallelly however, this approach is not feasible when we need to run larger scripts(when we have 1000+ files the given approach is not much feasible). Is there any other solution where scripts run parallelly in background without opening multiple CLI?

**Comment by Brijendra9322** [comment]
Hello @hassy ,

I would like to handle the browser launch options and parellel execution both from yml file. how to do that?
below is my yml file but launchOptions and parellel is not working . i want to run with multiple user id with diffrent browser sessions.
I see that Playwright.config.ts is not working in case of artillery. kindly help here.

config:
  target: "https://www.google.com/"
  playwright:
    launchOptions:
      headless: false
  phases:
    - duration: 1
      arrivalRate: 1
      name: "Phase 1"
  processor: "./tests/test/xyz.ts"
  engines:
    playwright: {}
  output:
    json: "report/artillery_report_{{__timestamp | dateFormat 'YYYY-MM-DD'}}.json"
scenarios:
  - engine: playwright
    testFunction: "annotateTest"
parallel: 2

**Reply by Brijendra9322** [reply]
@hassy could you please respond on my query? please ignore the indentation in yml file . just let me know how we can run multiple testFunction parallel. for typescript.

**Reply by bernardobridge** [reply]
Hey @Brijendra9322 👋 . I'm not sure where you're getting the `parallel: 2` from. There is currently no built-in way in Artillery to run multiple scenarios in parallel (whether in Playwright Engine or HTTP engine). 

What _is possible_ is to declare multiple scenarios with different weights (https://www.artillery.io/docs/reference/test-script#scenario-weights). Then, each VU will randomly execute one of the scenarios based on the probabilities set by the weights.

If that doesn't work for you, and you really want to run multiple scenarios in parallel, you'll need to create your own script that launches multiple artillery test runs in parallel.

**Reply by Brijendra9322** [reply]
Thanks for your reply. But i am doing ui performance using typescript.

I have tried multiple scenarios but only one scenario executes.

Scenario:
  - name: name of test
     engine: playwright
     testFunction: "test1"
   - name: name of test
     engine: playwright
     testFunction: "test2"

It randomly pick and run..one function has multiple sub function. How we can distribute the weight in sub functions.

**Reply by bernardobridge** [reply]
@Brijendra9322 as explained, it will execute one scenario per VU, but it will choose which one randomly. Here's an example:

```yml
scenarios:
  # Approximately 60% of all VUs will run this scenario.
  - name: test1
    weight: 6
    engine: playwright
    testFunction: test1
 
  # Approximately 30% of all VUs will run this scenario.
  - name: test2
    weight: 3
    engine: playwright
    testFunction: test2
 
  # Approximately 10% of all VUs will run this scenario.
  - name: test3
    weight: 1
    engine: playwright
    testFunction: test3
```
