### DISCUSSION TITLE
How to call multiple Playwright functions in YAML file under same scenario

### DISCUSSION THREAD

**Discussion by anildel8s** [artilleryio/artillery#2719] [Artillery]
Hi,
I tried this on http engine and it worked
```
scenarios:
 - name: "Account Settings API Call"
   weight: 3
   flow:
      - function: "getAgent"
      - think: 5
      - function: "getToken"
      - think: 5
      - get:
          url: "/account"
``` 
but when I try the same on playwright engine, its not working
```
scenarios:
 - engine: playwright
    name: "Login App"
    - flowFunction: "loginApp"
    - flowFunction: "validateAccountDetails"
    - flowFunction: "logoutApp"
    flow: []
``` 
I saw some suggestions where its advised to use separate flowFunctions on separate scenarios which doesn't work for me as loginApp should be followed by checking account details and then logout.

I have started to combine these functions into a single function using test.step but I am getting an error as below:
TypeError: step is not a function
So I am blocked on that route as well.  Really appreciate any help as to how to approach this scenario.

**Comment by bernardobridge** [comment]
Hello @anildel8s ,

There's a few things wrong here:

### Wrong YAML indentation

It should look something like this:

```yaml
scenarios:
  - engine: playwright
    name: "Login App"
    flowFunction: "loginApp"
```

### Can't use multiple `flowFunction` in Playwright scenarios

What you described is only valid in HTTP scenarios. The Playwright engine will run a single function that should contain your entire test.

### TypeError: step is not a function

This is likely a syntax problem in your Typescript/Javascript code, but using steps is exactly what I would recommend for what I understood of your use case. 

Can you please share the contents of your JS/TS file so I can help spot what's wrong?

**Reply by anildel8s** [reply]
Hi, Thanks for the quick response and confirming playwright engine only takes a single function.

For Issue 3 TypeError: step is not a function - I was able to resolve it by importing the 'test' from @playwright/test

Now I am getting an error when i try to change a variable in the session storage using page.evaluate()

Typescript file - myUITest.ts
```typescript
import { page } from 'playwright';
import { expect, test } from '@playwright/test';
import { ChildProcess } from 'child_process';

let mockoonChildProcess: ChildProcess;

export async function launchWebApp(page: Page, vuContext, events, test) {
  events.emit('counter','my-login-page-hits',1);
  const {step} = test;

  await step('start-mockoon-server', async() =>{
     await startMockoonServer();
  });

  await step('login-page', async() => {
     await page.goto("http://xyz:8088/my-login");
     await page.waitForURL(/.*my-login/,{timeout: 50000});
     await expect(page.locator("log out").toBeVisible();
  });

 await step('Set up storage session to launch UI', async() => {
     await setUserIdOnSessionStorage("Car");
  });

 await step('Click on the Car link', async() => {
    await page.click('id=vehicle-id');
    expect(page.url()).toContain("CarVal");
  });

 await page.close();
}

export async function startMockoonServer() {
   if(!mockoonChildProcess) {
     mockoonChildProcess = await setUpMockEnvironment(`mockoon-cli --data ${mockDataFilePath}` + 'bff.json');
    }
}
export async function setUserIdOnSessionStorage(value: string)
 {
   await page.evaluate((userId) => {
       window.sessionStorage.clear();
       window.sessionStorage.setItem('userid', userId);
      }, value);
 }
``` 

Yaml file:
```
config:
  target: "http://xyz.com"
  engines:
     playwright:
     aggregateByName: true
     launchOptions:
        headless: false
     defaultNavigationTimeout: 500
  processor: "./myUITest.ts"
  phases:
    - duration: 5
      arrivalRate: 1
      name: Warm Up
scenarios:
   - engine: playwright
      name: "Click Car link on Homepage"
      testFunction: "launchWebApp"
      flow:
        - beforeScenario: 'startMockoonServer'
``` 

Just wanted to check if Artillery allows us to tweak the session storage while using Playwright as this is quite easy on a normal playwright script.

Error encountered as below:
await page.evaluate(userId) => { 
                  ^
TypeError:  Cannot read properties of undefined (reading 'evaluate')
at async Array.scenario(c:\users\User\AppData\Roaming\npm\node_modules\artillery-engine-playwright\index.js:340:11)
