### DISCUSSION TITLE
Question - running multiple load tests in GitHub Actions & running multiple browsers in CI without AWS FARGATE

### DISCUSSION THREAD

**Discussion by Romarionijim** [artilleryio/artillery#2739] [Artillery]
Hello.

I have two questions

1. I've been using Playwright along with Artillery.
In UI and API tests - I usually tag my tests and run them via grep ikn the CI e.g npx playwright test --grep @SANITY and etc, I usually use a list of greps utilizing strategy matrix.

I was wondering if I can un multiple load tests this way in Artillery - from the documentation your providing an example with only one test file, how can I be able to run multiple tests or tag the tests to run them all instead of specifying more than one workflow?
I was thinking about using a matrix strategy as well to run the files in separate jobs,  but I was wondering if there is a built in way?
how I use it for example (without the artillery action).

```

on:
  workflow_dispatch:

env:
  USER_NAME: ${{ secrets.USER_NAME }}
  PASSWORD: ${{ secrets.PASSWORD }}


jobs:
  load_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: run load tests
        env:
          BASE_URL: 'https://saucedemo.com'
        run: BASE_URL=${{ env.BASE_URL }} npx artillery run LoginFlowPerfTest.yml
        working-directory: tests/loadTests/artillery

```

2.  If I wanna run a high number of browsers or users, what is the limit if I choose to run them via github actions without using AWS FARGATE? in my company we use GCP and cannot use AWS, i was wondering what is the limit of vusers or browsers that I can spin up and run locally and in GitHub Actions.

Thank you!
