### DISCUSSION TITLE
Difficulty in getting Datadog traces to poulate with tags etc.

### DISCUSSION THREAD

**Discussion by zoe-jobson-IL** [artilleryio/artillery#2758] [Artillery]
I have this as part of one of my tests
```yaml copy
 publish-metrics:
      - type: datadog
        apiKey: "{{ $env.DATADOG_API_KEY }}"
        apiHost: "app.datadoghq.eu"
        prefix: "art.test."
        traces: 
          serviceName: "ARTILLERY"
          useRequestNames: true
          tags:
            - "testName:Workforce"
            - "testId:{{ $env.RUN_ID}}"
            - "service:ARTILLERY"
        event:
          title: "Workforce Load Test {{ $env.RUN_ID }} Start"
          priority: normal
          tags:
            - "testId:{{ $env.RUN_ID }}"
 ```

I was hoping to be able to filter by testId (current set as a property of the github object in the GHA)- as I am thinking about working towards a historically based performance chart in datadog, so I can average the mean for a given metric, for a given test run and plot it over time so we can see how things are changing, and even alert via datadog when there's a loss of performance. But, my datadog metrics only get sent to the datadog metrics view i.e.
![image](https://github.com/artilleryio/artillery/assets/72204483/9d38f374-8eef-4034-8489-c8f606e7120b)

and when I go to APM -> traces like suggested in the video there's no sign of them. my tags do not appear to be showing up anywhere, nor does my 'service'.

**Comment by InesNi** [comment]
Hi @zoe-jobson-IL  👋🏻 ,

Thank you for reaching out! 

Would you be able to provide a bit more information:
- Artillery and Node.js version you're using
- Are you running locally or on Fargate?
- Could you share the rest of your tests script?
- Could you run the tests with `DEBUG=plugin:publish-metrics:datadog-statsd` and let me know if there are any errors reported

**Reply by zoe-jobson-IL** [reply]
artillery 2.0.12, node 18.19.0 
Its a playwright script, but the scenario is like this
```

  target: "https:/" 
  phases:
phase
  - duration: 10
    arrivalRate: 1
    maxVusers: 5
    name: P1
  - duration: 10
    arrivalRate: 1
    maxVusers: 10
    name: P2
  - duration: 10
    arrivalRate: 1
    maxVusers: 250
    name: P50
  engines:
    playwright: 
      trace: true
      aggregateByName: true
      contextOptions:
        extraHTTPHeaders:
          x-iml-waf-access: ""   
      showAllPageMetrics: true 
      #we could extend these timeout if we wanted
      defaultNavigationTimeout : 120 # in seconds, 
      defaultTimeout: 120 # locator timeouts etc (not expectations)
      testIdAttribute: "data-qaid" # configures getByTestId
      launchOptions:
        headless: true # should always be merged in as true for *this* yml
  processor: "../../dist/tests/artillery/workforce-exercise.art.js"
  plugins:
    publish-metrics:
      - type: datadog
        apiKey: "{{ $env.DATADOG_API_KEY }}"
        apiHost: "app.datadoghq.eu"
        prefix: "art.test."
        traces: 
          serviceName: "ARTILLERY"
          useRequestNames: true
          tags:
            - "testName:Workforce"
            - "testId:{{ $env.RUN_ID}}"
            - "service:ARTILLERY"
        event:
          title: "Workforce Load Test {{ $env.RUN_ID }} Start"
          priority: normal
          tags:
            - "testId:{{ $env.RUN_ID }}"
before:
  flow:
    - function: "fetchUserIds"
scenarios:
  - engine: playwright
    testFunction: "scenario"
  

```
(note there are usually a load more stages in the phases section)

I did try running it with the debug snippet but it was rather overwhelming... here is a new run with it

**Reply by InesNi** [reply]
Hi @zoe-jobson-IL ,

Thank you for the info!

There seems to be a bug in debug logic itself expecting a different value for tracing that the one for metrics. 
Would you mind running the test with: 
- `DEBUG=plugin:publish-metrics:datadog` instead of the previous `DEBUG` 
- and with a `--solo` tag? `--solo` will run the test with a  single virtual user which will reduce the noise in the output

Tags:

- The `test_id` is not added by default for metrics yet but you can add it to metrics like you did for `traces` and `event` :
```yaml copy
  plugins:
    publish-metrics:
      - type: datadog
        apiKey: "{{ $env.DATADOG_API_KEY }}"
        apiHost: "app.datadoghq.eu"
        prefix: "art.test."
        tags:         # tags for metrics
          - "testName:Workforce"
          - "testId:{{ $env.RUN_ID}}"
          - "service:ARTILLERY"
        traces: 
          serviceName: "ARTILLERY"
          useRequestNames: true
          tags:      # tags for traces
            - "testName:Workforce"
            - "testId:{{ $env.RUN_ID}}"
            - "service:ARTILLERY"
        event:
          title: "Workforce Load Test {{ $env.RUN_ID }} Start"
          priority: normal
          tags:      # tags for event
            - "testId:{{ $env.RUN_ID }}"
```
- Since your metrics don't seem to be affected (they are arriving to Datadog),  just adding the tags as shown above should work.
- As additional note just to mention that the test id is available as a test-level variable, meaning you can use it anywhere in the test script with `"{{ $testId }}"`


Events:
Are events arriving to Datadog properly and have tags?
