### DISCUSSION TITLE
Is it possible to use ensure plugin checks on a dynamic url?

### DISCUSSION THREAD

**Discussion by sujaybarooah** [artilleryio/artillery#2768] [Artillery]
I am using playwright engine with artillery and trying to add web vital checks for page load and interactions. In my scenario, the path of the url is dynamic, e.g. from the processor script:

```
export async function viewObjectDetails(page: Page, context, events, test) {
  const { step } = test
  await step("view-object-details", async () => {
    const applicationId =context.vars.certid; //this is set from a payload csv file
    await viewObjectDetails(page, applicationId)
  })
}
```

implementation for viewObjectDetails:
```
export async function viewObjectDetails(page: Page, applicationId: string){
  await page.goto(`https://my-test-app/objects/${applicationId}`);
  return page;
}
```

This is how I am trying to configure ensure in the artillery config file:

```
config:
  target: "https://"
  includeFiles:
    - ./myapp-storage.json
    - ./import-cert-ids.csv
  engines:
    playwright:
      launchOptions:
        channel: chrome
        # enable for local debugging
        headless: false
        #sloMo: 2000
      contextOptions:
        storageState: "./myapp-storage.json"
  payload:
    path: "import-cert-ids.csv"
    fields:
      - "certid"
    order: random
  phases:
    - name: Constant Load
      arrivalRate: 2
      duration: 1
  # Path to JavaScript file that defines Playwright test functions
  processor: "./myapp-processor.ts"
  plugins:
    ensure: {}
  ensure:
    thresholds:
       #list view
      - 'browser.page.CLS.https://my-test-app/objects.p95': 0.1
      - 'browser.page.CLS.https://my-test-app/objects/(ic-[A-Za-z0-9]+).p95' :0.1
      #details view
      - 'browser.page.LCP.https://my-test-app/objects.p95': 2000
      - 'browser.page.LCP.https://my-test-app/objects/(ic-[A-Za-z0-9]+).p95' : 2000
    conditions:
      - expression: vusers.failed == 0
```

```
fail: browser.page.LCP.https://my-test-app/objects/(ic-[A-Za-z0-9]+).p95 <= 2000
fail: browser.page.CLS.https://my-test-app/objects/(ic-[A-Za-z0-9]+).p95<= 0.1
ok: vusers.failed == 0
ok: browser.page.LCP.https://my-test-app/objects.p95 < 2000
ok: browser.page.CLS.https://my-test-app/objects.p95 < 0.1
```

Seems like I cannot use a regex to provide the dynamic path to look for metrics. Is there a way to do this?
