### DISCUSSION TITLE
Scenario metrics

### DISCUSSION THREAD

**Discussion by hiiiky** [artilleryio/artillery#2789] [Artillery]
Hey, sorry if I've missed something completely, but is there a (OOTB) way of creating a histogram metric for a scenario rather the individual requests which make up a scenario? Basically I'm looking to easily surface the time it take for the scenario to complete as well as the individual request timings

I've made a crude version using the beforeScenario & afterScenario hooks, but wondering if there's a better way? 

test.yml

``` 
config:
  target: https://example.io
  processor: processor.js
scenarios:
  - name: Sample flow
    beforeScenario: 'startScenarioTimer'
    afterScenario: 'endScenarioTimer'
    flow:
      - get:
          name: Request 1
          url: /req1
      - get:
          name: Request 2
          url: /req2
      - get:
          name: Request 3
          url: /req3
```
processor.js
```
const { Timer } = require('timer-node');

const timer = new Timer({ label: 'scenario-timer' });

function startScenarioTimer(context, events, done) {
    timer.start();
    return done();
}

function endScenarioTimer(context, events, done) {
    timer.stop();
    const histogramName = `Scenario: ${context.scenario.name}`;
    events.emit('histogram', histogramName, timer.ms());
    return done();
}

module.exports = { startScenarioTimer, endScenarioTimer };
```
