### DISCUSSION TITLE
How can I generate the html report with artillery using Docker?

### DISCUSSION THREAD

**Discussion by diegolatorre16** [artilleryio/artillery#2809] [Artillery]
I've been getting to know Artillery a few days ago. I have created several test scripts and run them with the following Docker Compose file:

```
version: '3'
services:
  artillery:
    image: artilleryio/artillery:latest
    build:
      context: ..
    volumes:
      - ../:/scripts
    command: ["run", "-o", "/scripts/metrics.json", "/scripts/test_create_delete_csvData.yml"] 


```
Reviewing the documentation, I can generate an html report with the following command:
`artillery report /scripts/metrics.json`

But I don't know how I can launch this command inside my docker container, once the test has finished. Can anybody help me?
