### DISCUSSION TITLE
Artillery and grafana

### DISCUSSION THREAD

**Discussion by rucko24** [artilleryio/artillery#3193] [Artillery]
**Hi, how are you ?** 

I think .json of artillery with prometheus for grafana is a bit outdated ? https://github.com/artilleryio/artillery-examples/tree/main/prometheus-grafana-dashboards

What I understand is that I should adjust the promtQL myself? 

My graph looks like this
![image](https://github.com/artilleryio/artillery/assets/17187599/e8fb6e42-745b-44c9-978c-3225d4a75c2e)

And this is the **.yml** that I'm using

```yml
config:
  target: "http://192.168.1.219:8080"
  phases:
    - duration: 1
      arrivalRate: 100
  http:
    timeout: 20
  plugins:
    publish-metrics:
      - type: prometheus
        pushgateway: 'http://192.168.1.6:9091'
        tags:
          - 'testId:blocking-test'
          - 'type:loadtest-blocking'

scenarios:
  - name: "Request word"
    flow:
      - get:
          url: "/words?limit=100"
```          

the graph I see in Artillery's blog post is a little bit different, 

https://www.artillery.io/blog/grafana-dashboards-for-prometheus-metrics

![image](https://github.com/artilleryio/artillery/assets/17187599/5f7b8f4d-61a0-4d61-98a7-2fc79752c648)
