### DISCUSSION TITLE
Very basic test ran for far longer than expected

### DISCUSSION THREAD

**Discussion by gperrow** [artilleryio/artillery#3197] [Artillery]
I am new to artillery so I expect I'm missing some very basic concept. I installed artillery and created a very basic config file, based on the [docs](https://www.artillery.io/docs/get-started/first-test):

```yaml
config:
  target: https://myhost/
  phases:
    - duration: 10
      arrivalCount: 1
      name: Warm up phase
    - duration: 10
      arrivalCount: 1
      name: Ramp up load
    - duration: 10
      arrivalCount: 1
      name: Sustained peak load
scenarios:
  - name: get index.html
    flow:
    - loop:
      - get:
          url: /myurl/index.html
    count: 1
```

When I ran `artillery run myconfig.yml`, I expected it to run for roughly 30 seconds and stop. Instead, it ran each of the three phases, which took 10 seconds each, and then continued running for another **15 minutes** (before I killed it), dumping some stats every 10 seconds. The stats implied that requests were being sent at a rate of 20-25 per second. 

My site requires authentication and none was provided, so I expected something to fail somewhere but I never saw anything other than "http.codes.200". How can I determine why the test took so long?

This is artillery 2.0.15, node.js 18.20.1

**Comment by hassy** [comment]
that's very odd @gperrow. Can you reproduce the behavior reliably? The only reason I can think of that this would happen is if you accidentally set `count` to a much larger value, so each VU would continue sending requests for a while after all load phases are finished.

**Comment by bernardobridge** [comment]
Hi @gperrow 👋 

I believe the problem is in the indentation of your YAML. `count` is in the wrong place, so it isn't being used, which I believe might be causing the loop to run infinitely. Try the following:

```yml
config:
  target: https://myhost/
  phases:
    - duration: 10
      arrivalCount: 1
      name: Warm up phase
    - duration: 10
      arrivalCount: 1
      name: Ramp up load
    - duration: 10
      arrivalCount: 1
      name: Sustained peak load
scenarios:
  - name: get index.html
    flow:
      - loop:
          - get:
              url: /myurl/index.html
        count: 1
```
