### DISCUSSION TITLE
[Fargate]: Workers running out of memory or out of space

### DISCUSSION THREAD

**Discussion by DanSmithSC** [artilleryio/artillery#3206] [Artillery]
While running some recent load tests on Artillery version 2.0.15 - I'm noticing we're starting to get early terminations and exits with EXIT CODE 6

In researching the logs i'm starting to see errors for:
`worker error, id: 1 Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory`

Additional Logged Error of maybe some importance:
`/artillery/loadgen-worker: line 277: echo: write error: No space left on device`

However the fargate containers were only run with a count of 2, and the memory allocation for those were set to 20gigs of memory

`--count 2 --launch-config '{\"cpu\": 4096, \"memory\": 20480}'`

Any idea why the containers may be running out of space or hitting these memory problems?

Let me know if you need any details - Thanks in advance!

**Comment by bernardobridge** [comment]
Hey @DanSmithSC 👋 

Would you be able to share some details about what you were running? If you are able to share the test and config, that would be helpful, so we can try to recreate it.

Also, was this same test working in older versions of Artillery and suddenly you're getting this issue (with no test changes), or you've only tried on 2.0.15?

Thank you!

**Reply by DanSmithSC** [reply]
I believe this was working before or at least on version 2.0.8. We had not seen these out of memory or spaces errors previously. 

Any hints would be helpful. 
```
config:
  ensure:
    p95: 5000
    maxErrorRate: 10
  variables:
    search_term:
      - tucker
      - test
      - west
      - savannah
  includeFiles: 
    - "../config/perf/events.csv"
    - "../config/perf/games.csv"
    - "../config/perf/schools.csv"
    - "../config/perf/users.csv"    
  payload:
    -
      path: "../config/{{ $environment }}/events.csv"
      delimiter: "\n"
      fields:
        - "eventKey"
    -
      path: "../config/{{ $environment }}/games.csv"
      delimiter: "\n"
      fields:
        - "gameKey"
    -
      path: "../config/{{ $environment }}/schools.csv"
      delimiter: "\n"
      fields:
        - "schoolSlug"
    -
      path: "../config/{{ $environment }}/users.csv"
      delimiter: "\n"
      fields:
        - "username"
    -
      path: "../config/sports.csv"
      delimiter: "\n"
      fields:
        - "sport"
  environments:
    perf: 
      target: "<ENV URL>"
      variables:
        memberService: "<ENV URL>"
      phases:
        - name: Starting
          duration: 1800
          arrivalRate: 1
          rampTo: 75
        - name: Warm up
          duration: 900
          arrivalRate: 75
          rampTo: 150
        - name: Ramp up load spike 1
          duration: 1800
          arrivalRate: 150
          rampTo: 250
        - name: Sustained load 
          duration: 900
          arrivalRate: 250
          rampTo: 300
        - name: Ramp up load spike 2
          duration: 900
          arrivalRate: 300
          rampTo: 600
        - name: Ramp down load
          duration: 4500
          arrivalRate: 600
          rampTo: 1
scenarios:
  - name: "Home page"
    weight: 2.5
    flow:
      - get:
          url: "/"
      - think: 5
  - name: "Login flow"
    weight: 1
    flow:
      - get:
          url: "/"
      - think: 5
      - get:
          url: "/users/sign_in"
      - think: 5
      - post:
          url: "{{ memberService }}/oauth/token"
          json:
            grant_type: "password"
            username: "{{ username }}"
            password: "{{ account_password }}"
            redir: "/"
          capture:
            - json: "$.access_token"
              as: "accessToken"
      - think: 5
      - get:
          url: "/member/account"
      - think: 5
  - name: "Watch events page"
    weight: 2
    flow:
      - get:
          url: "/watch-events"
      - think: 5
  - name: "Game page"
    weight: 2
    flow:
      - get:
          url: "/events/null/{{ gameKey }}"
      - think: 5
  - name: "School page"
    weight: 1.5
    flow:
      - get:
          url: "/schools/{{ schoolSlug }}"
      - think: 5
  - name: "School sport page"
    weight: 1
    flow:
      - get:
          url: "/schools/{{ schoolSlug }}/{{ sport }}"
      - think: 5
  - name: "Search query"
    weight: 2
    flow:
      - get:
          url: "/search?query={{ search_term }}"
      - think: 5
  - name: "Subscribe flow"
    weight: 1
    flow:
      - get:
          url: "/"
      - think: 5
      - get:
          url: "/subscribe/retail"
      - think: 5
```
