### DISCUSSION TITLE
How to run Artillery on a Password protected Vercel URL

### DISCUSSION THREAD

**Discussion by saraE2X** [artilleryio/artillery#3230] [Artillery]
Hi All, 
I would like to run a artillery test in top of the vercel deployed code url whic is protected by a password.
This is  my .yml `config:
```yml
  target: '<my URL>'
  phases:
    - duration: 1 # Total duration of the test in seconds
      arrivalRate: 1 # Initial arrival rate of users per second
      rampTo: 1 # Ramp up to 1137 users over the duration
      name: 'Ramp-up Users'
  engines:
    playwright:
      config:
        extraHTTPHeaders:
          'x-vercel-protection-bypass' : <my token>
        baseURL: '<my URL>'

      # Optional: Add Playwright-specific configurations here if needed.
  processor: './loadtest/artillery/search.ts'
scenarios:
  - engine: playwright
    testFunction: 'artilleryScript'
```
and my search.ts file 

```typescript
import { Page, expect } from '@playwright/test';

async function testSearch(page: Page) {
  await page.goto('');
  await page.getByTestId('search-input-header').click();
  await page.getByTestId('search-input-header').fill('test');
  await page.getByTestId('search-input-header').press('Enter');
  await expect(page.getByTestId('clear-button')).toBeVisible();
}


export async function artilleryScript(page: Page) {
  await testSearch(page);
}
``` 

when i try to run `artillery run load-test.yml`
I see that my link is not open with token password so getting "⠇ locator.click: Timeout 30000ms exceeded.
Call log:
  - waiting for getByTestId('search-input-header')" how do i pass x-vercel-protection-bypass for my target url  ?

**Comment by bernardobridge** [comment]
Hey @saraE2X 👋 

I think the issue here is that you're setting the config option under `engines.playwright.config`, but that is not where to set that in Artillery.

There's an example on how to do this in our docs (i.e. it should be under `contextOptions`): https://www.artillery.io/docs/reference/engines/playwright#example-2-set-extra-http-headers

---

P.S. Please try to use [Github Code Blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) when displaying code, as it helps visualise the issue 🙇 . I edited your post to make it easier.

**Comment by saraE2X** [comment]
Hi @bernardobridge 
Thank you for the response, I have followed the document but still same error
  ```config:
  target: 'https://digital-commerce-five.vercel.app/'
  phases:
    - duration: 1 
      arrivalRate: 1
      rampTo: 1
      name: 'Ramp-up Users'
  engines:
    playwright:
      ContextOptions:
        extraHTTPHeaders:
          'x-vercel-protection-bypass' : "<my token>"
        baseURL: '<my url>'

      # Optional: Add Playwright-specific configurations here if needed.
  processor: './automation-test/loadtest/artillery/search.ts'
scenarios:
  - engine: playwright
    testFunction: 'artilleryScript'
```
Error - Could not locate the element. Note: My search script runs without errors. The problem occurs when the URL is opened through an artillery run. Any insights would be really helpful.

**Reply by bernardobridge** [reply]
@saraE2X 👋  . you're still setting the config option incorrectly. It is case sensitive, and you have written `ContextOptions` rather than `contextOptions`.

**Reply by saraE2X** [reply]
Exactly

**Comment by saraE2X** [comment]
your right , good catch . Thank you 🥇 
```
config:
  target: 'https://digital-commerce-five.vercel.app/'
  phases:
    - duration: 1 
      arrivalRate: 1 
      rampTo: 1  
      name: 'Ramp-up Users'
  engines:
    playwright: 
      contextOptions:
        extraHTTPHeaders:
          'x-vercel-protection-bypass' : "<mytoken>"
      baseURL: '<my url>'
      # Optional: Add Playwright-specific configurations here if needed.
  processor: './automation-test/loadtest/artillery/search.ts'
scenarios:
  - engine: playwright
    testFunction: 'artilleryScript'
```
> Still encountering the same error. 🤕
> I've validated all the elements, but the error persists. Additionally, when I set headless to false, I can't see the browser.
> I am referring the document again.

**Reply by bernardobridge** [reply]
How are you setting `headless` to false? Did you follow [this example](https://www.artillery.io/docs/reference/engines/playwright#example-1-turn-off-headless-mode)?

**Reply by bernardobridge** [reply]
@saraE2X please share your script again with how you're setting headless to `false`. You should be seeing the browser, so there's a chance something else is wrong in your script.

**Reply by saraE2X** [reply]
Finally -Its opening as expected. Thank you so much @bernardobridge 

```
config:
  target: '<url>'
  phases:
    - duration: 2 
      arrivalRate: 1
      rampTo: 1 
      name: 'Ramp-up Users'
  engines:
    playwright:
      launchOptions:
        headless: false
      contextOptions: 
        baseURL: '<url>'
        extraHTTPHeaders:
          x-vercel-protection-bypass : "<my token>"
        
      # Optional: Add Playwright-specific configurations here if needed.
  processor: './automation-test/loadtest/artillery/search.ts'
scenarios:
  - engine: playwright
    testFunction: 'artilleryScript'
```
Now test passing only if i run in headed mode if i enable headless:true its failing.
