### DISCUSSION TITLE
How to pass Xml body in Artillery Get method ?

### DISCUSSION THREAD

**Discussion by priya-dsp** [artilleryio/artillery#3234] [Artillery]
Hi @hassy , we have Xml request body that we need to pass in Get Method but we are getting error during execution -->Error: Get method cannot be used in body. How to fix this? We have already tried with qs, body, json. None of them works.

**Comment by bernardobridge** [comment]
Hello @priya-dsp . The underlying http library that Artillery uses (`got`) does not allow GET methods to have a body (which is standard). 

I believe there is a way around it by setting the `allowGetBody` option to true. For example:

```yml
scenarios:
  - flow:
      - get:
          url: "/"
          allowGetBody: true
          json:
            msg: "Hello, world!"
```
