### DISCUSSION TITLE
How to upload file in POST request?

### DISCUSSION THREAD

**Discussion by priya-dsp** [artilleryio/artillery#3239] [Artillery]
Hi @hassy , We are trying to upload pdf file or jpg image in post request. Post request body is in Xml format. We have converted pdf file into Base64 encoding, however the xml body is not getting passed in request. Can you suggest how to either upload file or any other alternative solution ?

**Comment by hassy** [comment]
hi @priya-dsp 👋 There's ongoing work in #3232 to make file uploading easier. In the meantime you can do something like this:

```yaml
- post:
    url: /upload
    beforeRequest: attachFile # call a helper function to attach a file
```

```js
import * as fs from 'fs';
import FormData from 'form-data';

export async function attachFile(req, context, events) {
  const formData = {
    // "myfile" is the name of the file in the form
    myfile: fs.createReadStream('./files/artillery-logo.jpg')
  };

  req.body = new FormData(formData);
}
```
