### DISCUSSION TITLE
GET request body

### DISCUSSION THREAD

**Discussion by chiralcentre** [artilleryio/artillery#3240] [Artillery]
Can I check if Artillery supports GET requests having a JSON request body? I tried to include a JSON request body as seen in the sample file below, but I keep getting ERR_GOT_REQUEST_ERROR when running the load tests. If the issue is due to syntax errors, do let me know as well!

```
config:
  target: <TARGET>
  phases:
    - duration: 10
      arrivalRate: 1
      name: Warm up phase
    - duration: 10
      arrivalRate: 1
      name: Medium phase
    - duration: 10
      arrivalRate: 1
      name: Spike phase
  plugins:
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
scenarios:
  - flow:
    - get:
        url: <URL>
        headers:
          Content-Type: application/json
        json:
          columnNames: ['year']
```
