### DISCUSSION TITLE
Suggestion on using multiple authenticated users during playwright load test

### DISCUSSION THREAD

**Discussion by bshostak** [artilleryio/artillery#3243] [Artillery]
Hello again team,

I wanted to ask if you had a suggestion on the best way to accomplish this using artillery x playwright. 

We want to run through a product checkout script that does the following:

1. Login
2. Go to shop
3. Add products to cart
4. checkout processes

We want to do this using a handful of authenticated users (example 500). My thought was to loop the test or loop inside the function where needed but that doesn't seem to work (looks like we get a worker error which makes sense since this probably shouldn't be looped). Unless I am blind in the documentation, can't seem to find anything that could support this so wanted to ask if you know of a way to do this? Or maybe a way can be implemented in a future release?

Thanks

**Comment by shiva-taramani** [comment]
Hi, I used something like the following in the past. I am not sure if there are better ways though.

In your scenario file:
```
  config:
    variables:
      # Predefined list of logins
      users:
        - { username: "user1", password: "password1" }
        - { username: "user2", password: "password2" }
        - { username: "user3", password: "password3" }
```
I would suggest trying this instead of putting passwords in plaintext. Or even look at using secrets.
https://www.artillery.io/docs/reference/test-script#payload---loading-data-from-csv-files

In your flow function, you should be able to add a variables argument, and grab the values like `variables.vars.users.username`. For every vuser, you should get one from the list (I think; you should confirm that it works).
