### DISCUSSION TITLE
Relation between maxVusers limit and requests

### DISCUSSION THREAD

**Discussion by chiralcentre** [artilleryio/artillery#3246] [Artillery]
Can I check why setting limit on maxVusers does not affect the total number of requests made throughout the testing phase? For the following file, regardless of whether the maxVusers limit is set, the total number of requests made is 30. On a related note, can I check if the number of requests made per second is equivalent to the arrivalRate?

```
config:
  target: <TARGET>
  phases:
    - duration: 30
      arrivalRate: 1
      name: Warm up phase
      maxVusers: 3
  plugins:
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
scenarios:
  - flow:
    - get:
        url: <URL>
        timeout: 30000
```
