### DISCUSSION TITLE
Lambda testing at scale 8 million virtual users

### DISCUSSION THREAD

**Discussion by oscarsb66** [artilleryio/artillery#3251] [Artillery]
Version info: 
```
VERSION INFO:

Artillery: 2.0.16
Node.js:   v21.1.0
OS:        darwin
```

Running this command: 
```
artillery run-lambda --region us-east-2 blitz.yaml --tags artillery:test
```

I expected to see this happen:

Hello, 
We're currently trailing out this product to use it as part of our load testing scenarios.
We would like to hit a concurrency of 8 million virtual users.

Instead, this happened:

Even when changing the value of `rampTo` we haven't seen anything more than `vusers.created: 10948` approximately.
Is it achievable to generate these kind of figures with artillery ? (we're aware of the current 15 minutes maximum timeout)
Thanks in advance!  

Files being used:
```
config:
  target: https://foo.bar
  phases:
    - duration: 1200
      rampTo: 50000
      name: test
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
    thresholds:
      - http.response_time.p99: 100
      - http.response_time.p95: 75
scenarios:
  - flow:
      - loop:
          - get:
              url: '/some_endpoint'
        count: 1
```
