### DISCUSSION TITLE
VUsers stop generating after 1000

### DISCUSSION THREAD

**Discussion by okHadi** [artilleryio/artillery#3254] [Artillery]
Hi all,
I've been testing with 3-5k users on my site recently, and was generating users with success (with some VUs failing).
However now I'm unable to generate more than a 1000 users with the same configuration. VUs stop generating just around hitting that count.

Using FARGATE and playright engine.

These are my configurations:

```config:
  target: myurl
  phases:
  - duration: 1000
    arrivalRate: 1
    maxVusers: 150
  engines:
    playwright: {launchOptions: {headless: true}, defaultNavigationTimeout: 100000, extendedMetrics: true, useSeparateBrowserPerVU: false}

  processor: "./flow.js"
scenarios:
- engine: playwright
  testFunction: "loadTest"
```

and
``` - duration: 600
    arrivalRate: 1
    maxVusers: 150
```
    
  and
  
```  - duration: 200
    arrivalCount: 200
    maxVusers: 100
```
    
  With this command:
    
    ```artillery run-fargate --region us-east-1 --count 30 --cpu 16384 --memory 32768 config.yml --record --key mykey```
    
  I've used different counts and different maxVusers and arrival count, arrival rate. Still the same. 
    
 ### Last Configuration
    
 This was the configuration:
    
 ```
config:
  target: myurl
  phases:
  - duration: 1000
    arrivalRate: 1
    maxVusers: 150
  engines:
    playwright: {launchOptions: {headless: true}, defaultNavigationTimeout: 100000, extendedMetrics: true, useSeparateBrowserPerVU: false}

  processor: "./flow.js"
scenarios:
- engine: playwright
  testFunction: "loadTest"
```

This was the command:
```artillery run-fargate --region us-east-2 --count 30 --cpu 16384 --memory 32768 config.yml --record --key mykey```

This was the result.

![image](https://github.com/artilleryio/artillery/assets/64269712/3a8f2a51-e4ed-4fa2-86c4-280a62cf549e)

What could be the issue?
