### DISCUSSION TITLE
Value is not being captured from JSON.

### DISCUSSION THREAD

**Discussion by pedroluisjr** [artilleryio/artillery#3257] [Artillery]
Version info:
```
2.0.16
```

I have this scenario:
```
scenarios:
  - flow:
      - get:
          url: 'url/employeeId'
          headers:
            Authorization: 'Bearer {{ accessToken }}'
          capture: 
            - json: "$"
              as: "id"
      - log: "prescriptionId {{ id }}"
```

The value returned in the body is just an integer, like the image below:

![image](https://github.com/artilleryio/artillery/assets/107949739/36565cdc-884a-40a5-a6f7-47867401960d)

and I'm trying to capture this returned value but I'm not succeeding, thanks for the help!
