### DISCUSSION TITLE
Artillery-Playwright - Config and aggregated report analysis

### DISCUSSION THREAD

**Discussion by Romarionijim** [artilleryio/artillery#3258] [Artillery]
Hello,

I have a few small questions please regarding artillery-playwright.

1.  I am using playwright and want to implement artillery in our workplace,  my question is, we have the playwright.config.ts which we configure our framework's settings such as workers, reporters, launch options and etc, I noticed in artillery I need to provide the config in each yml test file such as target and engine e.g:
```
config:
  target: https://www.artillery.io
  # Load the Playwright engine:
  engines:
    playwright: {}
  # Path to JavaScript file that defines Playwright test functions
  processor: './flows.js'
scenarios:
  - engine: playwright
    testFunction: 'helloFlow'

```

my question is if I can set the engine to playwright on browser facing tests only once instead of repeating in each yml?

2. if I reuse a certain class that already has the goto function which navigates to a specific website, do I need to provide the `target` key in the yml file?

example of a loginFlow that navigates to a hardcoded url with the `loadApp()` function

```
import { Page } from "@playwright/test";
import { LoginPage } from "../../ui-automation/pages/LoginPage";

export async function loginFlow(page:Page) {
  let loginPage = new LoginPage(page)
  await loginPage.loadApp();
  await loginPage.login();
}
```

do I still need to provide the target in the yml file?

3.  is there a documentation that explains what each line means in the aggregated report?
4. are there learning recourses other than the documentation that you provide?

Thank you very much!
