### DISCUSSION TITLE
Script is running for more than defined time.

### DISCUSSION THREAD

**Discussion by shiv-vsics** [artilleryio/artillery#3275] [Artillery]
Hi @hassy /Team,

I have written a simple artillery script where i have taken query params by appending these to URL with ? and when i running this script , its running for more than 1 hour even after defined duration as 200 sec.

Could you please explain why its happening ?

```yml
config:
  payload:
    path: "filters.csv"
    fields:
      - "filter"
    loadAll: true
    skipHeader: true
    name: symb
 
  target: "https://qa.test.com"
  phases:
    - duration: 200
      arrivalRate: 1
 
scenarios:
  - name: "Performance Testing For test API"  
    flow:
      - loop:
        - get:
            url: '/test-data/testing-data/?{{ $testElement.filter }}'
            headers:
              appkey: 'TestAppkey'
        over: symb         
after:
  flow:
    - log: "Invalidate token"
    - log: "token is {{ token }}"
```
