### DISCUSSION TITLE
Help running Playwright TypeScript testcase in Azure Devops Pipeline with Artillery

### DISCUSSION THREAD

**Discussion by pditmar** [artilleryio/artillery#3285] [Artillery]
I am trying to use some of our functional testscripts and run them with Artillery in an Azure DevOps pipeline. I am using the example Github pipeline yaml with some small modifications:

```
#trigger:
#  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js v20.x'

  - script: npm install -g artillery@latest
    displayName: 'Install Artillery'
 
  - script: mkdir $(System.DefaultWorkingDirectory)/reports
    displayName: 'Make reports directory'
 
  - script: artillery run --output reports/report.json apps/e2e/online.yml
    displayName: 'Execute load tests'
 
  - script: artillery report --output reports/report.html reports/report.json
    displayName: 'Generate HTML report'
 
  - publish: $(System.DefaultWorkingDirectory)/reports
    artifact: artillery-test-report
```

The test fails to start with the following error :

```
Script contents:
artillery run --output reports/report.json apps/e2e/online.yml
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/dd785957-3e87-4393-975a-01758b9791e6.sh
Test run id: txnhc_xe3ntbrpz74588nzqaafzq67jdnne_mhye
Bundled Typescript file into JS. New processor path: /home/vsts/work/1/s/apps/e2e/src/e2e/post-deploy/serviceContact/dist/FindLocation.spec.js
worker error, id: 2 Error: Cannot find module '@playwright/test'
Require stack:
- /home/vsts/work/1/s/apps/e2e/src/e2e/post-deploy/serviceContact/dist/FindLocation.spec.js
- /opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/runner.js
- /opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/node_modules/@artilleryio/int-core/index.js
- /opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/lib/artillery-global.js
- /opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/lib/platform/local/worker.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/vsts/work/1/s/apps/e2e/src/e2e/post-deploy/serviceContact/FindLocation.spec.ts:1:30)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/vsts/work/1/s/apps/e2e/src/e2e/post-deploy/serviceContact/dist/FindLocation.spec.js',
    '/opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/runner.js',
    '/opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/node_modules/@artilleryio/int-core/index.js',
    '/opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/lib/artillery-global.js',
    '/opt/hostedtoolcache/node/20.15.1/x64/lib/node_modules/artillery/lib/platform/local/worker.js'
  ]
}
```

I've been looking at the docs and here in the knowledge base but I cannot seem to figure out what I am doing wrong. What am I missing here?
