### DISCUSSION TITLE
Complex URLs from CSV load not working

### DISCUSSION THREAD

**Discussion by CKalinski** [artilleryio/artillery#3286] [Artillery]
I am attempting to load a set of complex URLs from a CSV into a scenario loop. No joy on them coming through. Wondering if these are just too complex or do I have something amiss in the definitions here? Do I need to break them up and assemble a text string within the yml instead. Would like to avoid that as it would involve chopping the URL up into five or sixes pieces and then mapping that into the CSV setup.

No joy on getting this to load from the CSV file. I have verified it is a plain text file and UTF-8. The URL text runs fine if it is hard-coded into the yml scenario, but for some reason it is not loading from the CSV. In the log statement, I am getting back the message 'undefined' for the variable read in from the file.

Here is the yaml file (URL's scrubbed a bit). A sample of one of the URLs is included. (Most of this was copy/paste from either the docs or the examples, the intent being we would set the phase parameters once the baseline code was stable.)

```
config:
  target: "https://uat.something.com"
  payload:
    - path: .\csv\queries.csv
      fields: [query_url, code]
      order: sequence
      loadAll: true
      name: url_data
  phases:
    - duration: 10
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase

    # - duration: 15
    #   arrivalRate: 5
    #   rampTo: 10
    #   name: Ramp up load

    # - duration: 5
    #   arrivalRate: 10
    #   rampTo: 30
    #   name: Spike phase

  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
    thresholds:
      - http.response_time.p99: 1000
      - http.response_time.p95: 750

  environments:
    prod:
      target: "https://something.com"
    uat:
      target: "https://uat.something.com"


scenarios:
  - name: "test"
    flow:
      - loop:
        - log: "Element is: {{$loopElement.query_url}}"
        - get:
            url: "{{$loopElement.query_url}}"
            # The following URL works if run as hard-coded (the unscrubbed version that is). CSV has a list of similar text strings.  
            # url: /gismobile/rest/services/something/Something_Service/FeatureServer/21/query?where=AVONAME+%3D+%27Hungerrun+Creek+West%27+And+OBJECTID+%3C+10000&f=pjson
            expect:
                statusCode: "{{$loopElement.code}}"
        over: url_data
        count: 2

```

Pieces of the URL that change item from item in our list...
* the first word in URL (e.g. gismobile could be something else)
* FeatureServer could also be MapServer
* the number that follows that is always different
* everything after 'query?'

Command line being used:
artillery run -e uat -q -o ".\outputs\TEST.json" config-test.yml
