### DISCUSSION TITLE
Loop over multiple variables in API calls

### DISCUSSION THREAD

**Discussion by rushi** [artilleryio/artillery#3290] [Artillery]
I would like to use multiple variables and loop over them. For example if you have: `/armadillo?value={{ $firstVariable }}&productId={{ $secondVariable }}`

I would like Artillery to use a combination of both variables and make those API calls.  Here's a quick example of my test. Below I would like the `/armadillo` API calls to be made with:

1. ?value=**alpha**&productId=**id1**
2. ?value=**alpha**&productId=**id2**
3. ?value=**beta**&productId=**id1**
4. ?value=**beta**&productId=**id2**

```yaml
config:
  # target and phases omitted

  variables:
    value:
      - alpha
      - beta
    productIds:
      - id1
      - id2

scenarios:
  - flow:
      - loop:
          - get:
              url: "/dino?value={{ $loopElement }}"
          - get:
              url: "/armadillo?value={{ value }}&productId={{ $loopElement }}"
        over: "productIds"
        count: 1

```
