### DISCUSSION TITLE
Invoking AWS Lambda Function Directly

### DISCUSSION THREAD

**Discussion by laurelleb** [artilleryio/artillery#3292] [Artillery]
I am trying to invoke a lambda function by name. I do not have access to the function URL and cannot call the lambda that way. I found an engine called artillery-engine-lambda, but it is archived. It can be found here: (https://github.com/orchestrated-io/artillery-engine-lambda)

I have a few questions:

- Are there other ways to invoke the lambda name instead of the URL?

- Is there a way to add a stop condition to this script? I am not sure if some of the other parameters from say, HTTP, would work here. I would like the test to last no more than 15 minutes. I see that under the [AWS Lambda doc page](https://www.artillery.io/docs/load-testing-at-scale/aws-lambda)m that the test duration should last no longer than 15 minutes, but how can I make sure that my test stops at 15 min? Does it stop automatically? And if not, what do I need to add to my script to exit the test before 15 min?

- Finally, I need to be able to parameterize the target lambda name. I have multiple lambdas I need to change based on the environment build of Jenkins. For example, devtest-lambda and prod-lambda. Would it be as simple as making a variable in the yaml called {{ $lambda-name }} and making that the target variable? Or would I need to call it in my "artillery run" line of the Jenkins file. I am not a developer so I am a bit confused on this. 

For deeper context - the following code is the yaml script that should invoke the lambda and deliver a payload ( key/value pair dictionary removed for confidentiality). 

```yaml
config:
     target: "lambda-name"
     lambda:
         region: us-east-1
     phases:
        - duration: 60
        arrivalRate: 3
        name: Small warmup test
    engines:
        lambda: {}
scenarios:
    - name: "Invoke Lambda"
       engine: "lambda"
       flow:
           - invoke:
               invocationType: "Event"
               logType: "Tail"
               qualifier: 1
               payload: ""`
```
This load test is a stage within a Jenkins build.

The function that runs the yaml script:

```
def runloadtest(string environment, string awsenv) {
     dir(folderpath/folder) {
         sh script: """
              npm config set strict-ssl false
              npm install artillery-engine-lambda
              ./node_module/.bin/artillery run --output outputTest.json loadTest.yml
           """, label: "Run Lambda Load Tests for ${environment}"
     }
}
```

I did run a test with npm install artillery too but it wouldn't run without artillery-engine-lambda too. I think this is because of how I have written my yaml script.

I would appreciate any help. Thanks in advance. Let me know if you need more info to help.
