### DISCUSSION TITLE
feature: specify a Content-Type for individual values when building a formdata request

### DISCUSSION THREAD

**Discussion by RikdeVos** [artilleryio/artillery#3315] [Artillery]
One of our microservices requests multipart-formdata in the request body, with a JSON payload as `value` and a `Content-Type` for such a value.

Example of such a request body, notice `climate`:
```
----------------------------075665284739699357567720
Content-Disposition: form-data; name="activity"
surfing
----------------------------075665284739699357567720
Content-Disposition: form-data; name="type"
beach
----------------------------075665284739699357567720
Content-Disposition: form-data; name="location"
Lahinch
----------------------------075665284739699357567720
Content-Disposition: form-data; name="climate"
Content-Type: application/json
{"temperature": 25, "unit": "Celcius"}
----------------------------075665284739699357567720--
```

In Postman this can be done in the UI by setting a `Content-Type`:
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/f6ee3adb-41d8-4d09-add0-5cb98495430d">

As we're migrating from Postman to Artillery for our testing suite, we found Artillery doesn't support this out of the box. We were able to get this to work by using a [beforeRequest](https://www.artillery.io/docs/reference/engines/http#beforerequest-hooks) hook with some custom JS, but it's not nearly as nice.

Our suggestion is to extend the http engine to allow passing a `Content-Type`. YAML will look like this:
```yaml
- post:
    name: Post activity
    url: /climate
    formData:
      activity: '{{ activity }}'
      type: '{{ type }}'
      photo:
        fromFile: './photo.png'
      climate:
        value: '{"temperature": "{{ climate.temperature }}", "unit": "{{ climate.unit }}"}'
        contentType: application/json
    expect:
      - statusCode: 201
```
Additionally it would also be possible to set a `contentType` for a field where you attach a file, which is a nice benefit.
