### DISCUSSION TITLE
OpenTelemetry plugin, support for resource attributes

### DISCUSSION THREAD

**Discussion by viktorgagaleski** [artilleryio/artillery#3333] [Artillery]
Hello Artillery team,

We are evaluating Artillery in combination with Playwrigth in order to do UI performance testing. The PoC is going great and I am really positively surprised on what it can be achieved, especially if teams already have Playwight setup with pages, components etc.

We also want to leverage the oTel plugin and send the results of the runs to our oTel backbone. We managed to do this successfully but there are some issues that we observed. Our oTel collector expects the attributes to be inside of the resources -> attributes child, which at the moment doesn't seem to happen. All of the attributes are added in the metric -> attributes. We need this as that is how we filter our logs and metrics, and then decide on retention period etc.

This is the config that we use:
```
  plugins:
    publish-metrics:
      - type: open-telemetry
        serviceName: artillery-performance
        metrics:
          exporter: 'otlp-grpc'
          endpoint: '<URL>'
          attributes:
            service.namespace: 'test'
            team: 'e2e'
```

oTel example:
```{
  "resourceMetrics": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "my.service"
            }
          }
        ]
      },
      "scopeMetrics": [
        {
          "scope": {
            "name": "my.library",
            "version": "1.0.0",
            "attributes": [
              {
                "key": "my.scope.attribute",
                "value": {
                  "stringValue": "some scope attribute"
                }
              }
            ]
          },
          "metrics": [
            {
              "name": "my.counter",
              "unit": "1",
              "description": "I'm a Counter",
              "sum": {
                "aggregationTemporality": 1,
                "isMonotonic": true,
                "dataPoints": [
                  {
                    "asDouble": 5,
                    "startTimeUnixNano": 1544712660300000000,
                    "timeUnixNano": 1544712660300000000,
                    "attributes": [
                      {
                        "key": "my.counter.attr",
                        "value": {
                          "stringValue": "some value"
                        }
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}
```
We would like to add attributes here:

`
       "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "my.service"
            }
          }
        ]
      },
`

Is there any way on how we can add resource attributes via the yml configuration?

**Comment by hassy** [comment]
hi @viktorgagaleski 👋 will need to check, it might need a change to the OTel integration, but shouldn't be too difficult.

very happy to hear the PoC is going well!

**Reply by viktorgagaleski** [reply]
Thanks, I would appreciate if we can have:

```
publish-metrics:
   attributes:
     serviceName: ..
```

 that will go to the resource attributes of the metrics that we are sending. As the service name is actually part of them :)

**Reply by hassy** [reply]
Put together a quick prototype earlier to allow `resourceAttributes` to be set like this:

```yaml
  plugins:
    publish-metrics:
        - type: 'open-telemetry'

          # Set resource attributes:
          resourceAttributes:
            resource-attr-set-in-config: coffee

          metrics:
            exporter: 'otlp-http'
            endpoint: https://ingress.eu-west-1.aws.dash0.com/v1/metrics
            headers:
              Authorization: Bearer auth_mykey
          traces:
            exporter: 'otlp-http'
            endpoint: https://ingress.eu-west-1.aws.dash0.com/v1/traces
            headers:
              Authorization: Bearer auth_mykey

```

Which then produces this (using [Dash0](https://www.dash0.com/) in this example but should be similar for other vendors):

![CleanShot 2024-09-10 at 22 09 35](https://github.com/user-attachments/assets/6e049078-350a-4f41-aee3-82db307f6a65)

Would this solve your use case?
