### DISCUSSION TITLE
How do I include a TLS cert and passphrase in my request?

### DISCUSSION THREAD

**Discussion by JordanTheriault** [artilleryio/artillery#3351] [Artillery]
I have a `.p12` cert file and passphrase that I need to use in order to call a service. Everything is working well when tested in Postman or a similar application. But I can't find any reading on how to include them in the request within Artillery's docs.

I found a plugin called `http-ssl`, but I can't find a way to get it working, it appears to be out of date. Especially since a "cert" is not used by the new HTTP engine `got`, and I think `pfx` appears to be the right one for me since I'm using a `p12` cert.

I've configured it according to this post: https://github.com/artilleryio/artillery/discussions/1244#discussioncomment-8611347

It seems to be working, however my issue is that I need to load the file into the config somehow, to provide a byte stream of the `pfx` file.

```
config:
  target: 'https://mysite.com/api'
  tls:
      pfx: "./certs/mycert.p12"
      passphrase: "myPassphrase"
```

Can anyone help me get this working?
