### DISCUSSION TITLE
Is there anyway to make the window size bigger for Virtual Users?

### DISCUSSION THREAD

**Discussion by samhunter1** [artilleryio/artillery#3358] [Artillery]
Might be more to it but just wondering if there was a way to make the window size bigger for virtual users? I have an element that can't be accessed via scrolling and is only visible if the window is big enough. 

Thanks

**Comment by hassy** [comment]
You should be able to use the `page.setViewPortSize()` method to resize the window: https://playwright.dev/docs/api/class-page#page-set-viewport-size

Or you can set `viewport` via `contextOptions` - https://playwright.dev/docs/api/class-browser#browser-new-context-option-viewport to set default window size for all VUs when they're created. Something like this:

```yaml
config:
  target: "https://example.com"
  engines:
    playwright:
      contextOptions:
        viewport:
          width: 1600
          height: 1200
scenarios:
  # scenarios here
```
