### DISCUSSION TITLE
How to include multiple files or entire folders in the include section of YAML file

### DISCUSSION THREAD

**Discussion by amit-saini-tx** [artilleryio/artillery#3360] [Artillery]
Hi, 

Does anyone know how to include multiple files or entire folders in the include section of the artillery config file?

The example below shows that it is possible to add only one file at a time. However, in my case, it's tedious to add every single file because, by default, artillery only includes 2 files.

```
config:
  target: "http://example.com"
  phases:
    - duration: 60
      arrivalRate: 10

  include:
    - data/users.csv           # Include a specific CSV file
    - config/environment.yaml  # Include a YAML file from a config folder
    - payloads/payload1.json    # Include a JSON file from a payloads folder
    - payloads/payload2.json    # Another file from the same folder

scenarios:
  - name: "Login and Fetch User Data"
    flow:
      - post:
          url: "/login"
          json:
            username: "{{ username }}"
            password: "{{ password }}"
          capture:
            json: token
            as: token

      - get:
          url: "/user/{{ userId }}"
          headers:
            Authorization: "Bearer {{ token }}"
```

<img width="304" alt="image" src="https://github.com/user-attachments/assets/04a0636e-03c6-4ff3-ad0b-31dbc4393dbe">
