### DISCUSSION TITLE
http headers. cookie can configuration override default configuration?

### DISCUSSION THREAD

**Discussion by McDonald755** [artilleryio/artillery#3391] [Artillery]
In config.yaml  I set
```
  http:
    extendedMetrics: true
    defaults:
      cookie:
        name: "value"
```

In scenarios I reset this cookie

```
scenarios:
  - name: "get cookie"
    flow:
      - post: # create anonymous user
          url: "/getcookie"
          headers:
            Content-Type: 'application/json'
          capture:
              - json: '$.error.code'
                as: 'code'
              - json: '$.user.userID'
                as: 'userID'
              - json: '$.user.name'
                as: 'name'
              - header: 'set-cookie'
                as: 'cookie'
      - log: "cookie: {{cookie}}"
      - get: # get usere
          url: "/getuser"
          headers:
            cookie: '{{cookie}}'
```

Can I override my default options？
I hope can override my http.default.cookie
