### DISCUSSION TITLE
running several playwright load tests at the same time (or in sequence)

### DISCUSSION THREAD

**Discussion by zoe-jobson-IL** [artilleryio/artillery#3399] [Artillery]
We have a number of playwright load test that we want to reuse for a nightly performance test, so far I have this
```
before:
  flow:
    - function: ensureXlOrgIsReady # default to smallest org
    - function: fetchAllUsers
scenarios:
  - engine: playwright
    testFunction: "platformNavigation"
  - engine: playwright
    testFunction: "appsec"
  - engine: playwright
    testFunction: "bookmarking"
  - engine: playwright
    testFunction: "crisisSim"
  - engine: playwright
    testFunction: "leaderboard"
  - engine: playwright
    testFunction: "mitre"
  - engine: playwright
    testFunction: "workforce"

```
and this

```
export { scenario as appsec } from "@/tests/artillery/app-sec.art";
export { scenario as bookmarking } from "@/tests/artillery/bookmarking.art";
export { scenario as crisisSim } from "@/tests/artillery/crisis-sim-multi-feature.art";
export { scenario as leaderboard } from "@/tests/artillery/leaderboard.art";
export { scenario as mitre } from "@/tests/artillery/mitre-click-on-sub-technique.art";
export { scenario as platformNavigation } from "@/tests/artillery/platform-navigation.art";
export { scenario as workforce } from "@/tests/artillery/workforce-for-perf.art";

export { fetchAllUsers } from "@/framework/artillery/fetchUsers";
export { ensureXlOrgIsReady } from "@/framework/artillery/XlOrg";
export { $rewriteMetricName } from "@/framework/artillery/rewriteMetricName";

```

the trouble is that the way multiple scenarios works means that I often get one of the scenarios picked 3 times and another not picked at all, which means that ensure stats that are based off the not-picked one fail because they don't get triggered.

Is there are way of telling the artillery runner that I want exactly N versions (e.g. 1 or 3 or whatever) of each scenario to run, or failing that a way I can run them in sequence, I tried changing my import/exporter to run them, but obviously I lose the browser between scenarios, though it did run the first in the list.

**Comment by shanti-razr** [comment]
I am also doing something similar. Having the ability to just say run all tests X number in a round robin would be way better than the current system where it is all random.

**Comment by hassy** [comment]
There are two ways to do this:

1. Assign weights to scenarios - https://www.artillery.io/docs/reference/test-script#scenarios-section. For example:

```yaml
scenarios:
  - engine: playwright
    weight: 1
    testFunction: "platformNavigation"
  - engine: playwright
    weight: 2
    testFunction: "appsec"
  - engine: playwright
    weight: 3
    testFunction: "bookmarking"
```

The weight config above would make Artillery:
- pick `bookmarking` for around 50% of all virtual users (3 / (1 + 2 + 3))
- pick `appsec` for around 33% of all virtual users (2 / (1 + 2 + 3))
- pick `platformNavigation` for around 16% of all virtual users

(weights are relative to each other, and are probabilistic so the numbers won't be exact)

2. The other option to run multiple scenarios in a sequence would be to call them both from the same `testFunction`. Something like this:

```js

import { scenario as platformNavigation } from "@/tests/artillery/platform-navigation.art";
import { scenario as appsec } from "@/tests/artillery/app-sec.art";

async function runInSequence(page) {
  // We're passing the same page object here so there should be no issues with reusing the same browser instance
  await platformNavigation(page);
  await appsec(page);
}

export const runInSequence;
```

```yaml
scenarios:
  - engine: playwright
    testFunction: runInSequence
```
