### DISCUSSION TITLE
Running Artillery on GitHub Actions With Playwright

### DISCUSSION THREAD

**Discussion by SChellapuram** [artilleryio/artillery#3403] [Artillery]
My test configuration is simple: navigating to the UI and logging in. The script works fine locally, but when I try to set it up in GitHub Actions, I get errors. I tried adding **npx playwright instal**l under the 'Execute Load Tests' step, but I still get the same complaint. 

Error 

```
Run artilleryio/action-cli@v1
/usr/bin/docker run --name e307262d1027[4](https://github.com/Servita-Professional-Services/hc-test-automation/actions/runs/11800573889/job/32871800078#step:8:5)42939ba10c96e0215724_29f297 --label 24305e --workdir /github/workspace --rm -e "INPUT_COMMAND" -e "INPUT_WORKING-DIRECTORY" -e "CWD" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/hc-test-automation/hc-test-automation":"/github/workspace" 24305e:307262d1027442939ba10c96e0215724  "run src/tests/hc-pep/performance/artillery/management-portal/global-admin/ga-load-test.yml --output reports/load-test-report.json"
Test run id: ty5j7_bf9ckkkky4jkagnawdxzgrdjefwdf_yc97
Phase started: unnamed (index: 0, duration: 60s) 1[5](https://github.com/Servita-Professional-Services/hc-test-automation/actions/runs/11800573889/job/32871800078#step:8:6):37:14(+0000)

worker error, id: 1 browserType.launch: Executable doesn't exist at /github/home/.cache/ms-playwright/chromium-1140/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at Array.scenario (/home/node/artillery/node_modules/artillery-engine-playwright/index.js:149:55)
    at runScenario (/home/node/artillery/node_modules/@artilleryio/int-core/lib/runner.js:380:32)
    at EventEmitter.<anonymous> (/home/node/artillery/node_modules/@artilleryio/int-core/lib/runner.js:212:25)
    at EventEmitter.emit (/home/node/artillery/node_modules/eventemitter3/index.js:181:35)
    at UniformProcess.<anonymous> (/home/node/artillery/node_modules/@artilleryio/int-core/lib/phases.js:24[6](https://github.com/Servita-Professional-Services/hc-test-automation/actions/runs/11800573889/job/32871800078#step:8:7):10)
    at /home/node/artillery/node_modules/arrivals/lib/index.js:4[7](https://github.com/Servita-Professional-Services/hc-test-automation/actions/runs/11800573889/job/32871800078#step:8:8):10
    at NanoTimer.setInterval (/home/node/artillery/node_modules/nanotimer/lib/nanotimer.js:220:5)
    at Immediate._onImmediate (/home/node/artillery/node_modules/nanotimer/lib/nanotimer.js:203:6[8](https://github.com/Servita-Professional-Services/hc-test-automation/actions/runs/11800573889/job/32871800078#step:8:9)) {
  name:
```

**My YML File**

```
name:  Artillery Playwright Load Tests

on:
  workflow_dispatch:
  push:
    branches:
      - feature/mp-load-test

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Verify Playwright installation
        run: npx playwright --version

      - name: Create reports directory
        run: mkdir -p reports

      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run src/tests/hc-pep/performance/artillery/management-portal/global-admin/ga-load-test.yml --output reports/load-test-report.json

      - name: Upload Artillery report
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: reports/load-test-report.json
```

Is there anything missing above ?

**Comment by manfromanotherland** [comment]
I think you need to install browsers separately, try replacing the “Install Playwright browsers” step with:

```yml
      - name: Install Playwright Browsers
        run: npx playwright install && npx playwright install chromium
```

**Reply by SChellapuram** [reply]
@manfromanotherland  Thanks for the reply. Yes added as you mentioned and getting similar issue,
![Screenshot 2024-11-12 at 7 12 43 pm](https://github.com/user-attachments/assets/42ea68bf-e04a-4a19-bda5-5ba6f635639a)

**Reply by SChellapuram** [reply]
This one worked

```
name: Load Tests

on:
  workflow_dispatch:
  push:
    branches:
      - feature/mp-load-test

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Create reports directory
        run: mkdir -p reports

      - name: Install Playwright browsers
        run: |
          npx playwright install chromium  # Install Playwright browsers within the container

      - name: Install Artillery
        run: npm install -g artillery

      - name: Execute load tests with Artillery and Playwright
        run: artillery run src/tests/hc-pep/performance/artillery/management-portal/global-admin/ga-load-test.yml --output reports/load-test-report.json

      - name: Upload Artillery report
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: reports/load-test-report.json
```
