### DISCUSSION TITLE
Error with lambda request entity too large

### DISCUSSION THREAD

**Discussion by themr97** [artilleryio/artillery#3411] [Artillery]
I am currently trying to run multiple scenarios for testing my api gateway, whenever i start this run it gives me the following error as mentioned in my screenshots

![image](https://github.com/user-attachments/assets/ed419c0e-db61-4be7-9d0f-c1f9b8abeb23)
![image](https://github.com/user-attachments/assets/a7b9afc1-3a9d-4951-b95e-32acbd0cdf77)

this is the command i generally use

`artillery run-lambda --region ap-south-1 --count 10 filename.yaml`

```
config:
  target: "https://xx.cloud"  # The target API URL
  phases:
    - duration: 60  # Duration of the test in seconds
      arrivalRate: 100  # Number of requests per second
  http:
    requestTimeout: 60000  # Timeout for each request set to 60 seconds
  plugins:
    expect: {}

scenarios:
  - name: "1"
    flow:
      - get:
          url: "/livefeed/"
          headers:
            accept: "text/plain"
            Authorization: "Bearer xx"
          expect:
            - statusCode: 200
  - name: "2"
    flow:
      - get:
          url: "/feed/"
          headers:
            accept: "text/plain"
            Authorization: "Bearer xx"
          expect:
            - statusCode: 200
  - name: "3"
    flow:
      - get:
          url: "/livefeed/"
          headers:
            accept: "text/plain"
            Authorization: "Bearer xx"
          expect:
            - statusCode: 200

```
