### DISCUSSION TITLE
Can't exclude certain metrics from pushing to Datadog

### DISCUSSION THREAD

**Discussion by quentinkakudasonos** [artilleryio/artillery#3434] [Artillery]
I am trying to not push all metrics to Datadog but the `excluded` tag doesn't seem to work for me prrobably due to my own syntax in the test yaml.

I can't seem to find any examples or other discussions on the formatting for the metrics exclusion but every permutation I have tried of the metric name does not appear to stop it from being pushed.

```
    publish-metrics:
      - type: datadog
      # other config and env stuff etc...
        excluded:
          - 'artillery.publish_metrics.vusers.session_length.count'
          # - 'vusers.session_length.count'
          # - 'session_length.count'
```
