### DISCUSSION TITLE
Using custom processor.js file to generate custom JWT header per user when load testing websockets

### DISCUSSION THREAD

**Discussion by aleksandarvanced** [artilleryio/artillery#3438] [Artillery]
Hello,
I am trying to load test a websocket server where I want to add a JWT which is different per user - and that gets passed when establishing the connection.
Here are the files
`processor.js`
```
let tokens = [
  "token1",
  "token2,
  "token3"
]
function generateRandomToken (userContext, events, done) {
  userContext.vars.token = tokens[Math.floor(Math.random() * tokens.length)];
  return done()
}

module.exports = {
    generateRandomToken
};
```

Here is the main yaml file where the load test script is executed
```
config:
  target: "ws://localhost:8080/userMessages"
  phases:
    - duration: 1
      arrivalRate: 1
  processor: "./processor.js"
  function: "generateRandomToken"
  ws:
    headers:
      x-jwt-token: "{{ token }}"

scenarios:
  - engine: "ws"
    flow:
      - send: "Test message"
      - think: 30
```

The error that I am getting when executing this is ` worker error, id: 1 TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "x-jwt-token"`

I see there is a similar issue open here for socketio - it is closed but without any answer - https://github.com/artilleryio/artillery/issues/2003
Thanks a lot in advance

**Comment by hassy** [comment]
hi @aleksandarvanced - the call to your custom function needs to be inside the VU scenario, rather than at the `config` level:

```diff
config:
  target: "ws://localhost:8080/userMessages"
  phases:
    - duration: 1
      arrivalRate: 1
  processor: "./processor.js"
- function: "generateRandomToken"
  ws:
    headers:
      x-jwt-token: "{{ token }}"

scenarios:
  - engine: "ws"
    flow:
+     - function: "generateRandomToken"
      - send: "Test message"
      - think: 30
```

**Comment by aleksandarvanced** [comment]
hey @hassy ,
Thanks for getting back to me.
The thing is that I want to have a different token per connection - which will be generated via a function
I was looking at achieving something like that with the `connect` function in artillery v2 - but i cant seem to get it working, here is an example
https://www.artillery.io/docs/reference/engines/websocket#scenario-actions-and-configuration

```
config:
  target: "ws://localhost:8080/userMessages2"
  phases:
    - duration: 1
      arrivalRate: 1
  processor: "./processor.js"
scenarios:
  - engine: "ws"
    flow:
      - connect:
          function: "connectHandler"
      - think: 5
```

`processor.js` file
```

let tokens = [
  "token1",
  "token2",
  "token3"
]

function connectHandler(params, context, next) {
  console.log(`PARAMS`)
  params.target = "ws://localhost:8080/userMessages";
  params.ws = { headers: {'x-jwt-token': `${tokens[Math.floor(Math.random() * tokens.length)]}`}};
  console.log(params);
  console.log(`AFTER PARAMS`)
  next();
}
  
module.exports = {
    connectHandler
};

```

Any idea what am I missing?

**Comment by aleksandarvanced** [comment]
Ok i managed to fix it - here is a way how i achieved it - the documentation is a little bit confusing.
`processor.js`

```
let tokens = [
  "token1",
  "token2",
  "token3"
]

function connectHandler(params, context, next) {
  params.target = "ws://localhost:8080/userMessages";
  params.options.headers= {
    'x-jwt-token': tokens[Math.floor(Math.random() * tokens.length)]
  }
  next();
}
  
module.exports = {
    connectHandler
};
```

`yml` file
```
config:
  target: "ws://localhost:8080/userMessages"
  phases:
    - duration: 1
      arrivalRate: 1
  processor: "./processor.js"

scenarios:
  - engine: "ws"
    flow:
      - connect:
          function: "connectHandler"
```
