### DISCUSSION TITLE
Add tags for each scenario

### DISCUSSION THREAD

**Discussion by ClovisWuSonos** [artilleryio/artillery#3441] [Artillery]
When I use Artillery to push metrics into DataDog, I added tags in Artillery's YAML file:

```
publish-metrics:
      - type: datadog
        apiKey: 'myapikey'
        prefix: 'artillery.publish_metrics.'
        tags:
          - 'service:authservice'
          - 'reporterType:authservice'
```

However, what I need is adding tags on each scenario, i.e. each POST or GET needs to have a different tag, so that metrics are populated to Datadogs panels with different tags on each scenario in the flow. I did not find ways to achieve this from the Docs. Is this possible to achieve? 
```
scenarios:
  - beforeRequest: attachCertificate
    flow:
      - loop:
        - post: 
            url: "https://path/token"
        - post:
            url: "https://path/docs"
        - post
        - get
```

Also, the error messages from HTTP requests are not automatically populating into DataDog by Artillery. Is there a way to send the error message metrics to DD from Artillery? 

Appreciate your help,
