### DISCUSSION TITLE
[Help] I can't see http.downloaded_bytes in Metrics when i compress api response.

### DISCUSSION THREAD

**Discussion by ChanHHOO** [artilleryio/artillery#3459] [Artillery]
Hi everyone,

I have a question about the http.downloaded_bytes metric in Artillery.

I recently conducted a test using Artillery to compare the results with and without compression in Nest.js server. 
However, when I ran the test to observe the compression results, the http.downloaded_bytes metric didn’t appear. 
Interestingly, when I tested the same scenario using curl and Postman, I was able to see the downloaded bytes.

Could anyone explain why the http.downloaded_bytes metric isn’t showing up during the compression test with Artillery?

Here’s my environment:
- Node.js: 22.13.0
- Artillery: 2.0.22
- OS: macOS
- Compression Lib : compression^1.7.5
- Framework : Nest.js

Compression Test Log
```
--------------------------------------
Metrics for period to: 01:09:50(+0900) (width: 7.348s)
--------------------------------------

http.codes.200: ................................................................ 31
http.request_rate: ............................................................. 5/sec
http.requests: ................................................................. 40
http.response_time:
  min: ......................................................................... 1340
  max: ......................................................................... 3770
  mean: ........................................................................ 2470.3
  median: ...................................................................... 2416.8
  p95: ......................................................................... 3752.7
  p99: ......................................................................... 3752.7
http.response_time.2xx:
  min: ......................................................................... 1340
  max: ......................................................................... 3770
  mean: ........................................................................ 2470.3
  median: ...................................................................... 2416.8
  p95: ......................................................................... 3752.7
  p99: ......................................................................... 3752.7
http.responses: ................................................................ 31
vusers.completed: .............................................................. 31
vusers.created: ................................................................ 40
vusers.created_by_name.0: ...................................................... 40
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 1349.8
  max: ......................................................................... 3781.2
  mean: ........................................................................ 2489.8
  median: ...................................................................... 2465.6
  p95: ......................................................................... 3752.7
  p99: ......................................................................... 3752.7
```

Without compression
```
--------------------------------------
Metrics for period to: 00:53:40(+0900) (width: 3.273s)
--------------------------------------

http.codes.200: ................................................................ 5
http.downloaded_bytes: ......................................................... 3044115
http.request_rate: ............................................................. 5/sec
http.requests: ................................................................. 20
http.response_time:
  min: ......................................................................... 2040
  max: ......................................................................... 3101
  mean: ........................................................................ 2635.4
  median: ...................................................................... 2566.3
  p95: ......................................................................... 2951.9
  p99: ......................................................................... 2951.9
http.response_time.2xx:
  min: ......................................................................... 2040
  max: ......................................................................... 3101
  mean: ........................................................................ 2635.4
  median: ...................................................................... 2566.3
  p95: ......................................................................... 2951.9
  p99: ......................................................................... 2951.9
http.responses: ................................................................ 5
vusers.completed: .............................................................. 5
vusers.created: ................................................................ 20
vusers.created_by_name.0: ...................................................... 20
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 2063.6
  max: ......................................................................... 3118.7
  mean: ........................................................................ 2654.4
  median: ...................................................................... 2618.1
  p95: ......................................................................... 2951.9
  p99: ......................................................................... 2951.9
```

Compression middleware
```
app.use(
    compression({
      level: 3, 
      threshold: 51200, 
      filter: (req, res) => {
        const acceptEncoding = req.headers['accept-encoding'];
        if (!acceptEncoding) {
          return false;
        }
        if (req.headers['x-no-compression']) {
          return false;
        }
        const contentType = res.getHeader('Content-Type');
        if (contentType && /^(image|video)\//.test(contentType)) {
          return false;
        }
        return compression.filter(req, res);
      },
    }),
  );
```
scenario.yml

```
config:
  target: 'http://localhost:4000'
  phases:
    - duration: 10 
      arrivalRate: 5
  tls:
    rejectUnauthorized: false
  defaults:
    headers:
      Authorization: 'Bearer ${token}'
      Cache-Control: 'no-cache'
      User-Agent: 'Chrome/87.0.4280.88'
      Accept: 'application/json'
      Accept-Encoding: 'gzip, deflate, br'
      Connection: 'keep-alive'

scenarios:
  - flow:
      - get:
          url: '/api'
```

If you need any extra information, please tell me. 
Thank you.
