### DISCUSSION TITLE
What is the correct way to log?

### DISCUSSION THREAD

**Discussion by AdamCKWVersa** [artilleryio/artillery#3462] [Artillery]
Hi, I'm currently trying to learn how to do load testing with artillery and am currently unsure if log is working as intended. I'm seeing inconsistent behavior with `log` statements in my Artillery scenario. Here's my current config:

```yaml
scenarios:
  - flow:
      - log: "Log 1: Starting Request"
      - get:
          log: "Request completed"
          url: "/dino"
          capture:
            - json: "$"
              as: "dino"
      - log: "Log 2: Request End"
```

While "Log 1: Starting Request" appears in the output, "Log 2: Request End" doesn't show up. Even if I removed `Log 1`, `Log 2` will still not be shown. It only worked if placed at the start of the flow.
