### DISCUSSION TITLE
Is it possible to have multiple scenarios running sequentially in 1 test?

### DISCUSSION THREAD

**Discussion by timwy6** [artilleryio/artillery#3467] [Artillery]
Hi, We have 12 Artillery tests, and each can be configured with 4 different test data setups, leading to around 50 tests in total. We run these tests sequentially on Artillery Cloud with AWS Fargate. Each test run takes a little over 10 minutes, but with the added Fargate provisioning time and data setup, completing all 50 tests takes over 10 hours.

To address this, we are exploring the possibility of combining 4 tests into a single test, that's basically running 4 distinct scenarios sequentially within one test execution, each scenario will be run 10 mins with 1 RPS at a time, then move to next scenario. We would also like to use the `beforeScenario` hook to set up the test data before each scenario.

Ideally, we would structure our test configuration similarly to this:

```
scenarios:
  - name: "Scenario 1"
    beforeScenario: ["setupScenario1"]
    flow:
      - get:
          url: "/api/data"
    phases:
      - duration: 600
        arrivalRate: 1

  - name: "Scenario 2"
    beforeScenario: ["setupScenario2"]		
    flow:
      - get:
          url: "/api/data"
    phases:
      - duration: 600
        arrivalRate: 1

  - name: "Scenario 3"
    beforeScenario: ["setupScenario3"]		
    flow:
      - get:
          url: "/api/data"
    phases:
      - duration: 600
        arrivalRate: 1

  - name: "Scenario 4"
    beforeScenario: ["setupScenario4"]		
    flow:
      - get:
          url: "/api/data"
    phases:
      - duration: 600
        arrivalRate: 1        

```
Could you please advise if this type of sequential scenario execution within a single test is possible? This approach would significantly simplify our testing process by reducing the number of test runs to 12 and would also allow us to reduce the test data setup/teardown overhead, and crucially, reduce Fargate provisioning times.
