### DISCUSSION TITLE
Running Artillery Playwright Tests with Artillery GitHub Action

### DISCUSSION THREAD

**Discussion by viktorgagaleski** [artilleryio/artillery#3475] [Artillery]
Hello, I am trying to setup Artillery Playwright tests with GitHub Actions. My setup uses the artillery cli action but the test run fails with error complaining that playwright is not installed.

```
Test run id: t9gez_m4b63knehgrehhpf974qhfmm77nzn_xrha
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

browserType.launch: Executable doesn't exist at /github/home/.cache/ms-playwright/chromium-1148/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at scenario (/home/node/artillery/node_modules/artillery-engine-playwright/index.js:154:55)
    at /home/node/artillery/node_modules/@artilleryio/int-core/lib/runner.js:5[40](https://github.com/collibra/frontend/actions/runs/13286126732/job/37095113653#step:11:41):5
    at handleScriptHook (/home/node/artillery/node_modules/@artilleryio/int-core/lib/runner.js:519:10)
    at PlatformLocal.runHook (/home/node/artillery/lib/platform/local/index.js:159:31)
    at async PlatformLocal.init (/home/node/artillery/lib/platform/local/index.js:77:25)
    at async PlatformLocal.startJob (/home/node/artillery/lib/platform/local/index.js:30:5)
    at async Launcher.run (/home/node/artillery/lib/launch-platform.js:[41](https://github.com/collibra/frontend/actions/runs/13286126732/job/37095113653#step:11:42)5:5) {
  name: 'Error'
}
```

For the job in GitHub actions I used the PW docker image and I would expect PW to be installed there as that is how we use it for our other workflows as well and we don't have to install anything additionally

```
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
```

I even tried the following, but without success:

```
      - name: Install Playwright Browsers
        run: npx playwright install && npx playwright install chromium

      - name: Run Playwright Tests Performance
        uses: artilleryio/action-cli@v1
        with:
          command: run test.perf.test --environment test
          working-directory: ./apps/shell
        env:
          BASE_URL: ${{ inputs.url || env.BASE_URL }}
```

Any ideas on what might be missing? Should I switch to using ubuntu and then install artillery there?

**Comment by viktorgagaleski** [comment]
@hassy any directions on what would be the best approach? I managed to get it working by using:

image:
    name: artilleryio/artillery:latest
    
I had to also install PW, but the image complains that there are a lot of missing PW browser libraries.. I think the artillery docs are also lacking documentation on Artillery + Playwright runs

**Reply by hassy** [reply]
Will look into it @viktorgagaleski. Playwright tests *should* just work in the most recent image (`artilleryio/artillery`) as of the most recent CLI release - if you had to install Playwright again that's probably a bug we need to fix.

**Comment by viktorgagaleski** [comment]
For someone else that stumbled upon this, here is the setup that worked for me:

```
run-artillery:
    if: always()
    timeout-minutes: 60
    container:
      image: artilleryio/artillery:latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium --only-shell

      - name: Run Playwright Tests Performance
        uses: artilleryio/action-cli@v1
        with:
          command: run example.test.ts
          working-directory: ./apps/shell
```
