### DISCUSSION TITLE
Execute custom function after each scenario

### DISCUSSION THREAD

**Discussion by mrcsmchll** [artilleryio/artillery#3506] [Artillery]
Im trying to execute a custom function which creates and sends a slack report based on some specific metrics from the `.json` report but Im not able to execute once the scenario has finished and output a report. What Im doing is running this in a docker container:
```
artillery run -c artillery/configs/stage-config.yml artillery/api/my-scenario.yml --output artillery/outputs/report.json
```
My `stage-config.yml` looks something like this:
```
config:
  target: https://api-stage.mystage.org
  
  phases:
    - duration: 2
      arrivalRate: 5
      rampTo: 10
      name: Warm up the API

  processor: "./slackReport.js"

  defaults:
    headers:
      Content-Type: "application/json"
      Accept: "application/json"

  plugins:
    ensure: {}
    apdex:
      threshold: 4000
    metrics-by-endpoint: {}

      
  ensure:
    thresholds:
      - http.response_time.p99: 4000
      - http.response_time.p95: 2000
    maxDuration: 300 # 10 minutes 
```
And I'm calling the function `pepe()` defined in `slackReport.js` in `my-scenario.yml` that looks like this:
```
scenarios:
  - flow:
    - loop:
      - get:
          url: '/frontend/event/'
      count: 1
    afterResponse: 'pepe'
```
Its the only way I managed to execute the function but its executing multiple times since its inside the loop. The desired output is to execute the function only once after the scenario has finished. Using `- function` or `afterScenario` didnt execute the function or yielded the same result. Could someone please help me understand what Im doing wrong ?

**Comment by manfromanotherland** [comment]
Hi @mrcsmchll, I’m not sure how to do this using a custom processor, but you can use the [Slack plugin](https://www.artillery.io/docs/reference/extensions/slack) to send a message once the test is finished. Just update your config to include the `slack` plugin:

```yml
config:
  target: https://api-stage.mystage.org
  
  # rest of your config…

  plugins:
    ensure:
      thresholds:
        - http.response_time.p99: 4000
        - http.response_time.p95: 2000
      maxDuration: 300 # 10 minutes 
    apdex:
      threshold: 4000
    metrics-by-endpoint: {}
    # Add with your Slack webhook URL
    slack:
      webhookUrl: "https://hooks.slack.com/services/..."
```

The message will look similar to this:

![Slack message](https://github.com/user-attachments/assets/1d7c5098-5891-40e2-8ad4-f23fa4fd78e5)

Note: the **“See report on Artillery Cloud”** button only shows if you’re using [Artillery Cloud](https://app.artillery.io/login)!

Hope this helps!

**Reply by mrcsmchll** [reply]
Any way you know where I can make the slack plugin only report the failed tests or when for example one or more of the checks in place fails? Right now it will always send a report regardless if failed or pass

**Reply by mrcsmchll** [reply]
Another thing I noticed is that the slack plugin doesn't inform the scenario name so if I run this in my CI/CD with Jenkins I'll have a bunch of reports that I cant tell from which scenario it is. Unless of course I use the Artillery Cloud which is not something we are looking into using right now

**Comment by hassy** [comment]
The JSON file is only created after Artillery is finished running all virtual users, so if you need access to the entire output from the test run you'll need to run your script as a separate process that reads the JSON file. For example the results of the `ensure` checks are only available once all VUs have run, and won't be available during the execution of the test.

`afterScenario` should work with something like this:

```yaml
scenarios:
  - afterScenario: pepe
    flow:
      - loop:
        - get:
            url: '/frontend/event/'
        count: 1
```

The signature of an afterScenario hook function is different to an afterResponse hook - you can see them here: https://www.artillery.io/docs/reference/engines/http#loading-custom-code
