### DISCUSSION TITLE
SocketIO load test always timesout

### DISCUSSION THREAD

**Discussion by manthan55** [artilleryio/artillery#935] [Artillery]
Hi,

I have a Nodejs SocketIO server hosted in a Kubernetes cluster with 2 pods and I want to load test the same.

However, with the artillery test script below, I always get timeout errors.

socket-connect.yaml
```
config:
  target: "http://localhost:3001/"
  # target: "https://my-server.azurewebsites.net/"
  # target: "http://my-server-k8s-loadbalancer.com/"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 2
      arrivalRate: 2
scenarios:
  - name: Try to connect
    engine: socketio
    flow:
        - emit:
            channel: "join_chat_room"
            data:
                username: user-{{ $randomString() }}
        - think: 60
```

The result
```
Started phase 0, duration: 1s @ 19:19:39(+0530) 2021-02-23
Report @ 19:19:49(+0530) 2021-02-23
Elapsed time: 10 seconds
  Scenarios launched:  2
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN

Report @ 19:19:59(+0530) 2021-02-23
Elapsed time: 20 seconds
  Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN

Report @ 19:20:01(+0530) 2021-02-23
Elapsed time: 21 seconds
  Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Errors:
    timeout: 2

All virtual users finished
Summary report @ 19:20:01(+0530) 2021-02-23
  Scenarios launched:  2
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    Try to connect: 2 (100%)
  Errors:
    timeout: 2
```

I also have the same server running locally (localhost:3000) & on an Azure App Service and I am able to connect to all 3 hosted servers via a simple ReactJS client. Although, I always get timeout error regardless of either of the targets.

Server code

```
io.on("connection", (socket) => {
  console.log(`User connected : ${socket.id}`);
 
  socket.on("join_chat_room", (data) => {
    console.log("Joining room")
    socket.username = data.username;

    socket.broadcast.emit('user joined', {
      username: socket.username,
    });

  })
 
  socket.on("disconnect", (data) => {
    console.log(`User disconnected : ${socket.id}`);

    socket.broadcast.emit('user left', {
        username: socket.username
      });
  });
});
```

Any help would be really appreciated.
