### DISCUSSION TITLE
Best way to load test live HLS

### DISCUSSION THREAD

**Discussion by danroot** [artilleryio/artillery#939] [Artillery]
We would like to load test several always-on live HLS streams at once.  As best I can find, the documents all describe load testing a "on demand" style HLS stream.  I'm new to artillery, so not 100% sure I'm reading the output correctly.  When I attempt load testing a "live" always-on stream, the .m3u8 request completes, but it's not clear to me where to set how long  each user views the stream. 

Is there a way to test, for example "600 users watching these two streams for 10 minutes each"?

```
config:
  target: 'https://video.company.com'
  phases:
      - duration: 10
        arrivalRate: 1
  plugins:
    hls: {}
      
scenarios:
  - flow:
    - get:
        url: "/some.stream/playlist.m3u8"
        hls:
          concurrency: 2
          streamSelector:
            resolution:
              width: 720
              height: 480
    - get:
        url: "/some_other.stream/playlist.m3u8"
        hls:
          concurrency: 2
          streamSelector:
            resolution:
              width: 720
              height: 480
```

Output:

```
All virtual users finished
Summary report @ 22:58:31(-0600) 2021-03-01
  Scenarios launched:  10
  Scenarios completed: 10
  Requests completed:  20
  Mean response/sec: 0.44
  Response time (msec):
    min: 492.5
    max: 10677.3
    median: 2370.4
    p95: 9166.6
    p99: 10677.3
  Scenario counts:
    0: 10 (100%)
  Codes:
    200: 20
  HLS: segment download time:
    min: 2846
    max: 24564
    median: 12914
    p95: 24479
    p99: 24564
  HLS: stream download time:
    min: 0
    max: 31618
    median: 7358.5
    p95: 30839.5
    p99: 31618
  HLS: stream download started: 20
  HLS: segment download started: 30
  HLS: segment download completed: 30
  HLS: stream download completed: 20
```
