### DISCUSSION TITLE
Using a 'before' hook to get the access token gives an error

### DISCUSSION THREAD

**Discussion by savitanagaraj** [artilleryio/artillery#962] [Artillery]
I am trying to get the access token in the before section, before running actual scenarios that will use the access token. Here is my code snippet. It is worth noting though that the `before` block works fine with json files.
```
config:
  target: 'https://url1'
  phases:
   - name: "Default"
     duration: 1
     arrivalRate: 2
  payload:
    - path: "userlogin.csv"
      fields:
        - user1
        - user2
        - password1
        - password2
      order: "sequence"
before:
 - flow:
    #Get bearer token
   - log: "Getting token"
   - post:
      url: "https://url2/oauth2/v2.0/token"
      json:
       username: 'XXXX'
       password: 'XXXX'
       grant_type: 'password'
       client_id: '12345'
       client_secret: 'abcde'
       scope: 'openid
      capture:
       json: "$.id_token"
       as: "id_token"
      expect:
        - statusCode: 200
scenarios:
 - flow:
   - get:
       url: "url3"
       headers:
         authorization: 'Bearer {{id_token}}'
         user-login: "XXXX"
         user-role: "admin"
```

But I see the following error when I run my code in DEBUG mode:

 ```
 $ DEBUG=http:response artillery run Get_Token.yml
- TypeError: Cannot read property 'concat' of undefined
    at HttpEngine.createScenario (C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\core\lib\engine_http.js:91:23)
    at C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\core\lib\runner.js:511:37
    at new Promise (<anonymous>)
    at handleBeforeRequests (C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\core\lib\runner.js:501:10)
    at runner (C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\core\lib\runner.js:132:25)
    at Runner.run (C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\lib\runner-sp.js:60:3)
    at done (C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\lib\commands\run.js:191:14)
    at C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\node_modules\async\lib\async.js:52:16
    at C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\node_modules\async\lib\async.js:1209:30
    at done (C:\Users\snagaraj\AppData\Roaming\nvm\v12.20.1\node_modules\artillery\lib\commands\run.js:267:14)
 ```
 
Am I doing something wrong? Missing something?

**Comment by hassy** [comment]
hi @savitanagaraj👋 the contents of `config.before` should be an object rather than a list i.e.:

```yaml
before:
  flow: # <======== here, it's now an object
    #Get bearer token
   - log: "Getting token"
   - post:
      url: "https://url2/oauth2/v2.0/token"
      json:
       username: 'XXXX'
       password: 'XXXX'
       grant_type: 'password'
       client_id: '12345'
       client_secret: 'abcde'
       scope: 'openid
      capture:
       json: "$.id_token"
       as: "id_token"
      expect:
        - statusCode: 200
```

That should make it work :)
