### ISSUE TITLE
Can't use big payload files - ERR_STRING_TOO_LONG

### ISSUE THREAD

**Issue by A-styler** [artilleryio/artillery#1003]
I wanted to test our system with 3.5kk user agents (0.5GB CSV file), but have saw this error:

```
node:buffer:594
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at Object.readFileSync (node:fs:445:41)
    at readPayloadFile (/usr/local/lib/node_modules/artillery/lib/commands/run.js:248:21)
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:355:9)
    at Object.map (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:337:20)
    at readPayload (/usr/local/lib/node_modules/artillery/lib/commands/run.js:245:9)
    at fn (/usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34) {
  code: 'ERR_STRING_TOO_LONG'
}
```

node:15.14.0-alpine3.10
artillery@1.6.2
via docker

```
config:
  target: http://localhost
  phases:
    - duration: 600
      arrivalRate: 10
  payload:
    - path: "/data/useragent.csv"
      fields:
        - "useragent"

scenarios:
  - flow:
    - log: "{{useragent}}"

**Comment by hassy** [comment]
hi @A-styler - this is a limitation in Node.js itself (https://nodejs.org/api/errors.html#errors_err_string_too_long). To work around it, you could split the CSV file into two and load them separately:

```yaml
payload:
    - path: "/data/useragent1.csv"
      fields:
        - "useragent1"
    - path: "/data/useragent2.csv"
      fields:
        - "useragent2"
```

**Comment by A-styler** [comment]
@hassy Do you mean I just need to duplicate my requests? Like
```
  - flow:
    - get:
        url: "/"
        headers:
          User-Agent: "{{ useragent1 }}"
    - get:
        url: "/"
        headers:
          User-Agent: "{{ useragent2 }}"
```
or with looping
```
- flow:
  - loop:
      - get:
           url: "/"
           headers:
             User-Agent: "{{ $loopElement }}"
    over:
      - "{{ useragent1 }}"
      - "{{ useragent2 }}"
    
```
