### ISSUE TITLE
Log messages not working with ws engine

### ISSUE THREAD

**Issue by drewpushlive** [artilleryio/artillery#1021]
I'm not able to log anything using the websocket engine.

Given this test:
```
config:
  target: "wss://echo.websocket.org" # for example
  phases:
    - duration: 1
      arrivalRate: 1

scenarios:
  - name: Test log
    engine: ws
    flow:
      - log: "Hello"
      - send: 'some data' # for example
```

I get this response:
```
PS C:\Development\git\load-tests> artillery run .\tests\websocket.yml
Started phase 0, duration: 1s @ 19:12:09(+0100) 2021-05-06
| C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\core\lib\engine_ws.js:74
      payload = payload.toString();
                        ^

TypeError: Cannot read property 'toString' of undefined
    at f (C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\core\lib\engine_ws.js:74:25)
    at fn (C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:746:34)
    at C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:1213:16
    at C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:166:37
    at C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:706:43
    at C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:167:37
    at C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:1209:30
    at WebSocket.<anonymous> (C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\core\lib\engine_ws.js:119:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.setSocket (C:\Users\Drew\AppData\Roaming\npm\node_modules\artillery\node_modules\ws\lib\websocket.js:151:10)
```

If I remove the log line the rest of the test runs fine.

Am I formatting the test incorrectly, or is this not supported? Happy to be pointed at some documentation.
