### ISSUE TITLE
Version 1.7.0 Breaks Boolean Capture

### ISSUE THREAD

**Issue by RohanNagar** [artilleryio/artillery#1027]
I have this step that uses the artillery expect plugin and passes in version 1.6.2, but fails in 1.7.0.

```
- post:
        url: '/verify/reset?email=success@simulator.amazonses.com'
        headers:
          password: 5f4dcc3b5aa765d61d8327deb882cf99
        auth:
          user: application
          pass: secret
        capture:
          - json: $.email.address
            as: email
          - json: $.email.verified
            as: verified
        expect:
          - statusCode: 200
          - hasProperty: creationTime
          - hasProperty: lastUpdateTime
          - equals:
              - "{{ email }}"
              - "success@simulator.amazonses.com"
          - equals:
              - "{{ verified }}"
              - false
```

It's failing with this error:

```
not ok equals true, false
  expected: all values to be equal
       got: true, false
  Request params:
    http://localhost:8080/verify/reset?email=success@simulator.amazonses.com
    ""
  Headers:
   date : Wed, 12 May 2021 22:33:46 GMT
   content-type : application/json
   content-length : 254
  Body:
    "{\"email\":{\"address\":\"success@simulator.amazonses.com\",\"verified\":false,\"verificationToken\":null},\"password\":\"5f4dcc3b5aa765d61d8327deb882cf99\",\"attributes\":[\"hello\",\"world\"],\"creationTime\":1620858825642,\"uniqueID\":\"ABC123\",\"lastUpdateTime\":1620858826475}"
  User variables:
     target : http://localhost:8080
     $environment : undefined
     testMetrics : false
     $uuid : ccc8885d-e7d1-4038-b533-1b1f83083dcb
     email : success@simulator.amazonses.com
     creationOriginal : 1620858825642
     errorString : Unable to validate user with provided credentials. (User: success@simulator.amazonses.com)
     creationGet : 1620858825642
     verificationToken : c7bebcfc-89cd-4a98-91bb-343587572a8e
     verified : true
```

It looks like the capture here is not working correctly:

```
- json: $.email.verified
  as: verified
```

Because the JSON body has `verified` set to false, but artillery thinks it is set to true.
