### ISSUE TITLE
--quiet cli option is not working

### ISSUE THREAD

**Issue by xyngfei** [artilleryio/artillery#1028]
Followed the [guide](https://artillery.io/docs/guides/guides/command-line.html), when I run with the following quiet option
`artillery run --quiet demo.yml`

demo.yml
```
config:
  target: "https://example.com"
  plugins:
    expect: {}
  phases:
    - name: "ramp up"  
      duration: 30
      rampTo: 5
      arrivalRate: 1
scenarios:
  - name: "test demo site"
    flow:
      - post:
          url: "/api"
          capture:
            - json: "$.success"
              as: success
            - json: "$.errors"
              as: errors
          expect:
            - statusCode: 404
```

I only expect to see the summary standard output at end of the test

Why I can see the following outcome during test execution, any idea?
* POST /api 
  ok statusCode 404 
* POST /api 
  ok statusCode 404
