### ISSUE TITLE
HTTP authorization before socket.io connection

### ISSUE THREAD

**Issue by Dissfall** [artilleryio/artillery#1029]
Hi! Im trying test my API and in my case I should receive authorization token by HTTP request and then use the token to open socket.io connection. As I see, now I can provide query data only in config section means before my HTTP authorization request.

May be there is any way how I can produce authorization before open socket.io connection?

**Comment by flentini** [comment]
Hi @Dissfall , 
you could use a [before](https://artillery.io/docs/guides/guides/test-script-reference.html#The-before-and-after-sections) section in your scenario to fetch the token, and then use it when you connect to socket.io:

```
config:
  target: "http://localhost:3000"
  phases:
    - duration: 1
      arrivalRate: 1

before:
  flow:
    - log: "fetch auth token"
    - get:
        url: "/auth"
        capture:
          - json: "$.token"
            as: token

scenarios:
  - name: emit events
    engine: socketio
    socketio:
      extraHeaders:
        authorization: "Bearer {{ token }}"
    flow:
      - emit:
          channel: "test"
          data: "hello"
```

the "socketio" section in your scenario will allow you to pass additional headers
