### ISSUE TITLE
artillery-plugin-expect could not be found

### ISSUE THREAD

**Issue by y-melo** [artilleryio/artillery#1032]
I'm trying to use expect property. but I'm getting Module not found for artillery-plugin-expect

```sh
run config/test.yml
.   WARNING: Plugin expect specified, but module artillery-plugin-expect could not be found (MODULE_NOT_FOUND)
```

Plugin Config:
```yml
config:
  target: "https://server.com"
  plugins:
    expect: {}
```

Then in scenarios I'm using: flow.post.expect.statusCode = 201. ( I removed uncessary line)
```yml
scenarios:
  - flow:
      - post:
          expect:
            - statusCode: 200
```

The run works fine, I get 200 back, but if I set it to `statusCode=201`, it ignores the 'expect' statement.

```sh
node --version
v14.17.0

 npm list -g
/usr/local/node/lib
├── artillery-plugin-expect@1.3.0
├── artillery@1.7.2
└── npm@7.13.0

npm list
/opt/artillery/
└── (empty)
```
