### ISSUE TITLE
Matching false always succeed

### ISSUE THREAD

**Issue by mkadirtan** [artilleryio/artillery#1040]
I am trying to use socketio engine with artillery. My custom scenario requires acknowledge to be of type `{ status: false, data: ... }`. Even though socketio server replies with `{ status: true }`, no error is thrown. Same applies for all the falsy values of javascript.

```yaml
config:
  target: "http://localhost:3000/"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 1
      arrivalRate: 4
      maxVusers: 4

scenarios:
  - name: Test
    flow:
      - emit:
          channel: "custom_event"
          data: "{}"
          acknowledge:
            match:
              json: "$.0.status"
              value: false
```
