### ISSUE TITLE
Setting cookies does not work on the current request

### ISSUE THREAD

**Issue by kevinpione** [artilleryio/artillery#1056]
I am attempting to set a session cookie for all virtual users as part of a scenario. The issue I am running into is that when attempting to set a cookie, it doesn't set it for the current request, but sets it for all requests after the current request. 

Additionally, this means the website is setting its own session cookie on the initial request, and then on subsequent requests there are two session cookies (the one I've told it to set, and the one assigned by the website). Here is some example YAML showing the issue on google:

```
config:
  target: "https://google.co.uk"
  phases:
    - duration: 1
      arrivalRate: 1
      name: Warm up

scenarios:
   - name: "RunTest"
     flow: 
       - get:
           url: "/imghp"
           cookie:
             CustomCookie: "1234" # Does not set the cookie on this request
       - get:
           url: "/imghp" # Cookie gets set on this request
           
```
 
I also attempted to use the beforeRequest function, and when logging the cookies here, I can see my set cookie here, but it doesn't get sent with the request for some reason.
 
 Is there a good reason why the cookie doesn't get set on the same request you set it on? This is not how I expected it to function.
 
 Thanks,
 
 Kevin
