### ISSUE TITLE
Requests are multiplicated when POST and redirect is used

### ISSUE THREAD

**Issue by ambrosmiroslav** [artilleryio/artillery#1057]
I have a simple scenario:

```
config:
  target: "http://localhost:8080"
  phases:
    - duration: 1
      arrivalRate: 1
      name: Warm up
      maxVusers: 1

scenarios:
  - name: "Login"
    flow:
      - get:
          url: "/login"
      - post:
          url: "/login"
          form:
            username: "John Doe"
      - get:
          url: "/list"
```

which accesses my local HTTP server written in node.js:

```
var http = require("http");

http.createServer(function (req, res) {
  console.info("Request: " + req.url + ", " + req.method);

  switch(req.url)
  {
    case "/login":
      if (req.method === "GET") {
        res.writeHead(200, { "Content-Type": "text/html" });
        res.write("Login page <form action='/login' method='post'><input name='username'><input type='submit'></form>");
      } else {
        res.writeHead(303, { "Location": "/user" });  
      }
      break;
    case "/user":
      res.write("User page");
      break;
    case "/list":
      res.write("List page");
      break;
    default:
      res.write("Wrong page");
      break;
  }

  res.end(); //end the response
}).listen(8080); //the server object listens on port 8080
```

This setup tries to simulate user login.
The first GET request to /login displays HTML form.
Then form submission with POST creates request to /login, the server accepts username and redirects client to /user.
And finally user clicks to show some data with /list.

So there should be 4 requests in total (3x GET + 1x POST; the redirect is GET because the "303 See Other" is used).
But my HTTP server reports 5 requests - the /list is doubled...

And funny thing - if I repeat the "-post" section in my scenario then I get more and more superfluous /list requests. :-)
If I repeat my "-post" section four times I end up with 16 requests to /list... :-)

It seems like a new virtual user is created each time POST + redirect is processed and this new virtual user tries to finish started scenario?
