### ISSUE TITLE
Possible to use variables in json path capture? 

### ISSUE THREAD

**Issue by leduyminh48** [artilleryio/artillery#1058]
I have a get request and want to capture a value that match a context variable, is it possible? I tried this but it doesnt seem to work
```yaml
          - get:
              url: "/task/{{$loopElement.id}}"
              qs:
                relations: "[\"comments\"]"
              headers:
                Authorization: "Bearer {{STOKEN}}"
              capture:
                json: "$.comments[?(@['comment']==\"{{commentStr}}\")]"
                as: "capturedComment"

```
