### ISSUE TITLE
Typing error in "log" line causes the scenario is interrupted with no message

### ISSUE THREAD

**Issue by ambrosmiroslav** [artilleryio/artillery#1076]
I made a typo in "log" line in my scenario, see complete example:

```
config:
  target: "http://localhost:5000"
  phases:
    - duration: 1
      arrivalRate: 1
      maxVusers: 1

scenarios:
  - name: "Demo"
    flow:
      - log: "Good line."
      - log "Bad line."
      - log: "Another good line."
```

Only `Good line.` is displayed when the scenario is launched.
The scenario execution is interrupted and no error or warning is displayed (and exit code seems to be 0).
Not sure if the .yml file should by considered as corrupted due to a missing colon?
