### ISSUE TITLE
Artillery-pro  not running test script based on setup

### ISSUE THREAD

**Issue by bruno-salapic** [artilleryio/artillery#1080]
Hello Artillery,

I seem to be running into an issue. So I have a config file that looks like so

```
config:
  target: "HTTP://somewebsite"
  processor: ./processor.js
  phases:
    - duration: 1800
      arrivalCount: 1750
      name: WarmUp
  payload:
      path: ./accounts.csv
      fields:
        - email
        - password
  variables:
    numberofResourceSelections: 3
    minArrivalDate: "06/22/2021"
    maxArrivalDate: "06/25/2021"
```

and then I run it using the latest version or artillery-pro 
![image](https://user-images.githubusercontent.com/84862823/122439125-5d5fb080-cf69-11eb-85a5-99500ee5bf0e.png)

everything boots up as usual but the script ends really prematurely.

![image](https://user-images.githubusercontent.com/84862823/122438907-30130280-cf69-11eb-9158-fbb0f734f365.png)

I haven't tried it on the artillery-pro older version yet but something I have noticed on the latest release

EDIT:

So this only seems to be happening when I'm using a config file. if I set the desired values inside the test and don't use the --config flag the test runs the proper duration and amount of users I told It to,

yea seems to be the config-file it just hangs and spits out the "Final result" as if its done. 

to test this I copied the config at the top of the test script and place in new file and called it using the --config flag

**Comment by hassy** [comment]
Thanks for the detailed issue report @bruno-salapic! Has this just started happening on the latest version of Artillery Pro?

Are you running a test script directly, or is this a pre-packaged test (created with `artillery create-test` command)?

**Comment by bruno-salapic** [comment]
Well, I've tried installing older packages as well and running the same commands and it seems to be happening on both.
![image](https://user-images.githubusercontent.com/84862823/122552259-15419c00-d004-11eb-8540-bc2ea4d80c97.png)

This is also me running a test script directly I wrote not the pre-packaged-test

**Comment by hassy** [comment]
OK thank you, very curious. What does the `phases` section look like in the main script? I'm wondering if there's something funky going on with how they might be getting merged between the main script and the separate config.

**Comment by bruno-salapic** [comment]
so the main script looks like so 
```
config:
  target: 'https://uri/api'
  processor: "./BaseProcessor.js"
  phases:
    - duration: 1800
      arrivalCount: 2750
      name: "WarmUp"
    #order: "sequence"
  variables:
    numberofResourceSelections: 3
    preferredCultureName: "en-CA"
    minArrivalDate: "06/24/2021" # MM/DD/YYYY
    maxArrivalDate: "06/27/2021" # MM/DD/YYYY
```
and then config is 
```
config:
  target: https://uri/api
  processor: "./BaseProcessor.js"
  phases:
    - duration: 30
      arrivalCount: 20
      name: "WarmUp"
  payload:
    path: "./accounts.csv"
    fields:
        - "email"
        - "password"
    #order: "sequence"
  variables:
    numberofResourceSelections: 3
    preferredCultureName: "en-CA"
    minArrivalDate: 04/29/2021
    maxArrivalDate: 04/30/2021
```
