### ISSUE TITLE
Running a custom connection before scenarios

### ISSUE THREAD

**Issue by hsabillon7** [artilleryio/artillery#1087]
We have a custom client that's in charge of the connection to the services (opening and closing the connection). It's there a way to make the connection with this client and passes the function to each scenario? The only way I make it work it's opening/closing the client on each test but that makes it slower and seems like it reaches some kind of limits with 300 seconds or more. Have used ```before``` but only captures values, not functions. My test is something like this:

```
 config:
  target: "ws://localhost:8888"
  processor: "./myFunctions"
  phases:
    - duration: 10
      arrivalRate: 5
      name: Warm up

before:
  flow:
    - function: "openClient"

scenarios:
  - name: "Testing the connection"
    flow:
      - function: "customTest"
```

The custom function with the opening/closing for each test
```
const {CustomClient} = require("CustomClient");

module.exports = { customTest };

async function customTest(context, events, next) {
  const client = new CustomClient();

  try {
    await client.open(); // Could be share for all tests instead of opening/closing peer request?
    await client.sendData("some data");
  } catch (err) {
    console.log(err);
  } finally {
    await client.close();
  }

  return next();
}
```
