### ISSUE TITLE
Assert response body properties directly in artillery-plugin-expect

### ISSUE THREAD

**Issue by elton-okawa** [artilleryio/artillery#1089]
Greetings everyone 👋 

I'd be nice if we could compare object properties directly instead of extracting response and then comparing it.

### Nowadays
From docs, we need to use `capture` to extract the value to a variable and then compare it using `equals`. It works, but if we want to compare multiple object values, it might become verbose.
```
- get:
    url: "/dog/1"
    capture:
      - json: "$.age"
        as: age
      - json: "$.name"
        as: name
      - json: "$.nickname"
        as: nickname
    expect:
      - equals: ["{{ age }}", 5]
      - equals: ["{{ name }}", "scooby"]
      - equals: ["{{ nickname }}", "sb"]
```

### Feature proposal
We could have a new expectation function called `propertyEquals` that does a similar job of capture and equals using a positional syntax: `propertyEquals [<pathToProperty>, <expected>]`
```
- get:
    url: "/dog/1"
    expect:
      - propertyEquals: ["$.age", 5]
      - propertyEquals: ["$.name", "scooby"]
      - propertyEquals: ["$.nickname", "sb"]
```

After discussion and approval, I'd like to try to implement it.
