### ISSUE TITLE
Assert variables and object's properties types in artillery-plugin-expect

### ISSUE THREAD

**Issue by elton-okawa** [artilleryio/artillery#1092]
Greetings everyone 👋

**Use case**: Sometimes we don't need to check its content or we don't know the response value but we'd like to guarantee its type, such as randomly generated ids or string messages.
I'd be nice if we could assert variables and object's properties types.

### Feature Proposal
We could have a new expectation function called `typeOf` that receive a variable or object path and assert its type using the following syntax: `type: [<variable or path>, <expectedType>]`.
This method would assume that if it starts with `$` it's a path, else a variable.
```
- get:
    url: "/dog/1"
    capture:
      - json: "$.age"
        as: age
    expect:
      - typeOf: ["{{ age }}", "number"]
      - typeOf: ["$.name", "string"]
      - typeOf: ["$.owner", "object"]
```

I'm not so sure about the positional argument and using `$` to identify path or variables, it might be better if we receive an object but it can become verbose:
```
- get:
    url: "/dog/1"
    capture:
      - json: "$.age"
        as: age
    expect:
      - typeOf:
           value: "{{ age }}"
           type: "number"
      - typeOf:
           path: "$.name"
           type: "string"
      - typeOf: 
           path: "$.owner"
           type: "object"
```
