### ISSUE TITLE
Update wss Target To Include Query String

### ISSUE THREAD

**Issue by vakil-neelin** [artilleryio/artillery#1098]
For my application, in order to open a web socket the target needs to provide an id and access token from login as a query string. I can currently get the access token and save it to a variable using capture and the id is a variable from the csv. I have a `afterResponse` function running which appends the token to the target and I can see the updated value in the logs, but the scenario still uses the base target from the config. 

I have tried a few different methods to accomplish this task and none have consistently worked. I was able to get the target updated by using a `beforeScenario` but it is not consistent. If I run the same code multiple times, the function only runs for some cases but not all.

I am looking for a consistent method to append the access token to the target so the web socket can connect.

I am running the most recent dev version:
artillery/2.0.0-dev3 linux-x64 node-v16.3.0

YAML Code
```
config:
  target: "wss://XXXX"
  plugins:
    expect: {}
    metrics-by-endpoint: {}
  processor: "./testing-functions.js"
  phases:
    - duration: 1
      arrivalRate: 1
      name: "Single User Web Socket Client Testing"
  payload:
    # path is relative to the location of the test script
    path: "users.csv"
    skipHeader: true
    skipEmptyLines: true
    order: sequence
    fields:
      - "username"
      - "password"
      - "install_id"
  variables:
    web_host: "XXXX"

before:
  flow:
    # Log The User In
    - post:
        url: "{{web_host}}/login"
        beforeRequest: "encryptPassword"
        # afterResponse: "myAfterResponseHandler"
        json:
          grant_type: "password"
          username: "{{username}}"
          password: "{{encrypted_password}}"
        capture:
          json: "$.access_token"
          as: "access_token"
        expect:
          - statusCode: 200
          - contentType: application/json
          - hasProperty: access_token

scenarios:
  - beforeScenario: "updateClientParameters"
  - engine: ws
    name: Ping Pong
    flow:
      - send: "ping"
        expect:
          - matchesRegexp: "pong"

after:
  flow:
    # Log The User Out
    - post:
        url: "{{web_host}}/logout"
        headers:
          Authorization: "{{access_token}}"
        expect:
          - statusCode: 200
```

`beforeScenario` Code
```
function updateClientParameters(context, ee, next) {
  context.vars['target'] = context.vars['target'] + '?id=' + context.vars['install_id'] + '&access-token=' + context.vars['access_token'];
  console.log(context.vars['target']);
  return next();
}
```

`afterResponse` Code
```

function myAfterResponseHandler(requestParams, response, context, ee, next) {
  context.vars['target'] = context.vars['target'] + '?id=' + context.vars['install_id'] + '&access-token=' + context.vars['access_token'];
  console.log(context.vars['target']);
  return next();
}
```
If have the `beforeScenario` commented out and the `afterResponse` uncommented, then the log will show the target change but it will always fail.
If have the `beforeScenario` uncommented out and the `afterResponse` commented, then the function will only be run sometimes and the scenario will work.
