### ISSUE TITLE
artillery-plugin-expect does not support application/problem+json

### ISSUE THREAD

**Issue by elton-okawa** [artilleryio/artillery#1114]
Greetings everyone 👋 

### Description

There is a standardized content type called `application/problem+json` to describe any error thrown by an API, basically it still returns a json if an error occurred.

Because it's still a json, I'd be nice to handle it the same way as `application/json`, parsing its body to an object allowing us to use existent assertions.

More info:
* [Medium post by Sander](https://lakitna.medium.com/understanding-problem-json-adf68e5cf1f8)
* [RFC7807](https://datatracker.ietf.org/doc/html/rfc7807)

### Example 

API response
```
Content-type: application/problem+json

{
  "type": "https://example.com/pets/1",
  "title": "Pet not found",
  "detail": "Pet with id '1' not found",
  "status": 404,
}
```

Expectations:
```
- get:
     url: "/pets/1"
     expect:
       status: 404
       contentType: json
       hasProperty: type
```

After discussion and approval, I'd like to implement it 😄
