### ISSUE TITLE
Basic auth encodingURI before base64

### ISSUE THREAD

**Issue by andrei-cdl** [artilleryio/artillery#1144]
Unsure why this is the case that I'm experiencing, however with the following config for basic `auth`

```
config:
  target: '#'
  phases:
    - name: 'Warm up'
      duration: 1
      arrivalRate: 1
  processor: '../../helper.js'

# Defines the scenario to create a test user
scenarios:
  - flow:
      - log: 'generating new users'
      - post:
          url: '/user'
          beforeRequest:
            - 'set_new_user_body'
          capture:
            - json: '$.id'
              as: 'user_id'
            - json: '$.email'
              as: 'email'

      # user e-mail is created  
      # make sure to decodeURIComponent the user - weird bug.
      - log: 'starting user auth token retrival {{ email }}, {{ user_id }}'
      - get:
          url: '/user/auth'
          auth:
            user: '{{email}}'
            pass: '#'
          capture:
            - json: '$.token'
              as: 'token'
```

the issue is that the header sent will have the following operations applied to it.

* encodeURIComponent()
* base64()

This results in symbols being parsed (@ for example) and not having the correct email value being sent to the server to be decoded using just base64.
