### ISSUE TITLE
reportviewer webpage throws error on file load

### ISSUE THREAD

**Issue by oleg-koval** [artilleryio/artillery#1178]
https://reportviewer.artillery.io/ is throwing an error about not valid JSON for such kind of phase result and heavier:

```
      phases:
        # lasts 60 seconds, 10 new virtual users will be created every second.
        - duration: 60
          arrivalRate: 5
          maxVusers: 10
          name: Warm up
```

for small output works fine, like 

```
      phases:
        - duration: 10
          arrivalRate: 1
          maxVusers: 2
          name: Warm up
```

artillery version v2.0.0-2
