### ISSUE TITLE
`TypeError: done is not a function` when writing custom artilary extension

### ISSUE THREAD

**Issue by Mohamedemad4** [artilleryio/artillery#1182]
Info:
```
------------ Version Info ------------
Artillery: 1.7.9
Artillery Pro: not installed (https://artillery.io/pro)
Node.js: v16.9.1
OS: linux/x64
```
In my use case I want artillery to fetch a list of resources and execute an expensive operation on one of them randomly 

something like:
```

config:
  target: "https://api.backend.com"
  processor: "./artilleryHelpers.js"
  plugins:
    metrics-by-endpoint: {}
    hls: {}

  phases:
    - duration: 1
      arrivalRate: 1
      name: Warm up

- get:
    url: "/api/resources"
    capture:
      json: "$.resources"  
      as: "resources"
- function: "pickResourceRandomly"
- get:
    url: "/api/do/expensive/op/{{ resourceID }}"
```

and the code for that function looks something like:
```
function pickResourceRandomly(req, res, context, events, done) {
    req.vars.resourceID = randomly_pick_resource()
    done()
}
```
Now this is very much according to [official extension docs](https://artillery.io/docs/guides/guides/extending.html)
but i was getting this error:
`TypeError: done is not a function`
I was able to solve it by changing  `(req, res, context, events, done)` to `(req, res, done)`.
Is the documentation outdated? or is this some weird edge case?
