### ISSUE TITLE
Cannot read property 'capture' of null

### ISSUE THREAD

**Issue by morrikim** [artilleryio/artillery#1185]
I wrote the floowing, but the following issue still occurs. 

```yaml
before:
  flow: 
    - post:
        url: "/login"
        json:
          userEmail: "eamil@email.com"
          password: "password"
        capture:
          - json: "$.token"
            as: "token"
```

/usr/local/lib/node_modules/artillery/lib/commands/run.js:350
        (params.capture && params.capture.xpath) ||
                ^

TypeError: Cannot read property 'capture' of null

**Comment by morrikim** [comment]
hi @hassy, here is my my artillery version . 

Artillery: 1.7.9
Artillery Pro: not installed (https://artillery.io/pro)
Node.js: v12.10.0
OS: darwin/x64

**Comment by deviscreen** [comment]
when i wrote just one post then no problem. but i wrote addionaly get flow then issue occure.

**Comment by morrikim** [comment]
hi @hassy Thanks for your comment. 
here is my entire script .
I'd appreciate it if you could let me know what went wrong.

```yaml
config:
  target: "http://localhost:8080"
  phases:
    - duration: 1
      arrivalRate: 1
      name: Warm Up
  processor: "./login.js" 
        
scenarios:
  - name: "login test"
    flow:
      - post:
          url: "/login"
          json:
            userEmail: "morriskim@email.com"
            password: "qwer1234"
          capture:
            - json: "$.token"
              as: "token"
          beforeRequest:
            - "beforeRequestHandler"
          afterResponse:
            - "afterResponseHandler"
      - get:
        url: "/check"
        headers:
          auth: "{{token}}"
```

**Comment by hassy** [comment]
hi @morrikim - there should be an extra level of indentation on those `get` requests, e.g.:

```yaml
      - get:
          url: "/check"
          headers:
            auth: "{{token}}"
```

instead of:

```yaml
      - get:
        url: "/check"
        headers:
          auth: "{{token}}"
```
