### ISSUE TITLE
documentation updates: add more description about using pauses - "think"

### ISSUE THREAD

**Issue by savvagen** [artilleryio/artillery#1192]
Please add more description to the chapter: https://artillery.io/docs/guides/guides/http-reference.html#Pausing-execution-with-think
Describe how to execute think time less than 1 second, like:
```
- flow:
      - get:
          url: "/"
      - think: 0.5  # equvalent to 500 milliseconds
```
