### ISSUE TITLE
time information not shown in report html

### ISSUE THREAD

**Issue by dominikstohl** [artilleryio/artillery#1253]
Hello,
I have a bug, that time information are not shown in the report html.

I use the flag ```extendedMetrics: true``` in config, run the script and then generate the report.

In the report.json the time stuff is listed.

Minimal reproducable test:
```
# test.yml
config:
  target: 'https://www.google.com'
  http:
    extendedMetrics: true
  phases:
    - duration: 10
      arrivalRate: 1
      maxVusers: 1
scenarios:
  - flow:
      - get:
          url: '/'
```

```artillery run -o report.json ./test.yml```
```artillery report report.json```

The report is the following:
![Screenshot 2021-12-03 at 13-32-16 Artillery report](https://user-images.githubusercontent.com/40791087/144610785-1a95c96a-d566-4744-86d0-9a23c66d9597.png)

The output on the console is showing the information:
![image](https://user-images.githubusercontent.com/40791087/144610990-4ada1df3-4878-4b8a-86d5-f2d3cb1622af.png)

Artillery Version: artillery/2.0.0-6 win32-x64 node-v14.18.1
