### ISSUE TITLE
arrivalCount is not working as expected

### ISSUE THREAD

**Issue by BernhardMaier** [artilleryio/artillery#1265]
hi@all,

i'm using the `arrivalCount` to simulate a fixed amount of users in a defined duration, like the documentation says (https://www.artillery.io/docs/guides/guides/test-script-reference#fixed-number-of-arrivals-per-second)

The load test i want to simulate requires the usage of `arrivalCount`, because `arrivalRate` creates at least one user per second.

For exmaple this should generate 10 users over 5 minutes:
```
  phases:
    - name: '10 user in 5 minutes (1 user every 30 seconds)'
      duration: 300
      arrivalCount: 10
```

But at the end, only three users were created:
```
vusers.created_by_name.S5: .................................. 1
vusers.created.total: ....................................... 3
vusers.completed: ........................................... 3
vusers.created_by_name.S6: .................................. 2
```

Another thing i recognized is the slow start when using `arrivalCount`. It needs up to two minutes before the first request is sent.

This leads to the questions:
- Do i expect the wrong behaviour?
- Can this depend on the scenarios i implemented?
- Is there something wrong in my implementations?
- Could this just be a bug in artillery?

**Comment by BernhardMaier** [comment]
Another thing i recognized this morning while running a Artillery test in a Azure Devops pipeline:
![grafik](https://user-images.githubusercontent.com/46556453/146499883-ff62b52f-f5d6-4e55-a0b6-1b8fd64c61f6.png)
- Starting the phase at `06:25:35` (1)
- Metrics for first period at `06:27:50` (2)
- No output between (1) and (2)
- Failed user in first metrics output (3)

Can this be related to the use of `arrivalCount`?

**Comment by BernhardMaier** [comment]
It seems that the `arrivalCount` works fine on longer runs:
```
All VUs finished. Total time: 1 hour, 1 minute, 44 seconds

--------------------------------
Summary report @ 07:27:19(+0000)
--------------------------------

vusers.created_by_name.S5: .................................. 16
vusers.created.total: ....................................... 28
vusers.failed: .............................................. 1
vusers.completed: ........................................... 27
vusers.created_by_name.S6: .................................. 3
vusers.created_by_name.S7: .................................. 3
vusers.created_by_name.S3: .................................. 1
vusers.created_by_name.S0: .................................. 3
vusers.created_by_name.S4: .................................. 1
vusers.created_by_name.S2: .................................. 1
vusers.session_length:
  min: ...................................................... 26922.3
  max: ...................................................... 159529.3
  median: ................................................... 103811.8
  p95: ...................................................... 108048.6
  p99: ...................................................... 114730.2
http.request_rate: .......................................... 1/sec
http.requests: .............................................. 706
http.codes.503: ............................................. 1
http.responses: ............................................. 706
http.codes.200: ............................................. 427
http.codes.201: ............................................. 278
http.response_time:
  min: ...................................................... 35
  max: ...................................................... 14090
  median: ................................................... 77.5
  p95: ...................................................... 5826.9
  p99: ...................................................... 6187.2
```

So, maybe my small tests were just to short to work fine. I'll close the issue and if anyone else can contribute information on how to use "arrivalRate", I would be very happy to hear about it.

**Comment by hassy** [comment]
hi @BernhardMaier 👋 thank you for a very detailed bug report (I would love it if every bug report we get for Artillery was that detailed!)

I'm going to reopen the issue as it does look like there's an issue in the first report you shared - we'd expect `vusers.created.total` to equal 10.

**Comment by hassy** [comment]
The results of the second run you posted look OK. 

There's no output between (1) and (2) because Artillery didn't generate any VUs in that time period. As soon as one VU was created (some time between 06:27:40 and 06:27:50) and some metrics were generated, we got a report.

The VU is reported as failed because there was a 503 code returned for a request, i.e. it did not complete its scenario successfully.

Hope that makes sense!

**Comment by BernhardMaier** [comment]
Good Morning @hassy,

thank you for the nice reply. I do my best to provide as much information as i can 😁 I just double checked the output of the Azure DevOps pipeline and it seems that the output  in the screenshot was only incomplete at the first look. Reloading the output shows the "missing" failed user:
![grafik](https://user-images.githubusercontent.com/46556453/146513586-5cbe5483-2f82-43ff-90ab-133e5f583dfe.png)
The 503 error seems to be caused by the cold start of the Azure Function where the API is running on.

The phase used for this run was:
```
  phases:
    - name: 'Max 3 parallel users with 28 scenarios in 10 hours'
      duration: 3600
      arrivalCount: 28
      maxVusers: 3
```

You can ignore the `10 hours` in the name, i just forgot to update it after changing duration from `36000` (10h) to `3600` (1h).

Something that is differen to the runs yesterday is the usage of `maxVusers`, that wasn't set in the short test runs.
