### ISSUE TITLE
before section executes multiple times in artillery/2.0.0-5 linux-x64 node-v14.18.0

### ISSUE THREAD

**Issue by savvagen** [artilleryio/artillery#1277]
My demo scenario sample:

``` 
config:
  target: "http://localhost:3001"
  phases:
    - duration: 20
      arrivalCount: 4
      name: "My Load Stage"
  ensure:
    maxErrorRate: 1
  http:
    timeout: 60
    extendedMetrics: true
  processor: "../processors/main.js"
  variables:
    commentsNumber: 2
  payload:
    path: "./../data/people.csv"
    fields:
      - "userId"
      - "userName"
      - "userEmail"
    order: sequence  # sequence # random
    skipHeader: true
  defaults:
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  plugins:
    expect:
      outputFormat: pretty # silent / pretty / prettyError
    metrics-by-endpoint:
      useOnlyRequestNames: true
    statsd: # https://github.com/artilleryio/artillery-plugin-statsd
      host: "localhost"
      port: 8125
      # Prefix Format: "artillery.<SCENARIO_NAME>.<CONFIG_NAME>"
      # Set: "artillery.statsd_plugin" when publishing metrics to Datadog (using agent)
      prefix: "artillery.system.load"

before:
  flow:
    - log: "Starting Json-Server benchmarking."

scenarios:
  - name: Post Writer Scenario
    weight: 1
    flow:
      - log: "Found user {{ userId }} {{ userName }}"
```

The actual output:
```
⠏ Starting Json-Server benchmarking.
Starting Json-Server benchmarking.
Starting Json-Server benchmarking.
⠋ Starting Json-Server benchmarking.
Phase started: My Load Stage (index: 0, duration: 20s) 12:08:28(+0200)

```

The expected output:
```
⠏ Starting Json-Server benchmarking.
Phase started: My Load Stage (index: 0, duration: 20s) 12:08:28(+0200)

```
`before:` flow should be executed ones per test session
