### ISSUE TITLE
Load testing with Artillery 

### ISSUE THREAD

**Issue by YaphetKG** [artilleryio/artillery#1284]
I was using a very simple artillery config 
```
config:
  target: "{{ $processEnvironment.SERVER_URL }}"
  http:
    timeout: 60
  ensure:
    maxErrorRate: 1
    p95: 2
  phases:
    - duration: 15
      arrivalRate: 10000
  plugins:
    expect: {}
scenarios:
  - flow:
# test normalized nodes post
      - get:
          url: "/docs"
  ```
But after running the test I get a lot of errors 

<html>
<body>

EADDRNOTAVAIL | 51942
-- | --

</body>
</html>

In the report html artillery outputs.
