### ISSUE TITLE
test crushes while running artillery-2.0.0-10 with plugin

### ISSUE THREAD

**Issue by savvagen** [artilleryio/artillery#1290]
### Environment:
* linux-x64 
* node-v14.18.0

### Preconditions:
Plugin script: 
```

const debug = require('debug')('plugin:my-plugin');

module.exports = { Plugin: MyPlugin }

function MyPlugin(script, events) {
    this.script = script;
    this.events = events;
    const self = this;

    // Create processor object if needed to hold our custom function:
    script.config.processor = script.config.processor || {};

    script.config.processor.printEndpointMetrics = printEndpointMetrics

    script.scenarios.forEach((scenario) => {
        scenario.afterResponse = scenario.afterResponse || [];
        scenario.afterResponse.push('printEndpointMetrics');
    });

    return this;
}

function printEndpointMetrics(req, res, userContext, events, next) {
    const metricName = `${userContext.vars.statsdPrefix}.plugins.endpoint_metrics.${req.name}`
    debug(metricName)
    debug(req.url)
    debug(req.name)
    return next();
}
```

Test script:
```
config:
  target: "http://localhost:3001"
  phases:
    - duration: 120
      arrivalCount: 60
      name: "My Load Stage"
  processor: "../processors/main.js"
  defaults:
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  plugins:
    expect: {}
    metrics-by-endpoint:
      useOnlyRequestNames: true
    my-plugin: {}

scenarios:
  - name: Post Writer Scenario
    weight: 1
    flow:
      - post:
          url: "/users"
          name: "POST/users"
          headers:
            Authorization: "Bearer {{ token }}"
          expect:
            - statusCode: 201
            - hasProperty: id
          beforeRequest: "userBody"
          afterResponse: "saveUserId"
```

Artillery throws an error while running the script:
command:
```
 ARTILLERY_PLUGIN_PATH=`pwd`/src/plugins/ DEBUG=plugin:my-plugin artillery run src/scenarios/system.yaml
```

error:
```
(node:118325) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'printEndpointMetrics' on string '../processors/main.js'
    at new ArtilleryDatadogAdvancedMetricsPlugin (/home/user/WebstormProjects/artillery-poc-project/src/plugins/artillery-plugin-datadog-advanced-metrics/index.js:75:50)
    at Launcher.initPlugins (/usr/lib/node_modules/artillery/lib/launch-local.js:111:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Launcher.run (/usr/lib/node_modules/artillery/lib/launch-local.js:217:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:118325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:118325) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The main reason why it fails, I gues, that in artillery@2.0.0  plugin variable `script.config.processor` is String but not object where we can assign new functions
