### ISSUE TITLE
Sending header with a … char throws invalid char

### ISSUE THREAD

**Issue by nervetattoo** [artilleryio/artillery#1298]
Using auth0 generated tokens and trying to send them as a bearer token failed. I narrowed it down to the `…` character causing the issue.
Easily replicated:

```yaml
config:
  target: https://google.com/
  phases:
    - duration: 1
      arrivalRate: 1
  variables:
    token: …
scenarios:
  - name: Fail
    flow:
      - log: "{{ token }}"
      - get:
          url: "/"
          headers:
            authorization: "{{ token }}"
```

Removing the header and everything works again. Logging the token works.
