### ISSUE TITLE
Parsing properties from array responses is failing for hasProperty

### ISSUE THREAD

**Issue by Schachte** [artilleryio/artillery#1312]
I'm trying to parse an array from my response.

```
          json:
            input:
              - "input data"
          capture:
            json: "$"
            as: "result"
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: "result[0].input"
            - equals:
                - "input data"
                - "{{ result[0].input }}"
      - log: "result is {{ result }}"
```

The `equals` block is passing, however, the `hasProperty` block I can't get working with arrays. 
This example in the docs doesn't work properly for me:

```
expect:
  - hasProperty: 'data[0].id'
```
