### ISSUE TITLE
form does not seem to include anything in the body

### ISSUE THREAD

**Issue by jamesjmclaren** [artilleryio/artillery#1331]
```
scenarios:
  - flow:
      - log: "getting token"
      - post:
          url: "/....."
          headers:
            Content-Type: "application/x-www-form-urlencoded"
          form:
            grant_type: "password"
            response_type: "token"
            username: "Username"
            password: "password1234"
            client_id: "api"
            client_sercret: "clientsecret123"
          expect:
            - statusCode: 200
```

When I view the http request I do not see any body, only the header. If I change `form `to `json` then the body is populated but I do not want json.

Request:

```
url": "https://.......com",
  "method": "POST",
  "headers": {
    "user-agent": "Artillery (https://artillery.io)",
    "content-type": "application/x-www-form-urlencoded"
```
