### ISSUE TITLE
unhandled promise rejection on Before and After sections

### ISSUE THREAD

**Issue by robinComa** [artilleryio/artillery#1348]
Hello,

Requests on the before and after section have unhandled promise rejection.
When the request is in timeout for exemple the subprocess don't stop correclty.

Here an exemple : 
``` yml
config:
  ...
  http:
    timeout: 10
 ...
before:
  beforeScenario: "useDate"
  flow:
    - log: "* GET /api/auth/login"
    - post:
        url: "/api/auth/login"
        json:
          login: "{{login}}"
          password: "{{password}}"
        capture:
          - json: $.token
            as: "token"
    - log: "Bearer token : {{token}}"
after:
  flow:
    - log: "* DELETE /api/auth/logout"
    - delete:
        url: "/api/auth/logout"
scenarios:
  - flow:
    - get:
        url: "/"
        headers:
          authorization: "Bearer {{ token }}"
        expect:
          - statusCode: 200
``` 

Sometimes the login or logout is in timeout (or something wrong, status >= 400) and the process stop with this log : 
`To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict`

All process is stopped, and artillery don't run anymore.

PS : the expect plugin seems not working on before and after section

Versions : 
- **node** : v14.17.6
- **npm** : 6.14.15
- **artillery** : 2.0.0-11
- **artillery-plugin-expect** : 2.0.0-3
