### ISSUE TITLE
Artillery Resending The Same Requests

### ISSUE THREAD

**Issue by dooleyb1** [artilleryio/artillery#1357]
Hi there, I'm experiencing an issue with artillery whereby in a test sample of a random amount of users, requests are sent multiple times for the same virtual user. What I'm expecting in the below example is 360 unique `uid`'s to be taken from the `load-testing-users.csv` file and for the flow within the scenario to be sent 360 times for each unique `uid` taken from the  `load-testing-users.csv` file. 

In the scenario below users are not able to start & submit answers to a survey multiple times so this is why I am seeing the error crop up. There are no duplicates within the `load-testing-users.csv` file. 

From the logs on my API I can see 2 x requests to `/surveys/start` & 2 x requests to `/answers/submit` for the effected users. What I'm imagining happening is that artillery is not choosing a unique `uid` from this CSV file each time. 

```yml
config:
  target: "http://localhost:1337"

  http:
      # Responses have to be sent within 10 seconds, or an `ETIMEDOUT` error gets raised.
      timeout: 30

  phases:
    - duration: 60       # 60 second load phase
      arrivalRate: 6      # 6 new virtual users arriving every second on average
                                  # 60 * 6 = 360 virtual users over one minute
  defaults:
    headers:
      Content-Type: application/json
    
  payload:
    # Path is relative to the location of the test script
    path: "load-testing-users.csv"
    fields:
      - "uid"

  plugins:
    expect: {}


scenarios:
  - flow:
      # Step 1 - Start Survey
      - post:
          url: "/surveys/start"
          json:
            surveyId: "WA5ng4AMkmHiLoh0i8lA"
            uid: "{{ uid }}"
          expect:
            - statusCode: 200

      # Step 4 - Finish Survey
      - post:
          url: "/answers/submit"
          json:
            surveyId: "WA5ng4AMkmHiLoh0i8lA"
            response:
              {
                "answers":
                  {
                    "100000": "Sokog turwih devnab gow uvkow."
                  },
                "timeSubmitted": "2022-03-01T14:04:40.308Z",
                "timeToComplete": 33005,
                "uid": "{{ uid }}",
              }
          expect:
            - statusCode: 200
```

### Examples

1. First Request to `/answers/submit`

```
1:58:33 PM NETWORK 127.0.0.1 - - [02/Mar/2022:13:58:33 +0000] "POST /answers/submit HTTP/1.1" - - "-" "got (https://github.com/sindresorhus/got)" request {"surveyId":"WA5ng4AMkmHiLoh0i8lA","response":{"answers":{"100000":"Sokog turwih devnab gow uvkow."},"timeSubmitted":"2022-03-01T14:04:40.308Z","timeToComplete":33005,"uid":"2o1iZ8n7WzORcMmUqO1F"}}
```

2. Second Request to `/answers/submit`

```
1:58:02 PM NETWORK 127.0.0.1 - - [02/Mar/2022:13:58:02 +0000] "POST /answers/submit HTTP/1.1" - - "-" "got (https://github.com/sindresorhus/got)" request {"surveyId":"WA5ng4AMkmHiLoh0i8lA","response":{"answers":{"100000":"Sokog turwih devnab gow uvkow."},"timeSubmitted":"2022-03-01T14:04:40.308Z","timeToComplete":33005,"uid":"2o1iZ8n7WzORcMmUqO1F"}}
```
