### ISSUE TITLE
Processor file global variable not updated in "after" or "before" hooks

### ISSUE THREAD

**Issue by fabiohaertel** [artilleryio/artillery#1360]
Hi.

I'm trying to understand what is happening here.

When I create a global variable the processor JS file, I can update it inside the "afterResponse" hook without any problems.

    let mySum = 1000;
    function afterResponse(requestParams, response, context, ee, next) {
          mySum++;
          console.log("# afterResponse: mySum = ", mySum);
          return next();
    }

When I try to access the variable's value inside the "after" or "before" hooks, it's not updated, it still returns the initial value.

    function afterAll(context, ee, next) {
       console.log("# afterAll: mySum = ", mySum); // prints 1000
       return next();
    }

I don't know how artillery works here, is it instantiating a new processor file for the 'after' and 'before' hooks?
I just need to call a function when the whole test is finished so I can print my global variable which holds results based on the response data.

I was able to set up a quick test scenario:

````
config:
  target: "https://www.google.com"
  processor: "./processor.js"
  timeout: 10
  http:
    pool: 200
  phases:
    - duration: 5
      arrivalRate: 1
      name: Run Test

scenarios:
  - name: Test Global Variable
    flow:
      - get:
          afterResponse: "afterResponse"
          url: "/"

before:
  flow:
    - function: "beforeAll"

after:
  flow:
    - function: "afterAll"
````

Processor code:

````
let mySum = 1000;

module.exports = {
  afterResponse,
  beforeAll,
  afterAll,
};

function afterResponse(requestParams, response, context, ee, next) {
  mySum++;
  console.log("# afterResponse: mySum = ", mySum);
  return next();
}

function beforeAll(context, ee, next) {
  console.log("# beforeAll: mySum = ", mySum);
  return next();
}

function afterAll(context, ee, next) {
  console.log("# afterAll: mySum = ", mySum);
  return next();
}

````

Output:

````
# beforeAll: mySum =  1000
# afterResponse: mySum =  1001
# afterResponse: mySum =  1002
# afterResponse: mySum =  1003
# afterResponse: mySum =  1004
# afterResponse: mySum =  1005
# afterAll: mySum =  1000
````

Can anybody point me to the right direction?
Thank you!
