### ISSUE TITLE
JSONPath does not support Pipes

### ISSUE THREAD

**Issue by InsOpDe** [artilleryio/artillery#1406]
Trying to capture a value inside an array with JSONPath

Version info: 1.7.9
```
1.7.9
```

Running this command: 
```
artillery run tests/load.yml
```

I expected to see this happen:

log should output: 
```
    Auth user{"id":"8dc62968-5ea8-4358-bd5d-1781aa61372a","mailAddress":"Jerald.Farrell@hotmail.com","name":"Leonardo45","roles":[{"roleName":"user"},{"roleName":"ruler","value":"ff84685b-2305-4169-a3ff-258eefed76e3"}]} - rulerId: ff84685b-2305-4169-a3ff-258eefed76e3
```

Instead, this happened:

log output: nothing inside rulerId
```
    Auth user{"id":"8dc62968-5ea8-4358-bd5d-1781aa61372a","mailAddress":"Jerald.Farrell@hotmail.com","name":"Leonardo45","roles":[{"roleName":"user"},{"roleName":"ruler","value":"ff84685b-2305-4169-a3ff-258eefed76e3"}]} - rulerId: 
```

log didn't output anything.

Files being used:
```
config:
  target: "http://localhost:8078"
  processor: "../dist/processor/index.js"
  plugins:
    # Both requires atillery v2 and only works for http
#    metrics-by-endpoint: {}
#    expect: {}
  engines:
    socketio: {}
  phases:
    - duration: 1
      arrivalRate: 1
scenarios:
  - name: "Register"
    engine: socketio
    flow:
      - function: "generateRandomUser"
      - emit:
          channel: "command"
          data:
            correlationId: 1
            route: "/UserController/authenticate"
            payload:
              - "{{ newUser }}"
          response:
            channel: "command"
            capture:
              - json: "$.payload"
                as: "user"
              - json: '$.payload.roles[] | select(.roleName == "ruler") | .value'
                as: "rulerId"
      - log: "rulerId:{{ rulerId }}"
```

**additional info:**

```
echo '{"id":"8dc62968-5ea8-4358-bd5d-1781aa61372a","mailAddress":"Jerald.Farrell@hotmail.com","name":"Leonardo45","roles":[{"roleName":"user"},{"roleName":"ruler","value":"ff84685b-2305-4169-a3ff-258eefed76e3"}]}' | jq '.roles[] | select(.roleName == "ruler") |.value'
```
puts out `ff84685b-2305-4169-a3ff-258eefed76e3`
