### ISSUE TITLE
Update documentation of GitLab CI

### ISSUE THREAD

**Issue by khaledismaeel** [artilleryio/artillery#1418]
The official [`GitLab CI/CD` integration documentation page](https://www.artillery.io/docs/guides/integration-guides/gitlab-ci-cd) lists the following code snippet as a sample `/gitlab-ci.yml` file:

``` yaml
artillery:
  image:
    name: artilleryio/artillery:latest
    entrypoint: [""]
  script: |
    mkdir reports
    /home/node/artillery/bin/artillery run --output reports/report.json tests/performance/socket-io.yml
    /home/node/artillery/bin/artillery report --output reports/report reports/report.json
  artifacts:
    paths:
      - reports
```

This job will actually fail as [this](https://github.com/artilleryio/artillery/pull/1345) PR changed the executable name from `artillery` to `run`. The documentation should therefore be updated.
