### ISSUE TITLE
Setting cookies has no effect

### ISSUE THREAD

**Issue by MickL** [artilleryio/artillery#1420]
Version info: `2.0.0-14`

Setting cookies seem to have no effect. I dont receive any cookies in the incoming request on my Express server.

I tried using yaml:

```
scenarios:
  - name: "my scenario"
    flow:
      - post:
          url: /my-endpoint
          cookie:
            hello: 'world'
```

And also using beforeRequest:

```
export const beforeHandler: AsyncRequestInterceptor = async (
  request: ArtilleryRequest,
  context: ScenarioContext,
  ee: events.EventEmitter,
  next: Next
) => {
   request.cookie = {
     'hello': 'world'
   };

   return next();
}
```
