### ISSUE TITLE
Parallel requests not working

### ISSUE THREAD

**Issue by Thibobbs** [artilleryio/artillery#1436]
Hello,
I'm trying to make parallel requests with artillery and I saw that this feature is supposed to be supported (not in the doc though).
Unfortunately, it doesn't seem to do anything different than normal request behaviour.

Version info: 
```
Artillery Core: 2.0.0-15
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v14.18.3
OS:      linux
```

This is my yml file : 
```
config:
  target: "xxx"
  http:
    timeout: 360
  variables:
    token: "xxx"

scenarios:
  - flow:
      - parallel:
          - get:
              headers:
                Authorization: "Bearer {{ token }}"
              url: "/api/xxx1"
          - get:
              headers:
                Authorization: "Bearer {{ token }}"
              url: "/api/xxx2"
          - get:
              headers:
                Authorization: "Bearer {{ token }}"
              url: "/api/xxx3"
          - get:
              headers:
                Authorization: "Bearer {{ token }}"
              url: "/api/xxx4"

```

I was expecting to have a vusers.session_length similar to the max http.response_time. But here are the logs :

```
All VUs finished. Total time: 11 seconds

--------------------------------
Summary report @ 16:54:16(+0200)
--------------------------------

http.codes.200: ................................................................ 4
http.request_rate: ............................................................. 1/sec
http.requests: ................................................................. 4
http.response_time:
  min: ......................................................................... 2142
  max: ......................................................................... 2478
  median: ...................................................................... 2276.1
  p95: ......................................................................... 2276.1
  p99: ......................................................................... 2276.1
http.responses: ................................................................ 4
vusers.completed: .............................................................. 1
vusers.created: ................................................................ 1
vusers.created_by_name.0: ...................................................... 1
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 9337.7
  max: ......................................................................... 9337.7
  median: ...................................................................... 9416.8
  p95: ......................................................................... 9416.8
  p99: ......................................................................... 9416.8
```

As you can see, artillery seems to trigger the requests sequencially instead of being parallelized. I have little to no difference when I remove "parallel" from the flow.

Thank you in advance.
