### ISSUE TITLE
Concurrent users chart missing on reports

### ISSUE THREAD

**Issue by akhiljay** [artilleryio/artillery#1447]
I am unable to see the chart that shows concurrent users connected to the service I am testing against. 

Version info: 
```
Artillery Core: 2.0.0-16
Artillery Pro:  3.0.0-9

Node.js: v18.0.0
OS:      darwin
```

Running this command: 
```
artillery report result4.json
```

I expected to see this happen:

*A concurrent users chart within the HTML generated report*

Instead, this happened:

*I see vusers created and completed chart*

Files being used:
```
config:
    target: "wss://localhost:8888/ws"
    phases:
      - duration: 30
        arrivalRate: 10
        maxVusers: 500
        name: "Warming up"
      - duration: 30
        arrivalRate: 10
        maxVusers: 1000
        name: "Max load"
scenarios:
  - engine: "ws"
    flow:
      - send: "hello"
      - think: 1
      - send: "how are you?"
```
