### ISSUE TITLE
Ability to hit each row in payload one time?

### ISSUE THREAD

**Issue by mjclemente** [artilleryio/artillery#1458]
First, thanks for this awesome project - truly impressive and extremely useful. 

I'm new to it, and I've read the docs and looked through the issues, but I can't find anything related to this.

I'm running a smoke test and I'd like to make one request for each element in my payload csv to ensure that they are loading correctly. Here's what I'm starting with:

```yaml
config:
  target: 'https://testing.test-domain.dev'
  plugins:
    expect: {}
  payload:
    path: 'tests.csv'
    order: sequence
    fields:
      - 'uri'
      - 'name'
  tls:
    rejectUnauthorized: false

before:
  flow:
    - log: 'Reinit'
    - get:
        url: '/?reload=true'

scenarios:
  - name: Check Response
    flow:
      - get:
          name: Retrieve Response
          url: '{{ uri }}'
          auth:
            user: '{{ $processEnvironment.user }}'
            pass: '{{ $processEnvironment.pass }}'
          capture:
            - json: $['name']
              as: name
          expect:
            - statusCode: 200
```

When I run this, only the first `uri` in my payload is run.

I can get them all to run if I add a `phases` key, but then I need to limit the VU to 1 and try to define a duration that enables every `uri` to get tested once, but not multiple times.

Am I configuring this wrong, or is there no way to simply run each element in the payload one time?

Thanks again for the amazing tool!
