### ISSUE TITLE
Not able to execute sample github actions from your website

### ISSUE THREAD

**Issue by alexgocariq** [artilleryio/artillery#1475]
Version info: 
```
should be latest based on workflow



```

Running this command: 
```
Run /home/node/artillery/bin/artillery run -e echo$ENV --output reports/report.json tests/performance/pump-auth.yml
```

I expected to see this happen:

triggger the test

Instead, this happened:

Run /home/node/artillery/bin/artillery run -e echo$ENV --output reports/report.json tests/performance/pump-auth.yml
/__w/_temp/107e[4](https://github.com/org/performance-test/runs/6779650809?check_suite_focus=true#step:6:5)d1e-4bbb-4777-b6f2-9962617[5](https://github.com/org/performance-test/runs/6779650809?check_suite_focus=true#step:6:6)d164.sh: line 1: /home/node/artillery/bin/artillery: not found
Error: Process completed with exit code 127.

Files being used:
```
name: Artillery Socket.IO Load Test

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        description: Pick your target env
        required: true
        options:
          - dev
          - int
          - staging
          - prod
          - playground
      test-file:
        type: choice
        description: File which holds your test configuration
        required: true
        options:
          - pump-auth
      thread-count:
        description: 'Max thread count in test'
        required: false
        default: '10'
      iter-count:
        description: 'How many time execute flow'
        required: false
        default: '10'

jobs:
  artillery:
    runs-on: ubuntu-latest

    container: artilleryio/artillery:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make reports directory
        run: mkdir reports

      - name: Set target environment
        run: export ENV=${{ github.event.inputs.target-env }}

      - name: Execute load tests
        run: /home/node/artillery/bin/artillery run -e echo$ENV --output reports/report.json tests/performance/${{ github.event.inputs.test-file }}.yml

      - name: Generate HTML report
        run: /home/node/artillery/bin/artillery report --output reports/report reports/report.json

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: artillery-test-report
          path: reports/*
#    - uses: actions/checkout@master
#    - name: Set target environment
#      run: export ENV=${{ github.event.inputs.target-env }}
#    - name: Load Test action step
#      id: load-test
#      uses: kenju/github-actions-artillery@master
#      with:
#        filepath: -e $env  tests/performance/${{ github.event.inputs.test-file }}.yml

```
