### ISSUE TITLE
Expect's plugin Assertions not carried over to Socket-IO json report

### ISSUE THREAD

**Issue by eliezercazares** [artilleryio/artillery#1486]
Version info: 
```
2.0.0-16
```

Running this command: 
```
artillery run {filepath} --output {jsonReportFilePath} && artillery report {jsonReportFilePath}
```

When running artillery for SocketIO engine v3 or any, and if you are including parameters to produce JSON report and HTML report, I expect both the .json and .html to have the Assertions of Expect plugin, but they're not there.

Our socketio app it's sending back and forth json payloads, so we can actually use Expect validations such as:
 ```
     - emit: [ "myEvent", "{{ myDynamicallyGeneratedJsonPayloadFromProcessorJSFile }}" ]
        response:
          on: "myEvent" # catching response from "server" for this event, they emit same channel name
          capture:
            json: "$.success"
            as: "myEventResponseStatus"
          expect:
            - contentType: json
            - hasProperty: success
            - equals:
              - true
              - "{{ myEventResponseStatus }}"
```

This is an API testing (HTTP) terminal output for reference, it includes expect assertions...
<img width="656" alt="image" src="https://user-images.githubusercontent.com/385539/174928319-a1cf3c01-e002-4586-b175-b82b0873b111.png">

This is a SocketIO v3 test execution output, it's missing the expect assertions:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/385539/174929356-bb868809-cdc3-4182-a9e3-303c318a2c41.png">

Test file:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/385539/174929438-80c2e5dd-e148-4a9e-b0ca-4216d117c1f3.png">

Files being used:
```
<relevant yaml/js/csv go here>
```
