### ISSUE TITLE
Error with Datadog in Docker

### ISSUE THREAD

**Issue by sterankin** [artilleryio/artillery#1489]
Version info: 
```
Docker image: artilleryio/artillery:latest
```

Running this command: 
```
docker run  --rm  --volume ${PWD}:/usr/src/app --env USERNAME=<redacted> --env PASSWORD=<redacted> --env DD_API_KEY=<redacted> artilleryio/artillery:latest run /usr/src/app/artillery-config.yml
```

I expected to see this happen:

Metric be send to Datadog US.
Note that it works fine when not using Docker.

Instead, this happened:
```
  Telemetry is on. Learn more: https://artillery.io/docs/resources/core/telemetry.html
Phase started: Load Test (index: 0, duration: 20s) 09:50:10(+0000)

/home/node/artillery/node_modules/artillery-plugin-publish-metrics/lib/datadog.js:151
        if (res.status !== 'ok') {
                ^

TypeError: Cannot read properties of null (reading 'status')
    at /home/node/artillery/node_modules/artillery-plugin-publish-metrics/lib/datadog.js:151:17
    at ClientRequest.<anonymous> (/home/node/artillery/node_modules/dogapi/lib/client.js:122:13)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Files being used:
```
config:
  target: "<redacted>"
  plugins:
    publish-metrics:
      - type: datadog
        # DD_API_KEY is an environment variable containing the API key
        apiKey: "{{$processEnvironment.DD_API_KEY}}"
        prefix: 'artillery.publish_metrics_plugin.'
        tags:
          - "testId:GET_item"
          - "reporterType:datadog-api"
        event:
          title: "GET load test"
          priority: high
          tags:
            - "testId:GET_item"
    ensure: { }
  ensure:
    thresholds:
      - http.response_time.p95: 2000
    maxErrorRate: 1
  phases:
    - duration: 20
      arrivalRate: 5
      name: Load Test
  payload:
    path: "items.csv"
    fields:
      - "item"

scenarios:
  - name: "GET test"
    flow:
      - get:
          url: "/items/{{ item }}"
          auth:
            user: "{{$processEnvironment.USERNAME}}"
            pass: "{{$processEnvironment.PASSWORD}}"
          headers:
            Content-Type: "application/json"
            Accept: "*/*"
```
