### ISSUE TITLE
Multiple requests defined in "scenarios" -> only first one sent

### ISSUE THREAD

**Issue by sd-godaddy** [artilleryio/artillery#1508]
```
MacBook Pro intel Big Sur Verson 11.6
node: v16.15.1
yarn add "express@4.18.1" "nodemon@2.0.19" "serve-index@1.9.1"
```

# Version info: 
```
VERSION INFO:

Artillery Core: 2.0.0-11
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v16.15.1
OS:      darwin
```

# Running this commands: 

prepare directory and libs

```
mkdir __test
cd __test
echo "{}" > package.json
yarn add "express@4.18.1" "nodemon@2.0.19" "serve-index@1.9.1"
```

prepare server script

```
cat <<EEE > server.js

const express = require("express");

const serveIndex = require("serve-index");

const app = express();

app.use(express.json());

app.set("json spaces", 4);

let i = 0;
app.all("/artillery/:param?", (req, res, next) => {
  let k = ++i;

  console.log(
    JSON.stringify([
      String(k).padEnd(6, " "),
      req.method,
      req.url,
      "query:",
      req.query,
      "body:",
      req.body,
    ])
  );

  res.json({
    method: req.method,
    url: req.url,
    headers: req.headers,
    query: req.query,
    body: req.body,
    params: req.params,
  });
});

app.use(
  express.static(__dirname),
  serveIndex(__dirname, {
    icons: true,
    view: "details",
  })
);

const host = "0.0.0.0";

const port = 4236;

app.listen(port, host, () => {
  console.log("\n 🌎  Server is running http://" + host + ":" + port + "\n");
});

EEE
```

then run server in one terminal and keep an eye on it

```

node node_modules/.bin/nodemon server.js

```

send test request using CURL to see response:

```

curl \
    -H "Content-type: application/json; charset=utf-8" \
    -XPOST \
    -d '{"postparam":"bodyval"}' \
    "http://0.0.0.0:4236/artillery/something?abc=def&ghi=jkl"

```

create keywords.csv

```

cat <<EEE > keywords.csv
affectionate
agitated
amazing
angry
awesome
beautiful
blissful
bold
boring
brave
busy
charming
EEE

```

create artillery config

```
cat <<EEE > artillery.yaml
config:
  target: http://0.0.0.0:4236
  phases:
    - duration: 15
      arrivalRate: 5
      name: Warm up
    - duration: 15
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 15
      arrivalRate: 50
      name: Sustained load
  payload:
    path: keywords.csv
    fields:
      - keyword
scenarios:
  - name: "Search and buy"
    flow:
      - post:
          url: "/artillery"
          json:
            first_param: "{{ keyword }}"
          capture:
            - json: "\$.body.postparam"
              as: "cap1"
      - think: 1
      - get:
          url: "/artillery/{{ cap1 }}"

EEE
```

and run artillery in another terminal

```

artillery run --output report.json artillery.yaml
artillery report report.json

```

you might also visit if that provides any help

```

http://0.0.0.0:4236/report.json.html

```

# Expected

Since I'm logging on the screen all traffic incomming to the server.js then I would expect to see second request -> the one after `think: 1`.

... but it's not there.

**That's the main issue: second request is not sent**

# Instead, this happened:

Test seems to go on like nothing happen. Where if something is wrong with config then it should crash with error message... right?
