### ISSUE TITLE
Expect Plugin Feature Request

### ISSUE THREAD

**Issue by eliezercazares** [artilleryio/artillery#1522]
Current assertions are similar to:

"expect Variable to be equal to".. i.e.

```
expect:
  - statusCode:
    - 200
    - 301
```

However, I have a scenario where the API will create an entity and return 200, but if I send the exact same request again, API will reply with custom errors, like 403 or 500 to indicate it's a duplicate request.

I am looking to do something similar to:

```
expect:
  - statusCode:
    differentThan:
      - 200
      - 301
```
