### ISSUE TITLE
Log Socket Response always displays undefined 

### ISSUE THREAD

**Issue by kusaljr** [artilleryio/artillery#1524]
``` 
config:
  target: "http://localhost:3000"
  phases:
      - duration: 5 
        arrivalRate: 1
  socketio:
      transports: ["websocket"]

scenarios:
  - name: "Emit an event"
    engine: socketio
    flow:
      - think: 1
      - emit:
          channel: "chat-message"
          data: { "msg": "fooBar2" }
          response:
            channel: "chat-message"
            capture: 
              json: "$"
              as: "res"
      - log: "{{res}}"
```
What am i doing wrong here?
