### ISSUE TITLE
Variables set with --variables should be usable in templates

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#1560]
Original discussion: https://github.com/artilleryio/artillery/discussions/1552#discussion-4271168

Reported by @zodiase, extracted from discussion above:

----
even setting the context variable values with the `--variables` option doesn't work for default cookies either.
If I use option `--variables` with `{foo: 1, bar: 2}`, and this config:
```
config:
  defaults:
    cookie:
      foo: "{{ foo }}"
scenarios:
  - name: "bar"
    flow:
      - get:
        cookie:
          bar: "{{ bar }}"
```
I would see these cookies in traffic:
```
foo: undefined
bar: 2
```
