### ISSUE TITLE
artillery playwright does not publish metrics to honeycomb

### ISSUE THREAD

**Issue by rakesh-rameshtr** [artilleryio/artillery#1561]
**Version info:** 
```

Artillery Core: 2.0.0-22
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v17.9.0
OS:      darwin


    "artillery": "2.0.0-22",
    "artillery-engine-playwright": "^0.0.6",
```

**Running this command:** 

```
 DEBUG=plugin:publish-metrics:honeycomb  npx artillery run   PlaywrightTests/specs/DMP/PerfTesting/config/hello-world.yml
```

**YAML File** 
```
config:
  target: https://artillery.io
  # Enable the Playwright engine:
  engines:
    playwright: {}
  processor: "../flow.js"
  plugins:
    publish-metrics:
       - type: honeycomb
         apiKey: "{{ $processEnvironment.HONEYCOMB_API_KEY }}"
         dataset: "datasetname"
         sampleRate: 1
scenarios:
  - engine: playwright
    flowFunction: "helloFlow"
    flow: []

```

**JS File** 
```
async function helloFlow(page, vuContext, events) {
  //
  // The code below is just a standard Playwright script:
  //
  // Go to https://artillery.io/
  await page.goto('https://artillery.io/');
  events.emit('counter', 'user.page_loads', 1);
  // Click text=Pricing
  await page.click('text=Pricing');
  // assert.equal(page.url(), 'https://artillery.io/pro/');
  // Click text=Sign up
  await page.click('text=Sign up');
}

module.exports = { helloFlow };
```

**I expected to see this happen:**

metrics should be available on Honeycomb 

Instead, this happened:

* Metrics is not available on Honeycomb
* The access token used has all the rights to send data to honeycomb. I verified it via curl command. 

Files being used:
```
<relevant yaml/js/csv go here>
```
