### ISSUE TITLE
Artillery 2.0.0-22 Gzip Decoding + capture doesn't work

### ISSUE THREAD

**Issue by luneo7** [artilleryio/artillery#1562]
Version info: 
```
Artillery Core: 2.0.0-22
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v16.15.0
OS:      darwin
```

Running this command: 
```
artillery run -e env script.yml
```

I expected to see this happen:

*Gzip decoding happens and capture works*

Instead, this happened:

*Gzip decoding didn't happen and body was left with empty string*

```
load_test/running-tests/load_test/node_modules/artillery/core/lib/engine_http.js:613
                      new Error('Failed capture or match'),
                      ^

Error: Failed capture or match
    at load_test/running-tests/load_test/node_modules/artillery/core/lib/engine_http.js:613:23
    at load_test/running-tests/load_test/node_modules/async/dist/async.js:473:16
    at replenish (load_test/running-tests/load_test/node_modules/async/dist/async.js:1009:25)
    at load_test/running-tests/load_test/node_modules/async/dist/async.js:1019:9
    at eachLimit$1 (load_test/running-tests/load_test/node_modules/async/dist/async.js:3199:24)
    at Object.<anonymous> (load_test/running-tests/load_test/node_modules/async/dist/async.js:1049:16)
    at captured (load_test/running-tests/load_test/node_modules/artillery/core/lib/engine_http.js:578:21)
    at load_test/running-tests/load_test/node_modules/artillery/core/lib/engine_util.js:488:16
    at load_test/running-tests/load_test/node_modules/async/dist/async.js:473:16
    at replenish (load_test/load_test/restaurant-orderflow-staging/node_modules/async/dist/async.js:1009:25
```

Files being used:
script.yml
```
config:
  environments:
    env:
      target: "https://api-staging.blahblah.com"
      phases:
        - name: "Test 1"
          duration: 1
          arrivalRate: 1
        - pause: 60
        - name: "Break"
          duration: 1
          arrivalRate: 0
        - name: "2 times peak load"
          duration: 2
          arrivalRate: 2
        - name: "Break"
          duration: 1
          arrivalRate: 0
  payload:
    - path: "payloads/{{ $environment }}-payload.csv"
      fields:
        - "restaurant_id"
        - "email"
        - "password"
        - "etag"
        - "env"
      skipHeader: true
  processor: "./processor.js"
before:
  flow:
    - log: "DOING_LOGIN - env {{ env }}"
    - post:
        url: "http://api-resto-{{ env }}.blahblah.com/mobile/restaurants/login"
        afterResponse: "logErrors"
        gzip: true
        json:
          email: "{{ email }}"
          password: "{{ password }}"
        capture:
          - json: $.token
            as: user_token
    - log: "VALIDATE_TOKEN - userToken: {{ user_token }}"
    - think: 5
scenarios:
  ......
```
