### ISSUE TITLE
0x (hex) in csv data is not working

### ISSUE THREAD

**Issue by NicoSerranoP** [artilleryio/artillery#1577]
I am using Artillery to test a web3 API that I am currently building. The usual login mechanism with web3 is to verify if a signed message has a public key that matches with the public address claiming it signed it. To do that I need to send the signed message and the public address (both are hex code strings starting with ```0x```). In doing so, I realized that the server is not receiving the whole string (ex: ```0x102ff93e06C52A0C7a741D76Cf81Db18bDEc2E67```) but only ```0```. 

Version info: 
```
Artillery Core: 2.0.0-23
```

Running this command: 
```node server.js```
**server.js**
```
const express = require('express');

const app = express()
app.use(express.json());

app.post('/login', (req, res) => {
    console.log(req.body);
    res.json({'message':'ok'});
});

app.listen(3003, ()=> {
    console.log('Server running');
});
```

**test.yml**
```artillery run test.yml```
```
config:
  target: "http://localhost:3003"
  phases:
    - duration: 3
      arrivalRate: 1
      name: 'Warm up'
  payload:
    name: participants
    loadAll: true
    path: "./participants.csv"
    fields:
      - "address"
      - "signature"

scenarios:
  - name: "Login participants"
    flow:
      - loop:
        - post:
            url: "/login"
            json:
              address: "{{ $loopElement.address }}"
              signature: "{{ $loopElement.signature }}"
        over: participants
```
**participants.csv**
```
0x102ff93e06C52A0C7a741D76Cf81Db18bDEc2E67,0x0c1a27c10619f48aa3e5ae5901690277654fb8a28232f6135482ef2df70f412c6632e3e61e716f9a61e404244369f51b1879463b547c2adaa9cddc99278e768e1c
0x48Bb69535869E8018e079cAc14a864CF31543E86,0xb3bd39b4a50340190caa5208358744b98279c1e00e81c22c5349d248749319cd7ac04768824302ebe80fa9f31828e562ef8d28a54b72c885f23fc63b2367cbd61b
0x255eD3312E823dc3DD2AECD3F04C8F23D5dE11F7,0x4632722d61f8c8deface002287b7f46107a742b34f9d62991fa9fe64b911efa92ea64df7442a661120724a8aa99751c57bd0a49006e9e6658a90532fc4ac67f21c
```

I expected to see this happen:
```
Server running
{
  address: '0x102ff93e06C52A0C7a741D76Cf81Db18bDEc2E67',
  signature: '0x0c1a27c10619f48aa3e5ae5901690277654fb8a28232f6135482ef2df70f412c6632e3e61e716f9a61e404244369f51b1879463b547c2adaa9cddc99278e768e1c'
}
{
  address: '0x102ff93e06C52A0C7a741D76Cf81Db18bDEc2E67',
  signature: '0x0c1a27c10619f48aa3e5ae5901690277654fb8a28232f6135482ef2df70f412c6632e3e61e716f9a61e404244369f51b1879463b547c2adaa9cddc99278e768e1c'
}
{
  address: '0x102ff93e06C52A0C7a741D76Cf81Db18bDEc2E67',
  signature: '0x0c1a27c10619f48aa3e5ae5901690277654fb8a28232f6135482ef2df70f412c6632e3e61e716f9a61e404244369f51b1879463b547c2adaa9cddc99278e768e1c'
}
```

Instead, this happened:
```
Server running
{ address: 0, signature: 0 }
{ address: 0, signature: 0 }
{ address: 0, signature: 0 }
```

Temporary solution:
I made it work by changing the json values to:
```
 json:
              address: "0x{{ $loopElement.address }}"
              signature: "0x{{ $loopElement.signature }}"
```
And not deleting the ```0x``` from the csv values:
```
102ff93e06C52A0C7a741D76Cf81Db18bDEc2E67,0c1a27c10619f48aa3e5ae5901690277654fb8a28232f6135482ef2df70f412c6632e3e61e716f9a61e404244369f51b1879463b547c2adaa9cddc99278e768e1c
```
But I believe it should work with ```0x``` strings. I cannot think of a counter argument yet.
