### ISSUE TITLE
ensure plugin: add additional parameters to shutdown the artillery when SLO checks where failed

### ISSUE THREAD

**Issue by savvagen** [artilleryio/artillery#1599]
1. Add a way to stop artilley (`global.artillery.shutdown()`) injector when `conditions` or `thresholds` will be failed.
2. Add additional parameter to the `conditions` and `thresholds` with boolean type to made a signal to artillery `ensure` plugin
Example:
```
config:
  ensure:
    thresholds:
      - "metric.name.one": value1
         shutdown: true|false 
    conditions:
      - expression: "metric.name.one <= value1 and metric.name.two > value2"
         shutdown: true|false
```
