### ISSUE TITLE
Artillery running against Lambda runs endlessly

### ISSUE THREAD

**Issue by JoeGaebel** [artilleryio/artillery#1606]
Version info: 
```
VERSION INFO:

Artillery Core: 2.0.0-23
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v16.17.0
OS:      linux
```

Running this command: 
```
artillery run test.yml
```

I expected to see this happen:

Running a simple load test on AWS Cloud 9 with a barebones artillery install against a lambda endpoint.
I would expect the load test to finish successfully.

Instead, this happened:

Midway through, it resets the request counter, and then continues to run at a low request per second rate endlessly. Please see the attached log and notice it goes from 1107 http.200 codes, down to 139, as well as the requests per second being drastically reduced.

Files being used:
```
config:
  target: "https://somelambda.execute-api.ap-southeast-2.amazonaws.com/development"
  phases:
    - duration: 600
      arrivalRate: 1
      rampTo: 2000
scenarios:
  - name: "dothething"
    flow:
      - get:
          url: "/someurl"
```

```
--------------------------------------
Metrics for period to: 05:51:10(+0000) (width: 9.994s)
--------------------------------------

http.codes.200: ................................................................ 1107
http.request_rate: ............................................................. 110/sec
http.requests: ................................................................. 1098
http.response_time:
  min: ......................................................................... 0
  max: ......................................................................... 162
  median: ...................................................................... 22.9
  p95: ......................................................................... 40
  p99: ......................................................................... 67.4
http.responses: ................................................................ 1107
vusers.completed: .............................................................. 1107
vusers.created: ................................................................ 1099
vusers.created_by_name.dothething: ................................. 1099
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 25.1
  max: ......................................................................... 1076
  median: ...................................................................... 40
  p95: ......................................................................... 76
  p99: ......................................................................... 144


--------------------------------------
Metrics for period to: 05:51:20(+0000) (width: 9.95s)
--------------------------------------

http.codes.200: ................................................................ 139
http.request_rate: ............................................................. 14/sec
http.requests: ................................................................. 141
http.response_time:
  min: ......................................................................... 0
  max: ......................................................................... 164
  median: ...................................................................... 37.7
  p95: ......................................................................... 80.6
  p99: ......................................................................... 115.6
http.responses: ................................................................ 139
vusers.completed: .............................................................. 139
vusers.created: ................................................................ 140
vusers.created_by_name.dothething: ................................. 140
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 56.4
  max: ......................................................................... 923
  median: ...................................................................... 153
  p95: ......................................................................... 347.3
  p99: ......................................................................... 399.5
```

I wonder if this is due to the high rate. I was able to run other load tests with the same config with a less `rampTo` value ( <= 1000) and it worked fine.

**Comment by JoeGaebel** [comment]
Might not be endless, looks like Artillery respects the rampUp more than it respects the duration of the phase.
With the following as my only phase,

```
  phases:
    - duration: 600
      arrivalRate: 1
      rampTo: 1000
```
I would have expected it to run for 10 minutes, but it ends up taking 23 minutes.

```All VUs finished. Total time: 23 minutes, 45 seconds```

So I would say there are two bugs outlined here:
- Duration isn't respected if the network throughput isn't able to achieve the rampUp in time
- Under some condition (maybe very high ramp up and not high enough throughput) Artillery resets it's counters
