### ISSUE TITLE
[BUG] 404 on every request even though 200 is returned

### ISSUE THREAD

**Issue by rufreakde** [artilleryio/artillery#1613]
Version info: 
```
artillery version

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery Core: 2.0.0-23
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v16.17.1
OS:      darwin
```

Running this command: 
```
artillery run test/performance/artillery.self.test.yaml --dotenv .env
```

I expected to see this happen:

Run should go through with 200 ok on all API calls
```
http.codes.200: ................................................................ 20
```
Instead, this happened:

It seems all API calls are recorded as 404 by artillery even though they are not!
```
--------------------------------------
Metrics for period to: 14:32:00(+0200) (width: 9.056s)
--------------------------------------

http.codes.404: ................................................................ 20
http.request_rate: ............................................................. 2/sec
http.requests: ................................................................. 20
http.response_time:
  min: ......................................................................... 0
  max: ......................................................................... 2
  median: ...................................................................... 1
```

Additional Information:
```bash
# curl request:
curl 'http://localhost:4004/health/readiness()' --verbose
*   Trying 127.0.0.1:4004...
* Connected to localhost (127.0.0.1) port 4004 (#0)
> GET /health/readiness() HTTP/1.1
> Host: localhost:4004
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< x-correlation-id: 30c63c09-121a-4e9f-85f1-e8154b86184e
< OData-Version: 4.0
< content-type: application/json;odata.metadata=minimal
< Date: Thu, 06 Oct 2022 12:45:44 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Content-Length: 96
< 
* Connection #0 to host localhost left intact
{"@odata.context":"$metadata#Edm.String","value":"Service is ready to recieve network traffic!"}% 

```
Files being used:
```
config:
  target: "http://localhost:4004/" # EDIT THIS WAS THE ISSUE 'http://localhost:4004' was the solution
  phases:
    - duration: 20
      arrivalRate: 2
      name: Warm up
    - duration: 60
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 120
      arrivalRate: 50
      name: Sustained load
  environments:
    localhost:
      target: "http://localhost:4004"
scenarios:
  - name: "root"
    flow:
      - get:
          url: "/"
  - name: "startup"
    flow:
      - get:
          url: "/health/startup()"
  - name: "readiness"
    flow:
      - get:
          url: "/health/readiness()"
  - name: "liveness"
    flow:
      - get:
          url: "/health/liveness()"
  - name: "toggles"
    flow:
      - get:
          url: "/health/toggles()"
```
