### ISSUE TITLE
Correct way to sign in a VU in order to test an endpoint

### ISSUE THREAD

**Issue by adamcole123** [artilleryio/artillery#1616]
My first attempt at this was to just call the sign in end point each time i needed the cookie (which expires). I soon found out that bcrypt deliberately runs slowly to prevent a brute force attack. This means that when you're testing 50 requests a second, you're going to slow down other operations, and so the load tests fail.

What i need then is to sign in the user once for the entire file. The issue here is that i have different  roles in my system so the user needs to sign in to a different account to test each endpoint in a specific scenario.

Here is how i tried it, which failed:
```yml
before:
  flow:
    - log: 'Get user auth tokens'
    - post:
        url: "/user/signin"
        json: 
          username: "user"
          password: "Password1!"
        capture:
          cookie: "token"
          as: "user_token"
    - post:
        url: "/user/signin"
        json: 
          username: "admin"
          password: "Password1!"
        capture:
          cookie: "token"
          as: "admin_token"
    - post:
        url: "/user/signin"
        json: 
          username: "broker"
          password: "Password1!"
        capture:
          cookie: "token"
          as: "broker_token"
```

How do i achieve this?

**Comment by adamcole123** [comment]
Update: I have managed to do this with the following:

```yml

before:
  flow:
    - log: 'Get user auth tokens'
    - post:
        url: "/user/signin"
        json: 
          username: "user"
          password: "Password1!"
        capture:
          header: "set-cookie"
          as: "user_token"
    - post:
        url: "/user/signin"
        json: 
          username: "admin"
          password: "Password1!"
        capture:
          header: "set-cookie"
          as: "admin_token"
    - post:
        url: "/user/signin"
        json: 
          username: "broker"
          password: "Password1!"
        capture:
          header: "set-cookie"
          as: "broker_token"
```

Though now these values (user_token for example) are the cookie header string, e.g. "'token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNDFhMjU3ODhjMWI3MDE0YjMyOWM3NiIsInVzZXJuYW1lIjoiYnJva2VyIiwiZW1haWwiOiJicm9rZXJAc3RvY2t0cmAkaW5nc3lzdGVtLmNvbSIsImZpcnN0TmFtZSI6IkJyb2tlciIsImxhc3ROYW1lIjoiQWNjb3VudCIsInJlcG9ydHMiOltdLCJwYXNzd29yZCI6IiIsImNyZWRpdCI6NTAwMDAsInJvbGUiOiJCcm9rZXIiLCJpc0RlbGV0ZWQiOmZhbHNlLCJjYXJkRGV0YWlscyI6W10sImFjdGl2YXRpb25EYXRlIjoiMjAyMi0xMC0wOFQxNjoxNjoyMy4xNTRaIiwiX192IjowLCJpYXQiOjE2NjUyNDU3ODgsImV4cCI6MTY2NTg1MDU4OH0.76Ucbv1ROONtKkq8UwwyNnAyxy8RKOIH5A1WEi_v9PQ; Path=/; Expires=Sat, 15 Oct 2022 16:16:28 GMT; HttpOnly'"

How do i pass this into a test now?
