### ISSUE TITLE
[Question] How to use http and websocket calls in one flow

### ISSUE THREAD

**Issue by savvagen** [artilleryio/artillery#1632]
@hassy  Does artillery supports using `http` and `ws` engine in one single flow like:

```

scenarios:
  - name: Onboarding Flow
    engine: ws
    flow:
      - get:
           url: "/my/resource"
           expect:
             - statusCode: 200
      - connect: "{{ iws_url }}"
      - send: "{{ myData }}"
```
