### ISSUE TITLE
Tests start and get sent to aws fargate instance, and then immediately start deprovisioning, no logs no nothing

### ISSUE THREAD

**Issue by bruno-salapic** [artilleryio/artillery#1635]
I have a simple script that is to be launched via artillery pro. I've been using artillery pro for a few years and just recently using the exact same steps and procedures (all of this has been automated for at least 2 years) the process fails unexpectedly around fargate.
I have all the necessary cli tools, such as AWS and artillery pro, and core artillery.

when I launch my script it looks like so 

.\node_modules\.bin\artillery run-cluster --region us-east-1 --count 1 --launch-type ecs:fargate --cluster SomeCLusterNameFiller --subnet-ids someSubnetFillerValue .\RegisteringUser --config .\Config_Overrides_Accounts_1.yml

once that starts it does all the steps of bundling what is required and starts notifying me that it is provisioning the necessary resources. but then immediately it starts to deprovisioning them and the tests never end up running. I don't see any logs anywhere even when navigating AWS console

Version info: 
```
artillery --version

        ___         __  _ ____                  _
  _____/   |  _____/ /_(_) / /__  _______  __  (_)___  _____
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / / / / __ \/____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ / / / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__, (_)_/\____/
                                    /____/

------------ Version Info ------------
Artillery: 1.7.9
Artillery Pro: 2.3.0-0
Node.js: v14.17.0
OS: win32/x64
--------------------------------------
```

Running this command: 
```
.\node_modules\.bin\artillery run-cluster --region us-east-1 --count 1 --launch-type ecs:fargate --cluster SomeCLusterNameFiller --subnet-ids someSubnetFillerValue .\RegisteringUser --config .\Config_Overrides_Accounts_1.yml
```

I expected to see this happen:

I hope the test runs as it has the last 2-3 years

Instead, this happened:

the tests don't even start, goes from provisioning to deprovisioning 

Files being used:
```
config:
  target: 'someUrlHere/api'
  processor: "./BaseProcessor.js"
  # helps visualize the response code of every request only useful when working local currently
  plugins:
    metrics-by-endpoint:
    # Group metrics by request name rather than URL:
      useOnlyRequestNames: true
  phases:
    - duration: 1
      arrivalRate: 1
  variables:
    numberOfUsersToRegister: 1
    endofUserGeneration: 0
    registerViewModel: ""
    emailPrefix: 'test'
    generatedEmail: ''
    preferredCultureName: "en-CA"
scenarios:
  - name: "Register Users"
    flow:
      - loop:
        - function: generateRegisterViewModel
        - post:
            url: "/account/register"
            json: "{{ registerViewModel }}"
        whileTrue: moreUsersToRegister
```
