### ISSUE TITLE
Lambda: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by adamfisher** [artilleryio/artillery#1649]
**Version info:**
```
Artillery Core: 2.0.0-23
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v19.0.0
OS:      win32
```

**Running this command:** 
```
artillery run --platform aws:lambda --platform-opt region=us-east-1 --environment 29r artillery-test.yml
```

**I expected to see this happen:**

Lambda would spin up and run the tests.

Instead, this happened:

Failure with this error message output:

```
λ Creating AWS Lambda function...
    - Installing dependencies
C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\lib\platform\aws-lambda\index.js:104
      artillery.log(stdout.toString(), stderr.toString(), status, error);
                           ^

TypeError: Cannot read properties of null (reading 'toString')
    at PlatformLambda.init (C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\lib\platform\aws-lambda\index.js:104:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Launcher.run (C:\Users\17077\AppData\Roaming\npm\node_modules\artillery\lib\launch-platform.js:351:25)

Node.js v19.0.0
```

**Files being used:**

Changed for obscurity/security reasons but this is the `artllery-test.yml` file:

```
config:
  environments:
    29r:
      target: "https://example.com"
      variables:
        apiKey: "123456"
        eventGuid: "8d683883-6519-44ba-b25a-655c6490c1d7"
  phases:
    - duration: 300
      arrivalRate: 500
  before:
    flow:
      - name: "Get member IDs for the Event"
      - get:
        url: "/origin/GetAllMembers/{{ eventGuid }}"
        headers:
          X-ApiKey: "{{ apiKey }}"
        capture:
          - json: "$"
            as: "memberIds"
scenarios:
  - name: "Get Member Origins"
    flow:
      - loop:
          - get:
              url: "/origin/RetrieveOrigins/{{ $loopElement }}"
        over: "{{ $memberIds }}"
```
