### ISSUE TITLE
Not able to get socket events Artillery script

### ISSUE THREAD

**Issue by somanwal** [artilleryio/artillery#1669]
I am using following artillery script

```
config:
  target: "{{ $processEnvironment.TARGET }}"
  phases:
    - duration: "{{ $processEnvironment.DURATION }}"
      arrivalRate: "{{ $processEnvironment.RATE }}"
  processor: "./processor.js"
  socketio:
    path: "/socket.io"
  variables:
    website_id:
      - "{{ $processEnvironment.WEBSITE_ID }}"
scenarios:
  - flow:
      - post:
          beforeRequest: "options"
          url: "/start"
          json:
            websiteId: "{{id}}"
            pageUrl: "http://www.localhost:3000"
            preview: false
          capture:
            - header: "session-cookie"
              as: "session_id"
          afterResponse: "parseSessionValue"
      - function: "init"
      - loop:
          - think: "{{ nextEvent.think }}"
          - emit:
              channel: "{{ nextEvent.name }}"
              data: "{{ nextEvent.data }}"
        whileTrue: "nextEventsToComplete"
    engine: "socketio"
    name: "A new conversation that always finishes"
```

In processor.js I have method init like following:

```
exports.init = function init(context, _, done) {
  debug("initialized socket connection");
  context.vars.cursor = 0;
  context.vars.done = false;
  context.vars.events = [];
  const socket = context.sockets[""];
  if (socket) {
    socket.on("*", packet => {
      debug("*********************received event %o", packet.data[0]); // Not getting event here
      debugData("*******************event %o", packet.data);
      processServerEvent(context, packet.data);
    });
  } else {
    debug("Could not find socket in context");
  }
  return done();
};
```

Not able to figure out why I am not getting socket events in socket.on method. It used to work with old version of artillery. Any suggestions?
