### ISSUE TITLE
rampTo regression in v2.0.0-24

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#1682]
The following script fails in v2.0.0-24 or later but works fine on earlier versions of Artillery:

```yaml
config:
  target: http://asciizoo.artillery.io:8080
  phases:
    - duration: 300
      arrivalRate: 1
      rampTo: 5
    - duration: 300
      arrivalRate: 3
    - duration: 300
      arrivalRate: 3
      rampTo: 10
scenarios:
  - flow:
    - get:
        url: "/pony"
```

Set `WORKERS=7` to reproduce reliably as it seems to depend on the number of CPU cores available locally.

Output:

```
Timeout duration was set to 1.
(node:12259) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:12259) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:12259) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

**Comment by annawidera** [comment]
I am experiencing this error on version `Artillery Core: 2.0.0-27` (MacBook, Intel based, MacOS 12.6.1). 
My `load.yml` file: 
``` YML
config:
  target: "https://localhost/"
  phases:
    - duration: 30
      arrivalRate: 1
      name: "Phase: Warmup 1 user / s"
    - duration: 30
      arrivalRate: 1
      rampTo: 5
      name: "Phase: Ramp up to 5 users / s"
    - duration: 60
      arrivalRate: 5
      name: "Phase: Sustain 5 users / s "
    - duration: 30
      arrivalRate: 5
      rampTo: 10
      name: "Phase: Ramp up to 10 users / s "
    - duration: 60
      arrivalRate: 10
      name: "Sustain 10 users / s "
  http:
    timeout: 30
  defaults:
    cookie:
      COOKIE: "cookie"
scenarios:
  - name: "My App Load"
    flow:
      - get:
          url: "/api/SMTH_ELSE"
      - get:
          url: "/api/SMTH"
```
I am running the load test with: 
```
artillery run -k load.yml
```
