### ISSUE TITLE
Error message on engine missmatch

### ISSUE THREAD

**Issue by juanig1** [artilleryio/artillery#1693]
Version info: 
```
latest
```

Running this command: 
```
artillery run broken.yaml
```

I expected to see this happen:

- Error message explaining the engine I am using is not available
- Or, use scenario's engine if possible

Instead, this happened:

```
⠴ worker error, id: 1 TypeError [Error]: Cannot read properties of undefined (reading 'createScenario')
    at /Users/j/.nvm/versions/node/v19.1.0/lib/node_modules/artillery/core/lib/runner.js:300:23
    ...
```

Files being used:
`broken.yaml`:
```
config:
  target: https://socket.url.com
  # missing engines section
  #  engines:
  #    socketio-v2: {}
scenarios:
    - name: First Scenario
      engine: socketio-v2
      flow:
        - emit:
            channel: data
            data: data
```

Related:
See https://github.com/artilleryio/artillery/discussions/1694
