### ISSUE TITLE
HTTP Requests - An error has occurred

### ISSUE THREAD

**Issue by adamfisher** [artilleryio/artillery#1729]
I have two different environments configured in my yml file and environment 1 works successfully and completes the request but environment 2 fails with this error message below. Both environments have the same endpoint and same setup. I proved they both worked by sending the same request to both environments using postman and they complete successfully. However when I submit the request throw Artillery it returns this generic error which points to it having something to do with the way the request is formatted. Any advice on how to better evaluate what's going on here?

```
2022-12-13T21:04:40.952Z http request: {
  "url": "https://example.com/RetrieveSomething/1234",
  "method": "GET",
  "headers": {
    "user-agent": "Artillery (https://artillery.io)",
    "x-apikey": "34856734976"
  }
}
2022-12-13T21:04:40.952Z http:response {
  "cache-control": "no-cache",
  "pragma": "no-cache",
  "content-type": "application/json; charset=utf-8",
  "expires": "-1",
  "server": "Microsoft-IIS/10.0",
  "x-aspnet-version": "4.0.30319",
  "x-powered-by": "ASP.NET",
  "date": "Tue, 13 Dec 2022 21:04:40 GMT",
  "content-length": "36"
}
2022-12-13T21:04:40.952Z http:response "{\"Message\":\"An error has occurred.\"}"
```

Version info: 
```
Artillery Core: 2.0.0-27
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v19.0.0
OS:      win32
```

Running this command: 
```
artillery run --environment env2 artillery-test.yml
```

I expected to see this happen:

*The HTTP request completes successfully.*

Instead, this happened:

*The request fails with a generic "An error has occurred" error message. Running the generated URL in the Artillery output in postman with the API key produces a successful 200 OK so artillery is somehow sending this request differently.*

Files being used:
```
config:
  http:
    timeout: 30
  payload:
      - fields:
        - "MemberId"
  environments:
    env1:
      target: "https://example1.com"
      variables:
        apiKey: "12345678"
      payload:
        - path: "ArtilleryCampaignData-env1.csv"
    sandbox3:
      target: "https://example2.com"
      variables:
        apiKey: "45837462"
      payload:
        - path: "ArtilleryCampaignData-env2.csv"
  phases:
    - duration: 10
      arrivalRate: 1
scenarios:
  - name: "Load Offers"
    flow:
      - get:
          url: "/RetrieveOffers/{{ MemberId }}"
          headers:
            X-ApiKey: "{{ apiKey }}"
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: CustomerId
```
