### ISSUE TITLE
Error: spawnSync npm ENOENT on Windows trying to run on lambda

### ISSUE THREAD

**Issue by P2mb2** [artilleryio/artillery#1757]
Version info: 
```
VERSION INFO:

Artillery Core: 2.0.0-27
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v18.12.1
OS:      win32
```

Running this command: 
```
artillery run  --platform aws:lambda  --platform-opt region=eu-central-1  --count 1  tests/performance/aws_run.yml
```

I expected to see this happen:

*lambda functions being correctly created and submitting aws_run.yaml scenarios*

Instead, this happened:

*Get an error when trying to build dependencies and later lambda exits with error on library

- Installing dependencies
undefined undefined null Error: spawnSync npm ENOENT
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:857:24)
    at PlatformLambda.init (C:\Users\cardojp5\AppData\Roaming\npm\node_modules\artillery\lib\platform\aws-lambda\index.js:147:47)
    at async Launcher.run (C:\Users\cardojp5\AppData\Roaming\npm\node_modules\artillery\lib\launch-platform.js:358:25) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync npm',
  path: 'npm',
  spawnargs: [ 'install' ]
}

[6b0fe57a-bb70-4a73-bfb6-e9418e7ff224]: A Lambda function has exited with an error. Reason: ArtilleryError
{
  stdout: '',
  stderr: 'node:internal/modules/cjs/loader:936\n' +
    '  throw err;\n' +
    '  ^\n' +
    '\n' +
    "Error: Cannot find module '@oclif/command'\n" +
    'Require stack:\n' +
    '- /var/task/node_modules/artillery/bin/run\n' +
    '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n' +
*

Files being used:
```
aws_run.yml:

config:
  target: "url"
  phases:
    - duration: 10
      arrivalRate: 1
      name: Warm up

scenarios:
  - flow:
    - get:
        url: "/"
        headers:
          header: "valid"
```
