### ISSUE TITLE
Lambda Timeout waiting for function to be ready for invocation

### ISSUE THREAD

**Issue by nathankurt** [artilleryio/artillery#1772]
Version info: 
```
VERSION INFO:

Artillery: 2.0.0-28
Node.js:   v16.15.1
OS:        linux
```

Running this command: 
```
artillery run --platform aws:lambda --platform-opt region=us-east-1 --count 25 blitz.yml
```

I expected to see this happen:

When I run `artillery run blitz.yml` the command works as expected, and the load test is run, when i run the command above, i expect the same thing to happen just via the lambda. 

Instead, this happened:

I get an error after the build phase in AWS Codebuild where we are trying to run this. I didn't see a way to increase the timeout anywhere but that seems like it might be needed. 
```
Creating AWS Lambda function...
- Bundling test data
  - blitz.yml
- Installing dependencies
- Creating zip package
Preparing AWS environment...
 - Lambda function: artilleryio-[blahblahblah]
 - Region: us-east-1
 - AWS account: [ACT NUMBER]
⠋ /usr/local/lib/node_modules/artillery/lib/platform/aws-lambda/index.js:420
      throw new Error(`Timeout waiting for lambda function to be ready for invocation`);
            ^

Error: Timeout waiting for lambda function to be ready for invocation
    at PlatformLambda.runWorker (/usr/local/lib/node_modules/artillery/lib/platform/aws-lambda/index.js:420:13)
    at async Launcher.run (/usr/local/lib/node_modules/artillery/lib/launch-platform.js:407:7)
```

Files being used:

buildspec.yaml file 
```yaml
version: '0.2'
env:
  shell: /bin/bash
  variables:
    ENVIRONMENT: development
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
    - echo "Starting the build"
    - npm install -g artillery
    - cd stacks/artillery
    - pwd
    - ls
  build:
    commands:
    - artillery run --platform aws:lambda --platform-opt region=us-east-1 --count
      25 blitz.yml
  post_build:
    commands:
    - echo Build completed on `date`

```
