### ISSUE TITLE
All vusers getting skipped when match fails (since v2.0.0-28)

### ISSUE THREAD

**Issue by AlexVanderbist** [artilleryio/artillery#1776]
Hi there,

I just updated to v2.0.0-28 and noticed my test scenario stopped working. It's been working fine all week on v2.0.0-27 so I assume it's a change that was introduced in v2.0.0-28. Rolling back to the previous version fixes the issue.

### The issue

My HTTP testing scenario assumes most of the users in the scenario fail because they hit a lock (http 423). These responses don't include the expected data to be captured by Artillery, so the vuser fails the scenario and they count up in `vusers.failed`. This is fine, the scenario can continue, new users go through the scenario, all is well. Here's the relevant output for v2.0.0-27:

```
errors.Failed capture or match: ................................................ 989
http.codes.200: ................................................................ 1276
http.codes.201: ................................................................ 30
http.codes.422: ................................................................ 55
http.codes.423: ................................................................ 934
http.request_rate: ............................................................. 229/sec
http.requests: ................................................................. 2284
http.response_time:
  min: ......................................................................... 80
  max: ......................................................................... 2073
  median: ...................................................................... 391.6
  p95: ......................................................................... 1224.4
  p99: ......................................................................... 1495.5
http.responses: ................................................................ 2295
vusers.completed: .............................................................. 27
vusers.created: ................................................................ 1000
vusers.created_by_name.0: ...................................................... 1000
vusers.failed: ................................................................. 989
```

However, starting from the new v2.0.0-28, I noticed that new vusers aren't being added anymore. Instead I see the `vusers.skipped` metric creeping up until the entire run comes to a halt with `vusers.skipped = scenario.maxVusers`. Looking at the source code bellow, this likely is because the `pendingScenarios` for the failed vusers aren't being decreased (but I'm not super familiar with the inner workings of this tool):

https://github.com/artilleryio/artillery/blob/b4363a93f4c50046ede9b4aa8462f529810220ae/packages/core/lib/runner.js#L197-L199

For completion, here's the output (the last couple of updates) for the exact same scenario as displayed above, on v2.0.0-28:

```
--------------------------------------
Metrics for period to: 21:24:00(+0000) (width: 9.983s)
--------------------------------------

errors.Failed capture or match: ................................................ 2
http.codes.200: ................................................................ 8
http.codes.201: ................................................................ 2
http.codes.422: ................................................................ 2
http.request_rate: ............................................................. 2/sec
http.requests: ................................................................. 10
http.response_time:
  min: ......................................................................... 95
  max: ......................................................................... 311
  median: ...................................................................... 175.9
  p95: ......................................................................... 295.9
  p99: ......................................................................... 295.9
http.responses: ................................................................ 12
vusers.created: ................................................................ 2
vusers.created_by_name.0: ...................................................... 2
vusers.failed: ................................................................. 2
vusers.skipped: ................................................................ 168


--------------------------------------
Metrics for period to: 21:24:10(+0000) (width: 9.711s)
--------------------------------------

vusers.skipped: ................................................................ 170
```

And finally, the only phase in my scenario (I know the arrivalRate being equal to `rampTo` doesn't make sense, I'm just messing around with these numbers a lot):

```
  phases:
    - duration: 1200
      arrivalRate: 100
      rampTo: 100
      maxVusers: 1000
      name: "Warm up the application"
```

Version info: 
```
Artillery Core: 2.0.0-27
Artillery Pro:  not installed (https://artillery.io/product)

Node.js: v18.12.1
OS:      linux
```

Please let me know if I can help with any additional details or testing. I'm also happy to figure out a fix to PR if someone can point me in the right direction where this issue might've originated. Thanks!

**Comment by hassy** [comment]
thank you @AlexVanderbist, will take a look at this asap

**Comment by hassy** [comment]
@AlexVanderbist I've not been able to confirm that a failed capture does not stop the VU. Testing with this script:

```yaml
config:
  target: http://lab.artillery.io
  phases:
    - duration: 30
      arrivalRate: 10
      maxVusers: 10
scenarios:
  - flow:
      - get:
          url: /movies
          capture:
            - json: $.nosuchfield
              as: myvar
```

Which produces no `vusers.skipped` as expected, because each VU completes the request to `/movies` in <1 sec so the `maxVusers` limit is never exceeded. All 300 VUs are created as expected.

Adding a `- think: 1` step to the scenario in order to have the VUs hang around longer and increase the number of concurrent VUs, we see a mix of `vusers.created` and `vusers.skipped` as expected.

So there would seem to be a difference between `2.0.0-27` and `2.0.0-28` somewhere, but it does not seem to have to do with failed `capture` steps.
