### ISSUE TITLE
failed to execute script

### ISSUE THREAD

**Issue by alexgocariq** [artilleryio/artillery#1797]
Version info: 
```
VERSION INFO:

Artillery: 2.0.0-28
Node.js:   v19.5.0
OS:        darwin
```

Running this command: 
```
 artillery run -e dev --output reports/spending-estimation.json tests/spending-estimation/spending-estimation.yml
```

I expected to see this happen:

*Java script should log http status and url*

Instead, this happened:

worker error, id: 2 TypeError [Error]: Cannot read properties of undefined (reading 'path')
    at logHttpStatus (/Users/alexandermatsaylo/git/cariq/performance-test/scripts/http-log.js:2:44)
    at iteratee (/opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/engine_http.js:599:19)
    at /opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/async/dist/async.js:3113:16
    at replenish (/opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/async/dist/async.js:1014:17)
    at /opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/async/dist/async.js:1019:9
    at eachLimit$1 (/opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/async/dist/async.js:3199:24)
    at Object.<anonymous> (/opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/async/dist/async.js:1049:16)
    at captured (/opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/engine_http.js:581:21)
    at Object.captureOrMatch (/opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/@artilleryio/int-commons/engine_util.js:389:12)
    at responseProcessor (/opt/homebrew/Cellar/artillery/2.0.0-28/libexec/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/engine_http.js:515:22)

Files being used:
```
function logHttpStatus (requestParams, response, context, ee, next) {
    console.log(`${response.statusCode.uri.path}: ${response.statusCode}`);  
    return next();
}

module.exports = {
    logHttpStatus: logHttpStatus
}
```
```
config:
  http:
    extendedMetrics: true
  plugins:
    ensure: {}
    metrics-by-endpoint: {}
    expect: {}
  environments:
    dev:
      target: 'https://id-estimation-spending.dev.gocariq.com'
      phases:
        - duration: 10
          arrivalRate: 5
          rampTo: 5
          maxVusers: 30
          name: Warm up
        # - duration: 60
        #   arrivalRate: 30
        #   rampTo: 300
        #   maxVusers: 300
        #   name: Ramp up to 200 by 10
      processor: ../../scripts/http-log.js
      ensure:
        p99: 1600
        maxErrorRate: 15
      payload:
        path: ./payloads/vehicle-ids.csv
        fields:
          - vehicleid
    int:
      target: 'https://api-gateway.int.gocariq.com'
      phases:
        - duration: 15
          arrivalRate: 10
          rampTo: 100
    staging:
      target: 'https://api-gateway.stage.gocariq.com'
      phases:
        - duration: 15
          arrivalRate: 10
          rampTo: 100
    prod:
      target: 'https://api-gateway.dev.gocariq.com'
      phases:
        - duration: 15
          arrivalRate: 10
          rampTo: 100
    local:
      target: 'https://api-gateway.dev.gocariq.com'
      phases:
        - duration: 120
          arrivalRate: 10
          rampTo: 100
scenarios:
  - name: spending estimation
    flow:
      - get:
          url: '/spending_estimation?vehicle_id={{vehicleid}}'
          afterResponse: logHttpStatus
          headers:
            Content-Type: application/json
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: est_spending

```
