### ISSUE TITLE
ERR_GOT_REQUEST_ERROR reported on 200 responses

### ISSUE THREAD

**Issue by casramsey** [artilleryio/artillery#1800]
Hi - I'm quite new to artillery, so perhaps I am doing something wrong, but it all looks OK to me, so perhaps a bug.  Thanks for any help - much appreciated!

Version info: 
```
Artillery: 2.0.0-28
Node.js:   v19.4.0
OS:        darwin
```

Running this command: 
```
artillery run -o ./my-json-file.json ./my-yaml-file.yml
```

I expected to see this happen:
Artillery should give me the correct results - when there are no failures, show no failures.

Instead, this happened:
When I run this, it simply load tests an endpoint.  The top two lines in the summary show as:
```
errors.ERR_GOT_REQUEST_ERROR: .................................................. 4
http.codes.200: ................................................................ 4
```
Why I am I getting `ERR_GOT_REQUEST_ERROR` for every request, yet I also get a 200 response?  I have inspected the response and do not see any indication of `ERR_GOT_REQUEST_ERROR`, everything looks as it should and the response code is always 200. Where does the `ERR_GOT_REQUEST_ERROR` come from?

I do occasionally get some that do not fail with the error.  On a load test of 600 requests in 2 minutes, 48 of them passed and the rest got the error.  However, ALL of them had a 200 response and I couldn't see any difference in those responses.

Simplified version of my .yaml:
```
config:
  http:
    timeout: 60
  target: https://my-endpoint
  processor: "./my-js-file.js"
  phases:
    - name: "go hard"
      duration: 120
      arrivalRate: 5
      maxVusers: 30
  payload:
      order: "sequence"
      path: "cards.csv"
      cast: false
      fields:
        - "pan"
        - "ref"
        - "design"
scenarios:
  - flow:
    - post:
        url: "/"
        headers:
          Content-Type: "application/xml"
        beforeRequest: "setXMLBody"
        afterResponse: "postRequest"
        expect:
          - statusCode: 200
```

js file:
```
async function setXMLBody(requestParams, context, ee, next) {
  // some code to build the xml using pan, ref and design
  requestParams.body = '<some>xml</some>'
  return next()
}

const function postRequest (requestParams, response, context, ee, next) {
  //created this method to check there were no non-200 responses
  console.log(response.statusCode)
  if (response.statusCode !== 200){
    console.log(response)
    return next(new Error(response.statusCode))
  }
  return next()
}
```
