### ISSUE TITLE
Cookies don't work if the url is a $loopElement

### ISSUE THREAD

**Issue by anoopknayak** [artilleryio/artillery#1824]
Version info: 
```

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.0-29
Node.js:   v18.13.0
OS:        darwin
```

Running this command: 
```
artillery run test-config.yml
```

I expected to see this happen:

When you set a cookie like shown in the `test-config.yml` we should see it being set on the actual request.  You should be able to see it [here](https://requestbin.myworkato.com/wsvvhgws).

Instead, this happened:

No cookie header in the request bin response.

Files being used:
```
# test-config.yml
config:
  target: "https://requestbin.myworkato.com"
scenarios:
  - flow:
    - loop:
      - get:
          url: "{{ $loopElement }}"
          cookie:
            saved: "tapir,sloth"
      over:
        - "/wsvvhgws"
          
```

I have a fix for this, but don't have a test to simulate this yet.  The reason is that the cookie is apparently set on just the last portion of the url(i.e without the domain).
