### ISSUE TITLE
ERR_GOT_REQUEST_ERROR when using body.fromFile property

### ISSUE THREAD

**Issue by mbakker96** [artilleryio/artillery#1839]
Version info: 
```
✗ artillery -v output
(node:35259) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.0-30
Node.js:   v18.12.1
OS:        darwin
```

Running this command: 
```
DEBUG=http artillery run --output reports/test-run-report.json scenarios/ejournal.yml --config config.yml
```

 I expected to see this happen:

Http request sended with as body the content of the given file by `body.fromFile`. With `content-type: application/xml`

Instead, this happened:

When adding a .xml file with he `body.fromFile` property I receive the error: `errors.ERR_GOT_REQUEST_ERROR`. In my log I don't see any error message or a warning. When adding the file content directly in my .yml file it works file, but adding it by setting the from file prop works not. 

```
➜  stres-test git:(stress-test) ✗ DEBUG=http artillery run --output reports/test-run-report.json scenarios/ejournal.yml --config config.yml
(node:32536) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Phase started: Warm up (index: 0, duration: 3s) 09:41:38(+0100)

Phase completed: Warm up (index: 0, duration: 3s) 09:41:41(+0100)

--------------------------------------
Metrics for period to: 09:41:40(+0100) (width: 0.01s)
--------------------------------------

errors.ERR_GOT_REQUEST_ERROR: .................................................. 1
vusers.created: ................................................................ 1
vusers.created_by_name.Request all sations: .................................... 1
vusers.failed: ................................................................. 1


Warning: multiple batches of metrics for period 1677228090000 2023-02-24T08:41:30.000Z
--------------------------------------
Metrics for period to: 09:41:50(+0100) (width: 1.002s)
--------------------------------------

errors.ERR_GOT_REQUEST_ERROR: .................................................. 2
vusers.created: ................................................................ 2
vusers.created_by_name.Request all sations: .................................... 2
vusers.failed: ................................................................. 2


All VUs finished. Total time: 4 seconds

--------------------------------
Summary report @ 09:41:44(+0100)
--------------------------------

errors.ERR_GOT_REQUEST_ERROR: .................................................. 3
vusers.created: ................................................................ 3
vusers.created_by_name.Request all sations: .................................... 3
vusers.failed: ................................................................. 3
```

Files being used:
EJournal.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<test></test>
```

ejournal.yml
```
config:
  ensure:
    thresholds:
      # p99 of response time must be < 300 ms:
      - "http.response_time.p99": 300
      # p90 of response time must be < 200 ms:
      - "http.response_time.p90": 250
    conditions:
      - expression: "http.codes.200 > 0 and vusers.failed == 0"
        strict: true
      - expression: "((http.codes.500 ? http.codes.500 : 0 ) / http.requests * 100) <= 0.04"
        strict: true
      - expression: "(((http.codes.500 ? http.codes.500 : 0 ) + (http.codes.400 ? http.codes.400 : 0 )) / http.requests * 100) <= 0.08"
        strict: true

scenarios:
  - name: "Request all sations"
    flow:
      - post:
          url: "/orders/196a3963-0d3b-4199-8fac-22a354bcfd50/payments/0/ejournal?transactionID=0&device=stresstest"
          body:
            fromFile: "./eJournal.xml"
          headers:
            x-api-key: "[valid api key]"
            origin: "https://localhost"
            Content-Type: "application/xml"
  ```

project-structure:
```
- assets
  - eJournal.xml
- scenarios
  - ejournal.yml
- config.yml
- ejournal.xml
```
