### ISSUE TITLE
Third Party Pugin (aws sigv4) 

### ISSUE THREAD

**Issue by gabor386** [artilleryio/artillery#1856]
Version info: 
```
Artillery: 2.0.0-30
Node.js:   v16.19.1
OS:        linux


artillery-plugin-aws-sigv4 -v: 0.0.5

```

Running this command: 
```

when i run command: **artillery run test1.yml** i'm getting 200

when i run command on lambda: artillery run test1.yml --platform aws:lambda 

```

**I expected to see this happen:**

status error code: 200

**Instead, this happened:**

status error code: 403 

**Files being used:**
```
config:
  target: https://function-url.lambda-url.us-east-1.on.aws
  phases:
  - duration: 120
    arrivalRate: 2
  plugins:
    aws-sigv4:
      serviceName: lambda
scenarios:
- beforeRequest: addAmazonSignatureV4
  flow:
  - get:
      url: "/"
      headers:
        Accept: "*/*"

```
NOTE: 
and when run command line: **export DEBUG=http,http:capture,http:response** before running artillery script locally, DEBUG mode is printing out all info. 
BUT when running artillery script on AWS Lambda, there is no http response print out in the console
