### ISSUE TITLE
Unable to use chance plugin

### ISSUE THREAD

**Issue by amrsa1** [artilleryio/artillery#1866]
### Discussed in https://github.com/artilleryio/artillery/discussions/1861

<div type='discussions-op-text'>

<sup>Originally posted by **amrsa1** March 12, 2023</sup>
Seems that chance plugin is not working as expected when i need to generate random values 

i have used the following 

```
  plugins:
    expect: {}
    chance: {}
  variables:
    - fullName: 'name'
```

```
scenarios:
    - name: "Register"
      flow:
        - get:
            url: "/"
            capture:
              header: 
                - set-cookie
              as: "responseHeaders"
            expect:
            - statusCode: 200
            - contentType: text/html; charset=utf-8
        - log: "im here {{ fullName }}"

```

logging output is showing 
`im here undefined`</div>

**Comment by amrsa1** [comment]
@hassy

**Comment by bernardobridge** [comment]
Hi @amrsa1 ,

Apologies for the delay in a reply. This is an issue with the `artillery-plugin-chance` third-party plugin, not Artillery. However, there's a couple of things I can spot that are wrong:

### 1. You're not using the `~` when defining the variable
The plugin uses this to identify a "chance" variable, as you can see from their example: https://www.npmjs.com/package/artillery-plugin-chance#example . But in the example you posted above, you didn't include it.

### 2. The plugin documentation is wrong: variables should be an object, not an array
If you look at the [code for the plugin](https://github.com/beyonk-group/artillery-plugin-chance/blob/master/index.js#L42), they're expecting an object, not an array of objects.

Therefore, you should modify your config to:

```yaml
  plugins:
    expect: {}
    chance: {}
  variables:
    ~fullName: 'name'
```
---

Closing this now, as the issue is a bit old and isn't an Artillery issue. Hopefully the above has helped! 🙏
