### ISSUE TITLE
Extract string from JSON not working

### ISSUE THREAD

**Issue by damianobarbati** [artilleryio/artillery#1867]
My endpoint is returning a string:
```json
"abc"
```

But the following syntax is not capturing it:
```yml
          capture:
            - json: $
              as: token
```

How should I capture the string where the JSON contains a value (no object / array)?

**Comment by InesNi** [comment]
Hi @damianobarbati,

From what I understand your endpoint does not return a json, but a string. I ran into this issue before and I found that the best way to capture a string response is to use the `regexp` capture instead of `json` like suggested in https://github.com/artilleryio/artillery/issues/872#issuecomment-1350921712

The following will catch any string:
```yaml
capture:
  - regexp: "[^\n]+"
    as: capturedStringResponse
```

Here is a sample Artillery test script where I capture the returned string with the above syntax, and use expect plugin to test that the captured string matches the string I was expecting:

```yaml
scenarios:
  - name: Get name string
    flow:
      - get:
          url: "/"
          capture:
            - regexp: "[^\n]+"
              as: capturedStringResponse
          expect:
            - statusCode: 200
            - contentType: "text/html; charset=utf-8"
            - equals:
                - "{{capturedStringResponse}}"
                - "abc"
```
Hope that helps :)
