### ISSUE TITLE
Not sure if bug, but I am not able to add a (+60,000 lines) json file as the request body

### ISSUE THREAD

**Issue by eliezercazares** [artilleryio/artillery#1869]
Artillery 2.0.0-27

When running the tests, the request body seems to be empty, hence request fail.

This is the code:

custom.js

```
myPayloadVar = fs.readFileSync("./myFile.json");

exports.myPayload = (userContext, events, done) => {
userContext.vars.myPayloadStr = myPayloadVar;
return done();
}

```

tests.yaml

```
...
scenarios:
    - name: "Scenario 1"
       flow:
       - function: "myPayload"
       - post:
             url: "/endpoint"
             json: 
                  "text": "{{ myPayloadStr }}"

```

However using "DEBUG" flag I don't see a body in the request 

I intend to pass the variable "myPayloadStr" as the entire body, nothing else. But it seems empty when executing.

**Comment by InesNi** [comment]
Hi @eliezercazares,

If I understand correctly, what you are trying to do is just send your json file as a request body to your endpoint.
I believe the syntax you are using in the yaml above is only intended to send key-value pairs defined in the script itself. 
Because your JSON is large and possibly nested this is probably not the ideal way to do it.

May I suggest the following:

1. Change your processor function to a beforeRequest hook (https://www.artillery.io/docs/guides/guides/http-reference#beforerequest-hooks). This will allow you to intercept the request and set the request object's body to your JSON file directly:
```js
const myFile = require('./example.json')

function setRequestBody(req, context, ee, next) {
  req.json = myFile
  return next();
}

module.exports = {
  setRequestBody
}
```
Note: I used `req.json` here instead of `req.body` because this way it automatically sets the `Content-Type` header to `application/json` and expects a JSON value, therefore you can just set it to your JSON file without formatting it. If you use `fs` to get the JSON file, you will need to use JSON.stringify as well before passing it to `req.json`.

2. Now use the beforeRequest hook in your scenario:
```yaml
scenarios:
  - name: "Scenario 1"
    flow:
      - post: 
          url: "/endpoint"
          beforeRequest: "setRequestBody"
```

Hope this helps! :)

**Comment by eliezercazares** [comment]
> Hi @eliezercazares,
> 
> If I understand correctly, what you are trying to do is just send your json file as a request body to your endpoint. I believe the syntax you are using in the yaml above is only intended to send key-value pairs defined in the script itself. Because your JSON is large and possibly nested this is probably not the ideal way to do it.
> 
> May I suggest the following:
> 
> 1. Change your processor function to a beforeRequest hook (https://www.artillery.io/docs/guides/guides/http-reference#beforerequest-hooks). This will allow you to intercept the request and set the request object's body to your JSON file directly:
> 
> ```js
> const myFile = require('./example.json')
> 
> function setRequestBody(req, context, ee, next) {
>   req.json = myFile
>   return next();
> }
> 
> module.exports = {
>   setRequestBody
> }
> ```
> 
> Note: I used `req.json` here instead of `req.body` because this way it automatically sets the `Content-Type` header to `application/json` and expects a JSON value, therefore you can just set it to your JSON file without formatting it. If you use `fs` to get the JSON file, you will need to use JSON.stringify as well before passing it to `req.json`.
> 
> 2. Now use the beforeRequest hook in your scenario:
> 
> ```yaml
> scenarios:
>   - name: "Scenario 1"
>     flow:
>       - post: 
>           url: "/endpoint"
>           beforeRequest: "setRequestBody"
> ```
> 
> Hope this helps! :)

Hi Ines!

That is incredibly good, thanks for sharing! I should have updated the post, in the end, I am using artillery-include-json plugin which is really easy to use.

```
config:
  plugins:
    json-include: {}
scenarios:
  - flow:
      - post:
          url: "/route"
          json: "!include(relativePath.json)"
```

https://www.npmjs.com/package/artillery-plugin-json-include

I do recommend this plugin, it helps a lot. 

However I love your own programmatic style. Thanks a lot for sharing and for your help.
