### ISSUE TITLE
metrics-by-endpoint not grouping with randomized parameter in URL

### ISSUE THREAD

**Issue by damianobarbati** [artilleryio/artillery#1870]
My REST API has several endpoints in the classic form: `/api/entity/:id`.

Defining in my scenario the following step:
```yml
      - get:
          url: "/api/offers/{{ $randomNumber(1, 100) }}"
```
to simulate several calls to it with for random items, results in creating 1 entry for each randomized parameter in the report (with the `metrics-by-endpoint` plugin).

How can I have the `metrics-by-endpoint` properly recognize that the endpoint is just one? Without splitting it for each number provided as a route param?

**Comment by InesNi** [comment]
Hi @damianobarbati,

In order to accomplish this, you can follow the instructions in the plugin https://github.com/artilleryio/artillery-plugin-metrics-by-endpoint.

Make sure your config sets the `useOnlyRequestNames` option for the plugin to `true`. e.g.

```yaml
config:
  target: "https://my-app.acme-corp.internal"
  plugins:
    metrics-by-endpoint:
      useOnlyRequestNames: true
```

Then, simply name your endpoint whatever you want. For example:

```yaml
      - get:
          url: "/api/offers/{{ $randomNumber(1, 100) }}"
          name: "/api/offers/:offer_id"
```

Hope that helps! :)
