### ISSUE TITLE
stats.report is not a function Mixpanel.js

### ISSUE THREAD

**Issue by coderFB** [artilleryio/artillery#1888]
I am trying to run the test using artillery.js and using the mixpanel plugin.
The intend is to see the events on MixPanel dashboard.

```
plugins:
    publish-metrics:
      - type: mixpanel
        projectToken: "<YOUR-MIXPANEL-PROJECT-TOKEN>"

```

Version info: Artillery Core: 2.0.0-23

Running this command: 
```
artillery run config.yml
```

I expected to see this happen:

View events on MixPanel dashboard.

Instead, this happened:

/usr/local/lib/node_modules/artillery/node_modules/artillery-plugin-publish-metrics/lib/mixpanel.js 28
const report = stats.report();
^
TypeError: stats.report is not a function

Looking further I found that stats is a JSON object with the details and does not have any function.
Please fix this code and provide proper documentationw ith MixPanel.
