### ISSUE TITLE
"Error: Callback was already called" on attempt to send requests in the loop

### ISSUE THREAD

**Issue by SDLarmo** [artilleryio/artillery#1909]
Version info: 
```
Artillery: 2.0.0-31
Node.js:   v16.17.1
OS:        darwin
```

Running this command: 
```
artillery run suites/survey.yaml -o ./reports/report.json
```

I expected to see this happen:
```
Request must be sent in a loop.
```
Instead, this happened:
```
Only the first request is executed, then artillery crashes with an error:

worker error, id: 1 Error: Callback was already called.
    at /Users/serhii/git/tpusa/qa_performance/node_modules/async/dist/async.js:969:32
    at /Users/serhii/git/tpusa/qa_performance/node_modules/@artilleryio/int-core/lib/engine_http.js:702:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Files being used:
```
config:
  target: https://apiurl.net/api/
  timeout: 30000
  processor: "../processors/survey.js"
  payload:
    path: "../payload/users.csv"
    fields:
      - "email"
      - "password"
    order: sequence
  phases:
    - duration: 30
      arrivalCount: 1 
before:
  flow:
    - function: setConfig
scenarios:
  - beforeScenario: "loginByEmail"
    flow:
      - function: prepareContacts
      - loop:
        - post:
            url: "/surveys/{{surveyId}}/results"
            headers:
              Authorization: "Bearer {{ authToken }}"
            json:
              ContactId: "{{ $loopElement }}"
              QuestionId: "{{ questionId }}"
              AnswerId: "{{ answerId }}"
        over: contactIds
```
