### ISSUE TITLE
Header casing changed when request it sent

### ISSUE THREAD

**Issue by ValkyrieUK** [artilleryio/artillery#191]
I have a header in my configuration.
`"headers": {
        "X-Hub-Signature":"sha1=9046ee408f8c902dec5c84760f59djkfhasjfh73"
      }`

When watching the logs of the address I am testing the header comes through like `X-hub-signature`.

The authentication system I am using requires the header be as defined as is instead of lowercased.

**Comment by ltegman** [comment]
Looks like this is due to multiple calls to `lowcaseKeys` around https://github.com/shoreditch-ops/artillery-core/blob/master/lib/engine_http.js#L148

Since many headers are case sensitive could the lowcaseKeys calls be removed from the source, or would that be problematic in some way I'm not considering?

**Comment by hassy** [comment]
Off the top of my head, the code relies on the headers being lowercase for avoiding sending duplicate headers where the only difference is casing and possibly for capturing header values as well.

I'll gladly merge a PR with a fix. According to the HTTP spec, headers are supposed to be case-insensitive i.e. a server should accept both `X-Auth` and `x-auth`. In practice, some servers / APIs don't follow the spec, so it's something we'd definitely want to fix at some point.

**Comment by maximillianus** [comment]
Hi, sorry I have to raise another issue. The server i am testing on probably does not have accurate HTTP spec. It does not accept lower-case `Authorization` header.

How do I preserve the case of my Authorization header in artillery?

I want:
```json
{
    "Authorization": "Bearer my_key"
}
```

instead of 
```
{
    "authorization": "Bearer my_key"
}
```

**Comment by hassy** [comment]
@maximillianus we have just merged a PR which adds an option for preserving header casing: #839 which is now available on the v1.6 branch - https://github.com/artilleryio/artillery/tree/v1.6.x It will be part of the next release, but in the meantime you can try running Artillery directly from that branch.

**Comment by maximillianus** [comment]
@hassy I have cloned that branch. How to include the config? Is it like this below?

This is my config:
```yml
config:
  target: 'https://example.com'
  payload:
    path: "../data/load-test-data.csv"
    fields:
      - "request_type"
      - "account_number"
      - "client_id"
      - "data"
    skipHeader: true
    cast: false
  phases:
    - duration: 1
      arrivalRate: 1
  caseSensitive: true
  defaults:
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer my_key"
```
