### ISSUE TITLE
Rexexp capture groups broken

### ISSUE THREAD

**Issue by BanksySan** [artilleryio/artillery#1921]
Version info: 
```none
VERSION INFO:

Artillery: 2.0.0-32
Node.js:   v16.15.0
OS:        win32

```

Running this command: 
```
artillery run
```

I expected to see this happen:

I expect the regexp to be evaluates and, if I have supplied `group` field to the `regexp` capture command then it should return the group, not the entire match text.

The block starting at [line 609](https://github.com/artilleryio/artillery/blob/a1626a729637ef10f71b4d5009e70be257ba891d/packages/commons/engine_util.js#L609) in `engine_util.js` should be correctly extracting the group, if there is one.

Instead, this happened:

![Evaluations of match and groups.](https://github.com/artilleryio/artillery/assets/996280/1d164a4c-8f0e-4d77-9a95-e3ad2b9b7a36)

The code is using `group && match[group]`, this _should_ be `group && match.groups[group]`.  As you can see in the attached screenshot, the second returns the correct value `alice`, the former returns `undefined`.

Files being used:
```yaml
- get:
    url: "/names"
    capture:
      - regexp: "<li id=\\\"name-1\\\">(?<aliceGroup>\\w*)<\\/li>"
        as: alice
        group: aliceGroup
        flags:
        strict: false
```
