### ISSUE TITLE
Artillery script execution error: ERR_REQUIRE_ESM in @oclif/config plugin

### ISSUE THREAD

**Issue by aldousalvarez** [artilleryio/artillery#1933]
Version info: 
```
Artillery: 1.7.2 migrating to v.2.0.0-x
NodeJS: 16.14.2
```

Running this command: 
```
artillery run ${artilleryScriptLocation} --output report.json
```

I expected to see this happen:
```
It will proceed with the artillery load testing and will provide a report.json to see the results
```

Instead, this happened:
```
After migrating to version 2.0.0-x the @oclif/config has been added since the first release of [v2.0.0-x](https://github.com/artilleryio/artillery/blob/v2.0.0-0/package.json)

Err: Error: Command failed: artillery run ./packages/cactus-cmd-api-server/src/test/resources/artillery/benchmark-script.yaml --output report.json (node:700947) [ERR_REQUIRE_ESM] Error
  Plugin: artillery [ERR_REQUIRE_ESM]: require() of ES Module /******/cactus/node_modules/globby/index.js from /******/cactus/node_modules/@oclif/config/lib/plugin.js not supported. Instead
  change the require of index.js in /******/cactus/node_modules/@oclif/config/lib/plugin.js to a dynamic import() which is available in all CommonJS modules. module: @oclif/config@1.18.6 task: not
  loading commands, globby not found plugin: artillery root: /******/cactus/node_modules/artillery See more details with DEBUG=* (Use `node --trace-warnings ...` to show where the warning was
  created) › Error: command run not found

/@oclif/config/lib/plugin.js
Line 244 - const globbyPath = require.resolve('globby', {paths: [this.root, __dirname]})
Line 245 - globby = require(globbyPath)
```
Files being used:
```
artilleryScriptLocation
config:
  target: "{{ $processEnvironment.apiHost }}"
  phases:
    - duration: 3
      arrivalRate: 5
      name: Warm up
    - duration: 10
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 60
      arrivalRate: 50
      name: Sustained load
scenarios:
  - name: Load Test
    engine: skytrace
    flow:
      - get:
          url: "/api/v1/api-server/get-prometheus-exporter-metrics"

```
