### ISSUE TITLE
Incorrect payload path when using environments

### ISSUE THREAD

**Issue by cjsaurusrex** [artilleryio/artillery#1961]
When trying to load a(or multiple) payloads from a list within an `environment` using a relative path, the base path that is used is the directory of the config file loaded in using the `-c` parameter. This results in the file not being found and an error being thrown.

- If an Environment only contains a single payload, specified in a dictionary format, then the path is generated correctly.
E.g:
```yaml
...
  environments:
    staging:
      payload:
        path: "./data/my-data.csv"
        fields:
          - "id"
          - "name"
        skipHeader: true
        order: sequence
...
```
- If a list of payloads if specified outside of an `environment` the path is generated correctly.

**Version info:**
```
Artillery: 2.0.0-34
Node.js:   v20.3.0
OS:        darwin
```

**Running this command:** 
```
artillery run -e staging -c ./config/artillery-config.yaml my-test.yaml
```

**I expected to see this happen:**

I'd expect the `my-data.csv` file defined in my `staging` environments `payload` to be loaded from the `./data/my-data.csv` location.

**Instead, this happened:**

The `my-data.csv` is attempted to be loaded from `./config/data/my-data.csv` and an error is thrown, causing the test execution to be halted.

Error Details:
```
    Error: ENOENT: no such file or directory, open '/Users/christopher.orchard/Development/Testing/artillery-test/config/data/my-data.csv'
    Code: ENOENT
Error: ENOENT: no such file or directory, open '/Users/christopher.orchard/Development/Testing/artillery-test/config/data/my-data.csv'
    at Object.openSync (node:fs:592:3)
    at Object.readFileSync (node:fs:460:35)
    at readPayload (/opt/homebrew/lib/node_modules/artillery/lib/cmds/run.js:486:21)
    at prepareTestExecutionPlan (/opt/homebrew/lib/node_modules/artillery/lib/cmds/run.js:465:25)
    at async RunCommand.runCommandImplementation (/opt/homebrew/lib/node_modules/artillery/lib/cmds/run.js:196:20)
    at async RunCommand.run (/opt/homebrew/lib/node_modules/artillery/lib/cmds/run.js:49:5)
    at async RunCommand._run (/opt/homebrew/lib/node_modules/artillery/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/opt/homebrew/lib/node_modules/artillery/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/opt/homebrew/lib/node_modules/artillery/node_modules/@oclif/command/lib/main.js:28:9)
    at async Main._run (/opt/homebrew/lib/node_modules/artillery/node_modules/@oclif/command/lib/command.js:43:20)
```

**Files being used:**

*./config/artillery-config.yaml*
```yaml
config:
  plugins:
    metrics-by-endpoint:
      useOnlyRequestNames: true
      stripQueryString: true

```

*./data/my-data.csv*
```csv
id,name
123,christopher
456,not-christopher
```

*my-test.yaml*
```yaml
---
config:
  environments:
    staging:
      payload:
        - path: "./data/my-data.csv"
          fields:
            - "id"
            - "name"
          skipHeader: true
          order: sequence
  target: https://http.cat
  phases:
    - duration: 10
      arrivalRate: 1
      maxVusers: 1
      name: "low level"
scenarios:
  - name: Test Scenario
    flow:
      - log: "{{ id }}"
```
