### ISSUE TITLE
Artillery cannot generate any reasonable amount of load, the http client is slower then the http server.

### ISSUE THREAD

**Issue by Raynos** [artilleryio/artillery#1978]
Version info: 
```

VERSION
  artillery/2.0.0-34 linux-x64 node-v18.16.1

```

Running this command: 
```
$ pnpm artillery run --dotenv ./src/artillery/.env --output ./src/artillery/output/trivial-reads.json --config ./src/artillery/config.yaml ./src/artillery/scenarios/trivial-reads.yaml | tee logs.txt
```

I expected to see this happen:

Generate more load then the http server could handle.

Instead, this happened:

It only generates 450 QPS of outbound http requetss.

When I use `wrk` it can generate 50,000 QPS of load on my http server.

**Comment by Raynos** [comment]
I ran it again with different config values and it capped out at 4,500 QPS using what appears to be 8 CPUs

**Comment by hassy** [comment]
Thanks @Raynos. It'd be helpful to see at least some of the script you're running. There's a couple of common issues people who are used to tools like `wrk` or `ab` run into with Artillery. The workload model Artillery uses is very different. Artillery uses a [hybrid open-close model](https://www.artillery.io/blog/load-testing-workload-models) to emulate more typical real-world workloads rather than a closed one like `wrk`.

For a practical example, Artillery opens a new TCP connection for each virtual user, whereas `wrk` sends requests over a fixed number of connections. That means that a test script like this will show what seems like abysmal performance if compared to `wrk`:

```yaml
config:
  target: "http://www.example.com"
  phases:
    - duration: 60
      arrivalRate: 100
scenarios:
  - flow:
      get:
        url: "/"
```

Both tools will send 6,000 requests, but `wrk` will open 10 TCP connections at the start (that's the default iirc) and send 600 requests on each, whereas Artillery will open 6,000 TCP connections and send one request on each.

One way to improve performance would be to emulate what `wrk` does:

```yaml
config:
  target: "http://www.example.com"
  phases:
    # Create 10 virtual users, i.e. 10 connections
    - duration: 1
      arrivalCount: 10
scenarios:
  - flow:
    - loop:
        - get:
            url: "/"
       count: 600
```

But overall we never emphasized single node performance for trivial workload modeling. If all you need is to hammer a single endpoint with the same HTTP request in a loop - by all means use a tool like `wrk` (or better yet [`autocannon`](https://github.com/mcollina/autocannon) as it's also Node.js based and does not suffer from coordinated omission). Artillery's sweet spot is modeling complex workloads with multiple dependent steps and transactions, + the ability to [scale tests out on AWS Lambda or AWS Fargate](https://www.artillery.io/docs/load-testing-at-scale).
