### ISSUE TITLE
Artillery has a memory leak and uses an unreasonably high amount of RAM

### ISSUE THREAD

**Issue by Raynos** [artilleryio/artillery#1979]
![image](https://github.com/artilleryio/artillery/assets/479538/b7c7d940-3664-4430-8535-2c4c7f98e330)

The ram went upto 8 gigabytes.

**Comment by hassy** [comment]
Thanks @Raynos. Can you share any more information that could help reproduce the issue? How long has the test been running for, any plugins or custom code being used?

**Comment by Raynos** [comment]
the test case is pretty small

```
scenarios:
  - name: 'Fetch total raised'
    flow:
      - post:
          headers:
            Content-Type: application/json
            X-Sound-Client-Key: '{{clientKey}}'
          url: '/graphql?op=total-raised'
          json:
            query: |
              query TotalRaisedPlatformLoadTest {
                totalRaisedPlatform {
                  usd
                  ethInWei
                }
              }
          capture:
            json: '$.data.totalRaisedPlatform.usd'
            as: 'totalRaisedUsd'
```

The config is as follows

```
config:
  target: 'https://example.com'
  phases:
    - duration: 120
      arrivalRate: 100
      rampTo: 1000
  variables:
    clientKey: '{{ $processEnvironment.SERVICE_API_KEY }}'
    environment: 'staging'
  plugins:
    expect: {}
    metrics-by-endpoint:
      useOnlyRequestNames: true
    publish-metrics:
      - type: datadog
        # DD_API_KEY is an environment variable containing the API key
        apiKey: '{{ $processEnvironment.DD_API_KEY }}'
        prefix: 'artillery.publish_metrics_plugin.'
        tags:
          - 'environment:{{environment}}'
          - 'service:core-api'
  processor: 'processor.js'
  http:
    extendedMetrics: true
  ensure:
    maxErrorRate: 1
    max: 500
```
