### ISSUE TITLE
Artillery with socket.io-v3 latency min max avg p95 p99 not showing

### ISSUE THREAD

**Issue by exodia0x** [artilleryio/artillery#1983]
Artillery Version 2.0.0-34
OS : RHEL 8.8
[artillery-engine-socketio-v3] (https://github.com/ptejada/artillery-engine-socketio-v3)

### Example code:

```
config:
  target: "https://URL-Socket.io-Server"
  phases:
    - duration: 300
      arrivalRate: 100
      name: "100 Users for 5 minutes"
  engines:
   socketio-v3:
    extraHeaders: 
      key: "Teestingn server"
    transports: ["websocket"]

scenarios:
  - name: " > Send Message <"
    engine: socketio-v3
    flow:
      - emit:
          channel: "command"
          data:
            protocol:
            ..................
            header:
             .................
            body: {}
      - think: 600
```

### Final result output showing:
<img width="826" alt="image" src="https://github.com/artilleryio/artillery/assets/38641615/7c1e36a3-c978-46f9-b9a0-d9240e323673">
