### ISSUE TITLE
How to using processor js file in extraHeader

### ISSUE THREAD

**Issue by exodia0x** [artilleryio/artillery#2003]
Example Main artillery file 

```
config:
  target: "https://Domainnn"
  processor: "random.js"

  phases:
    - duration: 1
      arrivalRate: 1
      name: "100 Users for 5 minutes"

  engines:
   socketio-v3:
    extraHeaders: 
      key: "123189274198236"
    transports: ["websocket"]

scenarios:
  - name: " > Send Message and Check Respond "
    engine: socketio-v3
    flow:
      - function: "generateRandomData"
      - emit:
          channel: "command"
          event: "command"
          data:
            protocol:
              version: "1"
              command: "message"
              subCommand: ""
              invoke: "12343456827685"
              qos: "normal"
              topic: "mytopucc"
              token: "TOKENASDSS@@2222222"
              service: "AABC"
              diagMessage: ""
            header:
              version: "1.0"
              timestamp: "2023-05-04T14:51:06.157Z"
              orgService: "ABCModule"
              tid: "1234123.1232222"
              lastTid: "1234123.12312412312"
              session: "{{ mobile }}"
              transaction: "1234440000002929282AA"
              communication: "unicast"
              groupTags: []
              identity:
                device: "{{ mobile }}"
              tmfSpec: "123ddTMF"
              baseApiVersion: "4.0.0"
              schemaVersion: "1.0.0"
            body: {}
```

On random.js
```
module.exports = {
  generateRandomData
}

function generateRandomData (userContext, events, done) {
  userContext.vars.mobile = `${Math.floor(Math.random() * (9999999 - 1000000 + 1)) + 1000000}`
  return done()
}
```

I just want to make extraHeader "key", "session" and "device" is same number that generated.But now "session" and "device" is no problem but extraHeader can using function
