### ISSUE TITLE
artillery plugin issue

### ISSUE THREAD

**Issue by DanielGubay** [artilleryio/artillery#2017]
I'm running into an issue where I am using a load-gen aws cloud instance to run a load test. I setup and install artillery using Ansible, I'm using the 1.7.9 version of artillery. after running the playbook and sshing into the load gen, I try to run the test and run into two issues below.

Version info: 
```
1.7.9
```

Running this command: 
```
artillery run asciiart-load-test.yml
```

I expected to see this happen:

the test running and seeing data

Instead, this happened: 
1. issue 1
.   WARNING: Could not initialize plugin ensure (Unexpected token '.')
WARNING: Could not initialize plugin apdex (Unexpected token '.')

2. issue 2

Summary report @ 19:44:12(+0000) 2023-08-03
  Scenarios launched:  4525
  Scenarios completed: 0
  Requests completed:  0
  Mean response/sec: 149.49
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 4525 (100%)
  Errors:
    ECONNREFUSED: 4525

Files being used:
```
config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: http:example ip:80
  phases:
    - duration: 30
      arrivalRate: 0
      rampTo: 300
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
      thresholds:
        - http.response_time.p99: 100
        - http.response_time.p95: 75
scenarios:
  - flow:
      - loop:
        - get:
            url: "/1kb"
        count: 100
```
