### ISSUE TITLE
Same script under version 1.7.9 get much higher performance than 2.0.0-35.

### ISSUE THREAD

**Issue by SijieDingEsna** [artilleryio/artillery#2025]
I have the following script abc.yaml.
```
config:
  phases:
     - duration: 600
       arrivalRate: 100
       rampTo: 200
       name: Begin
   environments:
     sandbox:
       target: "https://eu.api-dev.avayacloud.com"
   variables:
     apikey:
       [...]
 
 scenarios:
   - name: "Call some apis"
     flow:
     - get:
         url: //hello-world-sandbox?apikey={{ apikey }}
```

When I use old version 1.7.9, the test can finish in 11 minutes and the output show the script can generate about 2000 scenarios in 10 seconds, and rps also arrive about 200 as well.

But when I use new version 2.0.0-35, the test needs 26 minutes and the output show the script can generate about 608 vusers in 10 seconds at most, and rps also only arrive about 60 at most.

Version info: 
```
2.0.0-35
```

Running this command: 
```
 artillery run -e sandbox  abc.yaml
```

I expected to see this happen:

*The new version should have similar performance as old version which was created 2 years ago.*

Instead, this happened:

*The new version get much poorer performance than old version which was created 2 years ago.*

<img width="783" alt="Screen Shot 2023-08-07 at 9 40 53 PM" src="https://github.com/artilleryio/artillery/assets/7290939/e4270063-3dfd-4637-86af-275d9c345ca3">

<img width="871" alt="Screen Shot 2023-08-07 at 9 40 22 PM" src="https://github.com/artilleryio/artillery/assets/7290939/5fe9250a-f626-4be8-85fe-ee2201d3eb3f">
