### ISSUE TITLE
Query String List Parameters aren't being encoded correctly

### ISSUE THREAD

**Issue by MaxBeauchemin** [artilleryio/artillery#2034]
List Query Parameters are not being encoded properly, instead it appears they are being comma-delimited, which many different API Controllers don't support by default. The standard way of accepting a List of values in a query parameter is to re-append the parameter name multiple times in the query string

Version info: 
```
Artillery: 2.0.0-35
Node.js:   v20.5.0
OS:        darwin
```

Running this command: 
```
artillery run test.yml
```

I expected to see this happen:

`HTTP GET : https://localhost:1234/api/v1/resource/byIds?ids=1&ids=2&ids=3`

Instead, this happened:

`HTTP GET : https://localhost:1234/api/v1/resource/byIds?ids=1,2,3`
`errors.The 'searchParams' value '1,2,3' must be a string, number, boolean or...`

Files being used:
```
config:
  target: "https://localhost:1234"
  phases:
    - name: "Light Load"
      duration: 30
      arrivalRate: 5

scenarios:
  - flow:
    - get:
        url: "/api/v1/Resource/GetByIds"
        headers:
          authorization: "Bearer {{ $processEnvironment.TOKEN }}"
        qs:
          ids:
            - 1
            - 2
            - 3
```
