### ISSUE TITLE
Docs: Default Configuration docs are wrong

### ISSUE THREAD

**Issue by cjthompson** [artilleryio/artillery#2036]
The [Default Configuration](https://www.artillery.io/docs/reference/engines/http#default-configuration) docs are wrong.

The current docs:
> You can set default configuration for the HTTP engine with config.http.defaults options.
> For example, to set a default header:
```
config:
  defaults:
    http:
      headers:
        X-My-Header: "123"
```

The description and example are wrong.

The [starter-kit example](https://github.com/artilleryio/artillery/blob/main/examples/starter-kit/scenarios/sample_task_03.yaml) uses the correct configuration.

The docs should be updated:
> You can set default configuration for the HTTP engine with config.defaults options.
> For example, to set a default header:
```
config:
  defaults:
    headers:
      X-My-Header: "123"
```
