### ISSUE TITLE
Running on Lambda fails with ArtilleryError: Error: Cannot find module '@oclif/core'

### ISSUE THREAD

**Issue by jakekgrog** [artilleryio/artillery#2085]
Version info: 
```
Artillery: 2.0.0-36
Node.js:   v18.16.0
OS:        darwin
```

Running this command: 
```
artillery run-lambda --region us-east-1 example.yml
```

I expected to see this happen:

The test runs

Instead, this happened:

```
λ Creating AWS Lambda function...
- Bundling test data
  - example.yml
  - package.json
  - package-lock.json
- Installing dependencies
- Creating zip package
Preparing AWS environment...
 - Lambda function: artilleryio-<ID>
 - Region: us-east-1
 - AWS account: <ACCOUNT_ID>
A Lambda function has exited with an error. Reason: ArtilleryError
{
  stdout: '',
  stderr: 'node:internal/modules/cjs/loader:1031\n' +
    '  throw err;\n' +
    '  ^\n' +
    '\n' +
    "Error: Cannot find module '@oclif/core'\n" +
    'Require stack:\n' +
    '- /var/task/node_modules/artillery/bin/run\n' +
    '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:873:27)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1100:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:108:18)\n' +
    '    at Object.<anonymous> (/var/task/node_modules/artillery/bin/run:8:16)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1076:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    "  requireStack: [ '/var/task/node_modules/artillery/bin/run' ]\n" +
    '}\n'
}
--------------------------------
Summary report @ 16:57:00(+0100)
--------------------------------

No measurements recorded during this period
```

Files being used:
```
config:
  target: https://api.mysite.com
  phases:
    - duration: 60
      arrivalRate: 1
      rampTo: 100
      name: Warm up phase
    - duration: 60
      arrivalRate: 5
      rampTo: 500
      name: Ramp up load
    - duration: 30
      arrivalRate: 50
      rampTo: 5000
      name: Spike phase
scenarios:
  - flow:
      - loop:
        - post:
            url: "/my-endpoint"
            headers:
              Api-Key: "<MY_API_KEY>"
              Content-Type: "application/json"
            json:
              key: "value"
        count: 1

```
