### ISSUE TITLE
payload with order sequence didn't work correctly with arrivalRate more than 1

### ISSUE THREAD

**Issue by fischel** [artilleryio/artillery#2115]
If I run a simple test over an userlist you will get a wrong behavior in the current verision.

script.yml:
```
config:
  target: "http://localhost"
  payload:
    path: "users.csv"
    fields:
      - "user"
    order: sequence
  phases:
    - duration: 3
      arrivalRate: 3
scenarios:
  - flow:
      - log: "user: {{ user }}"
```
users.csv
```
user1
user2
user3
user4
user5
user6
user7
user8
user9
```

With artillery version 1.7.9 I got this expected output:

```
Started phase 0, duration: 3s @ 13:37:30(+0200) 2023-09-05
user: user1
user: user2
user: user3
user: user4
user: user5
user: user6
user: user7
```

With version 2.0.0-36 I got this output:

```
user: user1
user: user1
user: user1
user: user2
user: user2
user: user2
user: user3
user: user3
user: user3


```
That really looks wrong. That's made it really more complex to write tests with single logins ...

Artillery: 2.0.0-36
Node.js:   v16.20.2
OS:        linux
