### ISSUE TITLE
Issue passing captured data to a variable

### ISSUE THREAD

**Issue by steverivers** [artilleryio/artillery#2140]
VERSION INFO:

Artillery: 2.0.0-36
Node.js:   v18.17.1
OS:        win32

I'm reasonably sure this is my error and not a bug but:

I'm having some issues with passing data captured in the before: stage to a variable in a flow; along the way I've found an issue with logging as well.

I've tried to do some searching and reading the docs and I'm still not sure if this my misunderstanding or a bug.

Here is a simplified and redacted version of the yml
The test works and generates the expected load.

```yml
config:
    #SNIP - 
before:
  flow:
    - post:
        variables:
            requestBodyTemplate: "./data/templates/template1.json"
            #SNIP - just setting up some variables here
        beforeRequest: generateGenericPostBody #script takes variables and uses a template file to populate the request body
        url: #"https://calling a different service than the one specified in config.target"
        json:
          "{{requestBody}}"
        capture:
          json: "$.array[0].id"
          as: "offerId"
scenarios:
    - name: "Part A"
      flow:
      - log: "Logging here and the captured value for offerId is substituted : {{ offerId }}"
      - post:
          log: "Logging here doesn't work but doesn't generate an error either : {{ offerId }}"
          variables:
            requestBodyTemplate: "./data/templates/template2.json"
            segmentId: "11112906"
            offerId: "{{ offerId }}"
            technicalCapability.internet.maxdownload: "1011"
          beforeRequest: generateGenericPostBody
          url: "/api/v1/request"
          headers:
            x_transaction_id: "Page PerfTesting {{ $uuid }}"
          json:
            "{{requestBody}}"
          afterResponse: "printStatus"
```

What I was expecting was the offerId captured in the before: stage to be substituted into the variable passed to the post request.

This is what I get after turning debug on (set DEBUG=http,http:capture,http:request)
```
Phase started: Warm up phase (index: 0, duration: 6s) 16:22:32(-0600)
Logging here and the captured value for offerId is substituted : 27587167
```

```
2023-09-13T22:22:33.996Z http request: {
  "url": "REDACTED",
  "method": "POST",
  "headers": {
    "user-agent": "Artillery (https://artillery.io)",
    "x_transaction_id": "c28ae5cf-7eb3-4eb4-875a-ea514cba1975"
  },
  "json": {
    "addons": [],
    "offerId": "{{ offerId }}",
    "offerCollectionId": "3XvsOTpQnDAxTXKXZiXxAk",
	//SNIPPED extra json
	}
}
```

**Comment by bernardobridge** [comment]
Hey @steverivers !

I think there may be a couple of things wrong with your scenario:

### 1. Variables defined inside request

```yaml
    - post:
        variables:
            requestBodyTemplate: "./data/templates/template1.json"
```
I'm guessing you're trying to use the `requestBodyTemplate` path inside your `generateGenericPostBody` function. But you can't define `variables` inside the request. That has to be done inside `config.variables`, or passed with `--variables`. You can also define them in javascript directly by setting `context.vars.requestBodyTemplate = "someString"` .

### 2. Logging inside request

Again, this is not valid Artillery DSL:

```yaml
  flow:
      - log: "Logging here and the captured value for offerId is substituted : {{ offerId }}" -> THIS IS CORRECT
      - post:
          log: "Logging here doesn't work but doesn't generate an error either : {{ offerId }}" -> THIS IS NOT CORRECT
```

The reason it doesn't generate an error is because Artillery doesn't error on unknown options (to allow developers to extend its engines), so `flow[1].post.log` will simply not be run by the http engine as `post` doesn't have that option.

---

As per `1.` that would probably be why you can't see the variables in the `post` request. There's no "variables per request" - they're set on a VU level, so you'll have to structure the scenario differently.

**Comment by steverivers** [comment]
@bernardobridge 
Thanks for the response, however I beg to differ on the first point referring to this comment https://github.com/artilleryio/artillery/issues/767#issuecomment-550379921 - took me a while looking through my browser history to find where I'd seen adding 'variables' to a request

Re-reading the whole thread again and looking deeper into what is passed in context I have solved my problem via the beforeRequest script.

However, it would be nice, and I know nice doesn't mean easy or even possible :), to have any instance of {{ variable_name }} in the yml to be replaced with the contents of that variable.

Closing this issue as it is a 'Steve' issue not an Artillery issue :)

Regards

**Comment by oguzhanakan0** [comment]
I have a similar use case where I want to retrieve an access token in `beforeRequest` for a set of users that are read from a payload CSV, eg:
```
config:
  ...
  payload:
    path: "users.csv"
    fields:
      - email

scenarios:
  - name: "Get"
    flow:
      - get:
          beforeRequest: "getAccessToken"
          variables:
            email: "{{ email }}"
          url: "/my-endpoint"
```
Do you think it's a good use case to add?
