### ISSUE TITLE
Cannot use variables in http qs: configuration

### ISSUE THREAD

**Issue by devilsgeographer** [artilleryio/artillery#2146]
Version info: 
```
Artillery: 2.0.0-37
Node.js:   v16.14.2
OS:        linux
```

Running this command: 
```
- get:
            url: "/1/query"
            qs:
              f: '{{ foo }}'
```

I expected to see this happen:

A request to "/1/query?f=`value of foo`"

Instead, this happened:

A request to "/1/query?f="       (variable is not recognized)

If we use
```
- get:
            url: "/1/query"
            qs:
              f: '${{ foo }}'
```
A request to "/1/query?f=**%24**`value of foo`" happens - note the extra $ prepended to the value, the variable is malformed. 

We have several variables, and need to use their values in the query params.  

It is the case that if I do not use the qs: configuration, and instead put all the querystring values on the url property, such as:
- get:
            url: "/1/query?f={{ foo }}.................."

This does seem to work, however it is very difficult to read and organize the values.  

Please fix whatever is reading and assigning variables, such that they can be applied to qs:  configuration.

**Comment by bernardobridge** [comment]
Hi @devilsgeographer,

How are you setting the variables that are being used (i.e. `foo`)? 

I just ran this sample script, and was able to see the query parameters reach my test server just fine:

```yaml
config:
  target: http://localhost:3000
  phases:
    - duration: 5
      arrivalRate: 1
      name: "Phase 1"
  variables:
    foo: 1

scenarios:
  - flow:
      - get:
          url: /
          qs: 
            foo: "{{ foo }}"
```

From my server:
```shell
Query Parameters: { foo: '1' }
```
