### ISSUE TITLE
Artillery with fargate is using ECR image outside our network

### ISSUE THREAD

**Issue by Vamsi0473** [artilleryio/artillery#2172]
Version info: 
```
Artillery: 2.0.0-37
Node.js:   v16.20.2
OS:        linux
```

Running this command: 
```
artillery run-fargate --region us-east-1 --cluster artillery-cluster --subnet-ids subnet-xxxxx asciiart-load-test.yml
```

I expected to see this happen:

expected to launch ecs fargate containers and execute test plans

Instead, this happened:

Checking AWS connectivity... [15:43:30]
Checking cluster... [15:43:30]
Tags: name:asciiart-load-test.yml [15:43:30]
Test run ID: tfc8p_kbyzkpar8pe8dxm55456qtfwdgxn7_wktp [15:43:30]
Preparing launch platform... [15:43:30]
Environment:
  Account:     XXX
  Region:      us-east-1
  Count:       1
  Cluster:     artillery-cluster
  Launch type: ecs:fargate
  Subnets:     subnet-xxxx
  

Preparing test bundle... [15:43:32]
Test bundle prepared... [15:43:32]
Test bundle contents:
┌────────────────────────┬─────────┬─────────────────────┐
│ Name                   │ Type    │ Notes               │
├────────────────────────┼─────────┼─────────────────────┤
│ asciiart-load-test.yml │ file    │                     │
├────────────────────────┼─────────┼─────────────────────┤
│ artillery-plugin-apdex │ package │ not in package.json │
└────────────────────────┴─────────┴─────────────────────┘

Launching workers... [15:43:33]
Waiting for Fargate... [15:43:34]
Waiting for workers to start: pending: 1 [15:44:05]
Waiting for workers to start: pending: 1 [15:44:15]
Waiting for workers to start: pending: 1 [15:44:25]
Waiting for workers to start: pending: 1 [15:44:36]
Waiting for workers to come online... [15:44:36]
Press Ctrl+C twice to stop the test
Stopping test run...
Cleaning up...

Files being used:
```
Follow test script I am using

config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: http://asciiart.artillery.io:8080
  phases:
    - duration: 60
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 60
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 30
      arrivalRate: 10
      rampTo: 30
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
      thresholds:
        - http.response_time.p99: 100
        - http.response_time.p95: 75
scenarios:
  - flow:
      - loop:
        - get:
            url: "/dino"
        - get:
            url: "/pony"
        - get:
            url: "/armadillo"
        count: 100
```
