### ISSUE TITLE
Unable to generate html reports from CLI

### ISSUE THREAD

**Issue by dudderzz** [artilleryio/artillery#2175]
Version info: 
```
Artillery: 2.0.0-37
Node.js:   v18
OS:        Mac OSX Ventura 13.5.2
 ```

Running this command: 
```
artillery report artillery-dev-report.json  
```

I expected to see this happen:

- HTML Report file generated in ./results directory of my project
- Preview of html report displayed in my IDE
- Report contains matching JSON report generated from completed artillery test

Instead, this happened:

- HTML Report file generated in ./results directory of my project
- Preview of html report shown with no metrics and following error "Errors at intervals"

Files being used:
```
config:
  target: https://service.name
  # target: http://localhost:8081

  plugins:
    expect: {}
  phases:
    - duration: 10
      arrivalRate: 1
      rampTo: 3
      name: "First Phase"
    - duration: 30
      arrivalRate: 3
      name: "Second Phase"
  defaults:
  ensure:
    maxErrorRate: 0
scenarios:
  - flow:
      - post:
          url: "/"
          expect:
            - statusCode: 200
```

https://i.imgur.com/cAqM1B8.png
