### ISSUE TITLE
Playwright tests not working with GitHub Action? browserType.launch: Executable doesn't exist at /github/home/.cache/ms-playwright/chromium-1076/chrome-linux/chrome

### ISSUE THREAD

**Issue by GeorgeXCV** [artilleryio/artillery#2198]
Version info: 
```
v2.0.0-37
```

Running this command: 
```
run tests/my-test.yml --output ./report.json
```

I expected to see this happen:

The test to run like it does locally.

Instead, this happened:

```
worker error, id: 1 browserType.launch: Executable doesn't exist at /github/home/.cache/ms-playwright/chromium-1076/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at Array.scenario (/home/node/artillery/node_modules/artillery-engine-playwright/index.js:56:38)
    at runScenario (/home/node/artillery/node_modules/@artilleryio/int-core/lib/runner.js:331:32)
    at EventEmitter.<anonymous> (/home/node/artillery/node_modules/@artilleryio/int-core/lib/runner.js:203:25)
    at EventEmitter.emit (/home/node/artillery/node_modules/eventemitter3/index.js:181:35)
    at UniformProcess.<anonymous> (/home/node/artillery/node_modules/@artilleryio/int-core/lib/phases.js:220:[12](https://github.com/nansen-ai/nansen-artillery/actions/runs/6467513570/job/17557698774#step:9:13))
    at /home/node/artillery/node_modules/arrivals/lib/index.js:47:10
    at NanoTimer.setInterval (/home/node/artillery/node_modules/nanotimer/lib/nanotimer.js:2[20](https://github.com//actions/runs/6467513570/job/17557698774#step:9:21):5)
    at Immediate._onImmediate (/home/node/artillery/node_modules/nanotimer/lib/nanotimer.js:203:68) ***
  name: 'Error'
```

Files being used:
Workflow:

```
name: Load Test

on:
    workflow_dispatch:
 
jobs:
  artillery:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup bun dependencies
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        
      - name: Install dependencies
        run: |
          bun install
          npx playwright install

      - name: Write the serviceAccountKey.json file 📝
        run: |
            echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json
 
      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run tests/my-test.yml --output ./report.json
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artillery-report
          # Reference the generated report in the file system.
          path: ./report.json
```

**Comment by hassy** [comment]
Try changing `npx playwright install` to `npx playwright@1.37.1 install`. Artillery's Playwright integration uses Playwright v1.37.1 ([source](https://github.com/artilleryio/artillery/blob/main/packages/artillery-engine-playwright/package.json#L14)), and browsers in Playwright need to be installed for specific versions.

**Comment by hassy** [comment]
Or better yet: run your tests on AWS Fargate ([docs](https://www.artillery.io/docs/load-testing-at-scale/aws-fargate)). That will let you generate more load (GitHub Actions is not a great place to actually execute the tests from), and you won't need to install browsers explicitly in the workflow.

**Comment by GeorgeXCV** [comment]
> npx playwright@1.37.1 install

Still get the same error.

**Comment by TestItEver** [comment]
> Or better yet: run your tests on AWS Fargate ([docs](https://www.artillery.io/docs/load-testing-at-scale/aws-fargate)). That will let you generate more load (GitHub Actions is not a great place to actually execute the tests from), and you won't need to install browsers explicitly in the workflow.

Hi @hassy! I've just got the same error on AWS Fargate, although a couple of days ago it works correctly. I didn't update or change anything in my project so far.

**Comment by harv-singh** [comment]
➕ was able to reproduce this

**Comment by nlyn** [comment]
I'm also getting this on Fargate

**Comment by freyjadomville** [comment]
We are also able to repro this with our Playwright test using Fargate, on the latest available release (v2.0.0-38).

**Comment by freyjadomville** [comment]
I *think* I have a way to get this working inside the flow itself so that the initialisation is done once per worker on Fargate - it behaves locally, so I'm hoping that I can execute the same command set on Fargate, depending on if npx itself is executable inside the Fargate cluster instance. I have some local issues to fix in my current Playwright test, but I'll report back separately once I have something working or not:

```yaml
before:
  flow:
    - function: "playwrightInit"
```

```javascript
async function playwrightInit(_context, _event, next) {
  const exec = require('child_process').exec;
  const util = require('util');

  const execPromise = util.promisify(exec)
  const { stdout, stderr } = await execPromise('npx playwright@1.37.1 install');
  console.log('stdout: ', stdout);
  console.log('stderr: ', stderr);
  next();
}
```
