### ISSUE TITLE
`ifTrue` Unexpected Behaviours

### ISSUE THREAD

**Issue by cjsaurusrex** [artilleryio/artillery#2253]
I've found that when using `ifTrue` conditions within my test script, the behaviour of it does not match up to what is described in the [documentation](https://www.artillery.io/docs/reference/engines/http#conditional-requests).

**Version info:** 
```
VERSION INFO:

Artillery: 2.0.0-38
Node.js:   v18.18.2
OS:        linux
```
_I've also tested this against 2.0.0-34_

**Running this command:** 
```
export DEBUG=http
artillery run <fileName>
```
_I've exported DEBUG=http, to make it easier to see what requests are being made_

**I expected to see this happen:**

Based on the documentation, `ifTrue` can work in 2 different ways. I've got problems with both.

1) > Set to a name of a scenario variable. If the variable is set, the request will be executed.
	- In the below example I've provided, the variable `hit200: true` is defined, and I have an `ifTrue: "hit200"`. 
		- **It was called** - This was expected behaviour.
	- In the same example, I've defined `hit201: false`. I've again got a GET to `/201` with an `ifTrue: hit201`.
		- **The endpoint was not called** - I would have expected it to be called.
	- Based on the documentation i've linked & quoted, both of these should have behaved in the same way, since it was just checking if a variable is set(as I've done no other conditional checks). However, **it appears they're taking the value of the variable into account.**

---

2. > Set to a simple conditional expression, which may refer to any of the scenario variables...
	- I've set 2 variables, `hit300: true` and `hit301: false`. I then have 2 GET requests, one with `ifTrue: "hit300 == true"` and `ifTrue: "hit301 == false"`
		- **Neither of these were called.** - I would have expected both to have been based on the conditional logic.
	- I've set 2 variables, `hit400: true` and `hit401: false`. I then have 2 GET requests, this time referencing the variables using `vars.hit400` and `vars.hit401`.
		- **Both of these were called** - This is what I expected. The only difference between this and the above is the addition of the `vars` prefix(which isn't shown anywhere in the docs).
	- I've set `hit402: false`, and have a GET with `ifTrue: "not vars.hit402 == true"`.
		- **This endpoint was not called** - I would have expected it to be(Confusing negation, sorry!)

---

I think the above should explain this well enough(it's quite tricky to explain). But to summarise, we're seeing conditional logic not work the same way everywhere and not adhere to the documentation.

Files being used:
```yaml
config:
  variables:
    hit200: true
    hit201: false
    hit300: true
    hit301: false
    hit400: true
    hit401: false
    hit402: false
  target: https://http.cat
  phases:
    - duration: 5
      arrivalRate: 1
      maxVusers: 1
scenarios:
  - name: Test Scenario
    flow:
      - get:
          name: "Hit 200"
          url: "/200"
          ifTrue: "hit200"
      - get:
          name: "Hit 201"
          url: "/201"
          ifTrue: "hit201"
      - get:
          name: "Hit 300"
          url: "/300"
          ifTrue: "hit300 == true"
      - get:
          name: "Hit 301"
          url: "/301"
          ifTrue: "hit301 == false"
      - get:
          name: "Hit 400"
          url: "/400"
          ifTrue: "vars.hit400 == true"
      - get:
          name: "Hit 401"
          url: "/401"
          ifTrue: "vars.hit401 == false"
      - get:
          name: "Hit 402"
          url: "/402"
          ifTrue: "not vars.hit402 == true"
```
