### ISSUE TITLE
Mean metric is not numeric

### ISSUE THREAD

**Issue by ematta** [artilleryio/artillery#2256]
Version info: 
```
v2.0.0-38
```

Running this command: 
```
yarn artillery run --output testrun.json tests/artillery/[playwright-test].yml
```

I expected to see this happen:

The `mean` to have a number

```
--------------------------------
Summary report @ 18:17:35(+0000)
--------------------------------

browser.http_requests: ......................................................... 4321
browser.page.CLS.https://url/:
  min: ......................................................................... 0
  max: ......................................................................... 0
  mean: ........................................................................ undefined
  median: ...................................................................... 0
  p95: ......................................................................... 0
  p99: ......................................................................... 0
browser.page.FCP.https://url/:
  min: ......................................................................... 427.2
  max: ......................................................................... 3348.1
  mean: ........................................................................ undefined
  median: ...................................................................... 1022.7
  p95: ......................................................................... 2276.1
  p99: ......................................................................... 2893.5
browser.page.LCP.https://url/:
  min: ......................................................................... 499.4
  max: ......................................................................... 3629.2
  mean: ........................................................................ undefined
  median: ...................................................................... 1587.9
  p95: ......................................................................... 3328.3
  p99: ......................................................................... 3605.5
browser.page.TTFB.https://url/:
  min: ......................................................................... 23.3
  max: ......................................................................... 425.8
  mean: ........................................................................ undefined
  median: ...................................................................... 46.1
  p95: ......................................................................... 295.9
  p99: ......................................................................... 415.8
vusers.completed: .............................................................. 27
vusers.created: ................................................................ 101
vusers.created_by_name.0: ...................................................... 101
vusers.failed: ................................................................. 74
vusers.session_length:
  min: ......................................................................... 45312.9
  max: ......................................................................... 85215.8
  mean: ........................................................................ undefined
  median: ...................................................................... 62964
  p95: ......................................................................... 83310.3
  p99: ......................................................................... 83310.3
vusers.skipped: ................................................................ 19
```

Instead, this happened:

`Mean` is `undefined`

```
--------------------------------
Summary report @ 18:17:35(+0000)
--------------------------------

browser.http_requests: ......................................................... 4321
browser.page.CLS.https://url/:
  min: ......................................................................... 0
  max: ......................................................................... 0
  mean: ........................................................................ undefined
  median: ...................................................................... 0
  p95: ......................................................................... 0
  p99: ......................................................................... 0
browser.page.FCP.https://url/:
  min: ......................................................................... 427.2
  max: ......................................................................... 3348.1
  mean: ........................................................................ undefined
  median: ...................................................................... 1022.7
  p95: ......................................................................... 2276.1
  p99: ......................................................................... 2893.5
browser.page.LCP.https://url/:
  min: ......................................................................... 499.4
  max: ......................................................................... 3629.2
  mean: ........................................................................ undefined
  median: ...................................................................... 1587.9
  p95: ......................................................................... 3328.3
  p99: ......................................................................... 3605.5
browser.page.TTFB.https://url/:
  min: ......................................................................... 23.3
  max: ......................................................................... 425.8
  mean: ........................................................................ undefined
  median: ...................................................................... 46.1
  p95: ......................................................................... 295.9
  p99: ......................................................................... 415.8
vusers.completed: .............................................................. 27
vusers.created: ................................................................ 101
vusers.created_by_name.0: ...................................................... 101
vusers.failed: ................................................................. 74
vusers.session_length:
  min: ......................................................................... 45312.9
  max: ......................................................................... 85215.8
  mean: ........................................................................ undefined
  median: ...................................................................... 62964
  p95: ......................................................................... 83310.3
  p99: ......................................................................... 83310.3
vusers.skipped: ................................................................ 19
```

Files being used:
```
config:
  target: https://url
  includeFiles:
    - ../../.yarnrc.yml
    - ../../.yarn/
  tls:
    rejectUnauthorized: false
  engines:
    playwright: 
      launchOptions:
        headless: true
      contextOptions:
        baseURL: https://url
  processor: "./index.bundle.js"
  phases:
    # - name: initLoad
    #   duration: 60
    #   arrivalCount: 1
    #   maxVusers: 1
    - name: normalLoad
      duration: 300
      arrivalRate: 5
      maxVusers: 50
scenarios:
  - engine: playwright
    testFunction: "func"

```
