### ISSUE TITLE
$env not templating correctly in config

### ISSUE THREAD

**Issue by bernardobridge** [artilleryio/artillery#2258]
**Version info:** 
```
2.0.0-38, but should be in prior versions too
```

**Running this command:**
artillery run

**I expected to see this happen:**

Variable being substituted

**Instead, this happened:**

Variable was not substituted (had to use the old `$processEnvironment`)

**Files being used (example of config):**
```
  engines:
    playwright:
      contextOptions:
        extraHTTPHeaders:
          someHeader: '{{ $env.SOME_HEADER }}'
```
