### ISSUE TITLE
Artillery lambda stuck after the load test

### ISSUE THREAD

**Issue by roisec** [artilleryio/artillery#2260]
When the script starts to test, 
I encourage in lambda logs: 
"WARNING: Plugin sqs-reporter specified but module artillery-plugin-sqs-reporter could not be found (MODULE_NOT_FOUND) warn"
 
```
config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: http://example.com
  phases:
    - duration: 10
      arrivalRate: 10
      # rampTo: 10
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    publish-metrics:
      - type: cloudwatch
        region: us-east-1

scenarios:
  - flow:
      - get:
          url: "/package.2json"
      # - get:
      #     url: "/pony"
      # - get:
      #     url: "/armadillo"

```
