### ISSUE TITLE
feat(engines/socketio): Allow for receiving responses without requiring input

### ISSUE THREAD

**Issue by josh-coderpad** [artilleryio/artillery#2286]
https://github.com/artilleryio/artillery/pull/2139#issuecomment-1741425517

It'd be nice to be able to specify:

```yaml
    flow:
      - response:
          channel: serviceStatus
          data: ready
```
rather than:
```yaml
    flow:
      - emit:
          channel: ignoreme
          data: ignore this (sent from load tests)
        response:
          channel: responseChannel
          data: some data I get automatically without needing to send anything
```
