### ISSUE TITLE
Discrepancies with dynatrace publish metrics plugin 

### ISSUE THREAD

**Issue by Thilaknath** [artilleryio/artillery#2308]
Version info: 
```
2.0.0-38
```

Running this command: 
```
  sh "/home/node/artillery/bin/run version"
  sh "/home/node/artillery/bin/run run --output reports/${testName}.json tests/performance/${testName}.yml"
  sh "/home/node/artillery/bin/run report --output reports/${testName}.html reports/${testName}.json"
```

I expected to see this happen:

*The metrics reported in the report.json to be in sync with the metrics reported to dynatrace so we could plot graphs*

Instead, this happened:

*Metrics are out of sync*
I am also noticing the following warnings and errors in the console. 
**Warning**
```
  plugin:publish-metrics:dynatrace Dynatrace reporter: WARNING Metric key 'plugins.metrics-by-endpoint./armadillo (armadillo).codes.200' does not meet Dynatrace Ingest API's requirements and will be dropped. More info in the docs (https://docs.art/reference/extensions/publish-metrics#dynatrace). +1ms
  plugin:publish-metrics:dynatrace Dynatrace reporter: WARNING Metric key 'plugins.metrics-by-endpoint./dino (dino).codes.200' does not meet Dynatrace Ingest API's requirements and will be dropped. More info in the docs (https://docs.art/reference/extensions/publish-metrics#dynatrace). +0ms
  plugin:publish-metrics:dynatrace Dynatrace reporter: WARNING Metric key 'plugins.metrics-by-endpoint./pony (pony).codes.200' does not meet Dynatrace Ingest API's requirements and will be dropped. More info in the docs (https://docs.art/reference/extensions/publish-metrics#dynatrace). +0ms
  plugin:publish-metrics:dynatrace Dynatrace reporter: WARNING Metric key 'plugins.metrics-by-endpoint.response_time./armadillo (armadillo)' does not meet Dynatrace Ingest API's requirements and will be dropped. More info in the docs (https://docs.art/reference/extensions/publish-metrics#dynatrace). +0ms
  plugin:publish-metrics:dynatrace Dynatrace reporter: WARNING Metric key 'plugins.metrics-by-endpoint.response_time./dino (dino)' does not meet Dynatrace Ingest API's requirements and will be dropped. More info in the docs (https://docs.art/reference/extensions/publish-metrics#dynatrace). +0ms
  plugin:publish-metrics:dynatrace Dynatrace reporter: WARNING Metric key 'plugins.metrics-by-endpoint.response_time./pony (pony)' does not meet Dynatrace Ingest API's requirements and will be dropped. More info in the docs (https://docs.art/reference/extensions/publish-metrics#dynatrace). +0ms
  plugin:publish-metrics:dynatrace Sending metrics to Dynatrace +0ms

```
**Error**
```
Apdex score: 0.6377952755905512 (poor)
⠧   plugin:publish-metrics:dynatrace Sending event to Dynatrace +165ms
  plugin:publish-metrics:dynatrace Cleaning up +1ms
  plugin:publish-metrics:dynatrace Waiting for pending request ... +0ms
⠸   plugin:publish-metrics:dynatrace There has been an error in sending metrics to Dynatrace:  HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1700595079319,
    socket: 1700595079319,
    lookup: 1700595079354,
    connect: 1700595079454,
    secureConnect: 1700595079560,
    upload: 1700595079560,
    response: 1700595079911,
    end: 1700595079911,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 35,
      tcp: 100,
      tls: 106,
      request: 0,
      firstByte: 351,
      download: 0,
      total: 592
    }
  }
} +431
```

Files being used:
```
config:
  target: http://asciiart.artillery.io:8080
  phases:
    - duration: 15
      arrivalRate: 50
      rampTo: 100
      name: Warm up phase
    - duration: 10
      arrivalRate: 20
      rampTo: 50
      name: Ramp up load
#    - duration: 15
#      arrivalRate: 10
#      rampTo: 30
#      name: Spike phase
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
    publish-metrics:
      - type: dynatrace
        # DY_API_TOKEN is an environment variable containing the API key
        apiToken: REPLACED-BY-PIPELINE
        envUrl: "https://apm.cf.company.dyna.ondemand.com/e/MASKED"
        prefix: "artillery."
        dimensions:
          - "service:orderAsyncService"
          - "test:createOrder"
          - "host_id:1.2.3.4"
        event:
          title: "Loadtest"
          entitySelector: "type(SERVICE),entityName.equals(MyService)"
          properties:
            - "Tool:Artillery"
            - "Load per minute:100"
            - "Load pattern:development"
  apdex:
    threshold: 100
  ensure:
    thresholds:
      - http.response_time.p99: 100
      - http.response_time.p95: 75
  metrics-by-endpoint:
    useOnlyRequestNames: true

scenarios:
  - flow:
      - get:
          url: "/dino"
          name: dino
      - get:
          url: "/pony"
          name: pony
      - get:
          url: "/armadillo"
          name: armadillo
```

Also kindly note. I am publishing these metrics from a jenkins job. When i execute the tests from my local. The correct metrics seem to be reported to dynatrace. But when I run the job from jenkins. Something seems a miss. I have setup the job following artillery documentation. 

**Something to note**: While executing from local, I run one test at a time. Metrics are published properly. When the jenkins job runs one test at a time as well metrics are correctly published. When there are more than 1 tests -> Thats where the issue seems to appear with one test reporting wrong metrics.

Kindly refer the screenshots from the jenkins console and also the screenshot showing the metric reported in dynatrace. 
![Screenshot 2023-11-21 at 2 56 00 PM](https://github.com/artilleryio/artillery/assets/3452073/b0bb46f7-97da-448c-97be-819efdb8cc02)
![Screenshot 2023-11-21 at 2 58 55 PM](https://github.com/artilleryio/artillery/assets/3452073/43d3419f-7388-4718-a568-33cbdfca509b)
