### ISSUE TITLE
Test file ignores duration, keeps running until cancelled

### ISSUE THREAD

**Issue by GeorgeXCV** [artilleryio/artillery#2310]
Have this Artillery test that is set to run for 1H but it always runs over it and doesn't stop until I cancel it.

Version info: 
```
Artillery: 2.0.0-37
Node.js:   v20.6.1
OS:        darwin
```

Running this command: 
```
    "sign-up": artillery run tests/sign-up.yml",
```

I expected to see this happen:

The test to run for 1 hour.

Instead, this happened:

The doesn't stop running unless I cancel it.

Files being used:
**sign-up.yml:**
```
config:
  target: https://auth.url.dev/
  phases:
    - duration: 3600
      arrivalCount: 8000
  processor: "./sign-up.js"
scenarios:
    - flow:
      - function: "signUpFreeUser"
```

**sign-up.js:**
```
module.exports = { signUpFreeUser };
const { createAccount } = require('../plugins/sign-up');
require('dotenv').config();

async function signUpFreeUser() {
    const email = `qa+${Date.now()}@dev.com`;
    createAccount(email)
}
```

**/sign-up.js:**
```
const fetch = require('node-fetch');
require('dotenv').config();

async function createAccount(email) {

    const userBody = {
        email: email,
    }

    const requestOptions = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(userBody),
    };

    try {
        const response = await fetch('https://auth.url.dev/sign-up', requestOptions);
        console.log(response)
        if (response.status === 200) {
            console.log(`Created account for ${email}`);
            return
        } else {
            throw new Error(`Unexpected response status: ${response.status}`);
        }
    } catch (error) {
        throw new Error(`Error creating account: ${error.message}`);
    }
}

module.exports = { createAccount }
```
