### ISSUE TITLE
InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes with artillery lambda

### ISSUE THREAD

**Issue by rakesh-tirupathi** [artilleryio/artillery#2337]
Version info: 
```
Artillery: 2.0.1
Node.js:   v20.0.0
```

Running this command: 
```
run --platform aws:lambda --platform-opt region=us-west-2 --count 1 asciiart-load-test.yml

artillery run-lambda --region=us-west-2 asciiart-load-test.yml
```

I expected to see this happen:

when i run the command above i expect it to successfully create the lambda function and execute it

Instead, this happened:

λ Creating AWS Lambda function...
- Bundling test data
  - asciiart-load-test.yml
- Installing dependencies
- Creating zip package
Preparing AWS environment...
⠴ /Users/user/.nvm/versions/node/v20.0.0/lib/node_modules/artillery/node_modules/aws-sdk/lib/protocol/json.js:80
  resp.error = util.error(new Error(), error);

Files being used:
```
config:
  target: http://asciiart.artillery.io:8080
  phases:
    - duration: 30
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 30
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 10
      arrivalRate: 10
      rampTo: 30
      name: Spike phase
scenarios:
  - flow:
    - loop:
      - get:
          url: "/dino"
      - get:
          url: "/pony"
      - get:
          url: "/armadillo"
      count: 10
```
This works successfully when i used the `v2.0.0-31` version but every other version that i tried it failed with above error.
