### ISSUE TITLE
Artillery fake-data not working with socketio engine

### ISSUE THREAD

**Issue by ZebboKlaufix** [artilleryio/artillery#2371]
Version info:

```
Artillery: 2.0.3
Node.js: v20.2.0
OS: win32
```

Running this command:

```
artillery run ./artillery/cfg.yaml --output ./artillery/report.json && artillery report --output ./artillery/report.html ./artillery/report.json
```

I expected to see this happen:

```
| Making request with query: Rose Fan
\ Making request with query: Kazuo Mohamed
- Making request with query: Musa Hussein
/ Making request with query: Amphon Rumbelow
| Making request with query: Asha Krüger
\ Making request with query: Ram Őllösová
\ Making request with query: Sibongile Méndez
- Making request with query: Gary Fröhlich
/ Making request with query: Rajendra Clarke
```

Instead, this happened:
As soon as I enable the socketio engine the fake-data plugin stops working.

```
| undefined
\ undefined
- undefined
/ undefined
| undefined
\ undefined
\ undefined
- undefined
/ undefined
```

Files being used:

```
config:
  target: "http://127.0.0.1:5000"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 10
      arrivalRate: 1
  plugins:
    fake-data: {}
 
scenarios:
  - name: My Socket.IO test
    engine: socketio # <----- Enabling the Socket.IO engine causes the error to happen
    flow:
      - log: "Making request with query: {{ $randFullName() }}"
      - emit:
          channel: "join_room"
          data: "demo"
```
