### ISSUE TITLE
Artillery Socket.io nested query params

### ISSUE THREAD

**Issue by rauldeheer** [artilleryio/artillery#2372]
We're trying to test our websocket (using socket.io) connection. For our websocket to accept a connection, we need to authenticate. This all works great inside our application, but now that we're trying to test it we're bumping into some issues that we cannot seem to resolve.

Please see this Artillery file:

```yaml
config:
  target: "http://localhost:3000"
  phases:
    - duration: 3
      arrivalRate: 1        
  processor: "./gameload.js"
  socketio:
    transports: ["websocket"]
    query: "auth[token]={{ token }}"
  variables:
    gameId: "1"


scenarios:
  - name: "Test game channel connect"
    engine: socketio
    beforeRequest: "generateToken"
    flow:
      - function: "getNextUser"
      - post:
          url: "/api/auth/login/password"
          json:
            username: "{{ username }}"
            password: "{{ password }}"
          capture:
            json: '$.token'
            as: 'token'
      - log: "Making WS request with token: {{ token }}"
      - namespace: "/game"
        emit:
          data: "sdf"
        response:
          capture:
            json: "$"
            as: "res"
      - log: "response={{res}}"
```

And this JS file (gameload.js):

```js
const fs = require("fs");

let index = 0;

const credentials = JSON.parse(fs.readFileSync("credentials.json"));

function getNextUser(userContext, events, done) {
  userContext.vars.username = credentials[index].username;
  userContext.vars.password = credentials[index].password;
  index++;
  return done();
}

module.exports = {
  getNextUser,
  generateToken: function (userContext, events, done) {
    // Logic to generate or fetch the token
    const token = 'your_dynamic_token';
    userContext.vars.token = token; // Set the token in the user context
    return done();
  }
};
```

Now the problem is that `{{ token }}` is always undefined. We're guessing that the reason behind this is that the config is initialised at the starting point of the test. How can we achieve what we want to achieve?

Thanks in advance!

Version info: 
- Artillery -> v2.0.3
- NodeJS -> v21.4.0
- OS -> darwin
