### ISSUE TITLE
localhost / 127.0.0.1 do not work in a github runner

### ISSUE THREAD

**Issue by erzz** [artilleryio/artillery#2376]
When trying to reach either localhost or 127.0.0.1 in the actions runner there is only `errors.ECONNREFUSED`  Same commands and plan work fine locally.  Added a wget step as debug in the workflow and that also responds.  Seems to be specifically the action

Examples would be:

**Plan**
```
config:
  plugins:
    ensure:
      p95: 500
      maxErrorRate: 1
  target: "http://127.0.0.1:8888"
  timeout: 10
  phases:
    - duration: 5
      arrivalRate: 1
      rampTo: 3
scenarios:
  - name: "get-homepage"
    flow:
      - get:
          url: "/index.html"
```

**locally started nodejs application**
```
- name: Launch local site
  run:  yarn start && sleep 10

- name: Debug
  run:  wget http://127.0.0.1:8888

- name: Execute Artillery
  uses: artilleryio/action-cli@v1.1.1
  with:
    command: run ${{ inputs.artillery-plan }} --output artillery-report.json
```

**Result**
```
Debug step:

--2023-11-07 15:21:18--  http://127.0.0.1:8888/
Connecting to 127.0.0.1:8888... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

     0K                                                        [53](https://github.com/org/repo/actions/runs/6786577243/job/18447410008#step:9:54).9M=0s


Artillery Step:
--------------------------------
Summary report @ 14:56:16(+0000)
--------------------------------

errors.ECONNREFUSED: ........................................................... 11
http.request_rate: ............................................................. 2/sec
http.requests: ................................................................. 11
vusers.created: ................................................................ 11
vusers.created_by_name.get-homepage: ........................................... 11
vusers.failed: ................................................................. 11
Log file: artillery-report.json

Checks:
fail: maxErrorRate < 1
fail: p[95](https://github.com/org/repo/actions/runs/6786242038/job/18446321521#step:10:96) < 500
```

Same issue for a locally started docker image (easy replication example):

```
- name: Launch local site
  run:  docker run -d -p 8888:80 nginx:latest

- name: Debug
  run:  wget http://127.0.0.1:8888

- name: Execute Artillery
  uses: artilleryio/action-cli@v1.1.1
  with:
    command: run ${{ inputs.artillery-plan }} --output artillery-report.json
```
