### ISSUE TITLE
Errors on aws fargate test errors.EMFILE 

### ISSUE THREAD

**Issue by pr1ntr** [artilleryio/artillery#2420]
Version info: 
```
2.0.4
win11
node 18
```

Running this command: 
```
artillery run-fargate --region us-west-2 xxxx.dev.yml --output dev.server.json
```

I expected to see this happen:
Tests to run without EMFILE errors
Tests to run with correct response times
Instead, this happened:

I check the logs on ECS and saw these happening:
```

January 16, 2024 at 11:16 (UTC-8:00) | UnknownEndpoint:  Inaccessible host: `sqs.us-west-2.amazonaws.com' at port `undefined'.  This service may not be available in the `us-west-2' region. | -
-- | -- | --
January 16, 2024 at 11:16 (UTC-8:00) | hostname: 'sqs.us-west-2.amazonaws.com', | -
January 16, 2024 at 11:16 (UTC-8:00) | originalError: Error: getaddrinfo EMFILE sqs.us-west-2.amazonaws.com | -
January 16, 2024 at 11:16 (UTC-8:00) | hostname: 'sqs.us-west-2.amazonaws.com',

```

the console output also doesn't show me the response times, just does this:
```
plugins.metrics-by-endpoint.response_time./submit:
  min: ......................................................................... Infinity
  max: ......................................................................... -Infinity
  mean: ........................................................................ NaN
  median: ...................................................................... 0
  p95: ......................................................................... 0
  p99: ......................................................................... 0

```

I am trying to load test a bunch of lambdas, I want to scale up to like 30k/s per region so I need to get these errors out of the way.

Files being used:
```
config:
  target: "https://xxxxxx.com"
  phases:
    - duration: 10m
      arrivalRate: 250
      rampTo: 0
      name: 'hammer'


scenarios:
  - flow:
      - loop:
          - options:
              url: "/submit"
              headers:
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                "Access-Control-Request-Method": "post"
                "Origin": "https:/xxxxx.com"
          - post:
              url: "/submit"
              json:
                fullName: "{{$randomString(7)}} {{$randomString(7)}}"
                email: "{{$randomString(7)}}@{{$randomString(7)}}.com"
                code: "{{$randomString(22)}}"
              headers:
                "Content-Type": "application/json"
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                "Origin": "https://xxxxxx.com"

        count: 100

```

**Comment by pr1ntr** [comment]
If i use --count, will it be like 250 * 100 * `count` ?

**Comment by bernardobridge** [comment]
Not exactly, @pr1ntr. 250 * `count` will be the number of VU arriving per second. Because each VU will take longer to complete due to the usage of `loop`, then the actual RPS will pile up per second (while there are VU's from previous iterations running). It's hard to predict exactly how much, because it depends on back-pressure from your server.

It's better to spread the test horizontally with a high `--count` than use loop for your use case I think.

**Comment by pr1ntr** [comment]
so scaling out my workers is creating issues. I tried to do something like 10 to  40 of them and not all of them make it. Here is a log of one of the failed ones.
https://gist.github.com/pr1ntr/f4629bca5decbe0a07f2ca0a116d8a3f

here is my yaml

```
config:
  http:
    timeout: 30
  target: "https://dev-api.xxxxxxx.com"
  phases:
    - duration: 2m
      arrivalRate: 167 # Approximately one-third of 500 for each region
      rampTo: 1667 # Approximately one-third of 5000
      name: 'Ramp Up - Game Start to Half-Time'
    - duration: 30s
      arrivalRate: 1667
      rampTo: 3333 # Approximately one-third of 10000
      name: 'Full Swing - Half-Time Show'
    - duration: 2m
      arrivalRate: 3333
      rampTo: 667 # Approximately one-third of 2000
      name: 'Cool Down - Second Half to Game End'


scenarios:
  - flow:
    - options:
        url: "/submit"
        headers:
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          "Access-Control-Request-Method": "post"
          "Origin": "https://dev.xxxxxxx.com"
    - post:
        url: "/submit"
        json:
          fullName: "{{$randomString(7)}} {{$randomString(7)}}"
          email: "{{$randomString(7)}}@{{$randomString(7)}}.com"
          code: "{{$randomString(22)}}"
        headers:
          "Content-Type": "application/json"
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          "Origin": "https://dev.xxxxxxx.com"
```

**Comment by bernardobridge** [comment]
Hi @pr1ntr . You have to modify your phases config to be spread across the workers. Each worker runs a copy of your script and config. So right now you're doing the same as before: too much per worker.

Try something like this:

**41 Workers** (I used 41 because the math for approximations worked out a bit better than 40)
```yaml
config:
  http:
    timeout: 30
  target: "https://dev-api.xxxxxxx.com"
  phases:
    - duration: 2m
      arrivalRate: 4 # Approximately one-third of 500 (4 * 41 * 3) for each region
      rampTo: 41 # Approximately one-third of 5000 (41 * 41 * 3)
      name: 'Ramp Up - Game Start to Half-Time'
    - duration: 30s
      arrivalRate: 41
      rampTo: 82 # Approximately one-third of 10000 (82 * 41 * 3)
      name: 'Full Swing - Half-Time Show'
    - duration: 2m
      arrivalRate: 82
      rampTo: 16 # Approximately one-third of 2000 (16 * 41 * 3)
      name: 'Cool Down - Second Half to Game End'
```

Then you can run your test with `--count 41` in each of the 3 regions you seem to be testing.
