### ISSUE TITLE
Durations not being honored on fargate

### ISSUE THREAD

**Issue by pr1ntr** [artilleryio/artillery#2433]
Version info: 
```
2.0.4
node18
fargate
```

Running this command: 
```
artillery run-fargate --region us-west-2 xxx.dev.yml --count 2 --output xxx.dev.json
```

I expected to see this happen:
Runs for a total of 
4m30s
Instead, this happened:
runs for 1m8s

Not sure if I am doing this wrong but the report html says:
![image](https://github.com/artilleryio/artillery/assets/1272089/3bd4757f-e74e-4029-a642-5c9e9c54c70e)

Files being used:

```
config:
  http:
    timeout: 30
  target: "https://dev-api.xxxxxx.com"
  phases:
    - duration: 2m
      arrivalRate: 167 # Approximately one-third of 500 for each region
      rampTo: 1667 # Approximately one-third of 5000
      name: 'Ramp Up - Game Start to Half-Time'
    - duration: 30s
      arrivalRate: 1667
      rampTo: 3333 # Approximately one-third of 10000
      name: 'Full Swing - Half-Time Show'
    - duration: 2m
      arrivalRate: 3333
      rampTo: 667 # Approximately one-third of 2000
      name: 'Cool Down - Second Half to Game End'


scenarios:
  - flow:
    - options:
        url: "/submit"
        headers:
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          "Access-Control-Request-Method": "post"
          "Origin": "https://dev.xxxxx.com"
    - post:
        url: "/submit"
        json:
          fullName: "{{$randomString(7)}} {{$randomString(7)}}"
          email: "{{$randomString(7)}}@{{$randomString(7)}}.com"
          code: "{{$randomString(22)}}"
        headers:
          "Content-Type": "application/json"
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          "Origin": "https://dev.xxxx.com"


```
