### ISSUE TITLE
Fargate - arrivalCount seems doesn't work as expected

### ISSUE THREAD

**Issue by robin-miro** [artilleryio/artillery#2494]
Version info: 
```
Artillery: 2.0.5
Node.js:   v21.6.1
OS:        darwin
```

Running this command: 
```
config:
      phases:
        - duration: 50m
          arrivalCount: 300
```
run-fargate --count = 10

**I expected to see this happen:**
Based on the doc, it should mean creating 300 VU in 3000 seconds, which means creating 1 VU per 10 seconds around, as I said fargate count equals 10, then means 10 VU per 10 seconds around in total. 

**Instead, this happened:**

not enough VUs are created, instead of 10 VU per 10 seconds, it randomly just creates 2 VU per 10 seconds. Those missing VUs are also **Not** failed.

<img width="1276" alt="Screenshot 2024-02-15 at 21 40 56" src="https://github.com/artilleryio/artillery/assets/95623827/fdf08d99-a78b-46c2-b93e-a6eacb9f2010">
<img width="1278" alt="Screenshot 2024-02-15 at 21 40 41" src="https://github.com/artilleryio/artillery/assets/95623827/c170b51f-0a9c-41b5-8e6f-cee7ff51723f">

**Additional notice**
When I switch to 50m with 600 VUs, meaning 1 VU per 5 seconds, it becomes a bit better. 

**Why this is important**
When we generate a latency benchmark instead of a Load/Stress test, we expect the load can be similar and with a small and stable load, meaning the VUs are roughly can have the same amount, and help to compare the latency benchmarks from different regions.

**Idea**
Because it's hard to check all workers from CloudWatch, as It's hard to figure out which Fargate/Worker doesn't generate VUs,  maybe it gonna be a bit easier to verify it with Artillery Cloud.

**Comment by robin-miro** [comment]
More findings: 
* I checked the summary vu.completed from each fargate, every thing is 100% correct, the number is expected

Meaning, the issue is happened from Fargate -> SQS -> AWS CLI, however I'm not sure how to check more details

**Comment by hassy** [comment]
thanks @robin-miro! will try to replicate here

**Comment by hassy** [comment]
btw @robin-miro feel free to drop me a line on hveldstra@artillery.io for an Artillery Cloud invite, would love for you to try it

**Comment by robin-miro** [comment]
Hey @hassy , thanks for sharing, I will drop you an email to have a look for collaboration for using the cloud. 

Just share some very interesting findings maybe you can reproduce in your test environment.

**Case #1 :**
10 Fargates 
config:
```
      phases:
        - duration: 10m 
          arrivalCount: 120 
```

Results:
```
vusers.completed: .............................................................. 376
vusers.created: ................................................................ 376
vusers.failed: ................................................................. 0
```

**Case #2 :**
10 Fargates 
config:
```
      phases:
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
        - duration: 60 
          arrivalCount: 12 # per fargate, 5 sec will have a new virtual user
```

Results:
```
vusers.completed: .............................................................. 1200
vusers.created: ................................................................ 1200
vusers.failed: ................................................................. 0
```
