### ISSUE TITLE
websocket.messages_received not displayed in stats

### ISSUE THREAD

**Issue by BalzySte** [artilleryio/artillery#2517]
Artillery fails to caputure websocket responses and display the messages_received count and rate

**Version info:** 
```
Artillery: 2.0.6
Node.js:   v21.5.0
OS:        linux
```

**Running this command:** 
```
artillery run test.yml
```

**I expected to see this happen:**

I expected to see the following stats on top of all the others 
```
websocket.messages_received
websocket.receive_rate
```
The websocket (wss://echo.websocket.org) echoes back as expected, verified with Postman.

**Instead, this happened:**

```
All VUs finished. Total time: 26 seconds

--------------------------------
Summary report @ 14:30:24(+0530)
--------------------------------

vusers.completed: .............................................................. 200
vusers.created: ................................................................ 200
vusers.created_by_name.My WebSocket test: ...................................... 200
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 4326
  max: ......................................................................... 4588.5
  mean: ........................................................................ 4382.4
  median: ...................................................................... 4403.8
  p95: ......................................................................... 4492.8
  p99: ......................................................................... 4583.6
websocket.messages_sent: ....................................................... 400
websocket.send_rate: ........................................................... 20/sec
artillery run test.yml  11.56s user 1.19s system 43% cpu 29.190 total
```

**Files being used:**

test.yml configuration
```
config:
  target: "wss://echo.websocket.org"
  phases:
    - duration: 20
      arrivalRate: 10
  ws:
    # Set WebSocket subprotocols:

scenarios:
  - name: My WebSocket test
    engine: ws # Enable the Socket.io engine
    flow:
      - send: "Hello world!"
      - think: 3
      - send: "Booo"
      - think: 1

```

**Others:**
On top of that, debug messages printed with `DEBUG=ws artillery run test.yml` only shows SENT messages. There's no mention of RECEIVED messages.

**Comment by niallcaro** [comment]
+1, also noticed the same when comparing our results to the WebSocket engine docs.

Version info:
```
Artillery: 2.0.6
Node.js:  v16.20.2
OS: darwin
```

**Comment by livecloud-labs** [comment]
After a bit of digging through the ws engine codebase, it looks as though the `messages_received` values are only applied to the output when `capture` is present (https://github.com/artilleryio/artillery/blob/65dd5386c960e1d93f7e208784036e91fb663d00/packages/core/lib/engine_ws.js#L184C1-L185C1).

This worked for me...

```
scenarios:
  - engine: ws
    name: client_pubsub
    flow:
      - connect:
          function: connectHandler
      - function: generateRoomId
      - function: generateRoomJoinEvent
      - send: '{{ roomJoinEvent }}'
      - function: generateRoomSubscribeEvent
      - send:
          text: '{{ roomSubscribeEvent }}'
          capture: # capture present here
            - json: '$.body'
              as: message
      - loop:
          - function: generateClientMessageEvent
          - send: '{{ clientMessageEvent }}'
        count: 10
```

**Comment by livecloud-labs** [comment]
After some digging through the codebase, it looks as though the `websocket.messages_received` and `websocket.receive_rate` values are only applied to the output when `capture` is enabled for a specific step.

https://github.com/artilleryio/artillery/blob/65dd5386c960e1d93f7e208784036e91fb663d00/packages/core/lib/engine_ws.js#L188

Unfortunately, in order to enable `capture` you would have to use the legacy `payload` option when sending a message

```
send: 
  payload: '{{ json }}'
  capture:
    - json: '$.body.message'
      as: message
```

Which, unless i'm mistaken, seems to cause a conflict with callbacks if used inside a loop step.

My solution was to register a custom function to enable a native websocket message handler using the context object provided by Artillery. We can then use this to interact directly with Artillery output via `events`.

```
function enableMessageLogging(userContext, events, next) {
  userContext.ws.on(`message`, (message) => {
    events.emit('counter', 'websocket.messages_received', 1);
    events.emit('rate', 'websocket.receive_rate');
  });

  next();
}
```

Here's my config just for reference...

```
config:
  target: ws://target.io
  phases:
    - duration: 10
      arrivalRate: 5
      name: warmup
  processor: './processorFunctions.js'
  variables:
    expiresIn: 3600

scenarios:
  - engine: ws
    name: client_pubsub
    flow:
      - connect:
          function: connectHandler
      - function: enableMessageLogging # to handle the messages
      - function: generateRoomId
      - function: generateRoomJoinEvent
      - send: '{{ roomJoinEvent }}'
      - function: generateRoomSubscribeEvent
      - send: '{{ roomSubscribeEvent }}'
      - loop:
          - function: generateClientMessageEvent
          - send: '{{ clientMessageEvent }}'
          - think: 2
        count: 10
      - think: 20
```

useful to know: https://github.com/artilleryio/artillery/blob/65dd5386c960e1d93f7e208784036e91fb663d00/packages/core/lib/engine_ws.js#L50C10-L50C11

```
--------------------------------
Summary report @ 12:09:07(+0100)
--------------------------------

vusers.completed: .............................................................. 50
vusers.created: ................................................................ 50
vusers.created_by_name.client_pubsub: .......................................... 50
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 40077.2
  max: ......................................................................... 40163.3
  mean: ........................................................................ 40110.9
  median: ...................................................................... 39747.5
  p95: ......................................................................... 39747.5
  p99: ......................................................................... 40550.5
websocket.messages_received: ................................................... 22904
websocket.messages_sent: ....................................................... 600
websocket.receive_rate: ........................................................ 461/sec
websocket.send_rate: ........................................................... 15/sec
```

```
VERSION INFO:

Artillery: 2.0.18
Node.js:   v20.11.0
OS:        darwin
```
