### ISSUE TITLE
Metrics from playwright to honeycomb

### ISSUE THREAD

**Issue by vikramjb** [artilleryio/artillery#2529]
Version info: 
```
2.0.6
```

Running this command: 
```
npx artillery run .\loaddefinition\test-load.yml
```

I expected to see this happen:

*Expecting to see the metrics getting uploaded to honeycomb*

Instead, this happened:

*I can see the tests running but no metrics are being uploaded to honeycomb. I tried commenting the apiKey and writeKey and sure enough validation kicked in. However when running with the api keys in the yaml file, I do not see the metrics being pushed to Honeycomb*

Files being used: 

**test-load.yml**
```
config:
  target: https://google.com
  phases:
    - duration: 30
      arrivalRate: 2
  processor: "../tests/testflow.js"
  engines:
    playwright:
      useSeparateBrowserPerVU: false
      aggregateByName: true
      defaultTimeout: 120
      defaultNavigationTimeout: 120
      extendedMetrics: true
      showAllPageMetrics: false
      launchOptions:
        headless: true
      contextOptions:
         viewport: null
  plugins:
    publish-metrics:
      - type: honeycomb
        apiKey: API_KEY
        writeKey: API_KEY
        dataset: "art-playwright-test1"
        sampleRate: 1
scenarios:
  - engine: playwright
    name: "TestCloudWaitListSignup"
    flowFunction: "cloudWaitlistSignupFlow"
```

**testflow.js**
```

async function cloudWaitlistSignupFlow(page, userContext, events, test) {
    await test.step('Go to Google', async()=>{
      const requestPromise = page.waitForRequest('https://google.com/');
      await page.goto('https://google.com/');
      const req = await requestPromise;
    })
  }
  
  module.exports = {
    cloudWaitlistSignupFlow
  };
  
```

When I run the same honeycomb config for a http engine, it works fine and I can see the report on Honeycomb without any issues.
