### ISSUE TITLE
Lambda environment variable not unwrapped

### ISSUE THREAD

**Issue by jdelaune** [artilleryio/artillery#2552]
Version info: 2.0.7
```
Artillery: 2.0.7
Node.js:   v20.10.0
OS:        darwin
```

Running this command: 
```
npx artillery run-lambda -e mysql8 --region us-east-1 ./scenarios/booking_flow.yml
```

I expected to see this happen:

Run the test.

Instead, this happened:

```
Error: ENOENT: no such file or directory, copyfile '/Users/***/Documents/load_test/data/{{ $environment }}-users.csv' -> '/var/folders/9_/1kr17s3n6cz7kprrqpbnw5g40000gn/T/d-202428-15076-1d8zp8r.3okt/data/{{ $environment }}-users.csv'
```

Files being used:
```yaml
  payload:
    path: "../data/{{ $environment }}-users.csv"
    fields:
      - "email"
      - "password"
    skipHeader: true
```
