### ISSUE TITLE
artillery-engine-processor could not be loaded

### ISSUE THREAD

**Issue by evan-easygo** [artilleryio/artillery#2569]
Version info: 
```
Artillery: 2.0.7
Node.js:   v19.9.0
OS:        darwin

I have multiple node versions but currently points to v19.9.0
```

Running this command: 
```
artillery run hello-world.yml
```

I expected to see this happen:
There shouldn't be any errors

Instead, this happened:
I get the error:
```
WARNING: engine processor specified but module artillery-engine-processor could not be loaded
Error: Cannot find module 'artillery-engine-processor'
Require stack:
- /Users/nnn/.nvm/versions/node/v19.9.0/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/runner.js
- /Users/nnn/.nvm/versions/node/v19.9.0/lib/node_modules/artillery/node_modules/@artilleryio/int-core/index.js
- /Users/nnn/.nvm/versions/node/v19.9.0/lib/node_modules/artillery/lib/artillery-global.js
- /Users/nnn/.nvm/versions/node/v19.9.0/lib/node_modules/artillery/lib/platform/local/worker.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
```

Files being used:
```yaml
config:
  target: https://www.artillery.io
  engines:
    playwright: {}
    processor: './tests/load/helloWorld.spec.ts'
scenarios:
  - engine: playwright
    testFunction: 'helloFlow'
```

```ts
import { type Page } from '@playwright/test';

async function helloFlow(page: Page) {
  await page.goto('https://www.artillery.io/');
}
```
