### ISSUE TITLE
InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes with artillery lambda

### ISSUE THREAD

**Issue by saurabhmarwaha** [artilleryio/artillery#2591]
Same bug reported in [https://github.com/artilleryio/artillery/issues/2337](https://github.com/artilleryio/artillery/issues/2337) is still occurring in latest version Artillery v2.0.8
\\\\-->

Same bug reported in [https://github.com/artilleryio/artillery/issues/2337](https://github.com/artilleryio/artillery/issues/2337) is still occurring in latest version Artillery v2.0.8

Version info:

```
 Artillery v2.0.8
Node.js:   v20.11.1
OS:        win32
```

Running this command:

```
artillery run-lambda backend-api.yml
```

I expected to see this happen:

*explanation*

Instead, this happened:

```
Test run id: tjw3m_x3arb3e5c5knp8faheyk3345c7fzg_gzh9
NOTE: AWS Lambda support is experimental. Not all Artillery features work yet.
For details please see https://docs.art/aws-lambda

λ Creating AWS Lambda function...
- Bundling test data
  - backend-api.yml
  - package.json
  - package-lock.json
- Installing dependencies
- Installing extra engines & plugins: artillery
- Creating zip package
Preparing AWS environment...
- C:\Users\<<user>>\AppData\Roaming\npm\node_modules\artillery\node_modules\aws-sdk\lib\protocol\json.js:80
  resp.error = util.error(new Error(), error);
                          ^

**InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes**
---
---
---
  code: '**InvalidParameterValueException**',
  '[Type]': 'See error.Type for details.',
  time: 2024-03-21T07:16:20.644Z,
  requestId: '95305fe6-826c-4d25-9645-8b8ff8541946',
  statusCode: 400,
  retryable: false,
  retryDelay: 90.7009000570459
}
Node.js v20.11.1
```

Files being used:

```
config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: https://domain.com
  phases:
    - duration: 60
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    ensure: {}
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
  ensure:
      thresholds:
        - http.response_time.p99: 100
        - http.response_time.p95: 75
scenarios:
  - flow:
      - loop:
        - get:
            url: "/"
        count: 100
```
