### ISSUE TITLE
load data from CSV

### ISSUE THREAD

**Issue by testsmith-io** [artilleryio/artillery#2609]
Hello,

I know how to load data from a CSV, but in my specific case, each line from the CSV can only be used once (otherwise the system rejects the data under test, and the performance test will fail)

How I load data:

```
  payload:
    - path: ./data/CombinedRandomized.csv
      order: random
      fields:
        - "url"
        - "type"
```

**Comment by hassy** [comment]
This isn't currently supported, but we're working on a solution. See https://github.com/artilleryio/artillery/discussions/2228 for more details.

**Comment by bernardobridge** [comment]
Hello @testsmith-io,

We now have an example of how to use [Upstash Redis](https://upstash.com/) to get unique data per VU:
https://github.com/artilleryio/artillery/tree/main/examples/using-data-from-redis

The same example can be changed to work with a Redis instance hosted elsewhere.

Feel free to comment on the [discussion here](https://github.com/artilleryio/artillery/discussions/2228) if you have any further questions about this! Thanks

**Comment by roydekleijn** [comment]
Ok going this way with Redis.

However it doesn't work in combination with Playwright.

This works:

```
config:
  target: example.com
  phases:
    - duration: 1 
      arrivalCount: 1
      name: "Steady load over 15 minutes"
  engines:
    playwright:
  processor: "./script.js"
scenarios:
  - engine: playwright
    beforeScenario: "getToken"
    flows:
      - log: "url: {{ url }} | type: {{ type }}"
```
 
 But when I try to invoke a playwright script, I get the following error:
 
```
 config:
  target: example.com
  phases:
    - duration: 1 
      arrivalCount: 1
  engines:
    playwright:
  processor: "./script.js"
scenarios:
  - engine: playwright
    beforeScenario: "getToken"
    flows:
      - testFunction: "myScript"
```


Error:

⠼ TypeError: fn is not a function
    at Array.scenario (/Users/abc/tmp/abc/node_modules/artillery-engine-playwright/index.js:250:17)

**Comment by bernardobridge** [comment]
Hey @roydekleijn 👋 

`beforeScenario` is not currently implemented in the Playwright engine (although we'll discuss this internally, as the use case has popped up a couple of times). 

However, you can run the `getToken` function directly from your `myScript` function, before your actual logic. So:

```yml
scenarios:
    - engine: playwright
      testFunction: 'myScript'
```

```js
async function myScript(page) {
  const token = await getToken();
  
  await page.goto('SOME_URL');
  ...
}
```
