### ISSUE TITLE
Getting triggerUncaughtException for artillery 2.0.9 with Node 18.17.0 on Windows

### ISSUE THREAD

**Issue by umarkhanTR** [artilleryio/artillery#2624]
While running artillery  2.0.9 with Node 18.17.0 on Windows (Jenkins) following error is displayed.

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
while running on local windows with 2.0.9 with Node 18.16.1 it works fine.
 
Version info: 
```
2.0.9
```

Running this command: 
```
set DEBUG=http*
artillery run --output results.json .\load.yml
```

I expected to see this happen:

*explanation*

Instead, this happened:

*explanation*

Files being used:
```
config:
  target: https:/
  # phases:
  #   - arrivalRate: 5
  #     duration: 10
  # Load the Playwright engine:
  engines:
    playwright:
      aggregateByName: true
      launchOptions:
        headless: true
      contextOptions:
        storageState: "storage.json"
  # Path to JavaScript file that defines Playwright test functions
  processor: "app.ts"
plugins:
  ensure: {}
  apdex: {}
  metrics-by-endpoint: {}
before:
  engine: playwright
  flowFunction: login
scenarios:
  - name: "HomePage"
    engine: playwright
    testFunction: "loadHomePage"
  - name: "CompaniesPage"
    engine: playwright
    testFunction: "loadCompanies"    
    # flow:
    #   - Load Home Page:
    #       url: "some url"
          
    #   - Load Companies:
    #       url: "some url"
    #       # engine: playwright
    #       testFunction: "loadCompanies"
  #

```
