### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME] when using a artillery runner file with a `.mjs` extension

### ISSUE THREAD

**Issue by thrandale** [artilleryio/artillery#2661]
Artillery is supposed to support ES Modules. Per the documentation, the way of doing this is to have your `artilleryRunner` file have the `.mjs` extension instead of the `.js` extension. I am using an `artillery.yaml` file to pass in the processor:
``` yaml
config:
  ...
  processor: "artilleryRunner.mjs"
  ...
```
When running artillery it gives the error `Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

In doing some tracing, this error is Coming from `core/lib/runner.js` when it is trying to load the `artilleryRunner.mjs` file. Per [this](https://stackoverflow.com/questions/69665780/error-err-unsupported-esm-url-scheme-only-file-and-data-urls-are-supported-by#:~:text=That%20actually%20is,g.%2C%20C%3A)) Stack Overflow Post: `the import() function [only works with file:// and data:// URLs](https://nodejs.org/api/errors.html#err_unsupported_esm_url_scheme), but path.resolve() only returns an absolute path (not a URL)`

This can be fixed by doing a `pathToFileURL()` before doing the `import()` of the module

Version info: 
```
Artillery: 2.0.10
Node.js:   v18.17.1
OS:        win32
```

**Comment by ShaunLawrie** [comment]
This is impacting me too. Windows paths are getting detected as urls

**Comment by ggecy** [comment]
This is making the artillery completely unusable on windows if we have a typescript configured to compile playwright tests to esm modules.

**Comment by cwongmt** [comment]
tests.yml

```
config:
  target: 'https://something.com'
  phases:
    - duration: 1
      arrivalRate: 1
  processor: '../auth.mjs'
  variables:
    user: 'tester'
scenarios:
  - name: 'Get'
    flow:
      - get:
          beforeRequest: 'auth'
          url: '/path'
          headers:
            Authorization: 'Bearer {{ token }}'
```
auth.mjs
```
export async function auth(requestParams, context, events) {
  const user = context.vars.user;
  console.log(`user: ${user}`);
  context.vars.token = 'test';
}
```

Facing the same error with above settings. This error renders it completely unusable on Windows.
