### ISSUE TITLE
Mismatch Datadog metrics vs Artillery Json report

### ISSUE THREAD

**Issue by Anonycoders** [artilleryio/artillery#2753]
Hi @hassy 👋🏼 

During our tests using Artillery, we noticed that reported metrics (i.e. req/sec) in `Datadog` are a not matched with those reported by Artillery logs! The numbers displayed in logs are more than those reported in Datadog.
Unfortunately, this deviation caused some issues in our final report.

I hope you can help us with this.

Version info:
```
2.0.11
```

Running this command: 
```
run-fargate -o report.json .../test.yml --count 6
```

In order to find out what is causing the issue, I created a test `.yml` to generate **300 req/sec** for 5 min ( Sustain phase) but each time, the req/sec reported in Datadog is around 150 req/sec but in Artillery logs it shows that it's 300 req/sec!

I tried to decrease the number of arrivals and scale out instead but, even with 6 instances and it still can not reach to 300 req/sec in Datadog.
Also tried `maxVusers: 50` in `Sustain` phase but the result was the same.

Here is the `.yml` file config for :

```yml
config:
  target: "https://xxxxxxxxxx/api"
  http:
    extendedMetrics: true
  phases:
  - name: WarmUp
    duration: 2m
    arrivalRate: 10
    rampTo: 50
  - name: Sustain
    duration: 5m
    arrivalRate: 50
 plugins:
   ensure: {}
   metrics-by-endpoint:
     useOnlyRequestNames: true
     stripQueryString: true
   publish-metrics:
   - type: datadog
      apiKey: ...
      appKey: ...
      prefix: ...
      tags:
        - XXXX
        - ....
      traces:
        ....
 

scenarios:
  - name: List users
     flow:
       - get:
          url: "/users"
```

I also found this https://github.com/artilleryio/artillery/issues/1569 issue which seems similar.

**Comment by InesNi** [comment]
Hi @Anonycoders 👋🏻 ,

Thank you for reporting the issue, and for all the info! Will take a look and get back to you.

**Comment by jCOTINEAU** [comment]
Hello, we have a similar issue.

When running a simple
```
  phases:
    - duration: 60
      arrivalRate: 1
      name: One per sec
```

I expect 60 aggregated user and this is the case when running from my machine and with fargate --count 1, but when I bump up the --count I start having weird numbers, is this expected ?
