### ISSUE TITLE
artillery is ignoring some scenario steps

### ISSUE THREAD

**Issue by milosgajdos** [artilleryio/artillery#2777]
Version info: 
```
Artillery: 2.0.12
Node.js:   v22.1.0
OS:        darwin
```

Running this command: 
```
artillery run --config config.yaml --environment local script.yaml
```

I expected to see this happen:

*explanation*

Instead, this happened:

1. Log `Create a foo`
2. Fire `POST` request
4. Log `Waiting`
5. Wait for 2 seconds
6. Log `Destroying foo`

Files being used:
```yaml
config:
  environments:
    local:
      target: https://localhost:8080
      phases:
        - duration: 30
          arrivalRate: 1
          rampTo: 5
          name: Warm up
        - duration: 30
          arrivalRate: 5
          rampTo: 10
          name: Ramp up
        - duration: 30
          arrivalRate: 10
          rampTo: 20
          name: Spike up
scenarios:
  - name: 'Foo Flow'
    flow:
      - log: 'Create a foo'
      - post:
          url: '/v1/foo'
          headers:
            authorization: 'Bearer {{ token }}'
          json:
            data: "some data"
          capture:
            json: '$.id'
            as: 'foo_id'
      - think: 2
      - log: 'Waiting ...'
      - log: 'Destroying {{ foo_id }}'
      - post:
          url: '/v1/foo?id={{ foo_id }}'
          headers:
            authorization: 'Bearer {{ token }}'
```

Instead, the only things I see is the following logs
```
⠙ Create a foo
⠼ Create a foo
⠦ Create a foo
⠇ Create a foo
```

No wait (`think`) is happening let alone any other steps following it. the `POST` requests are successful as I can see the `Foo`s being created in our database which makes me think something is rotting on the `think` step 🤔

**Comment by hassy** [comment]
thanks @milosgajdos! Could you throw a log in there right after the `post` step just to make sure the `capture` action is running successfully? Artillery will stop the VU by default if a `capture` fails, as it's likely that subsequent steps in a flow won't work anyway. Something like:

```
- post: {} # the post step
- log: "foo_id: {{ foo_id }}" # log
- think: 2 # rest of the flow
```

Also, are there any capture-related errors being reported in the summary?

**Comment by hassy** [comment]
sorry I missed the `log` that you also have later in the flow.

What's happening most likely is that the server is responding with something that `capture` can't process. It might not be returning valid JSON, or JSON in a different shape to what's expected by the JSONPath expression. You can confrm by capturing and printing the entire response:

```yaml
- post:
    url: '/v1/foo'
    capture:
      json: "$" # grab the entire response
      as: full_response
- log: "{{ full_response }}"

```
