### ISSUE TITLE
Artillery-engine-playwright: issue with metrics when using `pause`

### ISSUE THREAD

**Issue by vidhill** [artilleryio/artillery#2817]
I noticed that I was getting inconsistent values in my reports.

Most notably the report reporting that more VU's completed that created

Version info: 
```
        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.14
Node.js:   v18.20.3
OS:        darwin
```

Running this command: 
```
npx artillery run artillery-browser.yaml --dotenv=.env
```

I expected to see this happen:

*explanation*

I was seeing numerous, `Warning: multiple batches of metrics for period` warnings, 

When trying to chase down the source of the `multiple batches of metrics for period` warnings I realised that they only occur when I include a `pause` phase, 

*explanation*

I have a feeling that some VUs are completing during the pause phase and perhaps the pause phase is not from

Files being used:
```yaml
config:
  target: "{{ $processEnvironment.BASE_URL }}"
  engines:
    playwright: {}
  processor: "./tests/index.js"
  phases:
    - name: constantArrival2
      duration: 10
      arrivalRate: 1
    - pause: 60
    - name: constantArrivalRecovery
      duration: 10
      arrivalRate: 1
scenarios:
  - engine: playwright
    testFunction: artilleryScript
```

Sample test
```js
async function artilleryScript(page, vuContext) {
  await page.goto(vuContext.vars.target);
  await expect(page).toHaveTitle(/Home/);
}

module.exports = {
  artilleryScript,
};

```

Sample log output
```
Phase completed: constantArrival2 (index: 0, duration: 10s) 14:37:26(+0100)

Phase started: unnamed (index: 1, duration: 60s) 14:37:26(+0100)

--------------------------------------
Metrics for period to: 14:37:30(+0100) (width: NaNs)
--------------------------------------

No measurements recorded during this period


Warning: multiple batches of metrics for period 1717681040000 2024-06-06T13:37:20.000Z
Warning: multiple batches of metrics for period 1717681040000 2024-06-06T13:37:20.000Z
Phase completed: unnamed (index: 1, duration: 60s) 14:38:26(+0100)
```
