### ISSUE TITLE
Datadog Metrics are not sent when using Artillery with Fargate

### ISSUE THREAD

**Issue by 70mm1** [artilleryio/artillery#3236]
When trying to send metrics and events to Datadog while using Artillery with Fargate, no data is sent to Datadog. When trying the same parameters and configurations when using Artillery with the normal `run` command, everything works. 
Trying the debug environment variable behaves the same, it shows information when set for the normal `run` command but no information is shown when using `run-fargate`

Version info: 
```
v2.0.15
```

Running this command: 
```
docker run -i --rm \
                  -v .:/load-test \
                  -u root:root \
                  -e AWS_ACCESS_KEY_ID=\$AWS_ACCESS_KEY_ID \
                  -e AWS_SECRET_ACCESS_KEY=\$AWS_SECRET_ACCESS_KEY \
                  -e AWS_SESSION_TOKEN=\$AWS_SESSION_TOKEN \
                  -e DD_API_KEY=\$API_KEY \
                  -e DD_APP_KEY=\$APP_KEY \
                  -e DEBUG=plugin:publish-metrics:datadog-statsd \
                  artillery \
                  run-fargate \
                  --region eu-central-1 \
                  --subnet-ids *** \
                  --security-group-ids ***  \
                  --count 1 \
                  --cluster artilleryio-cluster \
                  --spot \
                  --output report.json \
                  /load-test/load-test.yml
```

I expected to see this happen:
Debug messages for Datadog appearing and metrics and events being sent to Datadog.

Instead, this happened:
Instead, only AWS debug messages are showing up and the test runs successfully.
No events or metrics are reported to Datadog. Using the normal artillery run command works with sending events and metrics to Datadog, so I do not assume that there is an issue with the API or APP key. 

Files being used:
Test script
```
config:
  target: ***
  phases:
    - duration: 10
      arrivalRate: 1
      name: Warmup
    - duration: 20
      arrivalRate: 1
      rampTo: 10
      name: rampUp
  plugins:
    publish-metrics:
      - type: datadog
        apiKey: "{{ $env.DD_API_KEY }}"
        appKey: "{{ $env.DD_APP_KEY }}"
        apiHost: "app.datadoghq.eu"
  engines:
    playwright:
      launchOptions:
        headless: true
      aggregateByName: true
      contextOptions:
        storageState:  "{{ $dirname }}/storage.json"
  processor: "./processor.ts"
```
