### ISSUE TITLE
Callback was already called

### ISSUE THREAD

**Issue by Phantomem** [artilleryio/artillery#3261]
Version info: 
```
2.0.17
```

Running this command: 
```
npx artillery run ./path-to-the-config.yml
```

Unfortunately I'm unable to utilize artillery receiving an error: 
```
PS C:\node-backend> npx artillery run .\test\performance.test.config.yml
Test run id: tfxwe_j56f6ac49yetweftawnh3xtxm8dnq_mfzk
Phase started: unnamed (index: 0, duration: 20s) 20:41:37(+0200)

- worker error, id: 3 Error: Callback was already called.
    at C:\node-backend\node_modules\@artilleryio\int-core\node_modules\async\dist\async.js:969:32
    at done (C:\node-backend\node_modules\@artilleryio\int-core\lib\engine_socketio.js:421:16)
    at Socket.<anonymous> (C:\node-backend\node_modules\@artilleryio\int-core\lib\engine_socketio.js:389:7)
    at Socket.on (C:\Users\Pawel\RustroverProjects\neighborly-node-chat\node-backend\node_modules\@socket.io\component-emitter\index.js:63:8)
    at Emitter.emit (C:\node-backend\node_modules\@socket.io\component-emitter\index.js:143:20)
    at Socket.onerror (C:\node-backend\node_modules\socket.io-client\build\cjs\socket.js:457:18)
    at Emitter.emit (C:\node-backend\node_modules\@socket.io\component-emitter\index.js:143:20)
    at Socket.onError (C:\node-backend\node_modules\socket.io-client\build\cjs\manager.js:151:18)
    at Emitter.emit (C:\node-backend\node_modules\@socket.io\component-emitter\index.js:143:20)
    at Socket.onError (C:\node-backend\node_modules\engine.io-client\build\cjs\socket.js:571:14)
```

OS: WINDOWS WSL 
Node.js verison: 20.13.1

Files being used:
```
config:
  target: "http://localhost:5001"
   
  phases:
    - duration: 20
      arrivalRate: 10
      rampTo: 1000000
  engines:
    socketio-v3: {}
scenarios:
  - name: "WebSocket Chat Test"
    engine: "socketio"
    flow:
      - function: "connect"
      - emit:
          channel: "join-room"
          data:
            username: "testuser"
            group_id: "testgroup"
      - emit:
          channel: "send-message"
          data:
            group_id: "testgroup"
            senderName: "testuser"
            senderPhoto: "testphoto.jpg"
            msg: "Hello, this is a test message!"
            sent_at: "{{ date '2024-07-10T12:34:56.789Z' }}"
            mediaLink: ""
      - emit:
          channel: "up-vote"
          data:
            msg_id: "message123"
      - emit:
          channel: "down-vote"
          data:
            msg_id: "message123"
      - think: 10
      - emit:
          channel: "leave-room"
          data:
            username: "testuser"
            group_id: "testgroup"
      - function: "disconnect"

```
