### ISSUE TITLE
Playwright Fargate HTTP_PROXY support

### ISSUE THREAD

**Issue by igor-dmitriev** [artilleryio/artillery#3266]
Version info: 
2.0.16

I expected to see this happen:

I would like to run the Playwright test on Fargate using HTTP_PROXY, but it does not work cause HTTP_PROXY param is ignored, apparently it is not supported

Instead, this happened:

HTTP_PROXY param does not work, I think it should be done through playwright config, that is somehow is configurable - https://playwright.dev/docs/network#http-proxy

**Comment by hassy** [comment]
You should be able to enable proxy support via `contextOptions` - https://www.artillery.io/docs/reference/engines/playwright#configuration. Any config set under `contextOptions` is passed right through to Playwright's `Browser.newContext()` method)

https://playwright.dev/docs/api/class-browser#browser-new-context-option-proxy

For example:

```yaml
config:
  engines:
    playwright:
      contextOptions:
        proxy:
          server: https://myproxy.net
```
