### ISSUE TITLE
showAllPageMetrics doesn't work when Target is changed in runtime

### ISSUE THREAD

**Issue by robin-miro** [artilleryio/artillery#3269]
`showAllPageMetrics` by default is `false`,  it enables webvitals metrics if the URL start with `target` 

but it doesn't work if `target` is changed within runtime (within js file)

```
  engines:
    playwright:
      contextOptions: {}
      defaultNavigationTimeout: 60 # in seconds
      aggregateByName: false
      useSeparateBrowserPerVU: false
      launchOptions:
        headless: false
target: replace_me.example.com
```

in JS
```
    vuContext.vars.target = vuContext.vars.target.replace("replace_me","new")
```

Version info: 
```
2.0.17
```

I expected to see this happen:
* either I can use a variable within target from yamle file
* or showAllPageMetrics should consider the runtime target somehow
