### ISSUE TITLE
Using $ref in YAML files to avoid duplication

### ISSUE THREAD

**Issue by RikdeVos** [artilleryio/artillery#3298]
We'd like to propose a feature to use get rid of some YAML duplication by using `$ref`. This syntax is also available in [openapi-spec](https://swagger.io/docs/specification/using-ref/) definitions, and seems to be getting more traction lately by other tooling using YAML.

Examples:

```yml
# test.artillery.yml
scenarios:
  - flow:
    - $ref: "auth.yml/#/steps/login"
    - get: 
        name: Get secure resource
        url: "/foo"
        headers:
          $ref: "auth.yml/#/headers"

# auth.yml
steps:
  login:
    - post:
        url: "/login"
        capture:
            - json: "$.accessToken"
              as: "accessToken"
headers:
  Content-Type: application/json
  Authorization: "Bearer {{ accessToken }}"
```
