### ISSUE TITLE
Cookie Failed to Parse

### ISSUE THREAD

**Issue by sam-barker** [artilleryio/artillery#3308]
Setting a cookie in my flows seems to keep causing an error, and I'm not sure why. If I remove any mention of cookies the error goes away. But I am confused as to why the cookie cannot be parsed, even with the unsafe-disabled security prefix set

Version info: 
```
2.0.19
```

Running this command: 
```
npx artillery run --quiet src/config/step-load-test.yml    
```

I expected to see this happen:

No errors when setting a cookie

Instead, this happened:

`Error: Cookie failed to parse`

Files being used:
```
config:
  target: "https://example.com"
  http:
    cookieJarOptions:
      prefixSecurity: "unsafe-disabled"
  phases:
    - duration: 1m
      rampTo: 3
      maxVusers: 3
      name: steady_state
  plugins:
    expect: 
      useOnlyRequestNames: true
      reportFailuresAsErrors: true
      expectDefault200: true
    metrics-by-endpoint:
      useOnlyRequestNames: true
      metricsNamespace: "scenario"
    ensure:
      maxErrorRate: 1
  payload:
    - path: "../data/search.csv"
      skipHeader: true
      cast: false
      loadAll: false
      fields:
        - "searchTerm"
scenarios:
  - name: "Search"
    flow:
      - get:
          url: "/search"
          cookie:
            LoadTest: "true"
          qs:
            q: "{{ searchTerm }}"
```
