### ISSUE TITLE
Basic Authentication (auth:) is not working in Artillery

### ISSUE THREAD

**Issue by resource-not-found-blank** [artilleryio/artillery#3346]
I think `auth:` (Basic Authentication) no longer works as described in the [documentation](https://www.artillery.io/docs/reference/engines/http#basic-authentication)

Version info:
```
Artillery: 2.0.20
Node.js:   v22.8.0
OS:        darwin
```

A `test.yaml` file:
```
config:
  target: http://asciiart.artillery.io:8080
  phases:
    - duration: 1
      arrivalRate: 1
scenarios:
  - flow:
      - get:
          url: '/dino'
          auth:
            user: username
            pass: password
```

Run the test with debug mode enabled to inspect request headers: 
```
DEBUG=http* artillery run test.yaml -s
```

I expected to see this happen:

I expected to see the `Authorization` header in the request headers.

Instead, this happened:

No `Authorization` header was present in the request.

![image](https://github.com/user-attachments/assets/909a93e9-0f4f-470b-83b8-1db2546c595d)
