### ISSUE TITLE
OpenTelemetry plugin missing crucial metrics

### ISSUE THREAD

**Issue by peterpakos** [artilleryio/artillery#3353]
We are trialling OpenTelemetry plugin for ingesting performance test metrics into our Grafana Cloud instance.

Everything appears to be working as expected but the selection of generated metrics is a bit sparse.

Version info: 
```
2.0.20
```

Running this command: 
```
artillery run getstatus.yml
```

I expected to see this happen:

More metrics being generated/ingested including HTTP requests/responses, status codes etc.

Instead, this happened:

Only the following metrics appear in Grafana:
```
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_median
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_min
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_p50
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_p75
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_p90
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_p95
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_p99
plugins_metrics_by_endpoint_response_time_TruAPI_rest_TruRest_GetStatus_p999
target_info
vusers_session_length_count
vusers_session_length_max
vusers_session_length_mean
vusers_session_length_median
vusers_session_length_min
vusers_session_length_p50
vusers_session_length_p75
vusers_session_length_p90
vusers_session_length_p95
vusers_session_length_p99
vusers_session_length_p999
```

Files being used:
```
    plugins:
      publish-metrics:
        - type: open-telemetry
          serviceName: GetStatus
          metrics:
            exporter: otlp-proto
            endpoint: https://xxx.grafana.net/otlp/v1/metrics
            headers:
              Authorization: 'Basic xxx'
```
