### ISSUE TITLE
Cannot find module excluded from bundling even though package.json is set

### ISSUE THREAD

**Issue by sam-barker** [artilleryio/artillery#3354]
Version info: 
```
latest
```

Running this command: 
```
artillery run-fargate \
          --region eu-west-1 \
          --dotenv ./.env \
          --cpu $CPU \
          --memory $MEM \
          --max-duration $MAX_DURATION \
          --count $TASK_COUNT \
          --cluster $CLUSTER_NAME \
          --subnet-ids $IDS \
          --security-group-ids $GROUP_IDS \
          --package ./package.json
          ${CONFIG_FILE} \
          --quiet
```

I expected to see this happen:

Test ran successfully

Instead, this happened:
`worker error, id: 2 Error: Cannot find module 'winston'`

Even though I have this in the package json, and I have specified the package json in the artillery arguments.

If I remove the bundling config
```
bundling:
    external: ['playwright', 'winston']
```

Then it just moans about marking the module as external, so it's an endless cycle.

Files being used:
```
config:
  target: "https://www.dunelm.com"
  phases:
    - duration: 10m
      arrivalRate: 1
      maxVusers: 1
      name: step_1
  engines:
    playwright:
      contextOptions:
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 PE"
      aggregateByName: true
      launchOptions:
        headless: true
  processor: ../../index.ts
  bundling:
    external: ['playwright', 'winston']
scenarios: ...blah
```
