### ISSUE TITLE
config.target not reading env from launch config when running in fargate

### ISSUE THREAD

**Issue by emmaLP** [artilleryio/artillery#3361]
Since upgrading to artillery 2.0.20, we are unable to set the target to be '{{ $env.TARGET_ENDPOINT }}' when running with fargate.

We always get the error `No target specified and no environment chosen`

Version info: 
```
 artillery 2.0.20
```

Running this command: 
```
 artillery run-fargate --region us-east-1 --cluster artillery --launch-type ecs:fargate --environment staging --output report.json artillery_admin_api.yaml --launch-config {
  "environment": [
    {"name": "TARGET_ENDPOINT", "value": "https://hello.com"}
  ],
  "cpu": "1024",
  "memory": "2048"
} --count 1

```

I expected to see this happen:

Artillery should take the env from launch config to set the target and then run the load testing in a fargate artillery cluster as expected

Instead, this happened:

![image](https://github.com/user-attachments/assets/8f6d8d12-3fdd-4521-97ec-5b6cf920b4d2)

Files being used:
```
config:
  target: '{{ $env.TARGET_ENDPOINT }}'
    environments:
      staging:
        phases: # load/change or increase number of workers as per expected traffic
          - duration: 100
            arrivalRate: 2
            rampTo: 5
      production:
        phases:
          - duration: 300
            arrivalRate: 2
            rampTo: 15
scenarios:
 ....
```

Workaround:
Either need to set TARGET_ENDPOINT env var or use -t option in the command to get the fargate runner to work
