### ISSUE TITLE
Better default user agent for http requests

### ISSUE THREAD

**Issue by ash211** [artilleryio/artillery#3407]
Version info: 
```
Artillery: 2.0.21
Node.js:   v22.9.0
OS:        darwin
```

Running this command with an http request configured: 
```
artillery run artillery-load-test.yml
```

I expected to see requests in my logs a request with a user agent that says something about artillery, like this: `Artillery/2.0.21 Node.js/v22.9.0 darwin`

Instead the default user agent is `got (https://github.com/sindresorhus/got)`

For reference, Apache Bench's user agent is `ApacheBench/2.3`

Files being used:

An example with an http request is the [sample](https://www.artillery.io/docs/get-started/first-test#create-an-artillery-test-script)

**Comment by hassy** [comment]
That's odd. The default user-agent header is set to `Artillery (https://artillery.io)` here:

https://github.com/artilleryio/artillery/blob/main/packages/core/lib/engine_http.js#L441

Just verified it with:

```sh
nc -l 10111
artillery quick http://127.0.0.1:10111/
```

```
❯ nc -l 10111
GET / HTTP/1.1
user-agent: Artillery (https://artillery.io)
accept-encoding: gzip, deflate, br
Host: 127.0.0.1:10111
Connection: keep-alive
```

**Comment by ash211** [comment]
Hmm, maybe it has something to do with the default headers settings in my `artillery-load-test.yml`?
```
  defaults:
    headers:
      accept: 'application/json'
      accept-language: 'en-US,en;q=0.9'
      authorization: 'Bearer {{ $env.TOKEN }}'
      content-type: 'application/json'
      cookie: 'TOKEN={{ $env.TOKEN }}'
      origin: 'https://mydomain.com'
      priority: 'u=1, i'
```
