### ISSUE TITLE
Artillery AWS Fargate

### ISSUE THREAD

**Issue by buenofc** [artilleryio/artillery#3435]
Version info: 
```
<version>
Artillery: 2.0.19
Node.js:   v22.12.0
OS:        win32
```

Running this command: 
```
npx artillery run-fargate performance\<my-test>.yml --region ap-southeast-2 --memory 16 --record --key <my key>
```

I expected to see this happen:

Expected the test would run in AWS Fargate.

Instead, this happened:

it seems the Error: Timed out waiting for workers to sync is back! I'm running artillery v2.0.19 with AWS Fargate with 1 user (1 worker). I tried increase the memory (--memory 16) to 16GB from 8GB, but no joy. Any help with will be much appreciated!!!

`Artillery Cloud reporting is configured for this test run
Run URL: https://app.artillery.io/load-tests/tdfqw_rp6n679rgmf5dc6ndjnpnq3b9zpwn_96z8
Checking AWS connectivity... [11:05:27]
Checking cluster... [11:05:28]
Tags: name:shine_bc_smoke.yml [11:05:29]
Test run ID: tdfqw_rp6n679rgmf5dc6ndjnpnq3b9zpwn_96z8 [11:05:29]
Preparing launch platform... [11:05:29]
Environment:
Account: 841162689491
Region: ap-southeast-2
Count: 1
Cluster: artilleryio-cluster
Launch type: ecs:fargate (On-demand)

Preparing test bundle... [11:05:30]
| =============

Test bundle prepared... [11:05:32]
Test bundle contents:
┌───────────────────────────────────────────────────────────┬─────────┬───────┐
│ Name │ Type │ Notes │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ performance\shine_bc_smoke.yml │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ performance\processor.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ support\pages\BasePage.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\login\LoginPage.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\home\HomePage.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\customer\CustomerCard.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\helpers\helpers.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\sales\SalesOrdersPage.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\purchase\PurchaseOrdersPage.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\components\TopBar.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\runs\RunsCard.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\statement\StatementRunCard.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\IncomeStatementDialog.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\PaymentsOnHoldDialog.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\AgedAccPayBackDatingDialog.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\AgedAccountsReceivableDialog.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\AgedAccRecBackDatingDialog.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\CustomerListDialog.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\credit-memo\PurchaseCreditNotePage.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\report\BankAccountLedgerEntriesPage.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ models\pages\index.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\purchase.to.pay.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\run.regular.sales.orders.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\statement.run.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\post.released.sales.orders.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\income.statement.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\payments.on.hold.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\aged.acc.pay.backdating.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\aged.acc.rec.backdating.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\customer.list.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\aged.accounts.receivable.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\sales.to.invoice.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\purchase.credit.memo.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ commands\reports\apd.eft.listing.ts │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ data\users.csv │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ data\sales.orders.csv │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ data\purchase.orders.csv │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ data\statement.run.csv │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ data\run.regular.sales.orders.csv │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ package.json │ file │ │
├───────────────────────────────────────────────────────────┼─────────┤ │
│ package-lock.json │ file │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ @eslint/compat │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ @eslint/js │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ @playwright/test │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ @types/eslint__js │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ @types/node │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ @types/uuid │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ artillery │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ artillery-engine-playwright │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ dotenv │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ eslint │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ eslint-config-prettier │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ eslint-plugin-prettier │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ foreach │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ playwright │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ playwright-ts-artillery-performancetesting │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ prettier │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ typescript │ package │ │
├───────────────────────────────────────────────────────────┼─────────┼───────┤
│ typescript-eslint │ package │ │
└───────────────────────────────────────────────────────────┴─────────┴───────┘

Launching workers... [11:05:35]
Waiting for Fargate... [11:05:36]
Waiting for workers to start: pending: 1 [11:06:06]
Waiting for workers to start: pending: 1 [11:06:16]
Waiting for workers to start: pending: 1 [11:06:26]
Waiting for workers to start: pending: 1 [11:06:37]
Waiting for workers to come online... [11:06:37]
Error: Timed out waiting for workers to sync
Error: Timed out waiting for workers to sync
at C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\artillery\lib\platform\aws-ecs\legacy\run-cluster.js:1862:29
at finished (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\artillery\lib\platform\aws-ecs\legacy\util.js:109:16)
at C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\async\dist\async.js:972:16
at next (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\async\dist\async.js:3025:18)
at Response. (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\artillery\lib\platform\aws-ecs\legacy\util.js:96:20)
at Request. (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\request.js:367:18)
at Request.callListeners (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
at Request.emit (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
at Request.emit (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\request.js:686:14)
at Request.transition (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\request.js:22:10)
Error: Timed out waiting for workers to sync
at C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\artillery\lib\platform\aws-ecs\legacy\run-cluster.js:1862:29
at finished (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\artillery\lib\platform\aws-ecs\legacy\util.js:109:16)
at C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\async\dist\async.js:972:16
at next (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\async\dist\async.js:3025:18)
at Response. (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\artillery\lib\platform\aws-ecs\legacy\util.js:96:20)
at Request. (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\request.js:367:18)
at Request.callListeners (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
at Request.emit (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
at Request.emit (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\request.js:686:14)
at Request.transition (C:\<path>\git\ampol-project-shine-bc-artillery-playwright\node_modules\aws-sdk\lib\request.js:22:10)
Cleaning up... [11:16:32]
/

Run URL: [https://app.artillery.io/load-tests/tdfqw_rp6n679rgmf5dc6ndjnpnq3b9zpwn_96z8`](https://app.artillery.io/load-tests/tdfqw_rp6n679rgmf5dc6ndjnpnq3b9zpwn_96z8%60)

Files being used:
```
config:
  target: https://<app-URL>
  # Load the Playwright engine:
  phases:
    - name: smoke-test
      arrivalCount: 1
      duration: 90
    variables:
    APD_URL_UAT: https://<app-URL>
  payload:
    - path: ../data/users.csv
      fields:
        - USERID
        - PASSWORD
      order: sequence
    - path: ../data/sales.orders.csv
      fields:
        - INPUTSO
        - CUSTOMERNUMBER
        - CODE
        - ITEMNUMBERSO
        - QUANTITYSO
        - DELIVERYPOINT
      order: sequence
    - path: ../data/purchase.orders.csv
      fields:
        - INPUTPO
        - VENDORNUMBER
        - LOCATIONCODE
        - ITEMNUMBERPO
        - QUANTITYPO
    - path: ../data/statement.run.csv
      fields:
        - INPUTSR
        - CUSTOMERNUMBERSR
      order: sequence
      #loadAll: true
      name: statement-run
    - path: ../data/run.regular.sales.orders.csv
      fields:
        - INPUTRR
        - RUNNUMBERRR
      order: sequence
      #loadAll: true
      name: statement-run
  plugins:
    metrics-by-endpoint: {}
  engines:
    playwright:
      launchOptions:
        headless: true
  # Path to JavaScript file that defines Playwright test functions
  processor: "processor.ts"
scenarios:
  - name: "sales-order"
    engine: playwright
    testFunction: "salesOrderScenario"

```
