### ISSUE TITLE
Question: Hook for ECONNRESETS

### ISSUE THREAD

**Issue by somecho** [artilleryio/artillery#3461]
The `afterResponse` hook gets called when a VU receives a response. I want to emit a custom metric during ECONNRESET. In this case, `afterResponse` does not work since it does not get called. How do I get a hook called (to emit a custom metric or log a request body) after an ECONNRESET?

**Comment by hassy** [comment]
There's a scenario-level `onError` hook for use cases like this. It's not documented, but it's been in the codebase for a while now and is unlikely to be dropped in future (we try to stay backwards-compatible as much as possible). The relevant code is here: https://github.com/artilleryio/artillery/blob/main/packages/core/lib/engine_http.js#L1014

The signature is:

```js
function myOnErrorHandler(error, requestParams, userContext, events, next) {
}
```

and it needs to be declared at scenario level:

```yaml
scenarios:
  - name: my scenario
    onError: myOnErrorHandler
    flow:
      - get:
          url: "/"
```
