### ISSUE TITLE
After Test are done in Fargate: InvalidParameterValueException: One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes

### ISSUE THREAD

**Issue by distante** [artilleryio/artillery#3463]
Version info: 
```
Artillery: 2.0.21
Node.js:   v20.11.1
OS:        darwin
```

Running this command: 
``` 
artillery run-fargate   --region eu-central-1 --memory 30720  --launch-config '{"ulimits":[{"name":"nofile","softLimit":"1048576","hardLimit":"1048576"}]}' --count 1 --record --key my_key path/to/file.yml -e my_environment
```

I expected to see this happen:

After the test is finish it completes without any error on the worker logs

Instead, this happened:

At the end, a `InvalidParameterValueException` is shown but no more context is given.

```log
...

vusers.created: ................................................................ 20
--
vusers.created_by_name.0: ...................................................... 20
vusers.failed: ................................................................. 0
vusers.session_length:
mean: ........................................................................ 233879.5
median: ...................................................................... 134637.8
p99: ......................................................................... 767122.4
vusers.skipped: ................................................................ 191
InvalidParameterValueException: One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes.
at Request.extractError (/artillery/node_modules/aws-sdk/lib/protocol/json.js:80:27)
at Request.callListeners (/artillery/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/artillery/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/artillery/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/artillery/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /artillery/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/artillery/node_modules/aws-sdk/lib/request.js:688:12)
at Request.callListeners (/artillery/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
code: 'InvalidParameterValue',
'[__type]': 'See error.__type for details.',
time: 2025-01-27T10:22:12.322Z,
requestId: '1a96ca47-ad39-59ea-9f54-aa56cdad1495',
statusCode: 400,
retryable: false,
retryDelay: 28.927775056643835
}
Finished with code 0
no ensure spec
Completed 256.0 KiB/425.0 KiB (7.9 MiB/s) with 1 file(s) remainingCompleted 425.0 KiB/425.0 KiB (425.2 KiB/s) with 1 file(s) remainingupload: ./output.txt to s3://artilleryio-test-data-314106084997/test-runs/tq99e_h5k9heyazfyapjtp3tptyxafzh96z_fwfa/worker-log-c35380a6e5e5431eb9a17e1d464b3ec3.txt
log: s3://artilleryio-test-data-314106084997/test-runs/tq99e_h5k9heyazfyapjtp3tptyxafzh96z_fwfa/worker-log-c35380a6e5e5431eb9a17e1d464b3ec3.txt
cleanup called, signal:
EXIT
Message body: {     "event": "workerDone" }
```

config.yml

```yml
config:
  engines:
    playwright:
      trace:
        enabled: true
        maxConcurrentRecordings: 10 # We have to increase this if we loose too much traces
      defaultNavigationTimeout: 60
      defaultTimeout: 60
      showAllPageMetrics: true
      extendedMetrics: false
      launchOptions:
        headless: true
  environments:
    my_env:
      target: "http://my-test.com"
  phases:
    - duration: 1
      arrivalRate: 1
      maxVusers: 1
      name: Test local
    ## just for CI, Without this you will get NO traces on fargate
    - duration: 20
      arrivalRate: 1
      rampTo: 20
      maxVusers: 20
      name: fargate warum-up
    # # just for CI, Without this you will get NO traces on fargate
    # - duration: 1
    #   arrivalRate: 20
    #   maxVusers: 20
    #   name: Sustained peak load
  processor: "./user-browsing.artillery-scenario.ts"
scenarios:
  - engine: playwright
    testFunction: "userBrowsing"
    # beforeScenario: 'setApiKey'
    afterScenario: "onEnd"
```

Could it be that the final output json report is too big?
