### ISSUE TITLE
Artillery fails the user when ECONNRESET is encountered

### ISSUE THREAD

**Issue by eshavkun** [artilleryio/artillery#3510]
Version info: 
```
2.0.22
```

I'm running a script with a simple loop over payload that sends one request. Like this:
```
scenarios:
  - name: "Download file"
    flow:
      - loop:
        - get:
            url: '/{{ $loopElement.fileId }}'
        over: fileIds
```

Sometimes I'm getting ECONNRESET. In this case I expect Artillery to continue and go on to the next request. Unfortunately, what I see is that the user is just marked as failed and the loop is not continued. And in case when I run test with only one user the whole test finishes. 
The log shows this error: `Error: The server aborted pending request`

Is there a way to force Artillery not to fail the user and continue the test in this case?
