### ISSUE TITLE
AWS Fargate: --task-role-name not setting task role in ECS task definition (v2.0.23)

### ISSUE THREAD

**Issue by icsabell** [artilleryio/artillery#3545]
Version info:
```
Artillery v2.0.23
Using GitHub Action: artilleryio/action-cli@v1
Image digest: sha256:fee27b18a744....
```
Running this command:
```
Run artilleryio/action-cli@v1
with:
  command: run-fargate --region us-west-2 --cluster artillery-cluster-dev --subnet-ids subnet-xxxxxxxxxxxxxxxxx,subnet-yyyyyyyyyyyyyyyyy,subnet-zzzzzzzzzzzzzzzzz --security-group-ids sg-aaaaaaaaaaaaaaaaa --task-role-name artilleryio-ecs-worker-role --record ./test-file.yml
```
I expected to see this happen:

*When using the --task-role-name artilleryio-ecs-worker-role flag in run-fargate, I expected the ECS task definition to be created with that role correctly set as the task role (taskRoleArn), so that the container would assume it at runtime.*

*This expectation is based on the changelog for Artillery v2.0.23, which explicitly states:*
 - *"Fix issue with --task-role-name flag not being taken into account"*

Instead, this happened:

*The ECS task definition has no task role attached. Only the execution role is set, and it is also artilleryio-ecs-worker-role*

*The task executes successfully, but the expected taskRoleArn is not present in the task definition, indicating that the --task-role-name flag is still not being respected*

Files being. used:

*GitHub Actions workflow snippet*
```
- name: Run Fargate Test
  uses: artilleryio/action-cli@v1
  with:
    command: run-fargate --region us-west-2 --cluster artillery-cluster-dev --subnet-ids subnet-xxxxxxxxxxxxxxxxx,subnet-yyyyyyyyyyyyyyyyy,subnet-zzzzzzzzzzzzzzzzz --security-group-ids sg-aaaaaaaaaaaaaaaaa --task-role-name artilleryio-ecs-worker-role --record ./test-file.yml
    working-directory: ./${{ inputs.base_path }}
  env:
    ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY }}
```

*The role being passed (artilleryio-ecs-worker-role) is valid, has a 6-hour max session duration, and contains the correct trust relationship:*
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "ecs.amazonaws.com",
          "ecs-tasks.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

<sub>Note: This issue also leads to expired credentials in long-running containers (e.g., failed AWS API calls), since no task role is available to provide refreshable credentials.</sub>
