### ISSUE TITLE
Too many vusers created for TypeScript test.

### ISSUE THREAD

**Issue by PatrickNausha** [artilleryio/artillery#3546]
# Version info: 
```
Artillery 2.0.23
Node.js v22.16.0
```

# Running this command: 
```
npx artillery@2.0.23 run ./too-many-vusers.ts
```
where the TS file is
```ts
// too-many-vusers.ts

export const config = {
  target: "https://example.com",
  phases: [
    {
      duration: 10,
      arrivalRate: 2,
    },
  ],
};

export const scenarios = [
  {
    flow: [
      {
        get: {
          url: "/",
        },
      },
    ],
  },
];
```

and running this command
```
npx artillery@2.0.23 run ./correct-vuser-count.js
```
where`correct-vuser-count.js` is the exact same contents as `too-many-vusers.ts`

# I expected to see this happen:

The output should contain
```
vusers.created: ................................................................ 20
```
in the `Summary report` for both the TS and JS load test runs

# Instead, this happened:

The output has
```
vusers.created: ................................................................ 40
```
for the the TS file and
```
vusers.created: ................................................................ 20
```
for the JS file

Full output for summary report in TS output:
```
--------------------------------
Summary report @ 09:39:34(-0700)
--------------------------------

http.codes.200: ................................................................ 40
http.downloaded_bytes: ......................................................... 25920
http.request_rate: ............................................................. 4/sec
http.requests: ................................................................. 40
http.response_time:
  min: ......................................................................... 12
  max: ......................................................................... 239
  mean: ........................................................................ 41.6
  median: ...................................................................... 16.9
  p95: ......................................................................... 194.4
  p99: ......................................................................... 223.7
http.response_time.2xx:
  min: ......................................................................... 12
  max: ......................................................................... 239
  mean: ........................................................................ 41.6
  median: ...................................................................... 16.9
  p95: ......................................................................... 194.4
  p99: ......................................................................... 223.7
http.responses: ................................................................ 40
vusers.completed: .............................................................. 40
vusers.created: ................................................................ 40
vusers.created_by_name.0: ...................................................... 40
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 48.5
  max: ......................................................................... 449.8
  mean: ........................................................................ 128.1
  median: ...................................................................... 80.6
  p95: ......................................................................... 424.2
  p99: ......................................................................... 432.7
```

# Files being used:

See https://github.com/PatrickNausha/artillery-typescript-vuser-bug-repro/, though the source is also copy-pasted above.

# Additional notes:

The number of vusers appears to be `duration * arrivalRate * arrivalRate` for TypeScript files as opposed to the expected count of `duration * arrivalRate` for JS files.

For example, the following code
```ts
export const config = {
  target: "https://example.com",
  phases: [
    {
      duration: 10,
      arrivalRate: 3,
    },
  ],
};
```
results in
```
vusers.created: ................................................................ 90
```
when run run as a TS file, but 30 when run as a JS file.

This problem is pretty severe since the growth is exponential and load may be orders of magnitude higher than I intend.
