### ISSUE TITLE
artillery run_fargate not aggregating correctly with multiple load generators

### ISSUE THREAD

**Issue by ericjdube-github** [artilleryio/artillery#3564]
I am running artillery with run_fargate.  I have just one phase.  It uses arrivalCount of 50 over a 3 minute duration.  When I look into the fargate task logs I can see 50 users created and 50 users completed.  Yet when I look at the aggregate in the output file, I see 50 created and 50 completed.

  "aggregate": {
    "counters": {
      "vusers.created_by_name.Connect and stream": 50,
      "vusers.created": 50,
      "vusers.failed": 0,
      "vusers.completed": 53,  ??? 53 doesn't even make sense ???

Version info:

VERSION INFO:
```
Artillery: 2.0.22
Node.js:   v22.14.0
OS:        win32
```

Running this command: 
```
artillery run-fargate --count 4 mytest.yml  -output out.json
```

I expected to see this happen:

  "aggregate": {
    "counters": {
      "vusers.created": 200,
      "vusers.failed": 0,
      "vusers.completed": 200,

Instead, this happened:

  "aggregate": {
    "counters": {
      "vusers.created_by_name.Connect and stream": 50,
      "vusers.created": 50,
      "vusers.failed": 0,
      "vusers.completed": 53,

When I look at the task logs on aws I see 50/50 on each of th the 4 load generator tasks

Files being used:
```
Here is my config:

config:
    target: "wss://<myapp>.com"
    phases:
        - name: "Do stuff"
          duration: "3m"
          arrivalCount: 50
    processor: "./do stuff.js"

scenarios:
    - name: "Do stuff"
      flow:
          - function: "dostuff"
```
