### ISSUE TITLE
Do selectors work?

### ISSUE THREAD

**Issue by markwylde** [artilleryio/artillery#435]
Looking at the [HTTP Reference](https://artillery.io/docs/http-reference/) I can see we can use selectors. I can't seem to get them to work using version 1.6.0-14 (node v8.9.4).

Also, just to let you know my page returns an HTML page, not a JSON.

My test.yml file looks like this:

```yaml
config:
  target: 'https://web-ui.internal.bts.dev:8003/'
  tls:
    rejectUnauthorized: false
  phases:
    - duration: 2
      arrivalRate: 2

scenarios:
  - flow:
    - log: "Show the login page"
    - get:
        url: "/login"
        capture:
          - json: "$.title"
            as: "id"
    - log: "Debug {{ id }}"
    - post:
        url: "/login"
        json:
          username: "test"
          password: "test"
```

The output I get is:

```bash
➜  stress-testing git:(master) ✗ artillery run test.yml
Started phase 0, duration: 2s @ 12:41:57(+0000) 2018-03-02
⠦ Show the login page
⠹ Show the login page
⠇ Show the login page
⠼ Show the login page
Report @ 12:42:04(+0000) 2018-03-02
  Scenarios launched:  4
  Scenarios completed: 0
  Requests completed:  8
  RPS sent: 1.14
  Request latency:
    min: 24.7
    max: 5035.7
    median: 1751.2
    p95: NaN
    p99: NaN
  Codes:
    200: 4
    302: 4

All virtual users finished
Summary report @ 12:42:04(+0000) 2018-03-02
  Scenarios launched:  4
  Scenarios completed: 0
  Requests completed:  8
  RPS sent: 1.14
  Request latency:
    min: 24.7
    max: 5035.7
    median: 1751.2
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 4 (100%)
  Codes:
    200: 4
    302: 4
```

Note how I get a bunch of "Show the login page" but nothing for "Debug..."

I have tried a bunch of selectors, all with the same output.

```yaml
capture:
  - regex: "/title(.*)/"
    as: "id"
```

```yaml
capture:
  - xpath: "(//Journey)[1]/JourneyId/text()"
    as: "id"
```

The Cheerio Selector get's me a bit further, but doesn't actually select anything.
```yaml
capture:
  - selector: "title"
    as: "id"
```
It returns a bunch of `Debug {}`
