### ISSUE TITLE
Exclude one or multiple phases from the Summary report

### ISSUE THREAD

**Issue by anthofo** [artilleryio/artillery#592]
I'm using artillery for load-testing of an AWS lambda function. There is a warm-up stage allowing to warm up the lambda, which takes a few seconds for the first invocation.

In production accordingly to our monitoring this case rarely happens, so I'd like to be able to exlude the warm up phase from the Summary report:

```yaml
phases:
    # warm up
    - duration: 1
      arrivalCount: 20
      name: "Warm up the lambda"
    - pause: 20
      name: "Wait for lambda warm up"
    # test
    - duration: 120
      arrivalRate: 14
      name: "Load test"
```

When executing the scenario I'd like to have a Summary report only for phase #3.
