### ISSUE TITLE
CSRF verification fail on seafile home page.

### ISSUE THREAD

**Issue by ygilbaum** [artilleryio/artillery#613]
When I'm running scenario against seafile local site, I'm getting an error (code 403), that contains the following message:

*CSRF verification failed. Request aborted. You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties. If you have configured your browser to disable cookies, please re-enable them*

The test file is:

```yaml
config:
  target: "https://seafile.localdomain"
  tls:
    rejectUnauthorized: true
  phases:
    - duration: 1
      arrivalRate: 1
  plugins:
    expect: {}
scenarios:
  - flow:
      - post:
          followRedirect: true
          url: "/"
          expect:
            - statusCode: 200
```

Do I have a configuration problem with this test?
