### ISSUE TITLE
Feature request: Variables at the scenario level

### ISSUE THREAD

**Issue by NivLipetz** [artilleryio/artillery#631]
Currently, Artillery supports `variables` at the `config` level of a test configuration.
**Example**:
```  config:
    target: "http://app01.local.dev"
    phases:
      -
        duration: 300
        arrivalRate: 25
   variables:   <---
      postcode:
        - "SE1"
        - "EC1"
        - "E8"
        - "WH9"
      id:
        - "8731"
        - "9965"
        - "2806"
```
It would be very useful to have the same ability to configure variables at the scenario level, which would enable users to create dynamic variables that are regenerated every run of the flow.
**Example**:
```
config:
  target: "https://example.com"
  phases:
    - duration: 10
      arrivalRate: 1
scenarios:
  - variables:  <--- new feature
      postcode:
        - {{ $randomString() }} .  <--- this value will be different at every run of the flow
  - flow:
      - log: "New virtual user running"
      - get:
          url: "/{{ postcode }}"
      - post:
          url: "/"
          json:
            postcode: "{{ postcode }}"
```
