### ISSUE TITLE
Expect repeats failed response data for each equals

### ISSUE THREAD

**Issue by ChaoticCoderr** [artilleryio/artillery#641]
For below expect conditions, when more than one condition fails, expects dumps the headers and response body for each failed condition. This creates much noise. It should be enough to dump once for all failed conditions for that request.

```
        expect:
          - statusCode: 200
          - equals:
            - "{{ rihSurfaceWeight }}"
            - 9570
          - equals:
            - "{{ poohSurfaceWeight }}"
            - 9970
          - equals:
            - "{{ rihMaxSetDownWeight }}"
            - -1477
          - equals:
            - "{{ poohMaxOverpull }}"
            - 20588

```
