### ISSUE TITLE
Inline variables, data from CSV, custom javascript variables not being passed properly in YAML.

### ISSUE THREAD

**Issue by sidsalunke** [artilleryio/artillery#644]
I'm trying to use inline variables to pass variables in my json body but in vain. 

I've also tried using data from CSV as well as context.vars in my custom javascript file. However, when trying to execute my yaml script, the `post` request uses the name of the variable rather than the value. 

The variables are stored correctly, however, when I pass them in through the yaml config, it only passes the the variable name and not the value.

Example:

**YAML - config section**
```
config:
  target: 'http://localhost:8080'
  phases:
    - duration: 1
      arrivalRate: 1
  variables:
    dummy_id:
      - "81b69ed9-2ac8-4ba8-9990-c7f32d45c640"
    test_id:
      - "1733a113-efbc-4f53-b9d1-660a3f107bfc"
```

**YAML - scenario section**
```
    - post:
        url: "{{ testURL }}"
        headers:
          Authorization: 'Bearer {{ access_token }}'
        json:
          - name: "dummy id"
            value: "{{ dummy_id }}" // sends the value as '{{ dummy_id }}' in the request body
          - name: "test id"
            value: "{{ test_id }}" // sends the value as '{{ test_id }}' in the request body
```

I've even tried setting the variables using `beforeRequest` as well as `function` but still the same result.

Strange thing is that I can see the the value of the variable if I log it. It's only when using in the json body that it grabs the variable name and not the value.

For example,

**This works:**

```
-log: "value is {{ test_id }}" // prints the value of test_id
```

**but  this doesn't work:**
```
json:
          - name: "dummy id"
            value: "{{ dummy_id }}" // sends the value as '{{ dummy_id }}' in the request body
``` 

For now, I'm using a workaround provided here -> https://github.com/artilleryio/artillery/issues/250#issuecomment-378384577
