### ISSUE TITLE
config variables cant be used in json lists

### ISSUE THREAD

**Issue by pithu** [artilleryio/artillery#645]
I wonder why config variables cant be used in json lists, is that a bug ?

I track down my issue to the following configuration:
```
config:
  target: "http://localhost"
  phases:
    - duration: 1
      arrivalRate: 1
  variables:
    foo: "bar"
scenarios:
  -
    flow:
      - log: "{{ foo }}"
      - log:
          foo: "{{ foo }}"
      - log:
        - "{{ foo }}"
```

log output is:

```
⠹ bar            // as expected
{ foo: 'bar' }   // as expected
[ '{{ foo }}' ]  // expect [ 'bar' ] here
```
substitution in strings and json objects worx, but in json lists not

**Comment by hassy** [comment]
That's specific to the `log` action which expects a string - but really there's no reason it shouldn't work with lists or objects!

**Comment by pithu** [comment]
Hello @hassy, first of all thanks for the quick reply and for providing this awesome tool.

The issue is specific for all json objects, currently its not possible to use variables in a list context at all. For example substitution in a rest call with a list schema do not work:
```
config:
  ...
  variables:
    foo: "bar"
  scenarios:
    - flow:
      - post:
          url: '/items'
          json:
            items:
              - "{{ foo }}"
```
sends `{ items: ["{{ foo }}"] }` instead of expected `{ items: ["bar"] }`.

I couldn't find a work around, does anyone has an idea how to send a list with a variable in it? 

Or could you provide a code pointer, for a good place to fix it, so i could try.  

Thanks in advance
