### ISSUE TITLE
how to log entire response (at least statusCode & body)

### ISSUE THREAD

**Issue by cyrfer** [artilleryio/artillery#650]
I'm trying to correlate the response statusCode with the response body. 

How can I get a log of the body & the statusCode? I attempted this:

```
...blah
scenarios:
  - name: POST /foo
    flow:
...blah
      - post:
          url: "/foo"
          capture:
            - json: "$"
              as: fooBody
...blah
      - log: "{{statusCode}} => {{ fooBody }}"
```

Obviously `statusCode` logs as `undefined`. The `fooBody` works.
