### ISSUE TITLE
Cookies not getting replayed from function

### ISSUE THREAD

**Issue by saranjaga** [artilleryio/artillery#652]
Rather than having login inside the flow I've invoked from the custom java script but the cookies does not replay as required. If i set them in the user context variable and use it in the subsequent methods in the flow, at times they are not setting as required and my post log in services throws back with 401. 

When i mention the log in the flow as part of the scenario, there are no problems at all and all the services works perfectly fine as expected but couldnt understand the behaviour when the log in extracted in to a function. Is there a way to replay the cookies in the flow in this scenario?

@hassy, any insights on this will be really helpful.

**Comment by hassy** [comment]
how are you setting the cookie in your custom JS code?

**Comment by saranjaga** [comment]
In JS inside function login

context.vars.sessionid = **get the cookie from log in response headers**

In yml

Cookie:
   SESSIONID: "{{sessionid}};Domain=.*****.com; Path=/; Secure; HttpOnly"

**Comment by sureshkrishnaselvam** [comment]
@hassy We have are executing login from custom js and tried calling from function as well as from before request. But we are getting 401 error response for few api calls. Could you please provide some solution for this.

**Login from before request:**

scenarios:
  - name: 'XXXXXXXX'
    flow:
    - post:
          name: "XXXXXXXX"
          beforeRequest:
            - "triggerLoginCall"
            - "recordStartTime"
          url: "/svc/profiles/{{pfId}}/(CustomerInsights+Actions)"
          cookie: 
            JSESSIONID: "{{jsessionId}}; Domain=.xxxxxxx.com; Path=/; Secure; HttpOnly"
          json:
            tier: tier2
            channel: desktop
          afterResponse: 
            - "reportLatency"

**Login from function:**

scenarios:
  - name: 'XXXXXX'
    flow:
      - function: "getLoginData"
      - get:
           name: "xxxxxxxxx"
           beforeRequest: "recordStartTime"
           url: "/svc/profiles/{{pfId}}/loyalty/(RewardsInfo)"
           cookie: 
             JSESSIONID: "{{jsessionId}}; Domain=.xxxxx.com; Path=/; Secure; HttpOnly"
           afterResponse: "reportLatency"

**Comment by hassy** [comment]
@sureshkrishnaselvam can you try setting just the value of the cookie, i.e.:

```yaml
name: 'XXXXXX'
flow:
  - function: "getLoginData"
  - get:
    name: "xxxxxxxxx"
    beforeRequest: "recordStartTime"
    url: "/svc/profiles/{{pfId}}/loyalty/(RewardsInfo)"
    cookie:
      JSESSIONID: "{{jsessionId}}"
    afterResponse: "reportLatency"
```
