### ISSUE TITLE
think + socket.io emit doesn't work

### ISSUE THREAD

**Issue by CharlieHess** [artilleryio/artillery#657]
I have a socket.io flow that looks like:

``` yml
config:
  target: 'http://localhost:5000'
  phases:
    - duration: 60
      arrivalRate: 2
  socketio:
    transports: ['websocket']
scenarios:
  - name: 'Simulate many users joining and leaving rooms'
    engine: 'socketio'
    flow:
      - think: 5
      - emit:
          channel: 'action'
          data: { 'type': 'CLIENT/JOIN_ROOM' }
      - think: 5
      - emit:
          channel: 'action'
          data: { 'type': 'CLIENT/LEAVE_ROOM' }
      - think: 5
```

The `emit` actions don't seem to run, maybe one or two of them get through at the end but certainly not what I'd expect to see.

I've tried changing the `transport`, `arrivalRate`, the time waiting in `think`, all to no avail. There is nothing special in my `socket.io` event handling besides parsing the `JOIN` and `LEAVE` actions.

If I remove the `think` portions from the flow everything starts working (of course, without any pauses in between).

Here's the summary from the run:

```
Summary report @ 17:04:17(-0800) 2019-02-24
  Scenarios launched:  120
  Scenarios completed: 120
  Requests completed:  240
  RPS sent: 3.45
  Request latency:
    min: 0.1
    max: 2.8
    median: 0.1
    p95: 0.3
    p99: 0.3
  Scenario counts:
    Simulate many users joining and leaving rooms: 120 (100%)
  Codes:
    0: 240
```
