### ISSUE TITLE
Context.vars as int / float from Javascript code!?

### ISSUE THREAD

**Issue by Siyfion** [artilleryio/artillery#660]
Essentially I'm trying to randomise my data from a _huge_ set of possibilities (numbers toned down in example source). But the API I'm testing has validation that checks to ensure that certain fields are `int` or `float` values. (For example: `tank`, `tillId`, `fuelQuantity`)

Due to the way variables are loaded it seems as though they are all coming across as strings. Is there any way around this?

I have the following load test config file:

```yml
config:
  target: 'https://some.api.com/'
  phases:
    - duration: 10
      arrivalRate: 1
      name: "Sustained max load"
  processor: "functions.js"
scenarios:
  - flow:
    - post:
        url: "/api/v1/transactions"
        beforeRequest: "generateVariableSiteData"
        json:
          requestTimestamp: "{{ currentTime }}"
          retailerId: "{{ retailerId }}"
          stationId: "{{ stationId }}"
          checksumScope: site
          checksum: 0
          transactions:
          - tillId: "{{ tillId }}"
            operatorId: "{{ operatorId }}"
            txRef: '55570'
            txTimestamp: "{{ currentTime }}"
            currency: GBP
            voidStatus: false
            totals:
              lineCount: 2
              grossValue: "{{ totalGrossValue }}"
            lineDetails:
            - lineNumber: 1
              stockType: WETSTOCK
              fuelGrade: 5
              pump: 4
              tankNumber: "{{ tank }}"
              productCode: '4'
              productDescription: SUPREME DIESEL 7.82L
              quantity: "{{ fuelQuantity }}"
              uom: litres
              unitNetValue: 1
              unitGrossValue: 1.2
              unitTaxValue: 0.2
              lineGrossValue: "{{ fuelLineGrossValue }}"
              categories: fuel
            - lineNumber: 2
              stockType: DRYSTOCK
              productCode: '5449000000996'
              productDescription: coca cola can 330ml
              quantity: 1
              uom: 330ml can
              unitNetValue: 0.99
              unitGrossValue: 0.99
              unitTaxValue: 0.2
              lineGrossValue: 1.19
              categories: soft drinks
            paymentDetails:
            - type: card
              cardExpiry: 10/23
              cardNumber: **************
            loyaltyDetails:
            - scheme: nectar
              identificationRef: '123456'
```

With a `functions.js` file:
```js
const dayjs = require('dayjs');

function pad(n, width, z) {
  z = z || '0';
  n = n + '';
  return n.length >= width ? n : new Array(width - n.length + 1).join(z) + n;
}

exports.generateVariableSiteData = (req, context, events, next) => {
  // Get the current time, used for the transaction time
  context.vars.currentTime = dayjs().toISOString();

  // Pick a random retailerId from the available pool
  context.vars.retailerId = pad(Math.floor(Math.random() * 6) + 1, 4)

  // Pick a random stationId from the available pool
  context.vars.stationId = pad(Math.floor(Math.random() * 6) + 1, 4)

  // Pick a random tank from the available pool
  context.vars.tank = Math.floor(Math.random() * 6) + 1

  // Pick a random tillId from the available pool
  context.vars.tillId = Math.floor(Math.random() * 10) + 1

  // Pick a random operatorId from the available pool
  context.vars.operatorId = (Math.floor(Math.random() * 200) + 1) + ''

  // Generate an amount of fuel to "buy"
  context.vars.fuelQuantity = +((Math.random() * 6) + 1).toFixed(2)
  context.vars.fuelLineGrossValue = +(1.2 * context.vars.fuelQuantity).toFixed(2)
  context.vars.totalGrossValue = context.vars.fuelLineGrossValue + 1.19

  console.log("VARS:", context.vars)

  return next();
};
```
