### ISSUE TITLE
Use payload with websocket target

### ISSUE THREAD

**Issue by Rykian** [artilleryio/artillery#663]
Hi there!

Is it possible to use payload to customize target URL in Websocket ?

I'm trying to use this config:
```yaml
config:
  payload:
    path: "users.csv"
    fields:
      - "access_token"
      - "login"
    skipHeader: true
  target: 'wss://localhost/websocket?auth={{ access_token }}'
  tls:
    rejectUnauthorized: false
  phases:
    - duration: 200
      arrivalRate: 1
scenarios:
  - engine: 'ws'
    flow:
      - think: 100
```

with the following CSV:
```csv
"access_token","login"
"A test token","Rykian"
```

But my auth param on server side is always `undefined`
