### ISSUE TITLE
Flow does not continue on a 302 status code

### ISSUE THREAD

**Issue by wmpay** [artilleryio/artillery#673]
I am using a sso page in my flow, which on successful login will redirect them and append a json web token to the url. It seems that if artillery receives a 302 status code, the flow will not continue. Is there a way to continue to the next step in the flow? I've tried the following: followRediect: false, expect plugin, and custom JS afterResponse function. Here is my code:

```
config:
  # plugins:
  #   expect: {}
  target: "http://localhost"
  processor: "./helpers.js"
  payload:
    path: "users.csv"
    fields:
      - "email"
      - "password"
  phases:
    - duration: 10
      arrivalRate: 10
scenarios:
  - name: "Login"
    flow:
      - get:
          url: "/login"
      - post:
          url: "/login"
          form:
            email: "{{ email }}"
            password: "{{ password }}"
          capture:
            header: "Location"
            transform: "this.split('/?jwt=')[1]"
            as: "jwt"
          followRedirect: false
          # afterResponse: "continueOn302"
          # expect:
          #   - statusCode: 302
      - log: "jwt: {{ jwt }}"
      - get:
          url: "/api/assignments"
          capture:
            json: "$.id"
            as: "id"
          headers:
            Authorization: "Bearer {{ jwt }}"
      - think: 15
      - post:
          url: "/api/assignments/{{ id }}"
          json:
            answer: "['foo', 'bar', 'baz']"
          headers:
            Authorization: "Bearer {{ jwt }}"
```
