### ISSUE TITLE
Conditional Requests

### ISSUE THREAD

**Issue by CamShft** [artilleryio/artillery#677]
Hello, 

i tried to add a conditional request because the value is not setted all time.

i use Artillery version: 1.6.0-27
on windows env

that's code that i tried to add : 
```
- get:
          url: "........./....."
          capture:
            json: $.items
            as: requests
- loop:
     - get:
              url:  "/resources/v1/suppliers/{{ $loopElement.supplierId }}"
              ifTrue: "$loopElement.supplierId not null"
              afterResponse: "logHeaders" 
  over: requests

```

thanks
