### ISSUE TITLE
BUGS? Loop on variable

### ISSUE THREAD

**Issue by CamShft** [artilleryio/artillery#678]
Hello,

i want loop on an array set in config, under variables.

**config**
```
  variables:
    requestToPost: ["386603", "386627", "386642"]
```
and the scenario : 
```
scenarios:
  - name: "'Planification' : Assigned/Unassigned"
    flow:
      - loop:
          - log: "teest {{ $loopElement}}"
        over: requestToPost
          requestToPost
```

and that won't log teest 386603, etc

can you explain me please because that seems like a bug
