### ISSUE TITLE
Cannot use variables in query-string

### ISSUE THREAD

**Issue by vmignot** [artilleryio/artillery#698]
Hello,

When using the HTTP engine, I'm doing the following :
```
      - get:
          url: "/users"
          capture:
            json: "$"
            as: "users"
      - get:
          url: "/companies"
          qs:
            user: "{{ users[0].id }}"
```

The `{{ users[0].id }}` is not replaces by its value: the send request is logged as the following:
`/companies?user=%7B%7B%20user%5B0%5D.id%20%7D%7D`

Thanks in advanced!

Regards,

Victor
