### ISSUE TITLE
using a shared config that uses a payload doesnt always set the context vars

### ISSUE THREAD

**Issue by simon-kyger** [artilleryio/artillery#713]
in a file: common_config.yml

```
config:
  target: "{{$processEnvironment.TARGET}}"
  payload:
    path: "../payloads.csv"
    fields:
      - "username"
      - "password"
  tls:
    rejectUnauthorized: false
  phases:
    - duration: "{{$processEnvironment.DURATION}}"
      arrivalRate: "{{$processEnvironment.ARRIVAL_RATE}}"
      #rampTo: 2000
  processor: "../js/processor.js"
```

in a file: test.yml
```
scenarios:
  - name: "Test"
    flow:
      - post:
          url: "/login"
          form: 
            username: "{{ username }}"
            password: "{{ password }}"`
          afterResponse: ["verifyLogin"]
```

in ../js/processor.js
```
module.exports = {
    verifyLogin: (requestParams, response, context, ee, next) => {
        console.log(`context.vars.username: ${context.vars.username}`);
        return next();
    }
}
```

in ./payloads.csv
```
username,password
apitest,apitest
```

issuing following command:
`TARGET='http://localhost' DURATION=1 ARRIVAL_RATE=1 artillery run -k -c "./common_config.yml" "./test.yml"`

sometimes when verifyLogin() is called, the following will echo:
context.vars.username: apitest
othertimes when verifyLogin() is called, the following will echo
context.vars.username: username
