### ISSUE TITLE
YAML: proper spec support

### ISSUE THREAD

**Issue by wwmoraes** [artilleryio/artillery#719]
It seems that artillery's YAML parser doesn't comply with the specs. I've got this spec-compliant YAML, with anchors and aliases:

```yaml
---
config:
  variables:
    basicauth: &basicauth
      user: myuser
      password: mypass
    loopcount: &loopcount
      10
    p1rampTo: &p1rampTo
      1000
  defaults:
    headers:
      Content-Type: application/x-www-form-urlencoded
  payload:
    -
      path: "{{ $environment }}-customer.csv"
      skipHeader: true
      fields:
        - "email"
        - "password"
    -
      path: "{{ $environment }}-catalog.csv"
      skipHeader: true
      fields:
        - "sku"
  environments:
    local:
      target: http://myservice.local
    qa:
      target: https://api.myservice.com
  phases:
    - name: "Warm up: 100 to {{ p1rampTo }} VU/s (ramp up) for 120 secs"
      duration: 120
      arrivalRate: 100
      rampTo: *p1rampTo
    - name: "Sustain: constant arrival of 100 VU/s for 1 secs"
      duration: 60
      arrivalRate: 1000

scenarios:
  - name: "Login and add {{ loopcount }} products to cart"
    flow:
      - get:
          url: "/customer/login"
          auth: *basicauth
          qs:
            username: customer@service.com
            password: customerpass
      - loop:
        - get:
            url: "/cart"
            auth: *basicauth
            qs:
              item: "{{ sku }}"
        count: *loopcount
```

the problem occurs with `rampTo: *p1rampTo`, which results in this error:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "size" is out of range. It must be >= 0 && <= 2147483647. Received NaN
    at assertSize (internal/crypto/random.js:34:11)
    at Object.randomBytes (internal/crypto/random.js:46:10)
    at createRamp (/home/<username></username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/core/lib/phases.js:103:30)
    at /home/<username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/core/lib/phases.js:50:16
    at arrayMap (/home/<username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/node_modules/lodash/lodash.js:639:23)
    at Function.map (/home/<username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/node_modules/lodash/lodash.js:9554:14)
    at phaser (/home/<username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/core/lib/phases.js:21:17)
    at run (/home/<username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/core/lib/runner.js:261:16)
    at EventEmitter.ee.run (/home/<username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/core/lib/runner.js:219:7)
    at /home/<username>/.nvm/versions/node/v11.6.0/lib/node_modules/artillery/lib/runner-sp.js:76:12
```

If I change `rampTo` to a static value, i.e. `rampTo: 1000` it works as expected.

Also, I'm unable to use those variables inside a phase name, as it parses as `undefined`.

It does't work for formatting even if I stand by the docs' [inline variables formatting guidelines](https://artillery.io/docs/script-reference/#inline-variables), i.e.:
```
config:
  variables:
    ...
    p1rampTo: &p1rampTo
      - "1000"
```

Output of both cases:
```
Started phase 0 (Warm up: 100 to undefined VU/s (ramp up) for 120 secs), duration: 120s @ ...
```
