### ISSUE TITLE
How do you extract data from file e.g. the whole file

### ISSUE THREAD

**Issue by bon960** [artilleryio/artillery#732]
Hi,
I'm simply trying to post xml to a endpoint via a xml file like so

```YML
config:
  target: "https://test.com"
  plugins:
    http-file-uploads: {}
  phases:
    - duration: 1
      arrivalRate: 1
scenarios:
  - flow:
    - post:
        capture: "hey"
        url: "/xml"
        headers:
          content-type: "application/xml"
        body: 
          fromFile: "./testdata/test.xml"
```
it seems to be posting the binary of xml file "test" , is there away to simply pass in a argument that extracts all data from a file?

thanks for reading.
