### ISSUE TITLE
artillery-plugin-expect :: Cannot run multiple expectation to multiple endpoints

### ISSUE THREAD

**Issue by ada-legion** [artilleryio/artillery#740]
**User Experience:** When user execute multiple endpoints it only test first url and skips next for example below url: 2.1-000002 and 2.1-000003> I have also tested the ordering and put different orders disabling expect in 2.1-000001 and leave it in 2.1-000002. Then again 2.1-000001 runs OK 2.1-000002 runs OK with Expectation OK and 2.1-000003 do not run at all

```
scenarios:
  - flow:
    - get:
        url: "/api/2.1-000001"
        capture:
          - json: "$response[0].account_id"
            as: account_id
        expect:
          - statusCode: 200
          - contentType: json
          - hasProperty: 'response[0].account_id'
          - equals:
            - "{{ account_id }}"   
    - get:
        url: "/api/2.1-000002"
        capture:
          - json: "$response[0].account_id"
            as: account_id
        expect:
          - statusCode: 200
          - contentType: json
          - hasProperty: 'response[0].account_id'
          - equals:
            - "{{ account_id }}"        
    - get:
        url: "/api/2.1-000003"
        capture:
          - json: "$response[0].account_id"
            as: account_id
        expect:
          - statusCode: 200
          - contentType: json
          - hasProperty: 'response[0].account_id'
          - equals:
            - "{{ account_id }}"
```
