### ISSUE TITLE
Functional testing with artillery-plugin-expect does not guarantee completeness

### ISSUE THREAD

**Issue by LesterTheTester** [artilleryio/artillery#741]
I am trying to use artillery-plugin-expect to also run my artillery tests as functional tests. However, the environment configuration shown to do this on the npm module page doesn't take into account the possiblity that one config file has multiple named scenarios:

```
config:
  environments:
    local:
      target: 'http://localhost:3000/'
      phases:
        - duration: 1
          arrivalRate: 1
      plugins:
        expect: {}
    staging:
      target: 'https://staging.myserver.com/'
      phases:
        - duration: 120
          arrivalRate: 10
  ensure:
    maxErrorRate: 1
scenarios:
  - name: Endpoint 1
    flow:
      - get:
          url: "/endpoint1"
          expect:
            - statusCode: 200
  - name: Endpoint 2
    flow:
      - get:
          url: "/endpoint2"
          expect:
            - statusCode: 200
```

It seems providing `duration: 1` and `arrivalRate: 1` means artillery will only ever execute 1 of my scenarios. Furthermore, due to the random selection, even if I change to `arrivalRate: 2`, I may just get two of the same scenario.

For proper functional testing, we need to validate ALL our scenarios in each run. Am I missing something here?
