### ISSUE TITLE
Query string not added to a url with a dynamic path param

### ISSUE THREAD

**Issue by a88zach** [artilleryio/artillery#745]
This will construct the correct URL
```
get:
  url: '/pricing/{{ zipcode }}?specialties={{ specialty }}'

output: /pricing/12345?specialties=Foo
```

This does not add the query string params correctly
```
get:
  url: '/pricing/{{ zipcode }}'
  qs:
     specialties: '{{ specialty }}'

output: /pricing/12345
```

Adding query string params via the `qs` property works correclty when you don't template the url
