### ISSUE TITLE
parseInt phases config

### ISSUE THREAD

**Issue by abarriel** [artilleryio/artillery#750]
Hey ! I would like to be able to perform an action like that

```yaml
 variables:
    count: 1
phases:
    duration: 1
    arrivalCount: "{{ count }}"
```

There is anyway?

**Comment by hassy** [comment]
yes, you can use `$processEnvironment` to set those values dynamically via environment variables, e.g.:

```yaml
config:
  phases:
    duration: 10
    arrivalRate: "{{ $processEnvironment.ARRIVAL_RATE }}"
```

and then run your script with:

```
ARRIVAL_RATE=20 artillery run my-script.yaml
```
