### ISSUE TITLE
Report y-axis contains wrong values

### ISSUE THREAD

**Issue by justin-vanwinkle** [artilleryio/artillery#764]
```
Artillery: 1.6.0-29
Artillery Pro: not installed (https://artillery.io/pro)
Node.js: v8.10.0
OS: linux/x64
```

When performing tests with low load (1rps - 2rps), the generated report contains the wrong y-axis values for RPS Count and HTTP Codes. Typically, I find that the graphs have y-axis values that are multiplied by 10.

This can be reproduced with:
```
  phases:
    - duration: 60
      arrivalRate: 1
      rampTo: 2
    - duration: 120
      arrivalRate: 2
```
