### ISSUE TITLE
Passing custom arguments to functions

### ISSUE THREAD

**Issue by ademartini** [artilleryio/artillery#767]
Is it possible to pass custom arguments to functions or to at least set variables within an HTTP request section like this:

```
- post:
    url: "some url"
    variables:
      some_var: "foo"
    beforeRequest: "someFunction"
```

Based on the docs it seems like the only time you can set a variable is in the `config` section or as part of a capture.  It would be nice to have more flexibility here.
