### ISSUE TITLE
Socket Server TLS example

### ISSUE THREAD

**Issue by nicolasfalk** [artilleryio/artillery#768]
Hello!

I am fairly new to artillery, have been using it to test a REST API. But due to certain circunstances, now I need to test a TLS Socket Server. I have succeeded in connecting to the server using the webscocket engine, but i can't send any data whatsoever, the problem, I believe, is being caused by the headers, not so sure on that regard.

The socket server is a Node.js application.

This is my .yml config:

```
config:
  target: 'wss://localhost:4433'
  processor: "PerformanceTestProcessor.js"
  phases:
    - duration: 1
      arrivalRate: 1
  ws: 
    headers: {}
    client: 
      key: "certs/tls/local/key.pem"
      cert: "certs/tls/local/cert.pem"
    rejectUnauthorized: false
scenarios:
  - engine: "ws"
    flow: 
      - function: "createData"
      - send: "{{data}}"
      - think: 15
```

and this is the data the socket is receiving and returning to my end:

```
GET / HTTP/1.1
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 7Ws1ZQ5Rw8dMB3J2K59qjg==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: localhost:4433
```

the variable data is set in the "createData" function, and is a binary simulating some POS information, but due to the data informed above, my test case isn't even starting the flow.

I have no idea if this is an error on my part, or in the apllication.

Best regards, Nicolas Falk.
