### ISSUE TITLE
Publishing metrics does not work

### ISSUE THREAD

**Issue by rnemeth1980** [artilleryio/artillery#772]
I am using artillery.io version

```
Artillery: 1.6.0-29
Artillery Pro: not installed (https://artillery.io/pro)
Node.js: v8.16.1
OS: linux/x64
```

this is the yaml script:

```yaml
---
config:
scenarios:
  - flow:
    - log: "LVL1"
    - get:
          url: /shop/hardware--10--c
          expect:
            - statuscode: 200
    - get:
          url: /shop/software--20--c
          expect:
            - statuscode: 200
    - get:
          url: /it-loesungen
          expect:
            - statuscode: 200
```

this is the configuration yaml:

```yaml
---
config:
  target: https://stage.abc.com
  tls:
    rejectUnauthorized: false
  phases:
    - duration: 120
      arrivalCount: 6
  plugins:
      publish-metrics:
        - type: influxdb-statsd
          host: abc.abc.de
          port: 32002
          prefix: artillery.
          tags:
          - team:abc
          - component:navigation
          - region:de
          event:
            tags:
              - team:abc
```

Using Atlassian Bamboo version 6.7.2 build 60706 - 10 Dec 18.

Published successfully to the Telegraf/InfluxDB/Grafana stack for a couple of days, then it stopped working two days ago and gives the following error on Bamboo:

```
14-Nov-2019 11:07:17 | (node:5379) UnhandledPromiseRejectionWarning: Error: Exited with code 3
-- | --
14-Nov-2019 11:07:17 | at ChildProcess.<anonymous> (/home/bamboo/.nvm/versions/node/v12.12.0/lib/node_modules/artillery/node_modules/opn/index.js:85:13)
14-Nov-2019 11:07:17 | at Object.onceWrapper (events.js:300:26)
14-Nov-2019 11:07:17 | at ChildProcess.emit (events.js:210:5)
14-Nov-2019 11:07:17 | at maybeClose (internal/child_process.js:1021:16)
14-Nov-2019 11:07:17 | at Socket.<anonymous> (internal/child_process.js:430:11)
14-Nov-2019 11:07:17 | at Socket.emit (events.js:210:5)
14-Nov-2019 11:07:17 | at Pipe.<anonymous> (net.js:658:12)
14-Nov-2019 11:07:17 | (node:5379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
14-Nov-2019 11:07:17 | (node:5379) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Exactly the same script publishes successfully to the stack when executed locally in a linux vm.
