### ISSUE TITLE
Config: how to set target from js?

### ISSUE THREAD

**Issue by whitebyte** [artilleryio/artillery#775]
I want to read a config target from a javascript file:
```yaml
config:
  target: "{{ target }}"
  processor: "../dist/helpers.js"
```

helpers.js:
```js
export { target: "my URL" };
```

yet when I run my test I get `No target specified and no environment chosen`
