### ISSUE TITLE
websocket requests

### ISSUE THREAD

**Issue by michyliao** [artilleryio/artillery#780]
hi

I am trying to run a logged in scenario, but i noticed that it is not using 1 websocket to connect, but multiple. How can i enforce 1 ws for each vu per scenario? 

thanks!

**Comment by hassy** [comment]
Do you want all virtual users to share the same connection? What you're describing ("1 ws for each vu per scenario") is the default behavior in Artillery. Each virtual users open a separate connection (as would be the case in the real world).

**Comment by michyliao** [comment]
I noticed when I was running my scenario, the vu was opening new ws connection for each flow.. (reason for my ask) Is there a way to debug this?

**Comment by hassy** [comment]
That is the expected behavior - each virtual user (i.e. each new execution of a scenario) opens a new connection to the server, just like it would in the real world. There is no way to create a fixed pool of WebSocket connections to be used by multiple virtual users in Artillery.

**Comment by michyliao** [comment]
I understand that. What i meant was my scenario has multiple flows under - and the flows are multiple sends, and the send are creating new sockets. I thought each execution of a scenario is a new connection, not each send of the scenario. 

ie. This created 3 separate web sockets, not 1 for each vu
```
scenarios:
  - engine: "ws"
    name: "name"
    flow: 
      - send: 
          data:data
      - think: 2
      - send:
          data: data
      - think: 2
      - send:
          data: data
```
