### ISSUE TITLE
Capture response from websocket using engine:ws

### ISSUE THREAD

**Issue by Arsalanliaqat** [artilleryio/artillery#800]
```
config:
  target: "ws://localhost:8080/4h4j4kl4n4j4h4k4k4j4h4j/8d7g8g9f87d7d988f8b9f8b?userId=QvHPh7NXWz"
  processor: "./load-test.js"
  phases:
    - duration: 6
      arrivalRate: 1
      rampTo: 10
      name: "Ramping up the load"

    - duration: 6
      arrivalRate: 10
      rampTo: 10
      name: "Pushing a constant load"

scenarios:
  - engine: "ws"
    flow:
      - function: "autheticationDetails"
      - send:
          type: "authenticate"
          attendee: "{{ attendee }}"
          token: "{{ token }}"
      - think: 5
      - send:
          type: "open_channel"
          participants: ""
      - think: 5
      - send:
          type: "send_message"
          channel: "5e3d6b72ab7f55516e3b34f4"
          body: { type: 'text', text: '==============Test==================' }
```
**While sending this message receives this response respectively.**

Message:` {"type": "open_channel","participants": ""}`
Response: `{"type":"channel","channel":"5e3d6b72ab7f55516e3b34f4","created":false}`

> Cannot capture channel from response and pass it to next request?
