### ISSUE TITLE
Add support for .JSON files as variables

### ISSUE THREAD

**Issue by Xillians** [artilleryio/artillery#824]
When I was setting up an `example.yml` file, I realised very early that rather than writing out what the entire json was in a yml format, it would be much easier to save the request body as a `.json` file that I could add as a variable, similar to how you have a payload with a `.csv` file. I tried searching online, and as far as I could gather, the main way to do that was by adding a javascript file that did something along the lines of: 

```Javascript
var JSONFile= require('fs').readFileSync("./requests/requestBody.json");

exports.setJSONBody = (req, context, events, next) => {
    const requestJSON= JSON.parse(JSONFile);
    
    context.vars.requestBody = requestJSON;
    return next();
};
```
And then adding `beforeRequest: "setJSONBody"` in the `.yml` file. Although this does work, I'm now adding a custom javascript file whose sole purpose is to find a `.json` file, parse this, and add that as a variable to the artillery config file. I felt doing that step could have been averted by either having `payload` support json as a file type on `path`, or have a field where you can add the path of a json file you want to use in the script. E.g.
```
file: "request.json"
   as: "requestBody"
```

Sidenote: 
The documentation wasn't entirely clear about how to use the custom JS to set the JSON value in a way that the config file could use it. Having an example of a valid JSON body that the `.yml` example used as a generic variable would help out a lot there.

**Comment by sayjeyhi** [comment]
This can be a very good feature... I need this as well

**Comment by eliezercazares** [comment]
Hi @Xillians , do you have the example in the YAML where you implement the JS method you included in the post?
I am not sure how to send a raw json in the request body, the documentation, as you mention, only covers building the JSON body within the YAML.

**Comment by Xillians** [comment]
Hi, @eliezercazares ! That plugin you showed on the update seems super useful! Thank you for bringing it up 💙 

and if you wanted to know, the way I added the js file using my example was essentially this:
```
config:
  processor: "./helper.js"
  ....
        - post:
          name: "xx"
          url: "/endpoint/"
          beforeRequest: "setJSONBody "
          headers: 
            Accept: "application/json"
          json: "{{ requestBody }}"
```
