### ISSUE TITLE
Header capture doesn't handle upper case characters

### ISSUE THREAD

**Issue by dandenton** [artilleryio/artillery#828]
When capturing header information it seems like the header's name must be all lower case.  The following script will run the first request but it stops before running the second.

```
config:
  target: https://artillery.io
  phases:
    - duration: 1
      arrivalRate: 1
scenarios:
  - flow:
    - get:
        url: /
        capture:
          - header: ETag
            as: pageETag
        expect:
          - statusCode: 200
    - get:
        url: /
        headers:
          If-None-Match: "{{ pageETag }}"
        expect:
          - statusCode: 304
```

```
All virtual users finished
Summary report @ 12:55:37(-0600) 2020-05-04
  Scenarios launched:  1
  Scenarios completed: 0
  Requests completed:  1
  Mean response/sec: 2.17
  Response time (msec):
    min: 124.7
    max: 124.7
    median: 124.7
    p95: 124.7
    p99: 124.7
  Scenario counts:
    0: 1 (100%)
  Codes:
    200: 1
```

If you change `- header: ETag` to `- header: etag` the script executes both requests correctly.  I would expect the initial script to either work or throw an error.

```
All virtual users finished
Summary report @ 13:01:25(-0600) 2020-05-04
  Scenarios launched:  1
  Scenarios completed: 1
  Requests completed:  2
  Mean response/sec: 2.11
  Response time (msec):
    min: 116.5
    max: 558.6
    median: 337.6
    p95: 558.6
    p99: 558.6
  Scenario counts:
    0: 1 (100%)
  Codes:
    200: 1
    304: 1
```
