### ISSUE TITLE
Timeout ignored when checking for acknowledgement with socketio

### ISSUE THREAD

**Issue by DanielGibbsNZ** [artilleryio/artillery#830]
When checking for an acknowledgement using `acknowledge` with socketio, the configured timeout is ignored. It is respected when checking for a `response` with socketio, but not `acknowledge`.

I'm using the following example:

```
config:
  timeout: 5
  # Target, phases etc.
scenarios:
- name: Test
  engine: socketio
  flow:
  - emit:
    channel: my_channel
    data:
      foo: bar
    acknowledge:
      match:
        json: "$.0"
        value: baz
```
