### ISSUE TITLE
How to emit response time in a custom function

### ISSUE THREAD

**Issue by benel** [artilleryio/artillery#837]
Hello ! 

@garnier5 and I discovered your great tool yesterday (thank you for it!). 

In the process of including Puppeteer steps in Artillery scenarios, I started with a "toy" function trying to mimic the official `get` step.

Here is my code : 

```js
const fetch = require('node-fetch');

module.exports = {

  visitHome: async (context, events, done) => {
    let start = new Date().getTime();
    await fetch(context.vars.target)
      .then(x => x.text());
    events.emit('histogram', 'response_time', new Date().getTime() - start);
    return done();
  }

}
```

```yaml
config:
  target: http://localhost:3000
  phases:
    - duration: 10
      arrivalRate: 20
  processor: ./custom.js

scenarios:
  - name: Discover the app
    flow:
      - function: visitHome
```

It results in:

```yaml
Summary report @ 12:52:49(+0200) 2020-05-09
  Scenarios launched:  200
  Scenarios completed: 200
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    Discover the app: 200 (100%)
  response_time:
    min: 2
    max: 34
    median: 3
    p95: 5
    p99: 14.5
```

Is it the right way to do this?
What would be the right key to use so that measures are displayed in the official `Response time (msec)` ?
