### ISSUE TITLE
[FEATURE] Set custom parser on Socket.IO

### ISSUE THREAD

**Issue by cesarlima-hotmart** [artilleryio/artillery#845]
Would be nice to have a property to set a custom parser to socket.io, like [socket.io-msgpack-parser](https://www.npmjs.com/package/socket.io-msgpack-parser).
```yml
config:
  target: "https://myapp.staging:3002"
  socketio:
    parser: "socket.io-msgpack-parser"
```
