### ISSUE TITLE
JSON using variables

### ISSUE THREAD

**Issue by PokeyOats** [artilleryio/artillery#848]
Good Day all,

I think I have found a bug in a situation using a variable with JSON.

Whilst the following works:

```
   - post:
        url: "/jsontest"
        json: 
          { "alerts": [ { "labels": { "alertname": "Watchdog" } } ] }
```
The following doesn't.

```
variables:
    jsontest1: "{ \"alerts\": [ { \"labels\": { \"alertname\": \"Watchdog\" } } ] }"

...

    - post:
        url: "/jsontest"
        json: 
          {{ jsontest1 }}
```
