### ISSUE TITLE
Incorrect time units in HTML report

### ISSUE THREAD

**Issue by cserby** [artilleryio/artillery#851]
I ran artillery (version `1.6.0`) using this script:
```
config:
  target: 'https://artillery.io'
  statsInterval: 0.1
  phases:
    - duration: 15
      arrivalRate: 67
scenarios:
  - flow:
    - get:
        url: "/docs"
```

This is a run, that takes 15 seconds (`.config.phases[0].duration`), however the report shows:
<img width="352" alt="Screen Shot 2020-06-29 at 1 38 33 PM" src="https://user-images.githubusercontent.com/14993439/86000519-f2426480-ba0d-11ea-833b-e3a1e44dd14c.png">

Also, the chart's X-axis shows time in some weird unit (1/100th of a second?):
<img width="883" alt="Screen Shot 2020-06-29 at 1 40 09 PM" src="https://user-images.githubusercontent.com/14993439/86000637-143be700-ba0e-11ea-81d7-44fff7b538f8.png">

[Load Test Report (1).zip](https://github.com/artilleryio/artillery/files/4845191/Load.Test.Report.1.zip)
