### ISSUE TITLE
JSONPath flattened array results in a random value being selected.

### ISSUE THREAD

**Issue by Plitzer** [artilleryio/artillery#853]
When capturing a flattened JSONPath array (e.g. using the `*` selector) the resulting variable contains one value selected at random from the array.

This should be storing the whole array into the variable.

Minimal repro:

```
config:
  target: 'https://jsonplaceholder.typicode.com'
  phases:
    - duration: 5
      arrivalRate: 1
scenarios:
  - flow:
    - get:
        url: "/todos"
        capture: 
          json: "$[*].id"
          as: "todoIDs"
    - log: "todoIDs: {{ todoIDs }}"
```
