### ISSUE TITLE
Interpret Artillery results

### ISSUE THREAD

**Issue by ihemantkumar** [artilleryio/artillery#857]
I had run an Artillary.io load test on my server for the WebSocket connection. The following is the configuration I used. Can anyone tell me how should I interpret the result?

This is my configuration yml file

```
config:
    target: "wss://mydomain.com/wss/"
    ensure:
      maxErrorRate: 1
    phases:
      - duration: 10
        arrivalRate: 5
        rampTo: 10
        name: "Warming up"
      - duration: 20
        arrivalRate: 10
        rampTo: 50
        name: "Mid load"
      - duration: 60
        arrivalRate: 100
        rampTo: 500
        name: "Mid 2 load"
      - duration: 120
        arrivalRate: 1000
        rampTo: 5000
        name: "Max load"
scenarios:
  - engine: "ws"
    flow:
      - send: "hello"
      - think: 3
      - send: "how are you?
```
Here is the result I captured in the JSON. Does this mean that my server has a capacity of handling 59k or more connections?
```
{
  "aggregate": {
    "timestamp": "2020-07-09T13:57:43.568Z",
    "scenariosCreated": 380469,
    "scenariosCompleted": 29625,
    "requestsCompleted": 59250,
    "latency": {
      "min": 0.1,
      "max": 1989.7,
      "median": 2.5,
      "p95": 346.8,
      "p99": 816.2
    },
    "rps": {
      "count": 59250,
      "mean": 21.72
    },
    "scenarioDuration": {
      "min": 3010.8,
      "max": 160541.7,
      "median": 14196.7,
      "p95": 66471.8,
      "p99": 98824.2
    },
    "scenarioCounts": {
      "0": 380469
    },
    "errors": {
      "Parse Error": 70,
      "read ECONNRESET": 137937,
      "Unexpected server response: 503": 27191,
      "connect ETIMEDOUT 34.208.199.54:443": 184453,
      "read ETIMEDOUT": 1193
    },
    "codes": {
      "0": 59250
    },
    "matches": 0,
    "customStats": {},
    "counters": {},
    "scenariosAvoided": 0,
    "phases": [
      {
        "duration": 10,
        "arrivalRate": 5,
        "rampTo": 10,
        "name": "Warming up"
      },
      {
        "duration": 20,
        "arrivalRate": 10,
        "rampTo": 50,
        "name": "Mid load"
      },
      {
        "duration": 60,
        "arrivalRate": 100,
        "rampTo": 500,
        "name": "Mid 2 load"
      },
      {
        "duration": 120,
        "arrivalRate": 1000,
        "rampTo": 5000,
        "name": "Max load"
      }
    ]
  },.....
