### ISSUE TITLE
Variable Templating translates strings into unicode in JSON POST body

### ISSUE THREAD

**Issue by aandersoncs** [artilleryio/artillery#862]
Hey guys, so I have this issue where I'm attempting to read login credentials (of multiple generated users) from a CSV and subsequently use those credentials in a HTTP POST step by using the variable templating solution. What I see as output in the debugging solution is that these strings from the CSV are being replaced with Unicode literals and causing the POST to return 500. Is this intended behavior?

Config:
```
config:
  payload:
    path: "users.csv"
    fields:
      - "user"
      - "password"
scenarios:
  - flow:
    - log: "Password: {{ password }} Username: {{ user }}"
    - post:
        url: "/mobile/login/"
        json:
          username: "{{ user }}"
          password: "{{ password }}"
```

Outputted Request Object from debug logs:
```
"json": {
    "username": "\u0000\n\u0000u\u0000s\u0000e\u0000r\u0000n\u0000a\u0000m\u0000e\u0000@\u0000s\u0000o\u0000m\u0000e\u0000t\u0000h\u0000i\u0000n\u0000g\u0000.\u0000c\u0000o\u0000m\u0000",
    "password": "\u0000p\u0000a\u0000s\u0000s\u0000w\u0000o\u0000r\u0000d\u0000"
  }
```
