### ISSUE TITLE
Feature: split large scenarios

### ISSUE THREAD

**Issue by jods4** [artilleryio/artillery#868]
Managing large scenarios can be challenging.

I think the following new features would help:

1. Be able to define named flows, with contextual variables and re-use them.
Example use-case: your scenario logs in as user A, perform some actions, then logs as user B, perform more actions, then as user C and completes a workflow.
If logging in requires several steps it's a lot of copy-pasted code.

Something similar to this might help (top level `flows` + `run` action):
```yaml
flows:
  login: 
    - get: { url: "/" }
    - post: 
        url: "/login"
        form: 
          username: "{{ user }}"
          password: "{{ password }}"

scenarios:
  - name: "Workflow"
    flow: 
      - run:
          flow: login
          variables: 
            user: UserA
            password: 1234
      # Do stuff
      - run: 
          flow: login
          variables: 
            user: UserB
            password: p@ss
      # Do stuff      
```
Login is just an example, any repeated actions in a single scenario or actions shared accross multiple scenarios would benefit from that.

When managing large/many scenarios, it would also be helpful being able to split the yaml in multiple files.
Maybe add `include` as a new option for scenarios and `includeFlows` on top of the proposed `flows`:
```yaml
includeFlows:
  - "./login.yaml"
scenarios: 
  - name: "Workflow"
    flow:
      - run: { flow: "login" }
      - include: "./userA.yaml"
```
