### ISSUE TITLE
Unable to publish metric into DataDog via "artillery-plugin-publish-metrics"

### ISSUE THREAD

**Issue by bcexopolllo** [artilleryio/artillery#876]
I have a sort of next script:
```
config:
    target: "target"
    plugins:
      publish-metrics:
        - type: datadog
          apiKey: cbe99fbe33c1e2dd077f5a4a982474fd
          # host: 127.0.0.1
          # port: 5002
          prefix: artillery.
          tags:
            - team:sre
            - component:eu-payments-backend
            - region:eu-west-1
          event:
            tags:
              - team:sre
    payload:      
      path: "./UsersTokens.csv"
      fields:
        - "staticTokens"
    processor: "./AdditionalScripts/customFunctions.js"
    defaults:
      headers:
        Authorization: "Bearer {{ staticTokens }}"
        Content-Type: "application/json"
    phases:      
      - duration: 1
        arrivalRate: 1
        rampTo: 2
        name: "debug"
scenarios:
##some scenarios..
```

I've installed "artillery-plugin-publish-metrics" and have no error during the artillery run.
but still seeing no test data log in DataDog

also I'm worrying about this issue:
https://github.com/artilleryio/artillery/issues/856

could anyone please assist?
DataDog trial period gonna end soon
