### ISSUE TITLE
POST event call with correct url specified gives error: "an URL must be specified"

### ISSUE THREAD

**Issue by savitanagaraj** [artilleryio/artillery#878]
I am writing a test case to do API testing, specifically a POST event call. Here is my code:
```
- log: "POST event call"
    - post:
       url: "/api/v1/events/"
       headers:
         content-type: "application/json"
         authorization: "bearer {{bearertoken}}"
       json:
       - eventType: "test"
         startTime: "{{ST_01}}"
         endTime: "{{ET_01}}"      
       expect:
        - statuscode : 204 
    - log: "completed POST event call"
```
I do have a target url specified at the very top of my script. The GET events are working, but not the POST. Here is the error:
```
POST event call
completed POST event call
Report @ 18:21:59(-0400) 2020-09-08
Elapsed time: 2 seconds
  Scenarios launched:  1
  Scenarios completed: 0
  Requests completed:  2
  Mean response/sec: 1.35
  Response time (msec):
    min: 140.3
    max: 975.1
    median: 557.7
    p95: 975.1
    p99: 975.1
  Codes:
    200: 1
    403: 1
  Errors:
    an URL must be specified: 1
```

What am I missing here?
