### ISSUE TITLE
Capturing a socket.io response is undefined

### ISSUE THREAD

**Issue by robertpaker888** [artilleryio/artillery#887]
Hi,

Is it possible with artillery to capture the response of a websocket created via socket.io. The response is always undefined. My example config is below. I can see from the summary report and by observing the socket-server, that data is being sent and returned. Below I have included my test config, sample socket-server code and summary report

```config:
  target: "http://localhost:3000/"
  phases:
    - duration: 5 
      arrivalRate: 2 
  socketio:
    transports: ["websocket"]
    extraHeaders:
      referer: foo1.team
  defaults:
    headers:
      referer: foo2.team
scenarios:
  - engine: "socketio"
    flow:
      - emit:
          channel: "chat-message"
          data: "fooBar"
        response:
          channel: "some-room"
          capture:
            json: "$"
            as: "res"
      - log: "response={{res}}   // **res is always undefined** 
```

**The socket server code being run below:**

```
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);
var port = process.env.PORT || 3000;

app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

io.on('connection', function(socket){
  
  socket.join('some-room');
   
  socket.on('chat-message', function(msg){
    //io.emit('chat message', msg);
	//io.to('some-room').emit('chat-message', msg);
	io.in('some-room').emit('chat-message', msg);

  });
  
});

http.listen(port, function(){
  console.log('listening on *:' + port);
});


//http://localhost:3000/
```

**The summary artillery report output**

```
Summary report @ 09:32:55(+0100) 2020-10-13
  Scenarios launched:  10
  Scenarios completed: 10
  Requests completed:  10
  RPS sent: 2.01
  Request latency:
    min: 0.1
    max: 1.4
    median: 0.2
    p95: 1.4
    p99: 1.4
  Scenario counts:
    0: 10 (100%)
  Codes:
    0: 10
```

**Comment by robertpaker888** [comment]
Got it working. Changed the config and server to explicitly take a json object and changed the response channel to chat-message . See below:

```
target: "http://localhost:3000/"
  phases:
    - duration: 5 
      arrivalRate: 2 
  socketio:
    transports: ["websocket"]
    extraHeaders:
      referer: foo1.team
  defaults:
    headers:
      referer: foo2.team
scenarios:
  - engine: "socketio"
    flow:
      - emit:
          channel: "chat-message"
          data: { "msg": "fooBar2" }
        response:
          channel: "chat-message"
          capture:
            json: "$"
            as: "res"
      - log: "response={{res}}   // **res is always undefined** 
```

*** Updated server code ***

```
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);
var port = process.env.PORT || 3000;

app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

io.on('connection', function(socket){
  
  socket.join('some-room');
   
  socket.on('chat-message', function(data){
    //io.emit('chat message', data.msg);
	//io.to('some-room').emit('chat-message', data.msg);
	
	data.msg = data.msg +  Date.now();
	io.in('some-room').emit('chat-message', data);

  });
  
});

http.listen(port, function(){
  console.log('listening on *:' + port);
});
```
