### ISSUE TITLE
metrics-by-endpoint plugin not working

### ISSUE THREAD

**Issue by sercasti** [artilleryio/artillery#888]
metrics-by-endpoint doesn't seem to be working, or I don't understand where to look for. I checked the plugin documentation but there wasn't much to see. 

I see the loadGenerator logs generating the median, p95, p99 metrics, but nothing by endpoint. See screenshots

This is my script.yml

```
config:   
  target: 'https://xxxxx.amazonaws.com/test'
  phases: 
    - duration: 120 # how long virtual users will be generated for.
      arrivalRate: 5 # Create 10 virtual users every second
      rampTo: 50
      name: "Warm up the application"
    - duration: 600
      arrivalRate: 260
      name: "Sustained max load"  
  plugins: 
    metrics-by-endpoint: {}
    cloudwatch:
      namespace: "performance_tests"
      
scenarios:
  - flow:
    - get:
        url: "/vanillahwlat"
    - get:
        url: "/vanillahwlatka"
```

<img width="1002" alt="Screen Shot 2020-10-13 at 12 02 14" src="https://user-images.githubusercontent.com/1434319/95879169-6d751f80-0d4c-11eb-8a99-ae9bbe21addc.png">
<img width="991" alt="Screen Shot 2020-10-13 at 11 57 46" src="https://user-images.githubusercontent.com/1434319/95879178-70701000-0d4c-11eb-9792-43492ba3eac7.png">
