### ISSUE TITLE
Handling of ampersand in querystring parameter

### ISSUE THREAD

**Issue by timorjim** [artilleryio/artillery#900]
Not sure if this is a bug or misuse on my behalf.

Using payload data from a csv to build a querystring. If the csv field contains `&` then it doesn't seem to get encoded and hence is truncated in transit.

Relevant yml:
```
  payload:
    path: "smoke-parameters.csv"
    fields:
      - "title"
    order: sequence
    skipHeader: true
scenarios:
  - flow:
      - get:
          url: "/v1/benchmarks/byrawtitle?country=au&locationId=1004&rawRoleTitle={{ title }}&subClassId=1000"
```

Csv data:
```
title
Civil ++ Demolition & Labourers
```

The console output (using the expectations plugin) shows a url with encoding applied to spaces, but not the `&`.
```
Request params:
    http://localhost:8888/v1/benchmarks/byrawtitle?country=au&locationId=1004&rawRoleTitle=Civil ++ Demolition & Labourers&subClassId=1000
  Body:
    "{\"requestParameters\":{\"country\":\"au\",\"locationId\":1004,\"subClassId\":1000,\"jobId\":null,\"hirerId\":null,\"rawRoleTitle\":\"Civil    Demolition \"},\" ... 
  User variables:
     target : http://localhost:8888
     $environment : local
     title : Civil ++ Demolition & Labourers
    * GET /v1/benchmarks/byrawtitle?country=au&locationId=1004&rawRoleTitle=Civil%20++%20Demolition%20&%20Labourers&subClassId=1000
```

I can't see any other options around encoding. Am I missing something?
