### ISSUE TITLE
Sanitize function is remplacing context variables that are null or undefined by ''

### ISSUE THREAD

**Issue by tychota** [artilleryio/artillery#904]
# Description

- BUG (not a new feature)
- see reproduction tests

# Version

- artillery: 1.6.1
- node: 12.16.1

# Reproduction steps:

- create a new dir
- install latest artillery
- create a request bin (in my example, got http://requestbin.net/r/1cmn1je1)
- add the following yaml file

```yaml
config:
  target: "http://requestbin.net/r/1cmn1je1"
  phases:
    - duration: 300
      arrivalRate: 1
  processor: "./processor.js"
scenarios:
  - flow:
      - post:
          url: "/test"
          beforeRequest: "setContextForTest"
          json:
            test1: "{{ test1 }}"
            test2: "{{ test2 }}"
            test1Ref: null
```
- add the following processor

```js
module.exports = {
  setContextForTest: setContextForTest,
};

function setContextForTest(_, context, __, next) {
  context.vars["test1"] = null;
  context.vars["test2"] = undefined;
  return next();
}
```

- watch request bin

| Expected | Reality |
|-------|------|
| ![image](https://user-images.githubusercontent.com/13785185/100447629-39ae4900-30b1-11eb-87cc-0bab6267833f.png) | ![image](https://user-images.githubusercontent.com/13785185/100447788-7e39e480-30b1-11eb-9cb9-559160a08b86.png) |

# Fix 

- I identified the culprit

![image](https://user-images.githubusercontent.com/13785185/100447873-a1649400-30b1-11eb-8046-f5a9e3779175.png)

- I wrote a small PR #905 

# Open question

Some people may be dependent on the previous workflow, meaning this PR is a breaking change.

![image](https://user-images.githubusercontent.com/13785185/100447995-df61b800-30b1-11eb-8cd1-22b8a3a07566.png)

Should we bump the minor? the major?
