### ISSUE TITLE
how to get latency statistics (like P95) by APIs

### ISSUE THREAD

**Issue by vichybaby** [artilleryio/artillery#908]
There are 2 APIs in my scenario: 
1. post - create a customer and get customerId from response body
2. get - query the customer by the customerId

How to get the latency statistics (like P95) for the 2 APIs separately?

```
scenarios:
  - name: "XXX Load Test"
    flow:
      - loop:
        - post:
            url: "{{ urlSubmission }}"
            json: "{{ requestBody }}"
            headers:
              content-type: "application/json"
            capture:
            - json: "$.customerId"
              as: customerId
        - think: 5
        - get:
            url: "{{ urlQuery }}/{{ customerId }}"
            headers:
              content-type: "application/json"
        - think: 5
        count: 100
```

Another scenario is 2 independent APIs with 50:50 weight. I would like to see the latency statistics (like P95) for the 2 APIs separately as well.
```
scenarios:
  - name: "XXX Load Test"
    weight: 50
    flow:
      - loop:
        - post:
            url: "/v1/createCustomer"
            ......
        - think: 30
        count: 100
  - name: "YYY Load Test"
    weight: 50
    flow:
      - loop:
        - post:
            url: "/v1/createOrder"
            ......
        - think: 30
        count: 100
```
