### ISSUE TITLE
Unable to send buffer as POST body

### ISSUE THREAD

**Issue by backendbee** [artilleryio/artillery#914]
Hi,

I am trying to compress the json and posting to my api endpoint

```
config:
    target: http://localhost:3000/
    phases:
      - duration: 1
        arrivalRate: 5
        name: Warm up
    processor: "./functions.js"
scenarios:
    # We define one scenario:
    - name: "Add new row"
      flow:
        - post:
            beforeRequest: "packItUp"
            url: "/api"
            body: "{{ jsondata }}"
        - log: "Sent a request"
  ```  

In functions.js

```
function packJson(req, ctx, ee, next) {
  const rawdata = fs.readFileSync('sample.json');
  const jsdt = cjson.compress(rawdata);
  ctx.vars.jsdt = jsdt;
  return next();
}
```

>DEBUG=http artillery run test.yml

```
Started phase 0 (Warm up), duration: 1s @ 20:30:31(-0800) 2020-12-15
...   http Error: Argument error, options.body.
  http     at setContentLength (/Users/psolanki/.nvm/versions/node/v10.21.0/lib/node_modules/artillery/node_modules/request/request.js:437:28)
  http     at end (/Users/psolanki/.nvm/versions/node/v10.21.0/lib/node_modules/artillery/node_modules/request/request.js:543:11)
  http     at Immediate._onImmediate (/Users/psolanki/.nvm/versions/node/v10.21.0/lib/node_modules/artillery/node_modules/request/request.js:578:7)
  http     at runCallback (timers.js:705:18)
  http     at tryOnImmediate (timers.js:676:5)
  http     at processImmediate (timers.js:658:5) +0ms
_http_outgoing.js:595
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
    at write_ (_http_outgoing.js:595:11)
    at ClientRequest.write (_http_outgoing.js:567:10)
    at Request.write (/Users/psolanki/.nvm/versions/node/v10.21.0/lib/node_modules/artillery/node_modules/request/request.js:1494:27)
    at end (/Users/psolanki/.nvm/versions/node/v10.21.0/lib/node_modules/artillery/node_modules/request/request.js:549:18)
    at Immediate.<anonymous> (/Users/psolanki/.nvm/versions/node/v10.21.0/lib/node_modules/artillery/node_modules/request/request.js:578:7)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Not sure , what I might be missing.
