### ISSUE TITLE
Duration output from Pause in Phases is Undefined in CLI output

### ISSUE THREAD

**Issue by gscooke** [artilleryio/artillery#919]
Expected:
The duration of a pause in the phases definition should be reported in the CLI output

Actual:
The duration of a pause is reported as undefined

Description:
I have a series of phases, and for some of them I have added pauses so that the affected system can recover. For example:
```
phases:
- duration: 120
  arrivalRate: 1
  rampTo: 10
  name: "Warm up"
- pause: 20
  name: "Pause 20s"
- duration: 300
  arrivalRate: 10
  rampTo: 50
  name: "Ramp up"
```
When I run the test, the output starts normally and reports the start of the first phase:
```
Started phase 0 (Warm up), duration: 120s @ 17:22:52(+0000) 2021-01-15
```
When the pause happens, the output does not report the duration correctly:
```
Started phase 1 (Pause 20s), duration: undefineds @ 17:24:54(+0000) 2021-01-15
```

Shouldn't the duration of the pause phase report the duration value correctly? Functionally the pause operates correctly and waits 20s before starting the next phase.
