### ISSUE TITLE
Csv not being read in sequence

### ISSUE THREAD

**Issue by eoinyoneill** [artilleryio/artillery#922]
I am using CSV files to store unique values to be used just once in a URL for GET's and PUTs. 

But the CSV file is not being read in sequence at all. some rows are being duplicated and some are not being used at all.

out of 200 unique values only 120-130 are being picked up uniquely 

using artillery 1.6.1 on node14

```yaml
payload:
    path: "../ztp.csv"
    fields:
      - serialNo
      - triggerText
  order: sequence

- get: 
          url: "/eem/ztp/ztpconfig/{{serialNo}}/{{triggerText}}"

```

**Comment by hassy** [comment]
It's probably Github's formatting in the code sample, but could you make sure that `output` is on the same level of indentation as the rest of the options?

I can't reproduce the issue with the same version of Artillery. Here's my test:

```yaml
config:
  target: "http://localhost"
  phases:
    - arrivalRate: 10
      duration: 20
  payload:
    path: "./inputcsv.txt"
    fields:
      - serialNo
      - triggerText
    order: sequence
scenarios:
  - flow:
      - log: "{{serialNo}}"
```

Which I run with:

```sh
artillery run -q test.yml > output.txt
```

And then to compare input lines with output:

```sh
diff inputcsv.txt output.txt
```

which shows no difference.

**Comment by miguelromero2000** [comment]
Hi, I have seen the issue happens when artillery is run with multicore options, in example:
MULTICORE=true ARTILLERY_WORKERS=6  ./node_modules/artillery/bin/artillery run --output ./reports/report.json config/config.yml
Each process executed in each core is taking the same record from the payload file.

**Comment by luislhl** [comment]
Hello @hassy 

I've experimented the same issue.

I've downloaded the same input file. This is my test:
```yaml
config:
  target: "http://localhost"
  phases:
    - arrivalRate: 2
      duration: 2
  payload:
    path: "./inputcsv.txt"
    fields:
      - serialNo
      - triggerText
    order: sequence
scenarios:
  - flow:
      - log: "{{serialNo}}"
```

Run with:

```
npx artillery run -q test.yml > output.txt
```

This is my generated output.txt:
```
ff114d3e-0ec9-4c68-963a-9e2c93fac051
ff114d3e-0ec9-4c68-963a-9e2c93fac051
6befd7f3-8c74-4402-b668-1386ca4ee1a7
6befd7f3-8c74-4402-b668-1386ca4ee1a7
```

This is my version:
```
artillery/2.0.0-5 linux-x64 node-v14.16.0
```

If I use the same config file, but changing the phases to this:
```
  phases:
    - arrivalRate: 10
      duration: 20
```

I'll get the following output:

[output.txt](https://github.com/artilleryio/artillery/files/7954272/output.txt)

By running again this exact config, I'll get a slightly different output:

[output2.txt](https://github.com/artilleryio/artillery/files/7954291/output2.txt)

**Comment by anbeck77** [comment]
I'm seeing the same behavior, consistently on my DELETE methods. I haven't seen it for POST. This is making the tool pretty much useless for performance testing DELETE, which is challenging enough at scale.

**Comment by shtlrs** [comment]
Hello @hassy , 

Let me start off by saying: Artilley is very cool, kudos on the work.

Second, I'm experiencing the same issue here when loading data from the csv.

Consider this setup

```js
// flow.js

module.exports = { helloFlow };

async function helloFlow(page, vuContext) {
  const email = vuContext.vars.username;
  const password = vuContext.vars.password;
  console.log(email);
  console.log(password);
}
```
And the following manifest
```yaml
config:
  payload:
    path: "users.csv"
    cast: false
    order: sequence
    fields:
      - "username"
      - "password"
  target: https://someurl.com
  phases:
    - duration: 90
      arrivalRate: 2
      maxVusers: 2
  engines:
    playwright {}
  processor: "flow.js"

scenarios:
  - engine: playwright
    flowFunction: "helloFlow"
    flow: []
```

users.csv
```csv
vehiclebouprod@yopmail.com,redacted
inesfkbackend@yopmail.com,redacted
```

The logs look like this

```text
| vehiclebouprod@yopmail.com
/ redacted
/ vehiclebouprod@yopmail.com
redacted
- inesfkbackend@yopmail.com
redacted
/ inesfkbackend@yopmail.com
- redacted
\ vehiclebouprod@yopmail.com
redacted
- vehiclebouprod@yopmail.com
\ redacted
- inesfkbackend@yopmail.com
\ redacted
- inesfkbackend@yopmail.com
redacted
```

The arrival rate here is 2, and max of virtual users I can have is also 2, doesn't that mean that for each VU that comes in, it should pick up data from one row ?

I'm saying this, because when I change the arrival rate to 1, for each virtual user created, they get a separate row of the csv, so it works pretty well then.
