### ISSUE TITLE
Reusing variable for emits in Socketio test

### ISSUE THREAD

**Issue by arunbg** [artilleryio/artillery#923]
I am load testing a socketio endpoint for a chatbot. Artillery v 1.6.1

```
config:
  target: "https://chatbot_socketio_endpoint"
  phases:
    - duration: 60
      arrivalRate: 5
  payload:
    path: "messages.csv"
    fields:
      - "message"

scenarios:
  - name: My Socketio test
    engine: socketio # Enable the Socket.io engine
    flow:
      - emit:
          channel: session_request
          data: {"session_id": "foobar"}
      - emit:
          channel: user_uttered
          data: {"session_id": "foobar", "message": "{{ message }}"}
          response:
              channel: "bot_uttered"
```

As you can see, an emit to the  `session_request` channel is sent first, followed by the message in the `user_uttered` channel.

I would like to have the value for `session_id` be a variable, in place of the constant "foobar". It should ideally be a UUID from a file, or generated by a Javascript function. The `{{}}` templating would not work since the values would be different in the same flow. Is this possible?
