### ISSUE TITLE
Feature Request - Clear Accept-Encoding header when request has a capture section

### ISSUE THREAD

**Issue by asgerjensen** [artilleryio/artillery#924]
Hi,

To be able to generate a workload that mimicks production as close as possible, i run my tests with
```
  defaults:
    think:
      jitter: 40%
    headers:
      Content-Type: application/json
      Accept: application/json
      Accept-Encoding: gzip
```

However, if a request has a capture section that will fail, because its being run on the compressed data stream. 
Only workaround I have found so far, is  adding a request override to clear the headers.

```
      - post:
          beforeRequest: setAuthHeaders
          url:  /order
          headers:
            Accept-Encoding:
          json:
            outOrderName: "orderId"
          capture:
            - json: $.orderId
              as: orderNrOne
```

But, it seems like a trap. if you forget to set it, capture will not exactly fail and stop the virtual user, but rather continue with unmatched results.

Ideally, capture would check if the stream was compressed, and uncompress it before running the matchers, but failing that, it would be great if the request handler could automatically clear the Accept-Encoding header if it had a capture group.
