### ISSUE TITLE
[Question] Multiple engines usage

### ISSUE THREAD

**Issue by elton-okawa** [artilleryio/artillery#927]
Hello everyone, how are you?

I've looked at the Artillery documentation, but I didn't find anything about the following topic:
Can I use two engines in the same scenario? I have an use-case where the user first needs to make an http request and them use the response to connect via websocket. I'd like to reuse all amazing features that lies with the builtin package.
```
scenarios:
  - engines: ['http', 'websocket']
     flow: 
       - get <some http args>
       - send <some websocket args>
```

Cheers,
Elton
