### ISSUE TITLE
Test Format Question

### ISSUE THREAD

**Issue by mpseay** [artilleryio/artillery#928]
Hey Guys,
Awesome stuff! Quick question around something I'm trying to do here.

A typical scenario:
```
  - name: "Book A New Item"
    weight: 2
    beforeScenario:
      - "authenticateAdmin"
      - "setPayload"
    flow:
      - post:
          url: "/api/v3/offers"
          headers:
            Content-Type: "application/json"
            Authorization: "Bearer: {{ adminToken }}"
          json: "{{ offer }}"
```

A lot of our tests follow this pattern, but, I'm finding it easier to do something like:
```
  - name: "Book A New Item"
    weight: 2
    beforeScenario:
      - "authenticateAdmin"
      - "setPayload"
    flow:
      - function: "testBookingNewItem"
```

Looking for more detalis on the context or event emitters, but, I'm not sure its documented very well yet AFAIK. Feel free to point me at that if its elsewhere! 

What would be the correct way of pass/failing tests this way? I definitely want to keep the status code, response time results of course. Is this recommended/feasible?
