### ISSUE TITLE
"TypeError: Cannot convert undefined or null to object" at Socket.IO testing

### ISSUE THREAD

**Issue by h6ak** [artilleryio/artillery#982]
The following error occurred in the case of Socket.IO testing with response timeout.
Summary report could not be displayed.

```
/Users/hiroaki-hotta/.config/yarn/global/node_modules/artillery/lib/console-reporter.js:167
    const coreRates = Object.keys(report.rates).filter(name => name.startsWith('core.'));
                             ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ConsoleReporter.printReport (/Users/hiroaki-hotta/.config/yarn/global/node_modules/artillery/lib/console-reporter.js:167:30)
    at ConsoleReporter.stats (/Users/hiroaki-hotta/.config/yarn/global/node_modules/artillery/lib/console-reporter.js:91:8)
    at EventEmitter.emit (/Users/hiroaki-hotta/.config/yarn/global/node_modules/eventemitter3/index.js:202:33)
    at EventEmitter.<anonymous> (/Users/hiroaki-hotta/.config/yarn/global/node_modules/artillery/lib/runner-sp.js:62:19)
    at EventEmitter.emit (/Users/hiroaki-hotta/.config/yarn/global/node_modules/eventemitter3/index.js:202:33)
    at SSMS.<anonymous> (/Users/hiroaki-hotta/.config/yarn/global/node_modules/artillery/core/lib/runner.js:332:8)
    at SSMS.emit (events.js:314:20)
    at SSMS._maybeEmitMostRecentPeriod (/Users/hiroaki-hotta/.config/yarn/global/node_modules/artillery/core/lib/ssms.js:480:12)
    at SSMS.aggregate (/Users/hiroaki-hotta/.config/yarn/global/node_modules/artillery/core/lib/ssms.js:474:10)
```

OS: macOS Catalina 10.15.7
Version: artillery/2.0.0-dev2 darwin-x64 node-v12.21.0 (globally installed)

**Comment by hassy** [comment]
hi @h6ak 👋 thank you for bravely testing the `dev` preview of Artillery 2.0! :)

Would you be able to share your test script (redacted as needed) to help debug the issue?

**Comment by h6ak** [comment]
I've prepared a simple server implementation and a scenario as follows.
You can see the same error.

Socket.IO server (in Typescript)
```typescript
// run a server by nodemon

import express from 'express';  // Express framework
import { createServer } from 'http';
import SocketIO from 'socket.io';

type DataType = {
  user: string;
  msg: string;
};

const options = {
  port: 3000,
};

///////////// Setup Express App ////////////////
const app = express();
app.get('/alive', function (_req, res) {
  res.sendStatus(200);
});

///////////// Setup Server ///////////////
const server = createServer(app).listen(options.port, (): void => {
  console.log(`Listening on port ${options.port}`);
});

// Socket.IO
const io = SocketIO(server);
io.on('connection', (socket) => {
  socket.on('to_server', (data: DataType) => {
    console.log(data.user);
    socket.join(data.user);

    // emit data to user in probability 0.5 to cause response timeout
    if (Math.random() < 0.5) {
      io.to(data.user).emit('to_client', data.msg);
    }
  });
});
```

Artillery scenario
```yaml
config:
  target: "http://127.0.0.1:3000"
  phases:
    - duration: 3
      arrivalCount: 100
scenarios:
  - engine: "socketio"
    flow:
      - emit:
          channel: "to_server"
          data:
            user: "{{ $randomString() }}"
            msg: "some message"
          response:
            channel: "to_client"
            data: "some message"
```
